### ISSUE TITLE
Key value storage support for Location and GBIF taxonomy lookups

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/la-pipelines#10]
GBIF make use of HBase for key value storage for runtime caches to support the pipelines.

HBase requires a relatively complex setup to which the GBIF team are very familar with having used it for many years.

Historically, HBase is not a technology in use ALA, and there is an opportunity to pick a more lightweight technology for ALA's use. Options include using Cassandra for this purpose, but something more lightweight might prove more cost effective.

**Comment by nickdos** [comment]
Would this be used just `qid` and user assertions data storage as well?

**Comment by djtfmartin** [comment]
These key-value stores are just intended to be semi-persistent caches, so the use case is slightly different.

I think for Stage 1, we will leave QIDs and assertions where they are in Cassandra, but we can downsize the production cassandra cluster to 2 nodes with lower spec VMs.

**Comment by ansell** [comment]
The only large table in our current cassandra is `occ.occ`. Once that is removed, cost is no longer an issue at all to support all of the other column families until Stage 3 on a reduced capacity cluster (no point to going to a single server, but we could switch to 2 small servers easily at that point). There is a fundamental conflict in the current project plan with both "no/or little biocache-service changes" and "remove cassandra".

Adding MapDB is a high-risk to the project as I haven't worked on it for a few years, and when I last used it I wasn't impressed by its performance and only used it to avoid memory issues with its disk serialisation.

**Comment by nickdos** [comment]
I don't think we're wed to `MapDB` so how about we create a sub-issue to investigate other options, taking into consideration performance, reliability, popularity/dev activity, etc.?

**Comment by djtfmartin** [comment]
MapDB is no longer in use for interpretation pipeline, or anywhere else. Performance seems to be fine for Interpretation just using the default in-memory cache2k caches that are the default cache to use with gbif pipelines where a separate cache implementation is not setup.

Currently interpretation (equivalent to the processing step of biocache-store) of dr2009 (18 million records) is running in 17 minutes.

This issue can probably be closed, and new issues raised for specific key value store issues.
