### ISSUE TITLE
Generate BitMap for SDS layers

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/la-pipelines#100]
We need to generate Bit Maps that can be used with GBIF's bit map lookups for SDS layers to support efficient lookups.

**Comment by RobinaSanderson** [comment]
SAme as State Province but for SDS

**Comment by qifeng-bai** [comment]
My understanding is: 
 
Mainly, by given a coordinate, generate the similar result like:   https://sds.ala.org.au/sensitivity-zones.xml
1, load related shp files in shp-layers.tgz to postgres
2, modify geocode-ws to load those layers
3, use BigMapGenerator

**Comment by qifeng-bai** [comment]
Target: Generate a SVG which colourises areas + ID (State / Country etc)
  `<path id='Australian Capital Territory' style='fill: #5a4e68' d='M 150.7718 `
 Work log:
1, QGIS crashed when SimpleSVG crashed when colour styles is applied.
2, ArcGIS need to buy a plugin to generate SVG + attributes (ID/Feature)
**I suspect that the attribute id will be discard when we convert SVG to PNG** 

Solution:  Import shp file to Postgres ( docker), and wrote a simple SVG generator (Borrowed from GBIF)
Generated cw_state_ploy.svg, this shp file is used to identify states.

Update GeocodeBitmapCache to the latest version. 
'Id' attribute is not used in GeocodeBitmapCache

Remaining issues:
1, Identify SHP files used by SDS  and then generate PNG
2, A world wide SVG was generated for Australia state SVG.   Check if a SVG on Australia size works with GeocodeBitmapCache
`height="3600" width="7200" viewBox="-180 -90 360 180"`
3, Whether compressing PNG will affect the correctness of our code?

**Comment by qifeng-bai** [comment]
Zones/Locations needed to be identified:
https://sds.ala.org.au/sensitivity-zones.xml
|type| layer | shp | svg |
| --- | --- | --- | --- |
|Country | "Australia", "New Zealand" , "Outside Australia" |    |  bitmap.png -gbif generated | 
|state |"ACT" "NSW" "QLD" "VIC" "TAS" "SA" "WA" "NT" | cs_state_poly.shp| cs_state_poly.png |
|External Territory| "Cocos (Keeling) Islands""Christmas Island""Ashmore and Cartier Islands" "Coral Sea Islands" "Norfolk Island" "Heard and McDonald Islands" "Australian Antartic Territory" || |
||||


<sensitivity-zone id="TSPZ" name="Torres Strait Protected Zone" type="Quarantine_zone"/>
<sensitivity-zone id="TSSQZ" name="Torres Strait Special Quarantine_zone" type="Quarantine_zone"/>
<sensitivity-zone id="FFEZ" name="Tri-State Fruit Fly Exclusion Zone" type="Quarantine_zone"/>
<sensitivity-zone id="PFFPQA1995" name="Papaya Fruit Fly Pest Quarantine Area 1995" type="Quarantine_zone"/>
<sensitivity-zone id="ECCPQA2004" name="Emerald Citrus Canker Pest Quarantine Area 2004" type="Quarantine_zone"/>
<sensitivity-zone id="RIFARA" name="Red Imported Fire Ant Restricted Area" type="Quarantine_zone"/>
<sensitivity-zone id="PIZNSWAC" name="Phylloxera Infested Zone - NSW Albury-Corowa" type="Quarantine_zone"/>
<sensitivity-zone id="PIZNSWSR" name="Phylloxera Infested Zone - NSW Sydney Region" type="Quarantine_zone"/>
<sensitivity-zone id="PIZVICNE" name="Phylloxera Infested Zone - Vic North East" type="Quarantine_zone"/>
<sensitivity-zone id="PIZVICMAR" name="Phylloxera Infested Zone - Vic Maroondah" type="Quarantine_zone"/>
<sensitivity-zone id="PIZVICNAG" name="Phylloxera Infested Zone - Vic Nagambie" type="Quarantine_zone"/>
<sensitivity-zone id="PIZVICMOR" name="Phylloxera Infested Zone - Vic Moroopna" type="Quarantine_zone"/>
<sensitivity-zone id="PIZVICUPT" name="Phylloxera Infested Zone - Vic Upton" type="Quarantine_zone"/>
<sensitivity-zone id="PIZVICWHB" name="Phylloxera Infested Zone - Vic Whitebridge" type="Quarantine_zone"/>
<sensitivity-zone id="PCNCAVICTHO" name="Potato Cyst Nematode Control Area - Vic Thorpdale" type="Quarantine_zone"/>
<sensitivity-zone id="PCNCAVICGEM" name="Potato Cyst Nematode Control Area - Vic Gembrook" type="Quarantine_zone"/>
<sensitivity-zone id="PCNCAVICKWR" name="Potato Cyst Nematode Control Area - Vic Koo Wee Rup" type="Quarantine_zone"/>
<sensitivity-zone id="PCNCAVICWAN" name="Potato Cyst Nematode Control Area - Vic Wandin" type="Quarantine_zone"/>

**Comment by qifeng-bai** [comment]
This doc explains how to generate a bitmap from SHP file(s)
https://confluence.csiro.au/display/CIU/Pipeline+bitmap+generation

**Comment by qifeng-bai** [comment]
According GBIF BitMapGenerator doc: 
This gives us a 7200×3600 image, with the "units" (pixels) on a scale -180°–180°,  -90°–90°. Therefore, 1px = 1°.

Bitmap generates 'black Boundary lines' for avoiding possible error caused by those boundary across <1px point.
Bitmap cache will return null if the colour code is 'black', and then force GeocodeBitmapCache search on SHP file.

It works well for large maps, like, country and state. However, it does work very will on small scopes

![Uploading Screen Shot 2020-10-19 at 10.23.21 am.png…](bitmap generated by GBIF)

![Uploading Screen Shot 2020-10-19 at 10.20.25 am.png…](Quarantine zone)

**Comment by nickdos** [comment]
I'm not sure if this is valid concern or not but I'm wondering if we'll end up putting records in the wrong state when the pixel resolution is lower than that of the layer. E.g. where the state border follows a river, we could place a record on the wrong side due to the effective "rounding" that the bitmap performs.

**Comment by qifeng-bai** [comment]
@nickdos GBIF's uncertainty is 5km, so they "buffered" 5km on boundaries

**Comment by nickdos** [comment]
Thanks @qifeng-bai - How does the buffer work? Do records in the buffer zone get placed in both jurisdictions?

**Comment by qifeng-bai** [comment]
@nickdos , If a coordinate sits in the 'buffered zone'/ black area, the BitmapCache return null, then the next step will try on SHP file

**Comment by qifeng-bai** [comment]
Bitmaps have been uploaded to https://archives.ala.org.au/archives/layers/

**Comment by djtfmartin** [comment]
merged
