### ISSUE TITLE
Create DWcA with images/media extension - implementation

### ISSUE THREAD

**Issue by RobinaSanderson** [AtlasOfLivingAustralia/la-pipelines#103]
In #50 we will figure out what needs to be done and how to do it. This task will list the steps and track their implementation

**Comment by sadeghim** [comment]
Here is the PR: https://github.com/AtlasOfLivingAustralia/biocache-store/pull/401

**Comment by peggynewman** [comment]
Is the Audobon Core (or Simple Multimedia) extension relevant here? Will we be implementing a solution that handles this as inputs? I would like to be clear to data providers how they should provide images and image metadata.

**Comment by javier-molina** [comment]
As per comment https://github.com/atlasoflivingaustralia/la-pipelines/issues/12#issuecomment-688251024 this can now be closed
