### ISSUE TITLE
Align countryCentrePoint and GeocodeShpIntersectService vocabularies

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/la-pipelines#106]
The vocabulary files do not align:

e.g. "United States of America" coming from GeocodeShpIntersectService vs "UNITED STATES"

See: https://github.com/gbif/pipelines/blob/ala-dev/livingatlas/pipelines/src/main/resources/countryCentrePoints.txt#L223

Todo
Our country centre file uses country name as key,  some countries may have different names due to languages. We plan to add a new "Country Code" as key to solve name matching issue.

**Comment by qifeng-bai** [comment]
The listed country names are not listed in CountryCentreFile, or different with the name in the file.

BONAIRE, SINT EUSTATIUS AND SABA
CABO VERDE
CONGO, DEMOCRATIC REPUBLIC OF THE
CONGO, REPUBLIC OF THE
CÔTE D'IVOIRE
CURAÇAO
CZECHIA
IRAN, ISLAMIC REPUBLIC OF
KOREA, DEMOCRATIC PEOPLE'S REPUBLIC OF
KOREA, REPUBLIC OF
NORTH MACEDONIA
MICRONESIA, FEDERATED STATES OF
MOLDOVA, REPUBLIC OF
PALESTINE, STATE OF
SAINT BARTHÉLEMY
SAINT MARTIN (FRENCH PART)
SINT MAARTEN (DUTCH PART)
SOUTH SUDAN
ESWATINI
TAIWAN
TANZANIA, UNITED REPUBLIC OF
UNITED STATES MINOR OUTLYING ISLANDS
VIRGIN ISLANDS, BRITISH
VIRGIN ISLANDS, U.S.
USER DEFINED
KOSOVO
**INTERNATIONAL WATERS
UNKNOWN OR INVALID**

**Comment by javier-molina** [comment]
Suggested by @sadeghim  https://worldmap.harvard.edu/data/geonode:country_centroids_az8

**Comment by qifeng-bai** [comment]
Countries need be identified
CABO VERDE  vs  Cape Verde 
FAROE ISLANDS   vs Faeroe Islands
FRENCH SOUTHERN TERRITORIES. vs  French Southern and Antarctic Lands

Countries lost
BONAIRE, SINT EUSTATIUS AND SABA
BOUVET ISLAND
CABO VERDE
CHRISTMAS ISLAND
COCOS (KEELING) ISLANDS
CONGO, DEMOCRATIC REPUBLIC OF THE
CONGO, REPUBLIC OF THE
CÔTE D'IVOIRE
CURAÇAO
FAROE ISLANDS
FRENCH GUIANA
FRENCH SOUTHERN TERRITORIES
GAMBIA
GIBRALTAR
GUADELOUPE
HEARD ISLAND AND MCDONALD ISLANDS
HOLY SEE
KOREA, DEMOCRATIC PEOPLE'S REPUBLIC OF
KOREA, REPUBLIC OF
LAO PEOPLE'S DEMOCRATIC REPUBLIC
NORTH MACEDONIA
MARTINIQUE
MAYOTTE
MICRONESIA, FEDERATED STATES OF
MOLDOVA, REPUBLIC OF
PITCAIRN
RÉUNION
SAINT BARTHÉLEMY
SAINT HELENA, ASCENSION AND TRISTAN DA CUNHA
SAINT MARTIN (FRENCH PART)
SAO TOME AND PRINCIPE
SINT MAARTEN (DUTCH PART)
SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS
SVALBARD AND JAN MAYEN
ESWATINI
SYRIAN ARAB REPUBLIC
TANZANIA, UNITED REPUBLIC OF
TOKELAU
TUVALU
UNITED STATES MINOR OUTLYING ISLANDS
VENEZUELA, BOLIVARIAN REPUBLIC OF
VIRGIN ISLANDS, BRITISH
WALLIS AND FUTUNA

**Comment by qifeng-bai** [comment]
The new SHP file records centre of AU is -25.73288704	134.4910001 
the old centre is -29.5328037	145.491477
I think the new one is accurate.

**Comment by qifeng-bai** [comment]
Rollbacked to ALA centre file and added missing countries/locations
Still missing:
AX : Åland Islands
BQ : Bonaire, Sint Eustatius and Saba
CI : Côte d'Ivoire
CW : Curaçao
FM : Micronesia, Federated States of
PS : Palestine, State Of
RE : Réunion
SZ : Eswatini
TW : Taiwan
UM : United States Minor Outlying Islands
AA : user defined
XZ : international waters
ZZ : unknown or invalid

**Comment by qifeng-bai** [comment]
https://github.com/gbif/pipelines/pull/370. @djtfmartin
