### ISSUE TITLE
Output pipelines jar version information at the start of pipeline runs

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/la-pipelines#110]
It would be useful if at the start of a pipeline run, the version (git commit ID etc) was visible in the logs so we can ascertain what version was used for running a pipeline.

cc @sadeghim

**Comment by qifeng-bai** [comment]
One solution:
Use git-commit-id-plugin to wrap commit version to git.properties in target jar.
Load commit version from git.properties when this jar is executed.

**Comment by qifeng-bai** [comment]
https://github.com/gbif/pipelines/pull/410

**Comment by qifeng-bai** [comment]
https://github.com/gbif/pipelines/pull/410
