### ISSUE TITLE
Using GBIF range parser to convert km

### ISSUE THREAD

**Issue by qifeng-bai** [AtlasOfLivingAustralia/la-pipelines#112]
GBIF has accepted our km-2-m code into its parser. https://github.com/gbif/parsers/issues/21

We need to refactor code to use GBIF range parser in  ALA pipeline

**Comment by qifeng-bai** [comment]
https://github.com/gbif/pipelines/pull/363

**Comment by djtfmartin** [comment]
Reviewed and merged.
