### ISSUE TITLE
Handle datasets without unique terms specified

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/la-pipelines#115]
The following 16 datasets don't have unique darwin core terms specified:

| Dataset ID | Metadata | Occurrences |
|------|------| ------|
| dr672 | https://collections.ala.org.au/public/show/dr672 | [occurrences](https://biocache.ala.org.au/occurrences/search?q=data_resource_uid:dr672)| 
| dr684 | https://collections.ala.org.au/public/show/dr684 | [occurrences](https://biocache.ala.org.au/occurrences/search?q=data_resource_uid:dr684)| 
| dr662 | https://collections.ala.org.au/public/show/dr662 | [occurrences](https://biocache.ala.org.au/occurrences/search?q=data_resource_uid:dr662)| 
| dr691 | https://collections.ala.org.au/public/show/dr691 | [occurrences](https://biocache.ala.org.au/occurrences/search?q=data_resource_uid:dr691)| 
| dr354 | https://collections.ala.org.au/public/show/dr354 | [occurrences](https://biocache.ala.org.au/occurrences/search?q=data_resource_uid:dr354)| 
| dr834 | https://collections.ala.org.au/public/show/dr834 | [occurrences](https://biocache.ala.org.au/occurrences/search?q=data_resource_uid:dr834)| 
| dr708 | https://collections.ala.org.au/public/show/dr708 | [occurrences](https://biocache.ala.org.au/occurrences/search?q=data_resource_uid:dr708)| 
| dr693 | https://collections.ala.org.au/public/show/dr693 | [occurrences](https://biocache.ala.org.au/occurrences/search?q=data_resource_uid:dr693)| 
| dr703 | https://collections.ala.org.au/public/show/dr703 | [occurrences](https://biocache.ala.org.au/occurrences/search?q=data_resource_uid:dr703)| 
| dr705 | https://collections.ala.org.au/public/show/dr705 | [occurrences](https://biocache.ala.org.au/occurrences/search?q=data_resource_uid:dr705)| 
| dr843 | https://collections.ala.org.au/public/show/dr843 | [occurrences](https://biocache.ala.org.au/occurrences/search?q=data_resource_uid:dr843)| 
| dr968 | https://collections.ala.org.au/public/show/dr968 | [occurrences](https://biocache.ala.org.au/occurrences/search?q=data_resource_uid:dr968)| 
| dr928 | https://collections.ala.org.au/public/show/dr928 | [occurrences](https://biocache.ala.org.au/occurrences/search?q=data_resource_uid:dr928)| 
| dr698 | https://collections.ala.org.au/public/show/dr698 | [occurrences](https://biocache.ala.org.au/occurrences/search?q=data_resource_uid:dr698)| 
| dr701 | https://collections.ala.org.au/public/show/dr701 | [occurrences](https://biocache.ala.org.au/occurrences/search?q=data_resource_uid:dr701)| 
| dr661 | https://collections.ala.org.au/public/show/dr661 | [occurrences](https://biocache.ala.org.au/occurrences/search?q=data_resource_uid:dr661)| 

We need to specify what to do about these datasets for migration.
Initial suggestion is that for these datasets the existing UUID is used to populate a `occurrenceID` in the export and we use this as the unique term. The down side of this is that we are including non-raw data in the DwCA export fields.

**Comment by djtfmartin** [comment]
@sadeghim @peggynewman 

I've done some work for AtlasOfLivingAustralia/la-pipelines#115 to allow datasets to be loaded without unique terms if the external configuration specifies `uuid.allowEmptyUniqueTerms=true` (the default is false). 

This is to avoid this issue being a blocker for other data migration work and testing. We should decide what to do in scenario where datasets have not specified unique terms.

**Comment by ansell** [comment]
biocache-store was changed recently to disallow loading of data resources where the unique term is not defined, so these datasets and any new datasets with this issue will not be able to be loaded anymore.

**Comment by peggynewman** [comment]
The IPT rejects datasets without an occurrenceID. In 2 of these data resources dr672 and dr691, catalogNumber is probably the unique key but the rest have no candidate unique fields.  They are all very old, and a couple of them don't even have basisOfRecord perhaps just to get images uploaded.
I agree that datasets shouldn't be allowed without unique terms specified.  To get these through I'm ok with updating these 2 to catalogNumber as the term (checking for uniqueness first) and setting the UUID as occurrenceID for the rest, provided occurrenceID is null (which I think it is).

**Comment by sadeghim** [comment]
My impression is that since this is the issue with the data, not the export/load, it's better to fix the data in Cassandra instead of adding code to the export or pipeline which only works for this issue.
I support @peggynewman on assigning `catalogNumber`/`occurrenceID` as the unique key in the `occ_uuid` table.

**Comment by djtfmartin** [comment]
Just adding notes from the standup so we dont forget the thinking. 
I think @sadeghim's favoured approach was to update the `occurrenceID` in cassandra to be the UUID of the record (i.e. the rowkey) for the other 14 datasets mentioned in this issue.  We'll then need to change the config in the  collectory to specify `occurrenceID` as the unique term to use.  @sadeghim - please say if thats incorrect.

For `dr672` and `dr691` we can use the catalogNumber as noted by @peggynewman

**Comment by sadeghim** [comment]
| dataResourceUid | count(dateDeleted) | count(dataResourceUid) | count(catalogNumber) | count(collectionCode) | count(institutionCode) | count(occurrenceID) | 
 |--|--|--|--|--|--|--| 
 | dr672           | 0                  | 23798                  | 23798                | 0                     | 0                      | 0                   | 
 | dr354           | 0                  | 2048                   | 0                    | 0                     | 0                      | 0                   | 
 | dr661           | 0                  | 54                     | 0                    | 0                     | 0                      | 0                   | 
 | dr843           | 0                  | 366                    | 0                    | 0                     | 0                      | 0                   | 
 | dr698           | 0                  | 182                    | 0                    | 0                     | 0                      | 0                   | 
 | dr708           | 0                  | 1575                   | 0                    | 0                     | 0                      | 0                   | 
 | dr662           | 0                  | 4256                   | 0                    | 0                     | 0                      | 0                   | 
 | dr691           | 0                  | 2153                   | 2150                 | 0                     | 0                      | 0                   | 
 | dr968           | 0                  | 352                    | 0                    | 0                     | 0                      | 0                   | 
 | dr703           | 0                  | 1012                   | 0                    | 0                     | 0                      | 0                   | 
 | dr693           | 0                  | 1115                   | 0                    | 0                     | 0                      | 0                   | 
 | dr928           | 0                  | 221                    | 0                    | 0                     | 0                      | 0                   | 
 | dr834           | 0                  | 1986                   | 0                    | 0                     | 0                      | 0                   | 
 | dr705           | 0                  | 841                    | 0                    | 0                     | 0                      | 0                   | 
 | dr701           | 0                  | 84                     | 0                    | 0                     | 0                      | 0                   | 
 | dr684           | 0                  | 6187                   | 0                    | 0                     | 0                      | 0                   |

**Comment by sadeghim** [comment]
dr672 is done.

**Comment by sadeghim** [comment]
dr691 done.

**Comment by sadeghim** [comment]
For the rest of the DRs, I added an `occurrenceID` an incremental number starting from 1 for each DR. Updated the `occ.occ` table and added the map to the `occ.occ_uuid` table in cassandra. Also updated the collectory.

As I see the DR numbers, it seems that the bug was temporary that led to this situation and it doesn't happen anymore.

**Comment by javier-molina** [comment]
Already covered by follow up work on #134
