### ISSUE TITLE
Create test scenarios matrix

### ISSUE THREAD

**Issue by javier-molina** [AtlasOfLivingAustralia/la-pipelines#119]
Create end to end test scenarios for different use cases.

Assumptions:
* We are testing that the new pipelines implementation replicates the functions of biocache, except for where we have agreed or made a conscience decision to change functionality.
* All test cases start with a DwCA of occurrence records.
* End result is a fully processed and indexed set of records available for search and download through the ALA's user interfaces (or should this just be biocache?). Conforming to all sensitive data or licensing restrictions.
* the test suite currently used to test biocache can form the basis of testing
* Assertions to be tested are or will be documented in the Data Quality Checks spreadsheet: https://docs.google.com/spreadsheets/d/1tAfQUsIzUNfa6Tn5Ezq2cfbMVB0QeXIyp7N0We2lBAY/edit?hl=en&hl=en&hl=en#gid=0
* the Data Quality Checks spreadsheet will be cross referenced with the ALA/GBIF issues mapping spreadsheet: https://docs.google.com/spreadsheets/d/1D8jQ2xyPP_Df4QuBQs0Ti3FTkpoquMiEErBorqjoxKI/edit?ts=5ea93bdb#gid=174696199
* It is reasonable to create a test suite and data set for each type of assertion rather than just one great big one. So that the the tester has more manageable number of things to check.

Things to include in test scenarios:
* generation of UUIDs from various criteria
* records with images in the DwCA (this would include where records are processed first and images may take longer if this architecture is put in place)
* records with image URLs in the DwCA
* records testing the creation of all **Location** type assertions from the Data Quality Checks spreadsheet
* records testing the creation of all **Temporal** type assertions from the Data Quality Checks spreadsheet
* records testing the creation of all **Taxonomic** type assertions from the Data Quality Checks spreadsheet
* records testing the creation of all **Miscellaneous** type assertions from the Data Quality Checks spreadsheet
* validation of the number of records flowing through each transform in the system
* other things??

Suggest separate issue(s) are created for:
* Performance testing
* Security testing
* Load testing

**Comment by djtfmartin** [comment]
@javier-molina @RobinaSanderson - can we add a description for this one ?
