### ISSUE TITLE
Export all existing data holdings in DwCA for pipeline ingestion (Part 1)

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/la-pipelines#12]
All the existing data holdings for occurrence data in the ALA need to be exported into DwCA (or other to be determined format) format in a non-lossy manner for ingestion into a pipelines based backend.

For `miscProperties` - a field currently containing a json blob in cassandra, `dynamicProperties` may be useful.

https://dwc.tdwg.org/terms/#dwc:dynamicProperties

**Comment by djtfmartin** [comment]
Note: GBIF developed a pipeline to export data from existing HBase cluster.

**Comment by nickdos** [comment]
tagging: data migration, datamigration

**Comment by ansell** [comment]
This is a very large task. It isn't as simple as dumping the current cassandra to Darwin Core Archives, as we also need to make sure that our original data providers are providing Darwin Core Archives so we can update their data resources still after the switch. There is a large list of "custom" data provider code in biocache-store which will need to be worked on individually:

https://github.com/AtlasOfLivingAustralia/biocache-store/tree/master/src/main/scala/au/org/ala/biocache/load

The timeframe for the data migration parts of this project should not be specified in "weeks" as it makes this task appear as those it is a fairly small task.

**Comment by RobinaSanderson** [comment]
Export from Cassandra need to be all raw data, not processed fields.
Ideally we would just used archived files from data providers but we don't have the full set.
Some datasets have been loaded and then have had deltas provided so we don't have a complete archive for them.
Instead take the dataset DwC archive from Cassandra for migrate and then as Data providers to provide DwC archive from now on. We could accept simple DwC but take this decision off line.
GBIF pipeline only ingests DwC archive. Doesn't currently convert DwC CSV to DwC archive - this could be a pre-ingestion step.
Need to consider images - original image URLs may no longer be available, does there need to be a separate image service see also issue.

Acceptance criteria:
* able to continue to do regular dataloads
* have everything in darwin core archive format in zip file and on system
* does not include images at this point
* does UUID need to be handled in the export - these should not have UUIDs as not in original archives - need to extract separately - see issue xxx - store UUIDs in Cassandra - agreed to not include in DwC archive

**Comment by peggynewman** [comment]
I understand this issue is becoming an epic and split into a number of other sub tasks. 
Responding to some of the above things though -

@djtfmartin re putting miscProperties into dynamicProperties field - wouldn't that create problems where dynamicProperties is already populated in any datasets? 

Should there be a separate issue to analyse the scala load code that Peter mentioned, to establish what is replaced by this project and take out the data loads that are hard coded into biocache-store and ensure they have coverage by the data management? eg Flickr 
https://github.com/AtlasOfLivingAustralia/biocache-store/tree/master/src/main/scala/au/org/ala/biocache/load

**Comment by djtfmartin** [comment]
@peggynewman yes thats possible, but i don't know if thats the case for many or any datasets. If thats the case, the dynamicProperties could be expanded to include additional miscProperties.

**Comment by sadeghim** [comment]
I thought maybe this is the good place to say how we can do some data queries on avro files using spark:
```
sudo -u  spark ./bin/spark-shell --packages org.apache.spark:spark-avro_2.11:2.4.6

spark.sqlContext.sql("CREATE TEMPORARY VIEW ALA_UUID USING avro OPTIONS (path 'hdfs://172.30.1.102:9000/pipelines-data/dr15860/1/identifiers/ala_uuid/interpret*')")

spark.sql("SELECT * FROM vw_occ_uuid limit 10").show( false)
```

**Comment by djtfmartin** [comment]
I think this work has been reviewed and merged in biocache-store. It can be marked as `Done`
