### ISSUE TITLE
Unable to specify working dir for DWCA expansion and sort

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/la-pipelines#121]
We are currently unable to specify working dir for DWCA expansion and sort.
This causes the following error for our largest archives in the `ALADwcaToVerbatimPipeline`:

```
20/08/14 18:29:46 [] 1  [INFO] Archive: Initializing Darwin Core Archive for iteration. This can take some minutes on large archives.
20/08/14 18:41:36 [] 1  [WARN] FileUtils: Error sorting file with GNU sort
sort: write failed: /tmp/sortX0e6tH: No space left on device

```
Issue discuss on Slack with GBIF and PR raised here:

https://github.com/gbif/gbif-common/pull/19

**Comment by djtfmartin** [comment]
This work has been done and tested on NCI. Awaiting review.

**Comment by javier-molina** [comment]
Waiting for Vicente to review this

**Comment by djtfmartin** [comment]
This just happened on AWS quoll. Reopening

**Comment by djtfmartin** [comment]
fixed on quoll.
