### ISSUE TITLE
dr2009 empty keys preventing loading of DwCA export

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/la-pipelines#122]
The dataset `dr2009` is currently configured to use `occurrenceID` as the unique terms for generating a unique key for records.

```json

termsForUniqueKey: [
"occurrenceID"
]

```

The current export in DwCA has **18,798,518** records, of which **18,200,264** have an empty `occurrenceID` value.

cc @sadeghim @peggynewman

**Comment by peggynewman** [comment]
@ansell has been working on the keys in Cassandra for this dataset, because the occurrenceID we had is slightly different to that provided in the GBIF export that we intend to upload.

**Comment by sadeghim** [comment]
Switched back the unique key field in collectory from `occurrenceID` to `catakogNumber` for now.

**Comment by sadeghim** [comment]
This issue is fixed for now. 
But the new load can cause the issue to raise again. So here is the another task that can prevent the new ebird load break the load.
AtlasOfLivingAustralia/la-pipelines#135
