### ISSUE TITLE
Rowkey-UUID mapping mechanism in pipeline

### ISSUE THREAD

**Issue by sadeghim** [AtlasOfLivingAustralia/la-pipelines#131]
Like the `occ_uuid` table in cassandra, we need to have a mechanism to tune the mappings of the unique fields to uuids.
This can be a script that reads the new mapping and updates the `uuid-mapping.avro`.

**Comment by djtfmartin** [comment]
Yes, we need this.

Extracting the data from AVRO can be done with SparkQL, but we need a tool that takes the 3 column CSV and creates the AVRO files using the AVRO schema.

**Comment by djtfmartin** [comment]
this hasnt been necessary yet. If it is required, it may be better just to create the avro with scripting in python as and when required. Closing.
