### ISSUE TITLE
Setup HDFS HA in NCI and AWS

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/la-pipelines#132]
The current installation of HDFS that has been setup with ansible on NCI and AWS is not a HA installation.

We need to investigate and enhance the current scripts to::

- [ ] Have multiple name nodes
- [ ] Name node installed on separate VMs

Investigation of HA installation is required.

https://hadoop.apache.org/docs/current/hadoop-project-dist/hadoop-hdfs/HDFSHighAvailabilityWithNFS.html

**Comment by djtfmartin** [comment]
Work has been done to separate name nodes and data nodes for AWS cluster. This work needs to be expanded on to support a HA Cluster (replicated name nodes).

**Comment by javier-molina** [comment]
Superseded by #496
