### ISSUE TITLE
Checking COUNTRY_COORDINATE_MISMATCH

### ISSUE THREAD

**Issue by qifeng-bai** [AtlasOfLivingAustralia/la-pipelines#133]
@RobinaSanderson  reported we missing this assertion in our assertion sheet. 
we need to check if the country calculated from a given coordinate matches the country supplied 

After reviewing code, COUNTRY_COORDINATE_MISMATCH has been in GBIF LocationInterpreter

Examples:
If an Australia coordinate is supplied with a country name: NZ, the output will be: NZ, COUNTRY_COORDINATE_MISMATCH

If an Australia coordinate is supplied without  a country name, the output will be: AUSTRALIA, COUNTRY_DERIVED_FROM_COORDINATES

**Comment by RobinaSanderson** [comment]
Thanks @qifeng-bai and thanks for updating the ALA/GBIF spreadsheet. In the first case, where the supplied country name doesn't match the coordinates, I think we currently replace the supplied country name in the user interface and display the processed country name. Would moving to the GBIF code mean that we would display the supplied country name in the user interface and just flag the record?

**Comment by qifeng-bai** [comment]
GBIF uses the original supplied country and flag coordinates mismatch

**Comment by djtfmartin** [comment]
This affects **177k** records:

https://biocache.ala.org.au/occurrences/search?q=*%3A*&fq=assertions%3A%22countryCoordinateMismatch%22

**Comment by qifeng-bai** [comment]
@peggynewman  Would you please confirm our decision in last meeting?

**Comment by peggynewman** [comment]
I'm good to go with the GBIF solution.
