### ISSUE TITLE
Datasets cant be loaded be loaded due to config issues

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/la-pipelines#134]
Of the **812** dataset archives we have produced from Cassandra, **31** datasets cant currently be loaded into SOLR.
This affects **29,461,372** records (30% of the occurrence data).

This for the following 3 reasons:

###  1. Unique terms not specified

Dataset ID | Record count | Resolution |
--  | -- | -- |
dr14141 | 43819 | <ul><li>- [x] </li></ul>  |
dr14171 |  22 |  <ul><li>- [x] </li></ul> |
dr807 | 81299 | <ul><li>- [x] </li></ul>  |

###  2. Has records with blank keys (i.e. all unique terms are blank)

_Note_: there is an open issue for dr359 here: #123 

Dataset ID | Record count|  Resolution |
-- | -- | ---|
dr10487  | 1170628 |<ul><li>- [x] </li></ul>  |
dr11900  | 1016 |<ul><li>- [x] </li></ul>  |
dr2383  | 718 |<ul><li>- [x] </li></ul>  |
dr382  | 291 |<ul><li>- [x] </li></ul>  |
dr6248  | 2346 |<ul><li>- [x] </li></ul>  |
dr689  | 9525 |<ul><li>- [x] </li></ul>  |
dr691  | 2153 |<ul><li>- [x] </li></ul>  |
dr732  | 53744 |<ul><li>- [x] </li></ul>  |
dr736  | 4155 |<ul><li>- [x] </li></ul>  |
dr737  | 11725 |<ul><li>- [x] </li></ul>  |
dr837 | 29220 |<ul><li>- [x] </li></ul>  |

### 3. Has duplicate keys

datasetID  | recordCount | Resolution |
-- | -- | -- |
dr1030  | 2663|<ul><li>- [x] </li></ul>  |
dr10487  | 1170628|<ul><li>- [x] </li></ul>  |
dr1089  | 3381819|<ul><li>- [x] </li></ul>  |
dr1132  | 1116785|<ul><li>- [x] </li></ul>  |
dr11900  | 1016|<ul><li>- [x] </li></ul>  |
dr130  | 214158|<ul><li>- [x] </li></ul>  |
dr1864  | 132035|<ul><li>- [x] </li></ul>  |
dr1902  | 270527|<ul><li>- [x] </li></ul>  |
dr2270  | 14352|<ul><li>- [x] </li></ul>  |
dr2287  | 550247|<ul><li>- [x] </li></ul>  |
dr2383  | 718|<ul><li>- [x] </li></ul>  |
dr340  | 1541734|<ul><li>- [x] </li></ul>  |
dr344  | 823543|<ul><li>- [x] </li></ul>  |
dr359  | 11635460|<ul><li>- [x] </li></ul>  |
dr376  | 4904028|<ul><li>- [x] </li></ul>  |
dr570  | 749213|<ul><li>- [x] </li></ul>  |
dr571  | 2712345|<ul><li>- [x] </li></ul>  |
dr6248  | 2346|<ul><li>- [x] </li></ul>  |
dr673  | 513 |<ul><li>- [x] </li></ul>  |
dr689  | 9525|<ul><li>- [x] </li></ul>  |
dr691  | 2153|<ul><li>- [x] </li></ul>  |
dr732  | 53744|<ul><li>- [x] </li></ul>  |
dr736  | 4155|<ul><li>- [x] </li></ul>  |
dr737  | 11725|<ul><li>- [x] </li></ul>  |
dr745  | 1289|<ul><li>- [x] </li></ul>  |
dr837  | 29220|<ul><li>- [x] </li></ul>  |

To generate this information, we've written a  tool to generate a report on this [129_dwca_parallel_loading branch](https://github.com/gbif/pipelines/tree/129_dwca_parallel_loading)

This can be considered part of #128 

c @sadeghim @peggynewman

**Comment by peggynewman** [comment]
All of the drs listed under the **blank keys** section with the exception of dr382 is also listed under the **duplicate keys** section
Bit of analysis on this in a teams spreadsheet: under Atlas of Living Aust/General/Data/data cleansing/
Work in progress

**Comment by peggynewman** [comment]
dr2009 has been reloaded in prod, is it loading successfully in pipelines?

**Comment by djtfmartin** [comment]
@peggynewman currently no. The validation reports **9,592,847 duplicate keys**.

**Comment by djtfmartin** [comment]
Current status list of datasets we are unable to load


datasetID | records | indexed | status | emptyKeyRecords | duplicateKeyCount | duplicateRecordKeyCount
-- | -- | -- | -- | -- | -- | --
dr1030 | 2663 |   | HAS_DUPLICATES |   | 4 | 8
dr1089 | 3381819 |   | HAS_DUPLICATES |   | 37 | 15431
dr1132 | 1116785 |   | HAS_DUPLICATES |   | 116 | 1215
dr130 | 214114 |   | HAS_DUPLICATES |   | 1 | 2
dr139 | 129 |   | HAS_DUPLICATES |   | 3 | 6
dr15863 | 806417 |   | HAS_DUPLICATES |   | 2 | 4
dr1864 | 132035 |   | HAS_DUPLICATES |   | 23413 | 56728
dr1902 | 303105 |   | HAS_DUPLICATES |   | 3 | 6
dr2270 | 14352 |   | HAS_DUPLICATES |   | 3159 | 12805
dr807 | 81299 |   | HAS_DUPLICATES |   | 20298 | 70007
dr10487 | 1170628 |   | HAS_EMPTY_KEYS | 1170628 | 1 | 1170628
dr11900 | 1016 |   | HAS_EMPTY_KEYS | 1016 | 1 | 1016
dr2009 | 20001649 |   | HAS_EMPTY_KEYS | 9592847 | 1 | 9592847
dr2383 | 718 |   | HAS_EMPTY_KEYS | 718 | 1 | 718
dr6248 | 2346 |   | HAS_EMPTY_KEYS | 2346 | 1 | 2346
dr689 | 9525 |   | HAS_EMPTY_KEYS | 36 | 2277 | 4660
dr691 | 2153 |   | HAS_EMPTY_KEYS | 3 | 427 | 2149
dr732 | 53744 |   | HAS_EMPTY_KEYS | 1430 | 1 | 1430
dr736 | 4495 |   | HAS_EMPTY_KEYS | 2089 | 1 | 2089
dr737 | 12233 |   | HAS_EMPTY_KEYS | 6279 | 1360 | 9849

**Comment by javier-molina** [comment]
@peggynewman, @djtfmartin, Mahmoud created #135 which I think still needs to be actioned to fix the issues reported.

**Comment by peggynewman** [comment]
Thanks for the report @djtfmartin 
The fixes we have in play are:
dr2009 @patkyn will have a look at when she gets back from leave
dr10487 @m-hope and @CorinnaPaeper are looking at
dr1132 I am working with Wildnet on a full refresh
dr15863 Will assign to @nielsklazenga 
dr1902 Questagame - I've gotten permission to remove the dud records that are causing this error

So that leaves us to maybe look at (datasets > 50K):
dr1089 NSW Bird Atlassers - old dataset from 2014, 3.4m records
dr1864 - IMOS Seals data - this is a much larger dataset that has been cleaned up, will follow up with IMOS
dr807 NIWA - 80K records, from 2013
dr732 - Northern Gulf Fauna Survey, from 2013

**Comment by nielsklazenga** [comment]
I think dr15863 should be okay now. The duplicate rowkeys were only in the `occ` table, not in the `occ_uuid` table (which will have caused the duplication).

**Comment by patkyn** [comment]
dr2009 - this is fixed now. Occurrence Id key should not be empty after the old records are deleted.

**Comment by peggynewman** [comment]
@djtfmartin we're still checking the ebird dataset but the records deleted from `occ` still have entries in `occ_uuid` ... does this matter? will the `occ_uuid` table be migrated across from Cassandra?

**Comment by djtfmartin** [comment]
@peggynewman sorry - i missed your comment. Yes, the `occ_uuid` is migrated. This work is all done and there is a jenkins job for this migration.

**Comment by peggynewman** [comment]
The last outstanding dataset in this issue is dr1864 - 132K records of seal tracking data from 2007-2014.
https://www.gbif.org/dataset/0471f28e-b58b-4c02-89e4-d2a1d621a9d8 2007-2014.
Added a ticket to the Data Management board to address this.
