### ISSUE TITLE
ebird dr2009 occ_uuid mapping for new unique keys

### ISSUE THREAD

**Issue by sadeghim** [AtlasOfLivingAustralia/la-pipelines#135]
ebird has change the unique key from `catalogNumber` to `occurrenceID` (tlasOfLivingAustralia/data-management#523) . 

This issue is for tracking the population of the new key mapping in the `occ_uuid`.

**Comment by sadeghim** [comment]
Closed by mistake

**Comment by peggynewman** [comment]
eBird data has been reloaded, with keys remapped. It's worth testing this again now to see if there are issues with the export.
