### ISSUE TITLE
Create disaster recovery plan

### ISSUE THREAD

**Issue by javier-molina** [AtlasOfLivingAustralia/la-pipelines#136]
- [ ] How to rebuild system using Ansible
- [ ] Configure regular backups - TBC Frequency
- [ ] Execute plan by recreating systems and restoring backups

Out of Scope
Persistence of source DwCAs. 

What to back up:

- UUIDS
- Cassandra DB
- Jenkins jobs
- ~~Solr index~~
- ~~Latest version of AVRO files~~

**Comment by matthewandrews** [comment]
Backups now running nightly for UUIDs, Cassandra, and shared storage used by data management.  Yet to do: Jenkins jobs.

**Comment by javier-molina** [comment]
Closing this.

Jenkins back ups will be tracked on #493
