### ISSUE TITLE
Source occurrence data from Solr only

### ISSUE THREAD

**Issue by javier-molina** [AtlasOfLivingAustralia/la-pipelines#138]
- [ ] Confirm whether biocache-service keeps sourcing occurrence data from Cassandra for its operation
- [ ] Any functionality that still touches Cassandra for occurrence data only needs to be updated to source the data from Solr instead.

**Comment by nickdos** [comment]
> Confirm whether biocache-service keeps sourcing occurrence data for its functions.

@javier-molina - I'm not sure what "data" and "functions" this relates to. Did you mean to reference SOLR perhaps? I think it needs a bit more detail provided.

**Comment by javier-molina** [comment]
@nickdos I updated the description of that point to "Confirm whether biocache-service keeps sourcing occurrence data from Cassandra for its operation" 

This task is all about decoupling biocache-service from Cassandra for purely pulling occurrence data.  There is a separate task #139 that has to do with making sure biocache-service can operate on a smaller Cassandra database for functions like QIDs, user assertions and other functionality that I might not be aware of.

**Comment by adam-collins** [comment]
Removed biocache-store. 

The following functionality was removed:
- ParserController.java (for sandbox)
  /parser/areDwcTerms
  /parser/matchTerms
  /parser/mapTerms
  /process/adhoc

- UploadController.java (for sandbox)
  /upload/status/{tempDataResourceUid}.json /upload/status/{tempDataResourceUid}
  /upload/charts/{tempDataResourceUid}
  /upload/charts/{tempDataResourceUid} /upload/charts/{tempDataResourceUid}.json
  /upload/layers/{tempDataResourceUid}
  /upload/layers/{tempDataResourceUid} /upload/layers/{tempDataResourceUid}.json
  /upload/customIndexes/{tempDataResourceUid}.json /upload/customIndexes/{tempDataResourceUid}
  /upload/dynamicFacets
  /upload/{tempDataResourceUid}
  /upload/post /upload/

- OccurrenceController.java (for sandbox)
  /occurrence/{dataResourceUid} method = RequestMethod.POST, upload records
  /occurrence/deleted method = RequestMethod.GET, retrieves from dellog cassandra table. No data so not in use.

- ValidationRuleController.java (Validation rule table in cassandra is empty, so not in use)
  /occurrences/{recordUuid}/validationRules /occurrences/{recordUuid}/validationRules /occurrences/{recordUuid}/assertionQueries /occurrences/{recordUuid}/assertionQueries/
  /assertions/query/add /validation/rule/add
  /validation/rules/rematch
  /assertions/query/{uuid}/apply /assertions/query/{uuid}/apply/ /validation/rule/{uuid}/apply /validation/rule/{uuid}/apply/"
  /validation/rules/{uuids} /validation/rules/{uuids}/ /assertions/queries/{uuids} /assertions/queries/{uuids}/
  /validation/rule/{uuid} /validation/rule/{uuid}/ /assertions/query/{uuid} /assertions/query/{uuid}/
  /validation/rules /validation/rules/ /assertions/queries /assertions/queries/

- removed dependency solr-core. No longer supporting EmbeddedSolrServer.

- OutlierController.java (removed cassandra lookup of jackknife outputs)
  /outlierInfo/**
  /outlier/record/{uuid}

- AdminController.java (SOLR index specific and not in use)
  /admin/ingest
  /admin/index/optimise
  /admin/modify*
  /admin/index/reindex
  /admin/isReadOnly
  /admin/refreshAuth

The initial commit is missing at least:
- SearchUtils.java convertRankAndName()
- Occurrence raw/processed comparison service.
- spatial-service sampling (special case user downloads)
- Update of tests.

Initial commit includes:
- SOLR schema versioning in SearchRequestParams. Needed something for testing.
- Cassandra keyspace and schema creation at application startup.
