### ISSUE TITLE
Prepare trimmed Cassandra database for biocache-service

### ISSUE THREAD

**Issue by javier-molina** [AtlasOfLivingAustralia/la-pipelines#139]
A new Cassandra database schema needs to be prepared once #138 is implemented which will contain only the necessary tables and columns for functions not directly related with retrieving occurrence data. 

The known functions that still require to use Cassandra are:

- [x]  QIDs
- [ ] User assertions

Question: What other functions need to be considered?

**Comment by adam-collins** [comment]
docker for cassandra3: https://github.com/AtlasOfLivingAustralia/biocache-service/blob/experimental/pipelines-remove-biocache-store/src/test/docker/solr7-cassandra3.yml
Default cassandra store 'biocache' creation: https://github.com/AtlasOfLivingAustralia/biocache-service/blob/experimental/pipelines-remove-biocache-store/src/main/java/au/org/ala/biocache/dao/CassandraStoreDAOImpl.java#L63

**Comment by brucehyslop** [comment]
There appears to be an error with the management of `UserAssersions` within cassandra.

The when user assertions are added they are created in the cassandra `qualityassertion` table however the retrieval of user assertions selects from the `userassertions`. 

see:
 - [AssertionController.java#L172](https://github.com/AtlasOfLivingAustralia/biocache-service/blob/3bc095cff3cbfb04b7a7728dad95f3472ce7f3b6/src/main/java/au/org/ala/biocache/web/AssertionController.java#L172)
 - [AssertionController.java#L227](https://github.com/AtlasOfLivingAustralia/biocache-service/blob/3bc095cff3cbfb04b7a7728dad95f3472ce7f3b6/src/main/java/au/org/ala/biocache/web/AssertionController.java#L227)

The `QueryAssertion` should be added to the `UserAssertions` and stored.

**Comment by brucehyslop** [comment]
@djtfmartin there is inconsistent use of field `class` and `classs`

There are:
 - 17699358 occurrences with both `class` and `classs` fields
 - 41277 occurrences with only `class`
 - 69017093 occurrences with only `classs`

Currently the mapping is `class` -> `class`

**Comment by djtfmartin** [comment]
I suspect `classs` is coming from the DwCA exports and we should probably clean that up in the migration (i.e. map to `class`).

cc @sadeghim

**Comment by brucehyslop** [comment]
Also is might be a bit late for this but change the field name for `rankID` to `taxonRankID` to keep consistency with the `taxonRank` field name.

**Comment by djtfmartin** [comment]
@brucehyslop I've changed pipelines so that the indexed field name is now `taxonRankID` for consistency.
