### ISSUE TITLE
Some dates from BiocacheStore cannot be parsed

### ISSUE THREAD

**Issue by qifeng-bai** [AtlasOfLivingAustralia/la-pipelines#140]
Those dates were collected from 10000 records in Biocache-Store

I also created a google sheet: 
https://docs.google.com/spreadsheets/d/12ekXON-aFJMCCTjxuyE7Ff7EqK98OUT0a8dLfAoVvpk/edit?usp=sharing

19-Feb-85.   
Nov 2001
Apr-85
0/5/1995
Feb
Autumn 2007
2-8 Oct. 1999
[1975-1985]
00/00/1954
26 Nov.-6 Dec. 2000.   
Aug.
[probably 1911]
Unknown {13 Jan}
1920's
c. 1963
Dec. 1915-Jan. 1916
Jan-Feb 1855
1982 ?
/09/1960
9 [=September]
19760000
"2013-03-16
28-September-1999
12-13 Apr. 1993
before 1917

**Comment by qifeng-bai** [comment]
Supported:  03/04/08.  - mm/dd/yy or dd/mm/yy  two digits year

**Comment by javier-molina** [comment]
thanks @qifeng-bai I added this as part of the data cleansing epic.

Is this the whole list of offending dates from prod? is this an aggregation or is it a list per record?  Would it be better to keep this in a spreadsheet as I see a decision need to be made on a case by case basis.

Finally do you expect any special treatment to address this dates or is it a matter of asking @peggynewman to help us make some decisions and possibly have @sadeghim fix records in prod as it has happened recently with other tasks?

**Comment by qifeng-bai** [comment]
@javier-molina Not all, I think. I have tested 10,000 records. That is what we have found so far. Since hundreds of same date format, like 2/3/08 have been found, we need to remove those duplicated cases, then we can test more dates

**Comment by javier-molina** [comment]
https://dwc.tdwg.org/terms/#dwc:eventDate

**Comment by peggynewman** [comment]
I doubt we would be applying data cleansing - Mahmoud hasn't updated data, but instead has made changes in our collectory to the unique identifier nominated for the dataset.

**Comment by qifeng-bai** [comment]
Current  TemporalInterpreter is using a  TextDateParser : inherited from:  org.gbif.common.parsers.date.TemporalParser

A standard Java TemporalAccssor instance is returned in key parse method:
ParseResult<TemporalAccessor> parse(String var1);
-which I don’t think TemporalAccssor can contain date range. 

Also I found line 521 in TemporalInterpretTest.java

assertResult(YearMonth.of(1999, 01), interpretEventDate("1999-01/1999-12"));

The date range string get parsed, but only return the start date, but not end date.

-------------------------

Another parser supporting date ranges (you mentioned) is 
org.gbif.pipelines.parsers.parsers.temporal.TemporalParser

An instance of ParsedTemporal supporting date range is returned
org.gbif.pipelines.parsers.parsers.temporal ParsedTemporal parse(String rawDate)
Seems org.gbif.pipelines.parsers.parsers.temporal.TemporalParser is used in a few of test cases, but not used in GBIF TemporalInterpreter
Correct me if I am wrong.

**Comment by qifeng-bai** [comment]
Issue: https://github.com/AtlasOfLivingAustralia/la-pipelines/issues/147  to support date range.

And throws invalid date assertion if a supplied date cannot be recognised.

**Comment by javier-molina** [comment]
A comment I shared with Bai about this:

> I was under the impression that 140 need it to be closed stating that unparsable dates are not a showstopper and will continue to generate assertions during interpretation in a similar way as biocache-store does.
