### ISSUE TITLE
ALA Location data assertions issues and questions

### ISSUE THREAD

**Issue by RobinaSanderson** [AtlasOfLivingAustralia/la-pipelines#141]
In trying to reconcile the ALA/GBIF mapping spreadsheet with the Data Quality Checks spreadsheet, I found some discrepancies. After checking with @qifeng-bai  we have found the following issues and questions.  The assertion numbers below are from the data Qualilty Checks spreadsheet https://docs.google.com/spreadsheets/d/1tAfQUsIzUNfa6Tn5Ezq2cfbMVB0QeXIyp7N0We2lBAY/edit?hl=en&hl=en&hl=en#gid=0 I've coloured the assertions this issue relates to purple in the spreadsheet. I'll remove the colours when the issue is resloved.

1. **Data assertions present in biocache, and listed as supported in the spreadsheet, but not in the pipelines implementation:**
Assertion 20 Row 21 - DETECTED_OUTLIER_ENVIRONMENTAL
Assertion 26 Row 28 - SPECIES_OUTSIDE_EXPERT_RANGE

2. **Data assertions present in spreadsheet and listed as supported but not in Location Interpreter. Are these still supported in biocache and needed?**
Assertion 36 Row 38 - COORDINATE_UNCERTAINTY_IN_METERS - this is currently used in the data quality filters
Assertion 39 Row 41 - DETECTED_OUTLIER_JACKKNIFE - there is an assertion called DETECTED_OUTLIER is this the same thing?
Assertion 49 Row 51 - DECIMAL_LAT_LONG_CALCULATED_FROM_EASTING_NORTHING
Assertion 50 Row 52 - DECIMAL_LAT_LONG_CALCULATION_FROM_EASTING_NORTHING_FAILED

3. **Data assertions present in spreadsheet and listed as not supported. Can we confirm these are not used?**
Assertion 41 Row 43 - INFERRED_FALSE_PRECISION
Assertion      Row 57 - COORDINATE_DECIMAL_PLACES_MISMATCH
Assertion      Row 58 - COORDINATE_SUSPECT_NUMBER_DECIMAL_PLACES
Assertion 55 Row 59 - SUPPLIED_COORDINATES_CONVERTED
Although all these are listed as not supported, 2 have numbers, just want to check they are no longer in use.

Bai - If I've forgotten anything please update the issue. I think you were going to look into the ones in that looked like they have just been missed (category1). We will probably need help from the Data Management team for category 2 and 3.

**Comment by RobinaSanderson** [comment]
Hi @peggynewman  - as discussed in the planning session. Let me know if I've not explained this well.

**Comment by RobinaSanderson** [comment]
From @charvolant. These assertions are not being used in Biocache:
COORDINATE_ACCURACY_INVALID (explicitly deprecated)
COORDINATE_PRECISION_UNCERTAINTY_MISMATCH (deprecated)
CONTINENT_COUNTRY_MISMATCH
CONTINENT_DERIVED_FROM_COORDINATES
DEPTH_NOT_METRIC
DEPTH_UNLIKELY
DEPTH_MIN_MAX_SWAPPED
DEPTH_NON_NUMERIC
ELEVATION_UNLIKELY
ELEVATION_NOT_METRIC
INTERPRETATION_ERROR

I'll update the Data Quality Checks spreadsheet to reflect this.

**Comment by javier-molina** [comment]
This is now mostly covered by #335, #336 #374
