### ISSUE TITLE
Implement Basic Transform extensions

### ISSUE THREAD

**Issue by javier-molina** [AtlasOfLivingAustralia/la-pipelines#146]
- [x] Collector name standardisation algorithm 
- [x] Licence

TBC what else we need to add as a result of #125

**Comment by qifeng-bai** [comment]
Changes on Collector Name related:
name | Biocache | Pipelines
-- | -- | --
David Ratkowsky (2589) | [Ratkowsky, D. David](https://github.com/AtlasOfLivingAustralia/biocache-store/blob/2bed497d30c2ea2d5240724736df0f35bd7cd36e/src/test/scala/au/org/ala/biocache/CollectorParserTest.scala#L53) | Ratkowsky, David
Hegedus, Ms Alexandra | Hegedus, A. Alexandra | Hegedus, Alexandra

**Comment by nickdos** [comment]
Commit: https://github.com/gbif/pipelines/commit/18e6168972834327c5cb42c414c04b8fa97e112c

**Comment by qifeng-bai** [comment]
GBIF currently supports three licences:

 CC0_1_0("Public Domain (CC0 1.0)", "http://creativecommons.org/publicdomain/zero/1.0/legalcode"),
  CC_BY_4_0("Creative Commons Attribution (CC-BY) 4.0", "http://creativecommons.org/licenses/by/4.0/legalcode"),
  CC_BY_NC_4_0("Creative Commons Attribution Non Commercial (CC-BY-NC) 4.0", "http://creativecommons.org/licenses/by-nc/4.0/legalcode")

For correctly parsing licence,  the source should be a valid URL

**Comment by djtfmartin** [comment]
This is done and merged.
