### ISSUE TITLE
Supporting date range in parsing EventDate and other Biocache date formats

### ISSUE THREAD

**Issue by qifeng-bai** [AtlasOfLivingAustralia/la-pipelines#147]
Current TemporalInterpreter uses a TextDateParser to parse a single date.  DwC eventCode supports a single date and date range;  https://dwc.tdwg.org/terms/#dwc:eventDate
dcterms:modified  / dwc:dateIdentified also support date range

Biocache Event (output) has the following fields:
year, month, day, 
eventDateStart, eventDateEnd - from parsed eventDate Result. 
a boolean **singleDate** indicates it is a date range or a single date

Pipeline TemporalRecord has
year, month, day, (integer)
eventDate.GTE,  (String)
eventDate.LTE. (String)

Assumption:  EventDate.GTE/LTE is equivalent with eventDateStart/End in BiocacheStore

### Tasks:

** 1979 **
| Biocache | GBIF | Expected -after discussed with @djtfmartin  |
| --- | --- | --- |
| Year: 1979  | Year:  1979 | Year: 1979 |
| Month:               null    | Month:               null   | Month:               null   |
| day:                    null | day:                    null | day:                    null |
|  eventStartDate: 1979   | eventDate.GTE:    1979-01-01 | eventDate.GTE:    1979-01-01 |
|   |  | eventDate.LTE:    1979-12-31 |

**_1979/1980_**

| Biocache | GBIF | Expected -after discussed with @djtfmartin  |
| --- | --- | --- |
| Year: 1979  | Year:  1979 | Year: 1979 |
| Month:               null    | Month:               null   | Month:               null   |
| day:                    null | day:                    null | day:                    null |
|  eventStartDate: 1979-01-01    | eventDate.GTE:    1979-01-01 | eventDate.GTE:    1979-01-01 |
| eventEndDate:   1980-01-01     | eventDate.LTE:   null | eventDate.LTE:    1980-12-31 |

**dateIdentified/modified :  _1979_**

| Biocache | GBIF | Expected | 
| --- | --- | -- |
| dateIdentified = 1979  | dateIdentified = 1979-01-01 | dateIdentified: 1979 | 
| modified = 1979  | modified = 1979-01-01 | modified: 1979 | 

Future improvement: in DwC, modified / dateIdentified both support date range. 

**1991-10-11/15**
| Biocache | GBIF | Expected | 
| --- | --- | -- |
| eventStartDate: 1991-10-11 | Null | eventDate.GTE:  1991-10-11 |
| eventEndDate: 1991-10-15 | Null | eventDate.LTE: 1991-10-15 |

----------------

Question:
Shall we set LTE for date: **1979-10-01** ?

Pipelines
Year:                  1979              
Month:               10                
day:                    1                
eventDate.GTE: 1979-10-01
**eventDate.LTE:    1979-10-01**

### Other date formats 

[Biocache supports](https://github.com/AtlasOfLivingAustralia/biocache-store/blob/develop/src/test/scala/au/org/ala/biocache/DateParserTest.scala)

Related to the issue: https://github.com/AtlasOfLivingAustralia/la-pipelines/issues/140

 |Formats|Biocache|GBIF|ALA pipelines|
 |--|--|--|--|
| "2011-09-13 09:29:08" | + | + |   |
|  "2009-02-20T08:40:01Z",| + | + |   |
 | "2009-02-20T08:40Z",| + | + |   |
| "2002-03-10T00:00:00.0"| + |  + |   |
| "2002-03-10 00:00:00.0",| + |  |   |
|  "1978-December-01",| + | + |   |
|  "2018-09-19T08:50+1000",| + | + |   |
|  "2013-11-06T19:59:14.961+1000",| + | + |   |
|  "2013-11-06T19:59:14.961",| + | + |   |
|  "2012-01-01T10:22:00",| + | + |   |
|  "2001-03-14T00:00:00-1130",| + | + |   |
|  "2001-03-14T00:00:00-11:00",| + | + |   |
|  "2001-03-14T00:00:00+11", | + | + |   |
|2004-11-01/2005-02-01|+|+  start date|+|
|  "05-02-1978"| + |  | + 1978-02-05  |
|  "1998-9-30/10-7"| + |  | +  |
|  "1998-9-7/30"| + |  | +  |
|  "1998-09-07/30"| + |  | +  |
|  "1998-09-07/10-01"| + |  | +  |
|||||
| "05/02/78",| + |  |   |
| "01/02/01",| + |  |   |
| "2011-05-00",| + |  |   |
| "Fri Aug 12 15:19:20 EST 2011",| + |  |   |
| "1978-01-",| + |  |   |
| "2011-10-31Z",| + |  |   |
| "1978/91",| + |  |   |
| "Aug-2005",| + |  |   |
| "05-02-1978 & 06-03-1979",| + | -  | +  |
| "05-02-1978 to 06-03-1979"| + | - | +  |

**Comment by qifeng-bai** [comment]
Current TemporalInterpreter is using a TextDateParser : inherited from: org.gbif.common.parsers.date.TemporalParser

A standard Java TemporalAccssor instance is returned in key parse method:
ParseResult parse(String var1);
-which I don’t think TemporalAccssor can contain date range.

Also I found line 521 in TemporalInterpretTest.java

assertResult(YearMonth.of(1999, 01), interpretEventDate("1999-01/1999-12"));

The date range string get parsed, but only return the start date, but not end date.

Another parser supporting date ranges (you mentioned) is
org.gbif.pipelines.parsers.parsers.temporal.TemporalParser

An instance of ParsedTemporal supporting date range is returned
org.gbif.pipelines.parsers.parsers.temporal ParsedTemporal parse(String rawDate)
Seems org.gbif.pipelines.parsers.parsers.temporal.TemporalParser is used in a few of test cases, but not used in GBIF TemporalInterpreter

**Comment by javier-molina** [comment]
Probably worth adding in the description that we need to preserve compatibility with what biocache-store parser currently does.

**Comment by qifeng-bai** [comment]
Conflicts:
GBIF parser set default starting month/day as 1, if day/month is missing, so 1990 will be parsed to 1990-1-1 
DwC eventDate explains 1900/1909 (some time during the interval between the beginning of the year 1900 and the end of the year 1909)

The following formats which DwC supports, but we have not yet:
 2007-11-13/15,   2007-11/12

**Comment by javier-molina** [comment]
Thanks @Bai for updating your analysis after the chat with @djtfmartin it looks to me indeed that neither Biocache store nor GBIF current parser are working as we need when it comes to intervals (ranges) and we have to come with a solution which you are tackling as we speak.

On a related note despite missing important tests like the year range (1979/1980) you showed in your analysis  I think 
[DateParserTest.scala ](https://github.com/AtlasOfLivingAustralia/biocache-store/blob/develop/src/test/scala/au/org/ala/biocache/DateParserTest.scala) does contain a good set of verbatim dates that does not conform  to ISO 8601 that we need to carry to our new implementation to make sure we are not missing any of those cases.

**Comment by qifeng-bai** [comment]
@javier-molina  My feeling is "Standard process" should be implemented into GBIF, and our ALA specific requirements can be re-tasked to https://github.com/AtlasOfLivingAustralia/la-pipelines/issues/140

**Comment by javier-molina** [comment]
https://github.com/gbif/pipelines/issues/389
