### ISSUE TITLE
Duplicate detection pipeline

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/la-pipelines#15]
Develop a pipeline for running duplication detection based on the biocache-store implementation of the duplicate detection.

This pipeline needs to be ran across all the data in one run (i.e. not just a single dataset).

For reference, the biocache code is here:

https://github.com/AtlasOfLivingAustralia/biocache-store/blob/master/src/main/scala/au/org/ala/biocache/tool/DuplicationDetection.scala

**Comment by djtfmartin** [comment]
It is likely we can reuse the clustering work GBIF has done (at least as a starting point) for duplicate detection.

**Comment by javier-molina** [comment]
A question raised in a meeting:

Is this pipeline manage linking child/related records?  

A typical example is a tissue sample record, there will be related records based on the original sample but they are not actually duplicates.

**Comment by djtfmartin** [comment]
Work is on this branch: https://github.com/gbif/pipelines/tree/15_duplicate_detection

**Comment by timrobertson100** [comment]
> Will this pipeline manage linking child/related records?

Not now, but not difficult to add

**Comment by timrobertson100** [comment]
To keep things linked, related work here https://github.com/gbif/pipelines/issues/468

**Comment by djtfmartin** [comment]
This work is done. Awaiting approval of https://github.com/gbif/pipelines/pull/460 before converting the PR https://github.com/gbif/pipelines/pull/467 from draft.

**Comment by djtfmartin** [comment]
Awaiting review of https://github.com/gbif/pipelines/pull/467

**Comment by djtfmartin** [comment]
Reviewed and Merged.
