### ISSUE TITLE
Is the Audobon Core (or Simple Multimedia) extension relevant here?

### ISSUE THREAD

**Issue by javier-molina** [AtlasOfLivingAustralia/la-pipelines#153]
Is the Audobon Core (or Simple Multimedia) extension relevant here? Will we be implementing a solution that handles this as inputs? I would like to be clear to data providers how they should provide images and image metadata.

_Originally posted by @peggynewman in https://github.com/AtlasOfLivingAustralia/la-pipelines/issues/103#issuecomment-686295946_

**Comment by djtfmartin** [comment]
GBIF have implemented some support for Audobon Core. Relevant interpretation class is here:

https://github.com/gbif/pipelines/blob/ala-dev/sdks/core/src/main/java/org/gbif/pipelines/core/interpreters/extension/AudubonInterpreter.java

The AVRO output that is persisted is here:
https://github.com/gbif/pipelines/blob/ala-dev/sdks/models/src/main/avro/extension/audubon-record.avsc

**Comment by djtfmartin** [comment]
I think can be closed. I can't see anything to action.
