### ISSUE TITLE
Support NON-ISO date formats  which current Biocache supports

### ISSUE THREAD

**Issue by qifeng-bai** [AtlasOfLivingAustralia/la-pipelines#154]
We plan to add a string preprocess to convert those formats to ISO date formats, by this mean, we can avoid to increase the complexity of our current date parser.

This task may need  Data team's effort on identifying those formats which we need to support.

 |Formats|Biocache|GBIF|ALA pipelines| pipeline |Required |
 |--|--|--|--| -- | --- |
| "2011-09-13 09:29:08 | + | + |   |   +|
|  "2009-02-20T08:40:01Z| + | + |   | +  |
 | "2009-02-20T08:40Z| + | + |   |  + |
| 2002-03-10T00:00:00.0| + |  + |   | +  |
| 2002-03-10 00:00:00.0| + |  Bug in GBIF |   | +  |
|  1978-December-01| + | + |   |  + |
|  2018-09-19T08:50+1000| + | + |   |  + |
|  2013-11-06T19:59:14.961+1000| + | + |   |   +|
|  2013-11-06T19:59:14.961| + | + |   |  + |
|  2012-01-01T10:22:00| + | + |   |  + |
|  2001-03-14T00:00:00-1130| + | + |   |  + |
|  2001-03-14T00:00:00-11:00| + | + |   | +  |
|  2001-03-14T00:00:00+11| + | + |   |   +|
|2004-11-01/2005-02-01|+|+  start date|+|+   |
|  05-02-1978| + |  | + 1978-02-05  | +  |
|  1998-9-30/10-7| + |  | +  |  + |
|  1998-9-7/30| + |  | +  |  + |
|  1998-09-07/30| + |  | +  | +  |
|  1998-09-07/10-01| + |  | +  | +  |
| 05-02-1978 & 06-03-1979| + | -  | +  |   |
| 05-02-1978 to 06-03-1979| + | - | +  |   |
| **String Preprocess** |
| 05/02/78| + |  |   |   |
| 01/02/01| + |  |   |   |
| 2011-05-00| + |  |   |   |
| Fri Aug 12 15:19:20 EST 2011| + |  | +  |   |
| 1978-01-| + |  |   |   |
| 2011-10-31Z| + |  |   |   |
| 1978/91| + |  |   |   |
| Nov 2001 |  |  | + | |
| Aug-2005| + |  | +  |   |

**Those dates Pipelines does not support / Biocache may/may not supports**
From: https://github.com/AtlasOfLivingAustralia/la-pipelines/issues/140
| |  Required? |
| ---| --- |
| 19-Feb-85. |  |
| Apr-85 |  |
| 0/5/1995 |  |
| Feb |  |
| Autumn 2007 |  |
| 2-8 Oct. 1999 |  |
| [1975-1985] |  |
| 00/00/1954 |  |
| 26 Nov.-6 Dec. 2000. |  |
| Aug. |  |
| [probably 1911] |  |
| Unknown {13 Jan} |  |
| 1920's |  |
| c. 1963 |  |
| Dec. 1915-Jan. 1916 |  |
| Jan-Feb 1855 |  |
| 1982 ? |  |
| /09/1960 |  |
| 9 [=September] |  |
| 19760000 |  |
| "2013-03-16 |  |
| 12-13 Apr. 1993 |  |
| before 1917 |  |

**Comment by javier-molina** [comment]
As per stand up meeting discussion all relevant cases are already covered and the effort should be on actually merging all those changes back to GBIF and releasing a new version of the pipelines.

All unparsable date formats will be flagged by raise an assertion in the pipelines.

A separate analysis task for unparable dates in current production data will be created shortly.

**Comment by qifeng-bai** [comment]
GBIF and Atalas both have the needs to handle some irregular dates

Here is the solution what Nikolay and I came up with:  

In TemporalTransform, a dateString preprocess will be executed before interpretTemporal
  `.via(temporalInterpreter::normalisation)`
`.via(temporalInterpreter::interpretTemporal)`

Normalisation process relies on Map<String, String>> mapSupplier to do string / regex replacement.
A simple example:

 Map<String, String> seps = new java.util.HashMap<String, String>() {{
      put(" & ", "/");
      put(" to ", "/");
    }}; 

this Map will be injected into normalisation process to convert 1999-01-02 to 1999-02-01  to  1999-01-02/1999-02-01

Finally, the content of map can be loaded to Text file defined in config

**Comment by qifeng-bai** [comment]
GBIF add a FI to support possible  date string reformatting, which means current date reformatting code in ALA-dev need to rewritten. 

Here is an example:
` SerializableFunction<String, String> fn =
        v -> {
          if (StringUtils.isNotEmpty(v)) {
            return v.replaceAll(" & ", "/");
          }
          return v;
        };`



    TemporalInterpreter interpreter =
        TemporalInterpreter.builder()
            .orderings(Arrays.asList(DMY_FORMATS))
            .preprocessDateFn(fn)
            .create();
    interpreter.interpretTemporal(er, tr);

**Comment by javier-molina** [comment]
Pipeline column in description has all the supported formats implemented as part of #158, any other format will be flagged.

Any format deemed need it, possibly because it is a common format will need to be raised on a separate ticket.
