### ISSUE TITLE
Identify records with invalid dates in production

### ISSUE THREAD

**Issue by sadeghim** [AtlasOfLivingAustralia/la-pipelines#157]
Need to analyse date fields including `eventDate`, `dateIdentified` and `modified` to identify problematic records.

**Comment by sadeghim** [comment]
http://aws-sc1b.ala:8983/solr/biocache/select?fl=id,verbatim_event_date,occurrence_date&fq=assertions:%22invalidCollectionDate%22&indent=on&q=verbatim_event_date:*&fq=occurrence_date:*&rows=100&wt=json 
gives us the records having a `invalidCollectionDate` flag while it has processed the given `eventDate`.

**Comment by javier-molina** [comment]
No longer required.

Temporal transform didn't require this analysis at the end.
