### ISSUE TITLE
Environmental outlier detection pipeline

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/la-pipelines#16]
Develop a pipeline for running environmental distribution outlier detection based on the biocache-store implementation of the jacknife algorithm.

This pipeline needs to be ran across all the data in one run (i.e. not just a single dataset). 

It will make use of spatial distribution polygons for species stored in the spatial-service (https://spatial.ala.org.au/ws/).

Relevant code in biocache-store is:

https://github.com/AtlasOfLivingAustralia/biocache-store/tree/master/src/main/scala/au/org/ala/biocache/outliers

The algorithm is here:

https://github.com/AtlasOfLivingAustralia/biocache-store/blob/master/src/main/scala/au/org/ala/biocache/outliers/JackKnife.scala

**Comment by adam-collins** [comment]
https://github.com/gbif/pipelines/tree/16_jackknife

**Comment by djtfmartin** [comment]
This has been reviewed and merged
