### ISSUE TITLE
AVH fields in biocache 

### ISSUE THREAD

**Issue by peggynewman** [AtlasOfLivingAustralia/la-pipelines#161]
This is a list of all non-DwC fields with record counts. Many of them are suspected to be attributable to AVH.

https://drive.google.com/file/d/1ze8lh3Y2hG--6ZbziVM3iIe0XNezHY2Y/view?usp=sharing

In the pipelines project the fields will be migrated to the DwCAs, but we should clarify whether to include them in the final index. Are they in use? Do they need to be exposed in future? Is there a subset that would suffice?

**Comment by nielsklazenga** [comment]
I only recognise a handful of these as former AVH fields. They have not been used for the last five years or so. I do not need them in the final index and, once we have full data set replacement, they will disappear from the DwCAs as well.

The ABCD loan-related fields are now in the GGBN Loan extension and I still hope to get typifiedName into Darwin Core some time.

**Comment by sadeghim** [comment]
Here is the list:
- [ ] `australianHerbariumRegion`
- [ ] `preferredFlag`
- [ ] `naturalOccurrence`
- [ ] `duplicates`
- [ ] `cultivarName`

**Comment by nielsklazenga** [comment]
Ah, you had #169 in the Google Sheet.

AVH field | Map to
-|-
loanDestination | http://data.ggbn.org/schemas/ggbn/terms/loanDestination
loanIdentifier | http://data.ggbn.org/schemas/ggbn/terms/loanIdentifier
loanDate | http://data.ggbn.org/schemas/ggbn/terms/loanDate

The rest has not been used for years and should not be used anymore.
