### ISSUE TITLE
secondaryCollectors from biocache

### ISSUE THREAD

**Issue by sadeghim** [AtlasOfLivingAustralia/la-pipelines#169]
- [x] `secondaryCollectors` -> `http://hiscom.chah.org.au/hispid/terms/secondaryCollectors`
it's part of #161

**Comment by nielsklazenga** [comment]
AVH field | Map to
-|-
loanDestination | http://data.ggbn.org/schemas/ggbn/terms/loanDestination
loanIdentifier | http://data.ggbn.org/schemas/ggbn/terms/loanIdentifier
loanDate | http://data.ggbn.org/schemas/ggbn/terms/loanDate

The rest has not been used for years and should not be used anymore.
