### ISSUE TITLE
Expert distribution outlier detection pipeline

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/la-pipelines#17]
Develop a pipeline for running expert distribution outlier detection.
This pipeline can be ran at a single dataset at a time and needs to make use of spatial distribution polygons for species stored in the spatial-service (https://spatial.ala.org.au/ws/).

Distributions are accessible via this webservice

```
https://spatial.ala.org.au/ws/distributions
```

**Comment by javier-molina** [comment]
@djtfmartin  have confirmed expert distribution outlier detection has not ran in production for 2 to 3 years, the current process is broken.

I have asked @peggynewman to start the conversation with the DM team and anyone in the wider ALA team that can shed some light on whether this functionality it is still required moving forward.

**Comment by djtfmartin** [comment]
I think we have decided via steering committee this issue will not be tackled. Suggest we can close.

**Comment by javier-molina** [comment]
Thanks @djtfmartin this slipped from my TODO list

An outcome from  2020-12-01 Reference Group session was:

Expert distribution outlier detection  won't be implemented as part of the Infrastructure Upgrade project.
