### ISSUE TITLE
Configure Jenkins jobs to start/stop Spark and Solr clusters

### ISSUE THREAD

**Issue by javier-molina** [AtlasOfLivingAustralia/la-pipelines#179]
Work has been done to move Jenkins to a separate VM. What is needed now is:

 Jenkins job for starting spark/hdfs cluster VMs and then starting/stopping spark/hdfs
 Jenkins job for starting SOLR

**Comment by djtfmartin** [comment]
Work has been done to move Jenkins to a separate VM. What is needed now is:

- [ ] Jenkins job for starting spark/hdfs cluster VMs and then starting/stopping spark/hdfs
- [ ] Jenkins job for starting SOLR
