### ISSUE TITLE
Will loading images included in the Dwca zip files end up in duplicates?

### ISSUE THREAD

**Issue by sadeghim** [AtlasOfLivingAustralia/la-pipelines#180]
Scenario is that if we have multiple dwca zip files with images included inside the zip files, and the file names are same in different zip files. What will happen to the image identifiers? Will we have duplicates? What is the load procedure?

**Comment by javier-molina** [comment]
Short answer is No.

A consideration mentioned by Peggy in past conversations it the idea to stop supporting zip files with images in favour of sourcing images from an external resource (URLs).

Having an additional pair of eyes to go through #182  will help clarify these an related questions around image loading.
