### ISSUE TITLE
Performance testing image loading 

### ISSUE THREAD

**Issue by javier-molina** [AtlasOfLivingAustralia/la-pipelines#182]
- [ ] Source representative Data resources

- [ ] Run images load and capture performance metrics

Currently biocacache store / image-service load images in production at a rate of 1000 images every 30 min.

**Comment by javier-molina** [comment]
Once Dave updates the environment Mahmoud should be able to give it a spin and test the current pipelines interpretation with the latest test image service.

**Comment by djtfmartin** [comment]
As a starting point, here are some numbers from tests on AWS.

The test archive isn't representative of a source archive as its our export from Cassandra with URLs pointing at production image service. Note: these timings don't include the time taken to generate all artefacts (thumbnails, tiles).  These are generated asynchronously.

### Clean load - empty DB

Test dataset |  Image entries in DwCA | Number of unique images | Time taken | Storage
-------------| -------------|-------------|-------------|-------------
dr893 |  72,368 |  71,199 | 1 hr 19 mins | S3
dr893 |  72,368 |  71,199 | 38 mins | Block


### Reload of same dataset

This is a reload of the same dataset, but as the images are already loaded its affectively just checking the metadata is in sync.

Test dataset |  Image entries in DwCA | Number of unique images | Metadata updates | Time taken | Storage
-------------| -------------|-------------|-------------|-------------|-------------
dr893 |  72,368 |  0 | 0 |  54 secs | S3
dr893 |  72,368 |   0 | 0 |  54 secs | Block

**Comment by javier-molina** [comment]
#251 is already covering automated tests for this
