### ISSUE TITLE
Check impact of index switching on current biocache queries

### ISSUE THREAD

**Issue by javier-molina** [AtlasOfLivingAustralia/la-pipelines#183]
See [2020-10-21 Meeting notes - Index Management and Switching](https://confluence.csiro.au/display/CIU/2020-10-21+Meeting+notes+-+Index+Management+and+Switching) for background info.

- [x] Confirm what is the behaviour when a large download (taking more than 1 hour to process) is running while a new index is swapped?

- Will the download fail? (Empirically it is understood that's not the case)
- Will the cursor source data from the old collection until the download finishes or will it mix results from the old and new collection?

Related to #25

**Comment by djtfmartin** [comment]
This has been tested in the NCI test environment. 
It was tested by:
1) Creating a full collection in SOLR of 88m records - `Collection A`
1) Creating a blank collection in SOLR - `Collection B`
1) Starting a large download (2.5 million records)
1) Waiting for the download to be pulled from the queue, set to a status of `running` and for some records to be written to file
1) Deleting the existing alias in SOLR through the SOLR admin API (or UI console)
1) Creating the alias to point at the empty SOLR

The behaviour we see is that the download continues to use `Collection A` for the life of the download even when the alias has been deleted and recreated to point to another collection.

This is a non-issue and can be closed.
