### ISSUE TITLE
 DwC and Dublin core fields currently in Miscellaneous Properties

### ISSUE THREAD

**Issue by RobinaSanderson** [AtlasOfLivingAustralia/la-pipelines#184]
There are new DwC fields that are currently stored in the Cassandra miscProperties field:

- RecordedByID
- IdentifiedByID
- ParentEventID

There are also Dublin Core fields stored in the Cassandra miscProperties field:

- type

The current plan for the pipeline implementation is to migrate these to the DynamicProperties field. 

To comply with DwC, and to stay consistent with GBIF, these fields should be moved out of DynamicProperties and into separate fields.

Example from Mahmoud:
select "miscProperties" from occ.occ where rowkey='a6164fce-c426-4d7e-ae64-be3a134584cd';
 miscProperties

 {"identifiedByID":"http://www.wikidata.org/entity/Q26912975","recordedByID":"https://orcid.org/0000-0003-2224-6821%7Chttp://www.wikidata.org/entity/Q26912975","parentEventID":"14th Australian Bryophyte Workshop","type":"PhysicalObject"}

**Comment by javier-molina** [comment]
Check with @peggynewman and @sadeghim

**Comment by javier-molina** [comment]
@sadeghim can you confirm that this has been addressed in the export from Cassandra?

**Comment by sadeghim** [comment]
@javier-molina my suggestion is to have a check in `dynamicProperties` interpretation in pipelines to extract these fields out  and process it as separate main field. 

If that's not doable/feasible, we will need to process each DwcA in DM and add that logic as a pre-ingestion step in jenkins. 
@peggynewman what do you think? Or @djtfmartin

**Comment by peggynewman** [comment]
Didn't this ticket only apply to the migration DwCAs? I don't see that anything else needs to be done.

**Comment by djtfmartin** [comment]
I agree @peggynewman 

I think this can marked as done.
