### ISSUE TITLE
Indexing dynamicProperties as a JSON field

### ISSUE THREAD

**Issue by sadeghim** [AtlasOfLivingAustralia/la-pipelines#185]
Indexing `dynamicProperties` as a json field in solr will reduce the complexity of the current indexing approach. We won't need any schema updates if the fields in `dynamicProperties` change.

refs:
https://lucene.apache.org/solr/guide/8_6/transforming-and-indexing-custom-json.html
https://lucene.apache.org/solr/guide/8_6/indexing-nested-documents.html

**Comment by djtfmartin** [comment]
I've looked into this, but I'm not clear on where to take it. 

I'm not seeing any real benefits to using nested documents for dynamic properties as there isn't a one-to-many relationship here.
For now, I'm indexing all properties in the `dynamicProperties` field using a SOLR dynamic field(s), so there isn't a requirement to update the schema as such.

**Comment by sadeghim** [comment]
@djtfmartin Thanks for the comment,

I think that I misunderstood the json indexing on Solr. There is no json field type in Solr.
The way that this can be done is using:
https://lucene.apache.org/solr/guide/8_8/transforming-and-indexing-custom-json.html#using-wildcards-for-field-names

This way the ingested field will be `dynamicProperties.prop1` compared to what we have something like `_prop1'. I think that the former is more standard and user friendly than the latter.

**Comment by javier-molina** [comment]
Dynamic properties are already being indexed in by the LA Pipelines
