### ISSUE TITLE
dr14171 is both a species list and data resource containing data

### ISSUE THREAD

**Issue by peggynewman** [AtlasOfLivingAustralia/la-pipelines#186]
https://lists.ala.org.au/speciesListItem/list/dr14171
https://biocache.ala.org.au/occurrences/search?q=data_resource_uid%3Adr14171
https://collections.ala.org.au/dataResource/show/dr14171

find out where this data came from and try to find a better home for it.

**Comment by sadeghim** [comment]
All these records are ingested in another DR: https://biocache.ala.org.au/occurrences/search?q=data_resource_uid:dr15912
**Marine fauna sightings within Australian marine parks during surveys by the company BMT, Western Australia (2019) **

These records are deleted now.
