### ISSUE TITLE
dr807 - add unique key

### ISSUE THREAD

**Issue by peggynewman** [AtlasOfLivingAustralia/la-pipelines#187]
• Extract dataset
	• Check for unique key - which fields ?
	• Update occ.occ_uuid mappings
	• Set unique key in collectory

**Comment by sadeghim** [comment]
`catalogNumber` is chosen as the unique key in collectory, and `occ.occ_uuid` updated accordingly.

**Comment by djtfmartin** [comment]
This dataset cant be loaded in pipelines due to duplicate key issues.

**Comment by peggynewman** [comment]
resolved in production
https://biocache.ala.org.au/occurrences/search?q=data_resource_uid%3Adr807
