### ISSUE TITLE
dr376 MEL AVH Duplicate keys

### ISSUE THREAD

**Issue by sadeghim** [AtlasOfLivingAustralia/la-pipelines#191]

**Comment by sadeghim** [comment]
|rowkey                              |catalogNumber| Resolution |
|------------------------------------|-------------|--|
|[c1984ae7-ecaf-4480-a69e-b4e1d33627d9](https://biocache.ala.org.au/occurrences/c1984ae7-ecaf-4480-a69e-b4e1d33627d9)|MEL 1578087A | |
|[db4878a5-df33-4903-a985-e4b8baeddc62](https://biocache.ala.org.au/occurrences/db4878a5-df33-4903-a985-e4b8baeddc62)|MEL 1578087A | |
|[e50272ad-1d34-42dd-b8d8-c3a196dd7a94](https://biocache.ala.org.au/occurrences/e50272ad-1d34-42dd-b8d8-c3a196dd7a94)|MEL 2152861B | |
|[ab4b00a4-d845-487f-b380-94b5b37f3d08](https://biocache.ala.org.au/occurrences/ab4b00a4-d845-487f-b380-94b5b37f3d08)|MEL 2152861B | |

**Comment by sadeghim** [comment]
@ansell @peggynewman @patkyn FYI:

This means that we have changed the unique key in DR and dropped the CollectionCode and only CatalogNumber is left there. Then deleted the old records and ingested the new ones. 
But due to a bug in the biocache-store (dropping a couple of records here and there for each DR during processing/indexing), these are the records escaped from the removal process.
Going to delete them.

I guess this will be a common issue if we have deleted the whole DR and we have changed the unique keys.

**Comment by ansell** [comment]
@sadeghim Yes, the indexing bug is insidious. Will just need to clean up these cases as they show up. From the statistics we have been gathering the indexing bug should only be affecting a few records each day.

Are they easy to identify with the last load date field?

**Comment by sadeghim** [comment]
@ansell here is the query that I ran:
```scala

scala> spark.sql("SELECT  count(rowkey) FROM  vw_occ_uuid WHERE instr(rowkey,'dr376|MEL|MEL') = 1").show(100, false)
+-------------+
|count(rowkey)|
+-------------+
|930281       |
+-------------+
```

But only 2 of them are still in the `occ.occ`.

The problem wth the date is that we don't really know when this has happened unless we identify those duplicates which may have different load dates and it won't be easy to identify.

I will run some queries to find the duplicates and remove the wrong records. But this means we need to be sure that remove records by query will need to be run against a multiple indexes in consequent days to clean-up any residual records..

**Comment by sadeghim** [comment]
```cql
delete from occ.occ where rowkey in ('e50272ad-1d34-42dd-b8d8-c3a196dd7a94', 'db4878a5-df33-4903-a985-e4b8baeddc62');
delete from occ.occ_uuid where rowkey='dr376|MEL|MEL2152861B';
delete from occ.occ_uuid where rowkey='dr376|MEL|MEL1578087A';
```
