### ISSUE TITLE
Field mapping spreadsheets consolidation

### ISSUE THREAD

**Issue by RobinaSanderson** [AtlasOfLivingAustralia/la-pipelines#192]
We have several spreadsheets holding information about fields and mapping relationships between GBIF pipelines code, code ALA has written to extend the pipelines code and biocache. It would be good to consolidate these spreadsheets into a single place that could be (as much as possible) automatically maintained.

We currently have the following spreadsheets:
- Cassandra-Darwin core fields - https://docs.google.com/spreadsheets/d/1DkYFLzt9377fXFBROvZbb4JK5rPinvYhcfisMU4K3jE/edit#gid=615617642 - created by Mahmoud to identify which biocache fields are also Darwin core fields
- Biocache fields for migration - https://docs.google.com/spreadsheets/d/1ze8lh3Y2hG--6ZbziVM3iIe0XNezHY2Y/edit#gid=315906871 - developed by Mahmoud when analysing the fields in use in biocache for migration
- Pipeline field mapping - https://docs.google.com/spreadsheets/d/1dyxeijtWzw6GP7Oc2kuMeuV96pQt_ivQoxKk1US6Jk4/edit#gid=1108232094 - created by Bruce as a full listing of fields indexed in pipelines, indexed in SOLR and used in biocache. Automatically generated via a script from pipelines SOLR index, biocache SOLR index and biocache fields service. Created to track the mapping between biocache fields service, existing fields in biocache index and what those fields will be in the pipeline implementation

Requirements:
1. Spreadsheet to include the following information:

- biocache service field name
- biocacche index field name
- pipelines implementation field name

2. If agreed, should also include:

- whether the field is a Darwin core field
- biocache fields that will be migrated and field name of the migrated fields in the pipeline implementation (assumed these will all be indexed, but if not include whether or not indexed)
- biocache fields that will be deprecated
- comments or decision column documenting any changes to the field and any further information

3. Automatic update of the field listing - this would mean that the additional information in point 2 would needs to be held in such a way that there could be a lookup from an unchanging piece of information to get these details (maybe the biocache SOLR index field name -  depends whether there are fields in biocache that aren't indexed?)

4. Store in a place accessible to all the ALA  - does this also need to be accessible to the Living Atlas community and GBIF?

**Comment by brucehyslop** [comment]
I've created a new spreadsheet for pipeline field mappings including the full list of Darwin Core fields. 
This link [pipeline_field_mappings.ods](https://drive.google.com/file/d/1bFGSKif3dB9PQmmQ7IwyYM2PDLnzGFf0/view) is the OpenDocument Spreadsheet with a link that should not change when the spreadsheet version is changed. Unfortunately the google drive preview of this spreadsheet does not show the conditional formatting or the column filters to help analyse the mappings. 

This link [pipeline_field_mappings](https://docs.google.com/spreadsheets/d/1fd-JrZBIIuy8PyqZcpfTsXgchlRr4-ROKaen1fX_bVQ/edit?usp=sharing) is a google sheets version of the original. Unfortunately this link will change every time the underlying spreadsheet is updated. 

These sheet contain:
 - Columns A - B: pipelines Solr field name and type
 - Columns C - D: current Solr field name and type
 - Columns E - G: Darwin Core fields from TDWG
 - Columns H - V: Biocache field list https://biocache-ws.ala.org.au/ws/index/fields?isMisc=true
 - Column X: status of pipelines and current Solr field name match (one of MATCH, PARTIAL, MISSING)
 - Column Y: status of pipelines and current Solr field type match (one of MATCH, DIFF, MISSING)
 - Column Z: status of Darwin Core field name match with pipelines Solr field (one of MATCH, PARTIAL, MISSING)
 - Column AA: status of Biocache field name (either MATCH or MISSING)

Some stats of the mapping:
 - 146 Solr fields with no corresponding pipelines field
 - 66 of those are also in the biocache field list
 - 21 fields where the field type differs between Solr schemas
 - 17 Darwin Core fields where this is no field in either Solr schema

**Comment by brucehyslop** [comment]
Shared [pipeline_field_mappings.xlsx](https://csiroau-my.sharepoint.com/:x:/g/personal/hys006_csiro_au/EcFdhwyRVBFLpibkvesS0XgBS_q0hw5ZxeAWkXpRRD8qCA?e=Jf7Amh) in OneDrive which is editable online and the link will not change when the mapping process is re-run. 

This new version has two extra sheets in order to record notes on the field mappings the note can be recorded for the legacy fields and/or the pipelines fields. The notes are looked up in the and displayed in columns W & X of the pipeline_field_mappings sheet.

**Comment by brucehyslop** [comment]
The mapping file has again been moved to SharePoint [pipeline_field_mappings.xlsx](https://csiroau.sharepoint.com/:x:/r/sites/ALAInfrastructureRefresh-WP12/Shared%20Documents/General/pipeline_field_mappings.xlsx?d=w5a1723baa0104cd9bc2db35f0e7c199a&csf=1&web=1&e=bwauTC)

**Comment by brucehyslop** [comment]
New columns have been added to capture the record counts for each of the fields. 
This should be useful it inform which fields can be safely deprecated.

**Comment by javier-molina** [comment]
Mapping work will be reviewed on #53 .

It is safe to close this one
