### ISSUE TITLE
Image service - occurrenceIDs

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/la-pipelines#193]
With the pipelines / image-service integration, we are no longer updating the occurrenceID in the image-service.
As noted by @sadeghim, the storage of occurrenceID is problematic in the current implementation, as it does not cater for when an image is associated with multiple occurrences.

Required work:
Implement ajax lookup on occurrence detail pages, so that we can provide links through to the occurrence record(s).
This can be done via a biocache service query like so:

https://biocache.ala.org.au/ws/occurrences/search?q=image_url:590a25eb-bd28-442d-80ca-6fdb8280a314&fl=id

It's possible for this to return multiple results.

<img width="1650" alt="Screen Shot 2021-05-14 at 9 29 33 am" src="https://user-images.githubusercontent.com/444897/118258953-67911980-b4a8-11eb-997c-3fb9d1ede284.png">

**Comment by javier-molina** [comment]
To discuss with @sbearcsiro
