### ISSUE TITLE
dr10487- duplicate keys in Biome of Australia Soil Environments (BASE)

### ISSUE THREAD

**Issue by sadeghim** [AtlasOfLivingAustralia/la-pipelines#196]

**Comment by peggynewman** [comment]
@sadeghim 

The unique identifiers for this dataset are SampleID and OTU (X_sampleid, X_otu in the miscellaneous fields in the download)
Example values from biocache hub: 

Sample ID: 102.100.100/12495
OTU:TCACGTATCCACGTATAAACCAATTCGTGAACTGTTTTACCCCACCTCTGGGCTATGGCCGCTGTCATTTGGACGCATGAGTTCATTGTATGATTATGGACTCGTCCTTGGCAATTAAGGCTGTTTCTTCAGAGCGTATTAATCATACTTTAATCAATTAACCACTTGAACACTATGTAAATTTTCTTTGTTTGAACTGATTTGTTTCTTACTCAGCGCTGTGTAATAACGGCGCCGAGAAGAAATCGATTTACG

when I do a download, these 2 fields contain unexpected values (with loads of duplicates)
X_sample_id: Forest
X_otu: 4.36

the fields that seem to contain sample_id and otu look to be X_texture(contains otu values) and X_gravel(contains sample id values)
They don't have duplicates

All looks well in Cassandra, the fields seem to align correctly. 

Is it possible that downloads/extraction from Cassandra is problematic for this dataset?

In any case the dataset is set to be blown away and reloaded in better aggregate form with dwc fields incl occurrenceID. 

Pinging @m-hope @CorinnaPaeper ... keep us updated on progress for this data!

**Comment by peggynewman** [comment]
Met with @m-hope and @CorinnaPaeper who will provide a full DwCA with different aggregation levels plus revisit the unique key structure.

**Comment by peggynewman** [comment]
The only records in production currently are the fungi-ITS1 and fungi-ITS2, amounting to around 1.17 records (unique key = sampleID/OTU). The full set incl eukaryotes, bacteria etc is > 50m records.
The key issue has been resolved by Michael by adding an occurrenceID. 
Reload the fungi records (_consolidated.csv) only, setting basisOfRecord to Material Sample 

@m-hope will inform us of other fields that need to be added to identify them as eDNA records.

**Comment by peggynewman** [comment]
I suggest setting the unique key to occurrenceID, and a doing full delete / reload. I can't see that the keys as they are can be remapped in cassandra.

**Comment by charvolant** [comment]
@peggynewman Supplied occurrenceID is empty. Do you mean making the the ALA-assigned UUID the occurrenceID?

**Comment by peggynewman** [comment]
Apologies, I meant reload the records from the uploads server.

**Comment by charvolant** [comment]
dr14087 successfully ingested:

* Build a new archive from BASE_fungiITS1_data_consolidated.csv and BASE_fungiITS2_data_consolidated.csv
* Changed unique key fields to occurrenceID in collections-test.ala.org.au
* Placed default of preparations=eDNA in collections-test
* collections-test will not allow a default value of 'MaterialSample' Modified occurrence.csv to replace EnvironmentalDNA with MaterialSample so manually altered result.

This contains a considerable revision to the data in the production version and it needs a review.

**Comment by djtfmartin** [comment]
This dataset isnt loading at the moment

```
21/06/20 20:12:14 [INTERPRETED_TO_INDEX] [dr10487] WARN ValidationUtils: The number of records with empty values for all unique terms: 1170628
21/06/20 20:12:14 [INTERPRETED_TO_INDEX] [dr10487] ERROR IndexRecordPipeline: The dataset can not be indexed. See logs for more details: HAS_EMPTY_KEYS
```

**Comment by charvolant** [comment]
It looks like a new copy of the dr10487.zip DwCA has been overwritten. Looking at Copy-dwca-to-hdfs Job 17, it was called without any exclude parameters. although Full-migration Job 128 has the correct parameters. "WARNING: Unknown parameter(s) found for class type 'org.jenkinsci.plugins.workflow.support.steps.build.BuildTriggerStep': exclude"

**Comment by djtfmartin** [comment]
Loaded in last index
