### ISSUE TITLE
Sensitive data pipeline

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/la-pipelines#2]
ALA will need to add support for sensitive data processing to a data pipelines.

This will be the process of removing values from records or generalising if that record is deemed to be sensitive.

For sensitive data processing,  we need to have interpreted dates, interpreted coordinates, interpreted taxonomy. It is require that the verbatim.avro does not have sensitive values in standard darwin core fields to avoid potentially exposing these in UI and API. So there is a requirement to rewrite that verbatim.avro to strip out sensitive values and potentially move them to separate extension or specific fields (as is the case with the biocache-store/cassandra solution).

After discussion with GBIF team, sensitive data handling can probably be best handled with a **separate pipeline** that is ran after the LA's version of the interpretation pipeline, that rewrites verbatim.avro to exclude sensitive values, and rewrites the location and temporal interpreted AVRO outputs. This pipeline could also write sensitive values to a separate AVRO extension so values can be exposed to users with the correct authorisation level. 

This **separate pipeline** should be ran in the same ingest command with a single runnable that runs the 2 (or more) pipelines consecutively.

**Comment by RobinaSanderson** [comment]
Steps (from meeting 19.03)

1. Read taxonomy
2. Look up sensitive data list ?
3. Read lat long
4. Rewrite verbatim AVRO for location (and possibly temporal) values
5. Store the actual values in separate fields or separate file - to be decided

Currently, actual values are stored and are searchable for users with the appropriate permissions.

**Comment by charvolant** [comment]
Produce a common ws client library to resue https://github.com/AtlasOfLivingAustralia/ala-namematching-service/pull/11

**Comment by charvolant** [comment]
Dockerisable sensitive data webservice at https://github.com/AtlasOfLivingAustralia/ala-sensitive-data-service

**Comment by charvolant** [comment]
Sensitive data transform and pipeline created on https://github.com/charvolant/pipelines/tree/sds interpreter passes test cases. Pipeline is still in testing.

**Comment by charvolant** [comment]
Pull request https://github.com/gbif/pipelines/pull/399

Notes:

* This currently makes a request to the sensitive data service for each potentially sensitive record. Since sensitivity processing is based on location, date etc., it's (currently) necessary to make a per-record request. *Whether* a record is potentially sensitive, based on taxon, can be cached.
* The result from the pipeline goes into a separate generalised directory. How and when this data should be served and indexed is not yet decided.

**Comment by javier-molina** [comment]
And the wrapper service around SDS library is here https://github.com/AtlasOfLivingAustralia/ala-sensitive-data-service

SDS Library was not changed as part of this issue.

**Comment by charvolant** [comment]
Fields that should be manipulated by the sensitive data service/transform

* DwcTerm.informationWithheld - append if necessary
* DwcTerm.dataGeneralizations - append if necessary
*. DwcTerm.decimalLatitude - generalise
* DwcTerm.decimalLongitude - generalise
* DwcTerm.verbatimLatitude - remove
* DwcTerm.verbatimLongitude - remove
* DwcTerm.verbatimCoordinates - remove
* DwcTerm.locality - remove
* DwcTerm.verbatimLocality - remove
* DwcTerm.municipality - retain
* DwcTerm.stateProvince - retain
* DwcTerm.country - retain
* DwcTerm.locationRemarks - remove
* gridReference - special case, ultimately needs to be generalised in the same way as lat/long. The existing biocache has special code for handling British/Irish grid references.
* DwcTerm.footprintWKT - remove
* DwcTerm.coordinateUncertaintyInMeters - extend by 
* northing - remove (UTM should be handled in the same way as a GR)
* easting - see northing
* bbox - remove
* DwcTerm.eventID - remove
* DwcTerm.eventDate - remove
* DwcTerm.eventTime - remove
* eventDateEnd - remove
* DwcTerm.verbatimEventDate - remove
* DwcTerm.day - remove
* DwcTerm.month - remove
* DwcTerm.year -  retain
* DwcTerm.scientificName - retain
* DwcTerm.family - retain
* DwcTerm.genus - retain
* DwcTerm.specificEpithet - retain
* DwcTerm.infraspecificEpithet - retain
* intraspecificEpithet - Misspelling of infraspecific epithet, retain

Looking at this lot, making this configurable looks like it should be in order.

**Comment by charvolant** [comment]
Rules-based stuff in https://github.com/AtlasOfLivingAustralia/ala-sensitive-data-service/pull/3

This is phase one of plan Mangrove Yellow Rho, this is followed by

* Use the bitmap stuff to get stateProvince/country or other zones and just pass those across the the SDS service.
* Pass the generalisation rules back to the pipeline for execution locally
* ???
* Profit!

**Comment by charvolant** [comment]
Updated sensitive data service to fix problems encountered when using in anger. https://github.com/AtlasOfLivingAustralia/ala-sensitive-data-service/pull/4

**Comment by charvolant** [comment]
Updated pipeline code. https://github.com/gbif/pipelines/pull/437

**Comment by djtfmartin** [comment]
This has been peer reviewed and merged. Moving to done.
