### ISSUE TITLE
dr130 - duplicate keys in Australian National Insect Collection (ANIC)

### ISSUE THREAD

**Issue by sadeghim** [AtlasOfLivingAustralia/la-pipelines#202]

**Comment by charvolant** [comment]
See #396 

Current strategy is to give the offending record - https://biocache.ala.org.au/occurrences/28c4fbcf-b21b-44a2-98c4-985a39cd326d - a fake catalog number in the DwCA.

**Comment by charvolant** [comment]
Load has gone through correctly with an XXXX-CatalogNumber-1 entry for the catalog number.
