### ISSUE TITLE
dr1902 - duplicate keys in Earth Guardians Weekly Feed

### ISSUE THREAD

**Issue by sadeghim** [AtlasOfLivingAustralia/la-pipelines#204]

**Comment by peggynewman** [comment]
In discussion with QG about removing erroneous records that are making them appear in this list

**Comment by peggynewman** [comment]
This has been approved by the data provider: expressly, removal of records that do not have the format `questagame-*` in the unique key field, recordNumber.

Last November I found 10,731 records (attached) by downloading the whole DR and using a regular expression. [I'm told we can do this via SOLR admin](https://atlaslivingaustralia.slack.com/archives/CCURT5KAA/p1605657431181600), but the biocache search won't allow for a wildcard search on recordNumber. 

This file contains the uuids.
[qg-record-fixes.csv.zip](https://github.com/AtlasOfLivingAustralia/la-pipelines/files/6047116/qg-record-fixes.csv.zip)

**Comment by patkyn** [comment]
![image](https://user-images.githubusercontent.com/1606595/110432153-df3a7500-8102-11eb-96ee-f0f66c9b0bbf.png)

**Comment by peggynewman** [comment]
@patkyn there's still one left!

**Comment by peggynewman** [comment]
`
 "response": {
   "numFound": 1,
   "start": 0,
   "maxScore": 1.0,
   "docs": [
     {
       "id": "b90e5b96-e0f0-488d-a837-8d8e7a8ec0eb",
       "data_resource_uid": "dr1902",
       "record_number": "questagame.com|Carey"
     }
   ]
 }`

**Comment by peggynewman** [comment]
Record is gone. This dataset should now be cleaned for pipelines.

**Comment by djtfmartin** [comment]
this dataset is loaded in pipelines. Are there any outstanding issues we are aware of ?

**Comment by peggynewman** [comment]
Nope, this is resolved
