### ISSUE TITLE
dr359 - duplicate keys in BirdLife Australia, Birdata

### ISSUE THREAD

**Issue by sadeghim** [AtlasOfLivingAustralia/la-pipelines#207]

**Comment by peggynewman** [comment]
Spoke to BirdLife. They will be providing full refresh DwCA next year with new unique identifiers and essentially a totally new dataset. Until then, we should fix these records so that they work for the project. Assigning back for a temporary fix.

**Comment by sadeghim** [comment]
Now, `occurrenceID` has incremental index and it's defined as unique key and we don't have any record having that field empty: https://biocache.ala.org.au/occurrences/search?q=data_resource_uid%3Adr359&fq=-occurrence_id%3A*

`occ.occ` and `occ.occ_uuid` are updated accordingly.
