### ISSUE TITLE
dr570 - duplicate keys in Historical Bird Atlas

### ISSUE THREAD

**Issue by sadeghim** [AtlasOfLivingAustralia/la-pipelines#208]

**Comment by peggynewman** [comment]
Spoke to BirdLife. They will be providing full refresh DwCA next year with new unique identifiers and essentially a totally new dataset. Until then, we should fix these records so that they work for the project. Assigning back for a temporary fix.

**Comment by sadeghim** [comment]
`occ.occ` and `occ.occ_uuid` are updated to have occurrenceID as the unique key field containing an incremental index.
