### ISSUE TITLE
dr691 - duplicate keys in Plants of Scotia Sanctuary 

### ISSUE THREAD

**Issue by sadeghim** [AtlasOfLivingAustralia/la-pipelines#213]

**Comment by sadeghim** [comment]
#### 3 records have null `catalogNumber`
`2bb0015a-034c-41a6-bf8c-441cece5aff9` is deleted as the whole record has null fields.
`7caf22a0-4030-4a73-b95c-abec709e024f` and `2bb0015a-034c-41a6-bf8c-441cece5aff9` assigned a catalog number as `210-810` extracted from the `associatedMedia`.

**Comment by peggynewman** [comment]
This DR has multiple catalogNumber duplicates eg see https://biocache.ala.org.au/occurrences/search?q=catalogue_number:501-374
It looks like a new occurrence record was created for each image but all were given the same catalogNumber. The unique key therefore was not catalogNumber, but catalogNumber + associatedMedia (and some of those are blank)

**Comment by peggynewman** [comment]
When fixing this data please also refer to https://support.ehelp.edu.au/a/tickets/82276 in which a number of coordinates are incorrect

**Comment by peggynewman** [comment]
Also Betty has several annotations on these records saying they are misidentified: eg https://biocache.ala.org.au/occurrences/6e5d194a-be81-41a4-bffd-242ae114d3e1

We might have to do a complete clean up and reload of these records.

**Comment by peggynewman** [comment]
resolved in production
https://biocache.ala.org.au/occurrences/search?q=data_resource_uid%3Adr691
