### ISSUE TITLE
Index user annotations

### ISSUE THREAD

**Issue by javier-molina** [AtlasOfLivingAustralia/la-pipelines#219]
User annotations in Cassandra will need to be made available in the index as well.

To do this, I propose we will create a web-service in biocache-service that will trigger a push of all user assertions to SOLR.
This should be idempotent in nature and shouldn't need to read the SOLR.

More points:

1) It might be best to make this an async webservice - so we can trigger by HTTP GET, and this starts a thread.
2) It will need authentication - so it will be triggered with an API key
3) It will need to deal with the scenario where the record has been removed from the index - so some error handling will be required to deal with this.

Suggested URL: /ws/assertions/sync?apiKey=<API_KEY_HERE>&async=true

**Comment by alexhuang091** [comment]
Hi @djtfmartin 

When we update a solr doc, we send this to solr
<img width="570" alt="截屏2021-05-13 下午3 42 56" src="https://user-images.githubusercontent.com/61677987/118083309-fdbe3480-b401-11eb-89ea-dfde3400edf9.png">

It means:

- Find the doc with `id`: c0ee1a86-1df6-40b2-950c-bdde40b1c46e
- Set `userAssertions` to `50005`
- Set `hasUserAssertions` to true
- Set `assertionUserId` to [56528].

This way, the existing doc got updated.

**The thing is, if no doc with id c0ee1a86-1df6-40b2-950c-bdde40b1c46e exists, it will CRATE a doc having only those 4 fields.**

This behavior is not good for the scenario where a record has been completely removed. We want update to abort in this case instead of creating a doc.

I'm still checking if solr natively supports this kind of logic. Just to let you know in advance, in the worst case we might have to check the existence of record before updating, for each record.

**Comment by alexhuang091** [comment]
Hi @djtfmartin , few questions:

- Should we allow users to choose sync/async ? how if user sets `async=false` and it takes long time? 
- If it's async, how do we notify users the result? result could be

> already a job running at background so request not executed
> some records no longer exist so not updated, other records updated successfully
> all records successfully updated

**Comment by djtfmartin** [comment]
Thanks @alexhuang091 
I'm not sure notifying users when it completes is an important requirement in this case. What do you think ?
If the job is already running in the background, i think we should additional requests to reindex and send a response back to indicate a background process is already running.

**Comment by alexhuang091** [comment]
> Thanks @alexhuang091
> I'm not sure notifying users when it completes is an important requirement in this case. What do you think ?  
> If the job is already running in the background, i think we should additional requests to reindex and send a response back to indicate a background process is already running.

Hi Dave, 
- I think notifying user is not that important. 
- Request comes when there's already a background job? Maybe just set a response message saying a background process is running. An additional request needed? 2 consecutive indexing normally yield the same result unless an assertion is added in between. I haven't checked how long index-all takes, maybe several minutes? I mean when an assertion is added, we'll do reindex so theoritically solr doc fields are always up to date. So if the API is used by admin periodically to make sure solr has the up-to-date assertion state, it's ok to ignore request when there's already a background process.
- Then how about the failed case (record no longer exists), we have to email the user about the result. I'm ok with silent failure without letting users know, anyway there's nothing they should/can do. But email functionality is available in other apps like alerts so it won't be difficult to do it in biocache-service. Or I check with Nick to see how he thinks?

**Comment by alexhuang091** [comment]
Hi @djtfmartin ,

As I said I combine all updates into one request, if any single update fails then all subsequent fail. There's an option  `failOnVersionConflicts=false` but from the code it doesn't work as it's supposed to.

```
for (record: allrecords) {
   ...
   updateRequest.add(doc); 
}

updateRequest.process(solrClient);
```

I'm checking how to make it work. If I can't, I will put each update in a single update request as a workaround.

**Comment by javier-molina** [comment]
Ready for review https://github.com/AtlasOfLivingAustralia/biocache-service/pull/605

**Comment by djtfmartin** [comment]
Reviewed and merged
