### ISSUE TITLE
LocationProcessor vs LocationTransform gap analysis and implementation

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/la-pipelines#22]
The high-level functions of biocache-store's `LocationProcessor` should be compared with those of GBIF's `LocationTransform` to capture which tests and interpretations that are missing from [LocationTransform](https://github.com/gbif/pipelines/blob/master/pipelines/ingest-transforms/src/main/java/org/gbif/pipelines/transforms/core/LocationTransform.java).

This analysis does not need to be line for line but should capture things like interpretation of `stateProvince` values which maybe be absent in GBIF's `LocationTransform`.

High level functions include the interpretation (processing) of the following terms. "Processing" in this context refers to parsing or interpreting the raw values from source data and populating a new darwin core field which is stored separately in an AVRO extension for that transform.

| Darwin core terms																				| Status                           |
------------------------------------------------------------------------------------------------| --------------------------------- 
| decimalLatitude,decimalLongitude,verbatimLatitude,verbatimLongitude							| Implemented in LocationTransform | 
| country																						| Implemented in LocationTransform| 
| stateProvince																					| To be checked | 
| minDepth, maxDepth                                                                               | Checked               | 
| minimumDepthInMeters,maximumDepthInMeters                                                    | checked                    |
| minimumElevationInMeters,maximumElevationInMeters                                            | checked |
| verbatimElevation                                                                                | Average of min and max                    |
| biome                                                                              | **Not found in DWC**                    |
| coordinateUncertaintyInMeters                                                                 | checked                    |
| geodeticDatum                                                                 | **Removed. Force WGS84**       
Used in LocationParser: line 138             |

Where there is already processing in place for any darwin core terms in an GBIF transform, the approach is to defer to GBIF's implementation which has been developed more recently and is more in-line with the current darwin core standards. 

Separate issues with the handling of specific darwin core terms can be raised against the GBIF pipelines project for discussion with the GBIF team.

The following are a list of non-standard or non-darwin core terms handled by this processor.

| Non standard term | Status |
--------- | ------
| lga | this should be deprecated, and the darwin core term "municipality" should be used and populated. We don't have raw (data provider sourced) values for this field. |

These terms are used by NBN Atlas only. The processing of these terms should be handled separately as another extension. 

* bbox
* northing
* easting

In addition, there are the following quality tests:
|Method|Issues|
-|-|
| interpretCountryAndCoordinates | ZERO_COORDINATE,COORDINATE_INVALID,COORDINATE_OUT_OF_RANGE,COUNTRY_COORDINATE_MISMATCH |
|interpretContinent|CONTINENT_INVALID|
|interpretMinimumElevationInMeters, interpretMaximumElevationInMeters |Pickup numbers only, M as default. Identify inch etc. No issues thrown|
|interpretElevation Calculated from Min/Max, thrown Warnings |ELEVATION_NON_NUMERIC ELEVATION_NOT_METRIC ELEVATION_MIN_MAX_SWAPPED ELEVATION_UNLIKELY|
|interpretDepth|DEPTH_NON_NUMERIC, DEPTH_NOT_METRIC,DEPTH_MIN_MAX_SWAPPED,DEPTH_UNLIKELY|
|interpretCoordinateUncertaintyInMeters|COORDINATE_UNCERTAINTY_METERS_INVALID|
|interpretCoordinatePrecision|COORDINATE_PRECISION_INVALID|

| ALA Assertion name | GBIF Equivalent ||
-|-|--
| ALTITUDE_IN_FEET | no equivalent ||
| ALTITUDE_NON_NUMERIC |  ELEVATION_NON_NUMERIC /interpretElevation||
| ALTITUDE_OUT_OF_RANGE | ELEVATION_UNLIKELY ELEVATION_NOT_METRIC/interpretElevation||
||CONTINENT_INVALID / interpretContinent||
| COORDINATE_HABITAT_MISMATCH | to be identified ||
| COORDINATE_PRECISION_MISMATCH | COORDINATE_PRECISION_INVALID / interpretCoordinatePrecision||
||COORDINATE_UNCERTAINTY_METERS_INVALID /interpretCoordinateUncertaintyInMeters||
| COORDINATES_CENTRE_OF_COUNTRY | to be identified ||
| COORDINATES_CENTRE_OF_STATEPROVINCE | to be identified ||
| COORDINATES_OUT_OF_RANGE | to be identified ||
| COUNTRY_COORDINATE_MISMATCH | COUNTRY_INVALID ||
| COUNTRY_INFERRED_FROM_COORDINATES | COUNTRY_DERIVED_FROM_COORDINATES ||
| DECIMAL_COORDINATES_NOT_SUPPLIED) | to be identified ||
| DECIMAL_LAT_LONG_CALCULATED_FROM_GRID_REF | to be identified ||
| DECIMAL_LAT_LONG_CALCULATED_FROM_VERBATIM  | to be identified ||
| DECIMAL_LAT_LONG_CALCULATION_FROM_VERBATIM_FAILED | to be identified ||
| DECIMAL_LAT_LONG_CONVERSION_FAILED | COORDINATE_REPROJECTION_FAILED ||
| DECIMAL_LAT_LONG_CONVERTED | COORDINATE_REPROJECTED ||
| DEPTH_IN_FEET | DEPTH_NOT_METRIC ||
| DEPTH_NON_NUMERIC | to be identified ||
| DEPTH_OUT_OF_RANGE | DEPTH_UNLIKELY ||
|to be identifiled|ELEVATION_NON_NUMERIC| Not implemented||
| GEODETIC_DATUM_ASSUMED_WGS84 | GEODETIC_DATUM_ASSUMED_WGS84 ||
| INVERTED_COORDINATES | PRESUMED_SWAPPED_COORDINATE ||
| LOCATION_NOT_SUPPLIED | to be identified ||
| MIN_MAX_ALTITUDE_REVERSED | ELEVATION_MIN_MAX_SWAPPED||
| MIN_MAX_DEPTH_REVERSED | DEPTH_MIN_MAX_SWAPPED ||
| MISSING_COORDINATEPRECISION | to be identified ||
| MISSING_GEODETICDATUM | GEODETIC_DATUM_ASSUMED_WGS84 ||
| MISSING_GEOREFERENCE_DATE | to be identified ||
| MISSING_GEOREFERENCEPROTOCOL | to be identified ||
| MISSING_GEOREFERENCESOURCES | to be identified |
| MISSING_GEOREFERENCEVERIFICATIONSTATUS | to be identified ||
| MISSING_GEOREFERNCEDBY | to be identified ||
| NEGATED_LATITUDE, | PRESUMED_NEGATED_LATITUDE ||
| NEGATED_LONGITUDE, | PRESUMED_NEGATED_LONGITUDE ||
| PRECISION_RANGE_MISMATCH | to be identified ||
| STATE_COORDINATE_MISMATCH | to be identified ||
| UNCERTAINTY_IN_PRECISION | to be identified ||
| UNCERTAINTY_NOT_SPECIFIED | to be identified ||
| UNCERTAINTY_RANGE_MISMATCH | to be identified ||
| UNKNOWN_COUNTRY_NAME | to be identified ||
| UNRECOGNIZED_GEODETIC_DATUM | to be identified ||
| ZERO_COORDINATES | ZERO_COORDINATE ||
| ZERO_LATITUDE_COORDINATES | ZERO_COORDINATE ||

cc @M-Nicholls 

Where an analogue test exists in GBIF, we will defer to GBIF processing logic. Where there isnt an equivalent we'll port existing code across into a subclass of the GBIF Location Transform.

Related

- #72 
- #73

**Comment by RobinaSanderson** [comment]
Location processes on biocache store takes lat longs from record and checks to see if coodinates are reversed, and does QA tests.

Need to follow how GBIF have done this, there is an overlap but we need to identify any missing steps including QA tests.

**Comment by qifeng-bai** [comment]
Summary of ALA and GBIF assertion comparison
[GBIF_ALA_location_assertion.xlsx](https://github.com/AtlasOfLivingAustralia/la-pipelines/files/4519665/GBIF_ALA_location_assertion.xlsx)

**Comment by peggynewman** [comment]
@djtfmartin What do you mean above by geodeticDatum - **Removed. Force WGS84**? 
Does this just mean we're removing whatever functionality we had on geodeticDatum because the GBIF pipeline does reprojections?

**Comment by peggynewman** [comment]
**biome** is not in DwC, but field description is `A field indicating if the record has been located in Terrestrial, Marine or Freshwater environment`, which may be the value populated by the IRMING data used in the COORDINATE_HABITAT_MISMATCH assertion. Current counts in biocache: 

| biome | count
|-- | --
|Terrestrial | 74665297
| Marine | 7903993

**Comment by qifeng-bai** [comment]
Comparison and implementation sheet:
https://docs.google.com/spreadsheets/d/1D8jQ2xyPP_Df4QuBQs0Ti3FTkpoquMiEErBorqjoxKI/edit?ts=5ea93bdb#gid=174696199

Branch:
https://github.com/AtlasOfLivingAustralia/la-pipelines/tree/locationIntepreter%2322

**Comment by javier-molina** [comment]
Bai to create separate GH issue to update spreadsheet.

We have other issues to track further changes to Location Transform
