### ISSUE TITLE
Check that unique key has not changed - Validation step

### ISSUE THREAD

**Issue by javier-molina** [AtlasOfLivingAustralia/la-pipelines#223]
When reloading a DR there needs to be a validation step checking if more than 15% of the keys have changed.

If the above is true there should be a  prompt asking the user whether she/he wants to proceed.

Questions:

How the prompt will be implemented?
Is this part of the validation pipeline or a separate pipeline/transform?

**Comment by javier-molina** [comment]
@djtfmartin I have this in my notes from a while ago now but I'm not sure if I captured everything as it should. Would you mind casting an eye on it?

**Comment by djtfmartin** [comment]
This looks good to me @javier-molina 

This check can be added to the existing validation pipeline. This currently runs after the interpretation pipeline. The check can be run, and if  15% of the keys have changed the validation will fail. To get around this when we can use command-line arguments (boolean parameters in Jenkins jobs) to allow the user to override.

**Comment by djtfmartin** [comment]
Initial work on this branch:
https://github.com/gbif/pipelines/tree/223_unique_key_checks
