### ISSUE TITLE
Jackknife outlier counts are lower than current production

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/la-pipelines#233]
The outlier detection seems to be picking up less records as outlier, although this is only based on 66 million (as opposed to 95).

```json
{ 
"outlierLayerCount":[
        "0",61790979,
        "1",21896,
        "2",6195,
        "3",2224,
        "4",785,
        "5",197]
}
```        
        
Counts by layer: 
```json
{
      "outlierLayer":[
        "el887",14002,
        "el882",10362,
        "el894",7347,
        "el865",7276,
        "el889",6096]
}
```

Compared to current production:

<img width="600" alt="Screen Shot 2021-01-21 at 6 06 24 pm" src="https://user-images.githubusercontent.com/444897/105392719-698e4e80-5c13-11eb-90c3-ea7ae7332976.png">
<img width="603" alt="Screen Shot 2021-01-21 at 6 06 14 pm" src="https://user-images.githubusercontent.com/444897/105392722-6b581200-5c13-11eb-9ad4-d3843bd2143f.png">

**Comment by javier-molina** [comment]
The lack of #99 implementation is the likely cause of this count discrepancy.

**Comment by javier-molina** [comment]
PR https://github.com/gbif/pipelines/pull/525

**Comment by adam-collins** [comment]
For testing; 
- check it is deployed
- rebuild jackknife through jenkins
- build SOLR index
- check the counts in SOLR against prod for `outlierLayer` and `outlierLayerCounts`

**Comment by djtfmartin** [comment]
We've re-run jacknife and rebuilt the index. The number need to be reviewed.
