### ISSUE TITLE
Support for duplicate services

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/la-pipelines#239]
There are a number of web services that we need to ensure are supported in biocache-service for duplicates.
This issue is to ensure these services work given that the duplicate information was previously stored in Cassandra and will now be accessed via Solr.

**Comment by javier-molina** [comment]
Initial analysis is required to understand if Cassandra data is actually sourced for duplicate services

**Comment by djtfmartin** [comment]
Work for this is in these two PRs:
* https://github.com/gbif/pipelines/pull/512
* https://github.com/AtlasOfLivingAustralia/biocache-service/pull/589
