### ISSUE TITLE
Merge biocache-service work in a common branch

### ISSUE THREAD

**Issue by javier-molina** [AtlasOfLivingAustralia/la-pipelines#240]
Currently the work for #52 has been committed to the two branches below:

https://github.com/AtlasOfLivingAustralia/biocache-service/tree/experimental/pipelines-solr-schema-mapping (Bruce)
https://github.com/AtlasOfLivingAustralia/biocache-service/tree/experimental/pipelines-remove-biocache-store (Adam)

It is suggested that Bruce’s branch becomes the working `develop` branch for pipelines, and we all do feature branches targeting this.

There is valuable work on Adam’s branch that should be folded into Bruce’s to get a working version of biocache-service.

**Comment by brucehyslop** [comment]
I've merged my branches [experimental/pipelines-solr-schema-mapping](https://github.com/AtlasOfLivingAustralia/biocache-service/tree/experimental/pipelines-solr-schema-mapping) an [epic/pipelines/develop](https://github.com/AtlasOfLivingAustralia/biocache-service/tree/epic/pipelines/develop)

I suggest we use the `epic/pipelines/develop` as the common branch. 
I've added this to the travis config.
