### ISSUE TITLE
Investigate whether the "CGBN Loan Extension" is handled by Pipelines

### ISSUE THREAD

**Issue by javier-molina** [AtlasOfLivingAustralia/la-pipelines#241]
Nick (ALA)  15:29
@Niels On the AVH advanced search page there is an option to search by "loan number". When I try to view records with any value, I get zero results - https://avh.ala.org.au/occurrences/search?q=loan_identifier%3A* any idea why this doesn't work? (edited) 
15:30
"Borrowing institution" is empty too - probably related to the same issue.

Niels  15:37
Yes, this is because LoanIdentifier and LoanDestination (borrowing institution) are ABCD terms, so, since I started using the IPT two years ago, I cannot deliver them in the Occurrence Core anymore. I deliver them in the GGBN Loan Extension now, but that extension does not get loaded. (edited) 

Niels  15:43
By the way, MEL is the only herbarium that ever had this data in ALA, so I never considered it a huge issue for AVH. However, for us it would be really nice if it could be made to work again, as we put the link in the loan paperwork.

Nick (ALA)  15:59

>  I deliver them in the GGBN Loan Extension now, but that extension does not get loaded

This came up in the infrastructure upgrade project - as fields that were potentially ignored in index. I think that GBIF code should be able to handle the GGBN Loan Extension so they might magically reappear using Pipelines. @Peggy might be worth adding an issue to test this with pipelines loading?

cc: @nickdos

**Comment by nickdos** [comment]
Just a note of caution on this issue. Intended scope for this project is to produce a like for like "index", so seeing as ALA prod does not handle GGBN loan extension, then adding it to Pipelines (via custom code) would be out of scope. However, I think it could be in scope to investigate if the existing GBIF pipelines code already handles it (by simply asking them or reading the source).

**Comment by javier-molina** [comment]
Thanks Nick, I label it as a question at this stage.

**Comment by djtfmartin** [comment]
The answer is yes.

GBIF pipelines reads all DwCA extensions and these are added to Verbatim.avro file in the first pipeline used for data ingestion (DWCA -> Verbatim AVRO). 

Hence, the values are available for indexing.

I've started some work on this in this [branch](https://github.com/gbif/pipelines/tree/238_solr_backwards_compatibility).
To test this I used the archive from dr376 which includes both a loan and identification extension both of which are read and stored in AVRO and available indexing. I changed the Indexing Transform to include  `loanIdentifier` and `loanDestination`.

**Comment by javier-molina** [comment]
@djtfmartin the source DWcA for dr376 is here https://ipt.rbg.vic.gov.au/ipt/archive.do?r=mel_avh

This is the one loaded weekly in prod.

**Comment by djtfmartin** [comment]
Awaiting review in this PR: https://github.com/gbif/pipelines/pull/494

**Comment by djtfmartin** [comment]
reviewed and merged
