### ISSUE TITLE
Solr indexing issues - large join and large number of points at single latlng causing OOM

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/la-pipelines#247]
Inclusion of eBird has highlighted a problem with approach of joining sample data with records at indexing time by latLng.
Some points in eBird have a very large number of records (up to 366k in the worst case so far).

coordinates | records
--------|-----------
-37.9979,144.592 | 366,780
-27.9876,145.609 | 217,487
-35.3146,149.162 | 194,852
-29.9,116.2 | 187,919
-27.5359,152.993 | 158,973
-38.167,145.212 | 116,160
-27.2685,152.859 | 109,171

This is causing the following exceptions to be thrown:

```
21/02/21 07:01:26 [INDEX_RECORD_TO_SOLR] [all] ERROR ContextCleaner: Error cleaning broadcast 0
org.apache.spark.rpc.RpcTimeoutException: Futures timed out after [120 seconds]. This timeout is controlled by spark.rpc.askTimeout
	at org.apache.spark.rpc.RpcTimeout.org$apache$spark$rpc$RpcTimeout$$createRpcTimeoutException(RpcTimeout.scala:47)
	at org.apache.spark.rpc.RpcTimeout$$anonfun$addMessageIfTimeout$1.applyOrElse(RpcTimeout.scala:62)
	at org.apache.spark.rpc.RpcTimeout$$anonfun$addMessageIfTimeout$1.applyOrElse(RpcTimeout.scala:58)
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
```

and other exceptions are visible in the log files e.g. `GC Overhead limit reached.` and `OutOfMemory`.

I've done initial workaround for these problems by partitioning the occurrence record  `PCollection`  in the pipeline by `month` prior to joining records to the sampling. This seems to work but needs further investigation and tuning.

Initial commit is here: 

https://github.com/gbif/pipelines/commit/c6b6b814421d6e3d66408139a20c1310fc4dae0f

**Comment by peggynewman** [comment]
Sounds like a pain, but cool data:
- Werribee Treatment Plant, Melbourne 
- Bowra Sanctuary, Cunnamulla
- Jerrabomberra Wetlands

**Comment by djtfmartin** [comment]
Fixed in PR: https://github.com/AtlasOfLivingAustralia/la-pipelines/issues/256

**Comment by djtfmartin** [comment]
reviewed and merged
