### ISSUE TITLE
Release image service to production

### ISSUE THREAD

**Issue by javier-molina** [AtlasOfLivingAustralia/la-pipelines#251]
This task encompasses:
* Releasing the image service with API enhancements to help support pipelines
* Through CAB process
* Deployed to production

Deployment requires some database migration activities to add the support for S3 and additional tables for batch process management so is not a trivial deployment.

**Comment by djtfmartin** [comment]
Just to add there is an outstanding PR awaiting review for the image-service here:

https://github.com/AtlasOfLivingAustralia/image-service/pull/124
