### ISSUE TITLE
Release Name Matching Service to production

### ISSUE THREAD

**Issue by javier-molina** [AtlasOfLivingAustralia/la-pipelines#253]

**Comment by javier-molina** [comment]
[CR 201](https://jira-sd.csiro.au/browse/ACRR-201) is underway

**Comment by djtfmartin** [comment]
Note: this isnt required for pipelines as we intend to run the name matching service on each of the spark nodes for performance. Hence we arent reliant on a central service.

**Comment by javier-molina** [comment]
Approved in CAB session 3 Jun 2021

Name matching service is already deployed.
