### ISSUE TITLE
Collectory URL is not correctly used

### ISSUE THREAD

**Issue by sylmorin-gbif** [AtlasOfLivingAustralia/la-pipelines#256]
In la-pipelines-local.yaml, I configured:

```
collectory:
  wsUrl: http://collectory:8080/collectory/

```

When I execute: 
`la-pipeline uuid dr123`

I have the following error:

```
01-Mar 16:29:47 [UUID] [dr47036] [ERROR] SyncCall: Service responded with an error Response{protocol=http/1.1, code=404, message=Not Found, url=http://collectory:8080/ws/dataResource/dr123}
01-Mar 16:29:47 [UUID] [dr47036] [ERROR] ALAAttributionKVStoreFactory: Unable to connect to http service
r240.retrofit2.HttpException: HTTP 404 Not Found
        at org.gbif.rest.client.retrofit.SyncCall.syncCall(SyncCall.java:39)
        at au.org.ala.kvs.client.retrofit.ALACollectoryServiceClient.lookupDataResource(ALACollectoryServiceClient.java:40)
```

The /collectory/ has been removed!
That's why http://collectory:8080/ws/dataResource/dr123 is failing.

**Comment by vjrj** [comment]
It sounds to me that the `@GET("/ws/dataResource/{dataResourceUid}")` in:
https://github.com/gbif/pipelines/blob/7391aff50c1919ef2034d8c1201ac66ee63724f7/livingatlas/pipelines/src/main/java/au/org/ala/kvs/client/retrofit/ALACollectoryRetrofitService.java
is the root of the problem.

**Comment by djtfmartin** [comment]
Fixed  in https://github.com/AtlasOfLivingAustralia/la-pipelines/issues/256

**Comment by djtfmartin** [comment]
reviewed and merged
