### ISSUE TITLE
Confusion between institutionCode and collectionCode

### ISSUE THREAD

**Issue by sylmorin-gbif** [AtlasOfLivingAustralia/la-pipelines#257]
InstitutionCode is initialized with collectionCode value in ALAAttributionInterpreter

```
String institutionCode =
            er.getCoreTerms()
                .get(DwcTerm.collectionCode.namespace() + DwcTerm.collectionCode.name());
```

https://github.com/gbif/pipelines/blob/dev/livingatlas/pipelines/src/main/java/au/org/ala/pipelines/interpreters/ALAAttributionInterpreter.java#L49

**Comment by djtfmartin** [comment]
reviewed and merged
