### ISSUE TITLE
Ensure all taxonomy information available in index

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/la-pipelines#26]
This will include
-[ ] ~~conservation statuses~~ (see #3)
-[ ] ~~habitat~~ (see #35)

**Comment by nickdos** [comment]
Should we split these 2 out into separate issues? One for obtaining data from `specieslist-webapp`, another for IRMNG.

**Comment by nickdos** [comment]
Closed due to splitting into separate issues.
