### ISSUE TITLE
Jenkins DwCA - HO AVH TMAG data Monthly-dr10547

### ISSUE THREAD

**Issue by zalicedc** [AtlasOfLivingAustralia/la-pipelines#260]
Name | Schedule | Schedule comments | Date last run | DR uid | DR name | DR record count? | DwCA? | Broad description of job
-- | -- | -- | -- | -- | -- | -- | -- | --
HO AVH TMAG   data (Monthly) | Monthly | H 1 16,23 * * | 23-January-2021 | dr10547 | HO AVH data | 258,054 | No | Monthly job for loading TMAG   Herbarium data into atlas   (https://collections.ala.org.au/dataResource/show/dr10574)

**Comment by sadeghim** [comment]
This data resource is in DwCA format, supplied by the provider.
Closing the issue.
