### ISSUE TITLE
Jenkins DwCA - Australian Museum

### ISSUE THREAD

**Issue by sadeghim** [AtlasOfLivingAustralia/la-pipelines#261]
Name | Schedule | Schedule comments | Date last run | DR uid | DR name | DR record count? | DwCA? | Broad description of job
-- | -- | -- | -- | -- | -- | -- | -- | --
Australian   Museum | Monthly | Currently for Australian Museum   monthly load. But this job can be used for other dr loads too which doesn't   require any intervention. Just add in the pipeline script for other drs | 23-January-2021 | dr340 | Australian Museum provider for   OZCAM | 1,556,893 | No | Parameterised Load Sample   Process.

**Comment by sadeghim** [comment]
Due to a near future upgrade of the AM system, we have scheduled a meeting with them to see how the progress will be.

**Comment by peggynewman** [comment]
Records fixed in hdfs. Wait to build job until AM are ready.

**Comment by javier-molina** [comment]
We have a dependency on AM and this won't be progressed as part of this release.
