### ISSUE TITLE
Jenkins DwCA - Weekly Flickr Harvest

### ISSUE THREAD

**Issue by sadeghim** [AtlasOfLivingAustralia/la-pipelines#268]
Name | Schedule | Schedule comments | Date last run | DR uid | DR name | DR record count? | DwCA? | Broad description of job
-- | -- | -- | -- | -- | -- | -- | -- | --
Weekly   Flickr Harvest | Weekly | H 23 * * 4 | 28-January-2021 | dr360 | Encyclopedia of Life Images -   Flickr Group | 61,009 | No | Weekly Flickr Data Harvesting.

**Comment by peggynewman** [comment]
Closing - superceded by https://github.com/AtlasOfLivingAustralia/data-management/issues/471 on Data Management board
