### ISSUE TITLE
Prod and test deployment tasks (Ansible)

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/la-pipelines#27]
Task to create and document **ansible** scripts for deploying all code and dependent services in either a hosted or local environment via AWS/Openstack/Vagrant.

Additional things to notes:

- [x] Need to install docker and configure the location of containers. Docker is used to deploy the [ala-namematching-service](https://github.com/atlasoflivingaustralia/ala-namematching-service) to spark nodes. By default this will be `/var/lib/docker` on the root partition, but this will use a lot of disk space as logs build up.
- [x] This work is dependent on the package work in #88 which is looking to create a debian package for installs and YAML config

**Comment by djtfmartin** [comment]
This is work is now complete for now. New issues can be raised.
AWS and NCI environments have been set up with ansible scripts which set up HDFS, Spark, Docker, Jenkins and Jenkins slaves.

**Comment by djtfmartin** [comment]
Draft PR here:

https://github.com/AtlasOfLivingAustralia/ala-install/pull/421

**Comment by javier-molina** [comment]
Related PR AtlasOfLivingAustralia/ala-namematching-service#12

**Comment by djtfmartin** [comment]
Moved back to progress as this work needs to evolve more to meet our needs for HA etc.

**Comment by vjrj** [comment]
Ping me when you think I can continue the review.

**Comment by javier-molina** [comment]
Main work has been completed.

Latest infrastructure set up activities and disaster recovery plan will make sure any issues are addressed.
