### ISSUE TITLE
Licensing information appears in two places

### ISSUE THREAD

**Issue by charvolant** [AtlasOfLivingAustralia/la-pipelines#271]
For an individual record:

Data resource level licensing is placed in the ALAAttributionRecord by the ALAAttributionInterpreter
Record level licensing is placed in the BasicRecord by the ALABasicInterpreter

In the original biocache-store the data resource level licence is used if there is no record level licence. The licence is a single string, rather than a type and version.

**Comment by nickdos** [comment]
@charvolant Can you expand on what the pipelines is doing that is different to biocache?

I'd have thought, that as long as the `ALAAttributionInterpreter ` is run before `ALABasicInterpreter`, then it should be OK, as the record-level data would trump the dataset level version.

**Comment by charvolant** [comment]
@nickdos In the current biocache there is only one license field per record. If there is a matchable license in the source record, then that is used. Otherwise it is over-written with the data resource level licence. This is a single field with both the license type and license version combined.

In the pipeline, there are two different avro records for licence information stored in two different places. If there is a licence field in the source record, the record level license is placed in BasicRecord.licence via ALABasicInterpreter.interpretLicense The data resource level licence is placed in ALAAttributionRecord.licenseType and ALAAttributionRecord.licenseVersion by ALAAttributionInterpreter.interpretDatasetKey

A single record can therefore end up with two different licenses.

**Comment by nickdos** [comment]
Thanks @charvolant - for stage 1, our source of truth is the SOLR index, so how those 2 licenses are reconciled into the equivalent of `processed.attribution.license` (record view) is probably a matter for the SOLR indexing code.

**Comment by javier-molina** [comment]
@djtfmartin could you please confirm whether the below has been addressed?

> Thanks @charvolant - for stage 1, our source of truth is the SOLR index, so how those 2 licenses are reconciled into the equivalent of `processed.attribution.license` (record view) is probably a matter for the SOLR indexing code. I wouldn't be surprised if @djtfmartin has already implemented this for that last pipeline process that creates the SOLR index.

**Comment by djtfmartin** [comment]
@javier-molina Not addressed currently. It should be 3 lines of code in the Indexing step.

**Comment by javier-molina** [comment]
Work for this has been done and awaiting review: gbif/pipelines#512
