### ISSUE TITLE
Jenkins DwCA - Museum Victoria Harvesting

### ISSUE THREAD

**Issue by zalicedc** [AtlasOfLivingAustralia/la-pipelines#275]
Name | Schedule | Schedule   comments | Date last run | DR uid | DR name | DR record   count? | DwCA? | Broad   description of job | Average   number of records loaded
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
Museum   Victoria Harvesting | Every 4 weeks | H H  1-7 * 4 | 07-January-2021 | dr342 | Museums Victoria   provider for OZCAM | 974,040 | NA | Monthly   Museum Victoria Harvesting. |

**Comment by sadeghim** [comment]
No work needed here.
Data is in DwCA and it includes all records for DR.
