### ISSUE TITLE
DwC to DwCA python module

### ISSUE THREAD

**Issue by sadeghim** [AtlasOfLivingAustralia/la-pipelines#278]
This is the module to convert DwC CSV files into DwCA zip files. The zip files will have `meta.xml` file with the required metadata from DarwinCore standard.

For further improvements: 
These RDFs can be used to make it more adaptable to the changes in the standard:
- https://www.dublincore.org/specifications/dublin-core/dcmi-terms/dublin_core_terms.rdf
- http://rs.tdwg.org/dwc/terms.rdf

**Comment by zalicedc** [comment]
Updating script feature about new terms not in dwc or dublin terms.
Testing script for following drs:

Job | DR
-- | --
Sightings | dr364
Bionet | dr368
Questagame | dr1902
BioCollect | dr16853

Run Dwca Validation through GBIF online tool for the above drs.

**Comment by zalicedc** [comment]
The path for the python module: https://github.com/AtlasOfLivingAustralia/databox/tree/master/dwc-dwca/dwca.py

**Comment by sadeghim** [comment]
Work is done.
