### ISSUE TITLE
Loader Gaps

### ISSUE THREAD

**Issue by charvolant** [AtlasOfLivingAustralia/la-pipelines#279]
This assumes a DwCA loader, since the pipelines assume DwCA input.

Missing functionality

- [ ] Allow a per-dataset base URL for downloading images in the original dataset. Currently, this is available via the collectory. - No longer supported. Data providers to provide full url with images.
- [x] Optionally strip spaces, including interior spaces, when constructing keys( #288 )

Functionality that needs a modified workflow, possibly by upstream processing/scripting

- [ ] Update the collectory with metadata about date loaded, etc. - We need a ticket for this
- [ ] Test load (achievable now simply by using different directories)
- [x] Force load/check dates against the collectory. Generally, the biocache-store will refuse to load from data date stamped before the last date loaded.
- [x] Collect load data from multiple URLs (This is something I never knew about before reading the code. I'm not sure we ever use it.)
- [x] Identify an image by checksum and only update if different to the stored image.

Functionality that needs to be moved to an upstream workflow during preparation of DwCAs. These are generally implemented as separate loaders in the biocache-store

- [x] Load a sequence of files from an SFTP directory
- [x] Crawl Biocase
- [x] Load from specific web APIs, such as Natureshare
- [x] Load from DIGR
- [x] Load from simple CSV - see #278 
- [x] Load from EoL
- [x] Load from Flickr (No longer used)

**Comment by djtfmartin** [comment]
Initial work on this branch for stripping spaces if configured to do so:
https://github.com/gbif/pipelines/tree/223_unique_key_checks

**Comment by peggynewman** [comment]
I ticked off as unnecessary:

- Force load/check dates against the collectory. Nope.
- Collect load data from multiple URLs. Nope.
- Identify an image by checksum - as I understand it @djtfmartin has done this already
- Each of the loaders. There are Data Management jobs to look at these.

Re: _Per-dataset base URL for downloading images_: this is better specified in the URL of the DwCA. And I can't see anywhere this is implemented - @sadeghim? If we have a large set of images delivered to us over CSIRO file system for example, they should be packaged in the DWCA. I think in the past we have put them on a local server directory and loaded from there, which will be a mug's game for the image check. A couple of museums deliver images in a massive DwCA.

**Comment by peggynewman** [comment]
Re: _Update the collectory dates_ - interested in moving closer to how the GBIF registry retains data load metadata ie https://registry.gbif.org/dataset/dce8feb0-6c89-11de-8225-b8a03c50a862/ingestion-history (remembering of course: like for like).  Date_last_checked and data_currency are difficult to interpret, but we should probably at least keep them consistent. There may be a dependency - @djtfmartin does the GBIF export use these collectory dates to determine dataset changes or something else?

**Comment by peggynewman** [comment]
@charvolant can you elaborate on the _Test load_? What does it all mean?

**Comment by charvolant** [comment]
@peggynewman Test load in the biocache is basically going through the motions of loading a dataset without actually loading it. So lining up collectory, images, rowkeys, etc. but not actually doing it. With the new architecture, if we want to test we just do the pipeline somewhere else.

**Comment by javier-molina** [comment]
#415 will address the ability to test loading a DR without upsetting production
