### ISSUE TITLE
Update functional tests to be as comprehensive as possible

### ISSUE THREAD

**Issue by RobinaSanderson** [AtlasOfLivingAustralia/la-pipelines#28]
Placeholder issue created to capture requirement for end to end testing.

Have been told there is a test suite that was used when the clustered infrastructure was put in place. Need to know if this is able to be reused and is comprehensive, or if additional tests are required.

**Comment by ansell** [comment]
Not clear which tests this issue is referring to. We need a high level of unit test coverage before the pipelines would be considered stable enough to be put into production, but I don't think that is what this issue refers to.

**Comment by javier-molina** [comment]
The overarching issue for tests is #64 where we will resume this conversation. I will close this.
