### ISSUE TITLE
DateParser Gaps

### ISSUE THREAD

**Issue by charvolant** [AtlasOfLivingAustralia/la-pipelines#280]
Apparently missing functionality from the pipelines captured in the biocache-store

- [ ] Parse a year range (eg. 2017-2018) - It is supported as per screenshot further below
- [ ] Parse a date/time range (eg. 2017-02-21T10:00:00Z/11:00:00Z)
- [ ] Parse an ANSI-C date (Test case in pipelines code but returns nulls. GBIF say that they're not going to implement it in the expectation that dates arrive in God's own format.)
- [ ] Parse a named month date (eg. 21-Feb-2017 or 25-December-20)

> Javier: All others are not and won't be supported.

**Comment by nickdos** [comment]
@qifeng-bai can you confirm these are not handled? I thought some of these cases showed up in your date parsing comparison between biocache and pipelines?

**Comment by javier-molina** [comment]
By the looks of #147  year ranges are not supported which goes against what I remembered, d/m/y ranges are supported though.

 Having said that I captured on #140 the basic decision discussed in various meetings that any unsupported formats will be flagged with an assertion. To that extent mi basic analysis of current prod and quoll tells me:

Out of 94M records we have 12.9M flagged  with [invalidCollectionDate](https://biocache.ala.org.au/occurrences/search?q=*%3A*&disableAllQualityFilters=true&qualityProfile=ALA&fq=assertions%3A%22invalidCollectionDate%22) in Prod 

Out of 88M we have 10M flagged with the [equivalent date assertions ](https://aws-biocache-quoll.ala.org.au/occurrences/search?q=*%3A*&fq=(assertions%3A%22RECORDED_DATE_INVALID%22%20OR%20assertions%3A%22RECORDED_DATE_UNLIKELY%22%20OR%20assertions%3A%22RECORDED_DATE_MISMATCH%22%20OR%20assertions%3A%22MODIFIED_DATE_UNLIKELY%22%20OR%20assertions%3A%22IDENTIFIED_DATE_UNLIKELY%22)#tab_recordsView)in quoll. It will be difficult to get into the nitty gritty detail but what I want to highlight is that we are not losing or adding an order of magnitude date assertions in the process. Happy to be corrected.

**Comment by djtfmartin** [comment]
We are parsing year ranges. Ive done the initial work for date precision:

![Uploading Screen Shot 2021-04-13 at 8.28.34 pm.png…]()

**Comment by RobinaSanderson** [comment]
So this looks like the only change that we need to tell end users about is that we no longer support Alpha months and we recommend they provide dates in DwC standard. Is that correct?
