### ISSUE TITLE
Attribution Processor Gaps

### ISSUE THREAD

**Issue by charvolant** [AtlasOfLivingAustralia/la-pipelines#281]
Functionality present in biocache-store but apparently absent in the pipelines.

Missing functionality

- [x] Process data hub ID - Implemented in pipelines
- [x] Process provenance - Implemented in pipelines
- [x] Handle attribution. See #271 
- [x] Flag unrecognised collection/institution code combination with an issue - #303 (implementation task)

**Comment by peggynewman** [comment]
Last one is useful. GBIF has issues `Collection match none` and `Institution match fuzzy`

**Comment by RobinaSanderson** [comment]
Hi @peggynewman  - I'm looking at these gap issues to see if there is likely to be any changes that need to be communicated back to data providers or data users. 

This is probably a foolish question, but... is the data hub ID used to calculate and provide record use statistics back to hubs like AVH? 

Similarly, does the handle attribution process have any effect on how we provide data volume statistics for institutions or collections?

I'm just thinking if how we calculate the stats we provide the collections, institutions and data hubs, they might see some chnages in record numbers and we'll need to let them know to expect them. Of course, if we get those stats without using these processes, then all good.

**Comment by charvolant** [comment]
My understanding of how hubs work is incorrect. The hub id is used to allow a direct query on the solr index to pull records from the biocache. @djtfmartin Does this mean that it should be a multi-valued field?

**Comment by djtfmartin** [comment]
thanks @charvolant  - yes. We are currently indexing it as a multi-valued field.

https://github.com/gbif/pipelines/blob/dev/livingatlas/solr/conf/managed-schema#L457

**Comment by djtfmartin** [comment]
I believe this can be marked as done. @javier-molina to confirm.

**Comment by djtfmartin** [comment]
I think this is done. The remaining issue about flagging collection codes has another issue:

https://github.com/AtlasOfLivingAustralia/la-pipelines/issues/303
