### ISSUE TITLE
Classification Processor Gaps

### ISSUE THREAD

**Issue by charvolant** [AtlasOfLivingAustralia/la-pipelines#282]
Functionality present in biocache-store that is not in pipelines or present in a modified form. All functionality described below is not a gap per-se but a different way of doing things that needs to be reviewed.

- [x] Only accept a classification if match hints pass. The pipelines system passes hints to the name matching service. The name matching service then uses the hints to find a plausible match if the supplied classification is ambiguous. The biocache-store also only stores the match if the match corresponds to the supplied hints.
- [x] Mark a record as having a name belonging to the national species lists. This does not seem to be used.
- [x] Convert a match with a homonym flag into no match. The current version accepts the best-result homonym if it is returned.

**Comment by djtfmartin** [comment]
I dont have strong views on these differences.  My preference is drop them to reduce complexity and difference with GBIF.
Happy for  @charvolant to make a call on whether we need/want these additional features.

**Comment by nickdos** [comment]
Agree with @djtfmartin - there are valid cases where we DON'T want to follow the hints and therefore DO want to store the classification if hints don't match. E.g. there are lots of records in Herbaria collections that are for animals (often pest-host interactions). The hints for those collections tend to be "plantae" but records contain "Animalia".

**Comment by charvolant** [comment]
@djtfmartin @nickdos I agree. The hints should be used as hints (and they are in the name matching service). The national species lists thing seems to be a vestigial organ from some earlier time and doesn't seem to reflect any current use. 

I think the homonym flag that already exists in the name matching issues is enough. However, we may find that we need to re-introduce this when we find out that it hides a swathe of poorly classified records. Until then we should leave it alone.

**Comment by charvolant** [comment]
Ticked off. I'll leave someone else to close this once they've reviewed my comments.
