### ISSUE TITLE
Event Processor Gaps

### ISSUE THREAD

**Issue by charvolant** [AtlasOfLivingAustralia/la-pipelines#283]
Functionality in the biocache-store event processor not found in the pipelines implementation.

Missing functionality

- [ ] Try and parse the verbatim event date if an actual event date is not present.
- [x] Date precision setting #298 

Questionable functionality

- [ ] Default a YY date to previous/this century. This needs review. A base year can be supplied to a DateTimeParser but it's not obvious that it's used anywhere.
- [ ] Provide an issue warning that the georeference date is after the event date. If I read the code correctly, the biocache-store operates on a same-day-or-one-after basis, rather than being strict

**Comment by nickdos** [comment]
Similar to another issue I commented on - I think we should avoid trying to parse verbatim values. Cost-benefit analysis seems to tip it towards costing us more (in terms of writing and maintaining code) than we benefit from (usage would be miniscule Im' guessing - if any at all).

**Comment by javier-molina** [comment]
@peggynewman, @djtfmartin apart from implementing date precision setting is there anything else you think it needs to be implemented from this issue?

**Comment by peggynewman** [comment]
Yes I agree to not process the verbatim event date.
I also agree that both the questionable ones are questionable and we should leave them out. I'd be pretty pleased to get feedback that the georeferenceDate check is important functionality, but I wonder if we're likely to.

**Comment by djtfmartin** [comment]
@javier-molina - i dont think so.

**Comment by javier-molina** [comment]
Refer to comment from Peggy on 13 Apr, nothing else to do on this one.
