### ISSUE TITLE
Identification Qualifier Processor Gaps

### ISSUE THREAD

**Issue by charvolant** [AtlasOfLivingAustralia/la-pipelines#284]
The entire identification qualifier processing chain that is in biocache-store is missing.

**Comment by nickdos** [comment]
Not sure what the processing chain does but the DwC term is identification_qualifierhttps://dwc.tdwg.org/list/#dwc_identificationQualifier.

Looking at search interface, we don't even provide a facet for the "processed" version of this field, only the `raw` one:

![image](https://user-images.githubusercontent.com/532845/112238993-d668a800-8c99-11eb-84b1-89af43ab46df.png)

There is so much junk in the values, I'm not really surprised. 

My suggestion is shelve this for future version (don't hold up release for it).

**Comment by javier-molina** [comment]
@peggynewman, @djtfmartin are you happy to follow Nicks suggestion or otherwise is there a strong reason to bring it accross?

**Comment by djtfmartin** [comment]
thanks @javier-molina 
I agree with @nickdos

**Comment by peggynewman** [comment]
Checked this with Niels. Happy to remove the processed value and keep the raw.
