### ISSUE TITLE
Miscellaneous Processor Gaps

### ISSUE THREAD

**Issue by charvolant** [AtlasOfLivingAustralia/la-pipelines#286]
Functionality from the miscellaneous processor in biocache-store that is either missing or requires review.

Missing functionality

- [x] Create an issue for a missing catalogNumber
- [x] Create an issue for dataGeneralizations present in the source data
- [x] Create an issue for an establishmentMeans suggesting an escaped introduced species or cultivar
- [x] Canonicalise the identificationQualifier. See #284 but the functionality is also present here.
- [x] Create an issue for a missing identificationQualifier
- [x] Create an issue for a missing identifiedBy
- [x] Create an issue for a missing identificationReferences
- [x] Create an issue for a missing dateIdentified
- [x] Match and canonicalise interactions and create an issue if needed

Functionality performed in another part of the workflow

- [x] Load images/sounds/videos etc from URLs in the data or in the DwCA

**Comment by peggynewman** [comment]
These look useful to collections, these create the show/hide missing properties in the front end: https://biocache.ala.org.au/occurrences/9db7e97c-d100-4839-9505-554493023c2a 

I'm pretty sure GBIF are working with a new vocab for establishmentMeans. I was asked for data on this issue(assertion)today by AM.

**Comment by nickdos** [comment]
I did a quick check of the ALA data profile for the DQ filters and none of those (missing) assertions are used.

@charvolant, it would be helpful in the future if you could include a link to the code in bioacache-store for each bit of missing functionality. ATM its hard to make a call without more info (that code could provide).

**Comment by peggynewman** [comment]
I checked the usage patterns of these fields with some herbarium folk. There doesn't seem to be a consistent approach to managing data quality with their datasets, aside from a movement towards using the reverse DQ profiles to find problem records. Many of these 'missing' field flags can be found via a SOLR parameter and we can add/remove them in a relatively agile way in any case.

**Comment by RobinaSanderson** [comment]
If I understand the conservation above correctly the End user documentation should list these assertions as no longer being flagged. If you are a data provider and looking to correct records where these assertions would have applied, they can be found by searching for records where the fields are not populated. Is this correct?

**Comment by javier-molina** [comment]
That's my understanding Robina.
