### ISSUE TITLE
Type Status Processor Gaps

### ISSUE THREAD

**Issue by charvolant** [AtlasOfLivingAustralia/la-pipelines#287]
- [x] The pipelines handling of typeStatus suggests that it is trying to extract the typified name (whatever that is but it's the name part of "holotype - Acacia dealbata") The biocache-store attempts to match type status against a vocabulary.

**Comment by djtfmartin** [comment]
I dont think there is anything to do here.  Pipelines also attempts to match type status to a vocabulary. 

See `TypeStatusParser` in GBIF parsers which is used by the `BasicInterpreter` via the `VocabularyParser`.

This relies on a dictionary file currently, but these dictionaries are being migrated into the GBIF registry:

https://github.com/gbif/parsers/blob/master/src/main/resources/dictionaries/parse/typeStatus.tsv

Suggest this can be closed.

**Comment by peggynewman** [comment]
There are a lot of typeStatus values in our vocab that aren't in the GBIF list. Is that a problem?
https://github.com/AtlasOfLivingAustralia/biocache-store/blob/c3088fc796799635273a63c7e9123174128a7e06/src/main/resources/typeStatus.txt

**Comment by javier-molina** [comment]
I feel a bit lost here, from https://github.com/AtlasOfLivingAustralia/la-pipelines/issues/56 Bai identified that only isoparatype was missing and GBIF folks added that to different places as per https://github.com/gbif/gbif-api/issues/72 

Could it be that typeStatus.tsv from Dave's comment only needs to be regenerated to pick the latest changes from https://github.com/gbif/gbif-api/issues/72 ?

**Comment by nickdos** [comment]
I just did a comparison and all values in `typeStatus.txt` are present in GBIF's `TypeStatus.java` file

https://docs.google.com/spreadsheets/d/19fpO1rSxvczQlm7UpVgBf7qqASYdwFAHxKHZa0vRuYw/edit?usp=sharing

**Comment by peggynewman** [comment]
Thanks Nick, as Javier pointed out I was checking the wrong list. So yes, I think that this can be closed so I've ticked it.

**Comment by peggynewman** [comment]
Also, link back to old issue for this https://github.com/AtlasOfLivingAustralia/la-pipelines/issues/56
