### ISSUE TITLE
DRs having the spaces stripped in their key, will cause issues in pipelines?

### ISSUE THREAD

**Issue by sadeghim** [AtlasOfLivingAustralia/la-pipelines#288]
Do we have the occ_uuid mapped to the space-stripped keys? If so, do we have the logic to do same in pipeline?

**Comment by javier-molina** [comment]
@sadeghim  is it better to keep the question in #279 otherwise we can end up with a fair amount of GH issues that will be difficult to track.

**Comment by djtfmartin** [comment]
Initial work on this branch:
https://github.com/gbif/pipelines/tree/223_unique_key_checks
