### ISSUE TITLE
filter deprecated field by default from /ws/index/fields service

### ISSUE THREAD

**Issue by brucehyslop** [AtlasOfLivingAustralia/la-pipelines#293]
Deprecated fields should be not returned by default when retrieving a list of the `/ws/index/fields` web service.

A new parameter will need to be added to include the deprecated fields.

**Comment by brucehyslop** [comment]
Should the deprecated fields where this is a new field include all the properties of the _real_ field?

**Comment by djtfmartin** [comment]
Sorry @brucehyslop  - im not clear on what you mean by "all the properties of the real field. Maybe an example will help.

**Comment by brucehyslop** [comment]
The properties of the non deprecated (_real_) fields listed contain a bunch of properties
```
{
  name: "scientificName",
  jsonName: "scientificName",
  downloadName: "scientificName",
  dataType: "string",
  indexed: true,
  docvalue: true,
  stored: true,
  multivalue: false
}
```

for the deprecated field I currently have:
```
{
  name: "taxon_name",
  deprecated: true,
  newFieldName: "scientificName"
}
```

should we merge all the properties of the `scientificName` into deprecated field `taxon_name`?
eg.
```
{
  name: "taxon_name",
  deprecated: true,
  newFieldName: "scientificName"
  jsonName: "scientificName",
  downloadName: "scientificName",
  dataType: "string",
  indexed: true,
  docvalue: true,
  stored: true,
  multivalue: false
}
```

My preference is to not, this add a little bit more encouragement for users to use the new fields.

**Comment by djtfmartin** [comment]
I agree @brucehyslop
I don't think we need to do this.

**Comment by RobinaSanderson** [comment]
Hi @brucehyslop  - does this mean an end user querying on a old field name can't get the properties for field without querying via the new field name? If this is the case, I will include it in the user documentation.

**Comment by brucehyslop** [comment]
> Hi @brucehyslop - does this mean an end user querying on a old field name can't get the properties for field without querying via the new field name? If this is the case, I will include it in the user documentation.

@RobinaSanderson, that is correct. The rational is that it's a stronger indication that to go and lookup the properties from the new field name.
