### ISSUE TITLE
review changes to config properties

### ISSUE THREAD

**Issue by brucehyslop** [AtlasOfLivingAustralia/la-pipelines#295]
There config properties properties that will change with the updates to the field names.

 - [x] `/data/biocache/config/biocache-config.properties`
   - [x] `auth.substitution.fields`
   - [x] `default.download.fields`
   - [x] `index.fields.tohide`
   - [x] `sensitiveAccessRoles20`
 - [x] `/data/biocache/config/message.properties`
 - [x] `/data/biocache/config/facets.json`

**Comment by javier-molina** [comment]
@brucehyslop I'm not sure this is actively been progressed, feel free to return it to In Progress and assign it to yourself otherwise.

**Comment by adam-collins** [comment]
ansible-inventories changes to biocache-service-quoll look ok. 
biocache-service changes look ok.
ala-install changes look ok for the 27_pipelines_spark_hadoop branch. That pipelines-field-config.json is manually kept in sync with biocache-service is of concern.

ansible-inventories files should contain a comment if they are for use with ala-install's 27_pipelines_spark_hadoop branch.
