### ISSUE TITLE
Fix missing functionality in SearchUtils

### ISSUE THREAD

**Issue by brucehyslop** [AtlasOfLivingAustralia/la-pipelines#296]
The [SearchUtils.class](https://github.com/AtlasOfLivingAustralia/biocache-service/blob/epic/pipelines/develop/src/main/java/au/org/ala/biocache/util/SearchUtils.java) is missing functionality previously provided by `biocache-store`

 - [x] `ALANameSearcher` [SearchUtils.class#289](https://github.com/AtlasOfLivingAustralia/biocache-service/blob/67f92f722024addc20d246918554d1d3df1583a7/src/main/java/au/org/ala/biocache/util/SearchUtils.java#L289)
 - [x] `RankType` [SearchUtils.class#256](https://github.com/AtlasOfLivingAustralia/biocache-service/blob/67f92f722024addc20d246918554d1d3df1583a7/src/main/java/au/org/ala/biocache/util/SearchUtils.java#L256)

**Comment by brucehyslop** [comment]
replacement of `ALANameSearcher` in PR https://github.com/AtlasOfLivingAustralia/biocache-service/pull/583

**Comment by djtfmartin** [comment]
Is this done now ?

**Comment by brucehyslop** [comment]
this has been completed in AtlasOfLivingAustralia/biocache-service/pull/596
