### ISSUE TITLE
Flag unrecognised collection/institution code combination with an issue

### ISSUE THREAD

**Issue by javier-molina** [AtlasOfLivingAustralia/la-pipelines#303]
Comes from #281 and #13

GBIF has issues Collection match none and Institution match fuzzy

Implement UNRECOGNISED_COLLECTION_CODE and UNRECOGNISED_INSTITUTION_CODE

**Comment by peggynewman** [comment]
Example dataset for these issues in GBIF: https://www.gbif.org/occurrence/search?dataset_key=15738fee-78b1-4751-bcc1-cbf7139c68de

Ambiguous institution 0
Ambiguous collection 0
Institution match none 0
Collection match none 0
Institution match fuzzy 1,013,073
Collection match fuzzy 713,054
Institution collection mismatch 300,019

**Comment by adam-collins** [comment]
https://github.com/gbif/pipelines/pull/533

**Comment by nickdos** [comment]
Test site seems to have zero records with either `UNRECOGNISED_COLLECTION_CODE` or `UNRECOGNISED_INSTITUTION_CODE` set (or else its not indexed):

https://biocache-test.ala.org.au/occurrences/search?taxa=&fq=assertions:UNRECOGNISED_COLLECTION_CODE&qualityProfile=ALA&disableAllQualityFilters=true

https://biocache-test.ala.org.au/occurrences/search?taxa=&fq=assertions:UNRECOGNISED_INSTITUTION_CODE&qualityProfile=ALA&disableAllQualityFilters=true

So can't test this from a functional test aspect.

**Comment by adam-collins** [comment]
This is the expected and correct result. 

There are 0 occurrences with `assertions:UNRECOGNISED_COLLECTION_CODE` and `assertions:UNRECOGNISED_INSTITUTION_CODE`.
