### ISSUE TITLE
Investigate the difference in numbers of generalised and alreadyGeneralised

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/la-pipelines#305]
We should investigate the difference in numbers between quoll and prod:

Quoll:

<img width="605" alt="Screen Shot 2021-04-14 at 7 58 50 pm" src="https://user-images.githubusercontent.com/444897/114764559-00befa00-9d5c-11eb-9631-0d51735e25d0.png">

Prod:

<img width="604" alt="Screen Shot 2021-04-14 at 7 58 44 pm" src="https://user-images.githubusercontent.com/444897/114764591-0b798f00-9d5c-11eb-8991-950f6270dac4.png">

cc @charvolant

**Comment by charvolant** [comment]
Looking at some examples, it looks like "already generalised" in the current system includes records with coordinates already below the precision imposed by the SDS, which leads to an "already generalized" term in the dataGeneralzation statement from the SDS. In pipelines, it's based on whether there's a specific dataGeneralizations or informationWithheld term set.

Converting to biocache-store treatment.

**Comment by djtfmartin** [comment]
<img width="633" alt="Screen Shot 2021-04-28 at 4 10 13 pm" src="https://user-images.githubusercontent.com/444897/116427908-586d6300-a83c-11eb-96da-2a7d34b14df4.png">

the counts are more comparable to current production.

LGTM.

Code merged - moving to review

**Comment by javier-molina** [comment]
Sorry @djtfmartin I just noticed this was assigned to me but I'm not sure I'm the best to review this, however from the first comparison in the description to me it seems that one is using Data profiles and not the other has Data profiles disabled.

Here is what I have with Data profile enabled:

![Screen Shot 2021-05-04 at 3 01 09 pm](https://user-images.githubusercontent.com/8326394/116962700-0d46ca80-acea-11eb-9b3c-538ec9576b74.png)

![Screen Shot 2021-05-04 at 3 02 47 pm](https://user-images.githubusercontent.com/8326394/116962707-1172e800-acea-11eb-98e6-4a21dba7eca3.png)

To me there is still something going on with Generalised count, we seem to be marking double what we did in the past.

**Comment by charvolant** [comment]
With profies disabled prod and quoll are much more in-line. 

Prod 
![image](https://user-images.githubusercontent.com/4031353/118575149-23b05400-b7c9-11eb-9fc8-9b8c8fc129fc.png)

Quoll 
![image](https://user-images.githubusercontent.com/4031353/118575199-3e82c880-b7c9-11eb-83d4-5ebd179d85aa.png)

There is something odd going on with the filters on prod, since it presents unrealistically low numbers of records removed.

**Comment by charvolant** [comment]
The most common generalised species Chelonia mydas (Green Turtle) has comparable numbers of generalised records with no profiles: 23384 quoll, 23428 prod). When quality filters are turned on, the numbers change to 23384 quoll and 28 prod. Many of these come from the IMOS data, which have spatial issues. For example https://aws-biocache-quoll.ala.org.au/occurrences/9face0c5-6007-43a5-974e-433b6ce91a04 flags the uncertainty/precision transposition as a warning but https://biocache.ala.org.au/occurrences/087eefe7-d283-476e-9f31-e9a508500095 treats these as a failure and also (incorrectly) flags a biome mismatch.

**Comment by charvolant** [comment]
@javier-molina I think this is a by-product of quality filters triggering in production but not in pipelines.

**Comment by javier-molina** [comment]
@M-Nicholls, @peggynewman do you think this is the case that the pipelines is doin a better job at flagging issues?

**Comment by javier-molina** [comment]
We will accept it as a fact unless otherwise demonstrated, there has been no further input to it.

**Comment by M-Nicholls** [comment]
@javier-molina , Sorry this took me so long to look at.  With the information available I can't say whether pipelines is doing a better job at flagging issues. Pipelines looks to be flagging different issues and so the data pre-filtering is working differently - some of the assertions the filters rely on aren't generated which, along with the different total record counts, is resulting in different results.
