### ISSUE TITLE
Field value enum mapping doesn't happen for the old names

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/la-pipelines#308]
`occurrenceStatus:absent`  is correctly mapped to  `occurrenceStatus:ABSENT`

but

`occurrence_status:absent` isn just mapped to  `occurrenceStatus:absent`

the workaround for this is to add a mapping twice in  [deprecated-enum-values.json](https://github.com/AtlasOfLivingAustralia/ala-install/blob/27_pipelines_spark_hadoop/ansible/roles/biocache-service/files/config/deprecated-enum-values.json)

```
{
    "occurrenceStatus": {
        "present": "PRESENT",
        "absent": "ABSENT"
    },
    "occurrence_status": {
        "present": "PRESENT",
        "absent": "ABSENT"
    },  

```

but this isnt ideal.

**Comment by brucehyslop** [comment]
confirmed that querying for `occurrence_status:absent` and `occurrenceStatus:absent` on biocache-quoll return the same results without seperate mappings configured.
