### ISSUE TITLE
Record view issues

### ISSUE THREAD

**Issue by javier-molina** [AtlasOfLivingAustralia/la-pipelines#309]
Compare current prod vs biocache Quoll

https://biocache-test.ala.org.au/occurrences/b2b2d325-6c4c-40f5-a479-b1d03359c764

https://biocache.ala.org.au/occurrences/b2b2d325-6c4c-40f5-a479-b1d03359c764

1. ~~Occurrence record title is missing~~
2. ~~Additional properties missing~~, ~~instead Dynamic properties is displayed with JSON content.~~ #346 
3. ~~"Data quality tests" list is very short~~
4. ~~Missing "Additional political boundaries information" section~~
5. ~~Missing "Environmental sampling for this location" section~~
6. ~~Missing Catalog number and Other catalog numbers~~
7. Basis of record appears as UNKNOWN supplied basis "Genomic DNA"
8. Licence appears  as UNSPECIFIED instead of CC-By-Int
9. ~~Geospatial section: No Locality, Longitude and Latitude. Is coordinate precision not expected as per the decision of not implementing gbif/pipelines#517 or it should still display the value regardless.~~

**Comment by djtfmartin** [comment]
1. We are missing a basisOfRecord dictionary mapping for the string"Genomic DNA"
2. I think this something to raise an issue for in `ala-hub`. It could be hidden ala-hub using config.
6. `catalogNumber` and `otherCatalogNumbers` is being incorrect mapped to `processed.occurrence.catalogNumber` in biocache service
7. See (1)

**Comment by djtfmartin** [comment]
2. This is now fixed - ive added the parsing of `dynamicProperties` and `miscProperties` is now populated for backwards compatibility
4. This was a deployment issue. Now fixed.
5. This was a deployment issue. Now fixed.

**Comment by javier-molina** [comment]
@djtfmartin I added point 8 and 9. 
7 is still an issue.

**Comment by adam-collins** [comment]
8. https://github.com/gbif/pipelines/pull/532

**Comment by adam-collins** [comment]
7. https://github.com/gbif/parsers/pull/33 and https://github.com/gbif/gbif-api/pull/83

Within biocache-store the mapping of raw to processed basisOfRecord values is inconsistent. e.g. the raw value `Sound` maps to both `BasisOfRecord.Sound` and `BasisOfRecord.HumanObservation`. With this in mind I have avoided making such changes to https://github.com/gbif/parsers/blob/master/src/main/resources/dictionaries/parse/basisOfRecord.tsv  


In deciding what to include  from `biocache-store` I have  included at least the BasisOfRecord types in  production SOLR and those raw_basisOfRecords that  currently do not map in ALA pipelines but do map in production.

**Comment by adam-collins** [comment]
3 & 9 appear to be working in test.

**Comment by djtfmartin** [comment]
I think the mapping of basisOfRecord values should be discussed/coordinated with GBIF. 
We should avoid maintaining our own vocabulary or our own additions to this vocab.

cc @timrobertson100  - this is specifically about a basis of record value we've supported in the past `Genomic DNA`

**Comment by adam-collins** [comment]
discussion for 7 https://github.com/gbif/gbif-api/issues/84

**Comment by javier-molina** [comment]
Any further work on 7. will occur on #397 

Other than that it seems that this ticket needs to be reviewed and deployed to test 8.

**Comment by adam-collins** [comment]
8. is fixed on test.

**Comment by djtfmartin** [comment]
Verified 8. is fixed on test.

I think this can be marked as done. #397 will be a long running issue requiring discussion with GBIF.

**Comment by javier-molina** [comment]
Tested 8 OK

Indeed I created #397 to  work original point 9 on its own.
