### ISSUE TITLE
Search by taxa not working properly 

### ISSUE THREAD

**Issue by javier-molina** [AtlasOfLivingAustralia/la-pipelines#310]
This [search query](https://aws-biocache-quoll.ala.org.au/occurrences/search?taxa=pogona) is not doing the right thing, as compared [with prod](https://biocache.ala.org.au/occurrences/search?taxa=pogona). It might be a name matching issue...

Reported by @nickdos

**Comment by djtfmartin** [comment]
The fix for this has been done by @brucehyslop and is in this Draft PR

https://github.com/AtlasOfLivingAustralia/biocache-service/pull/582

**Comment by brucehyslop** [comment]
the fix was made in PR AtlasOfLivingAustralia/biocache-service#596
