### ISSUE TITLE
Spatial portal - Area report – Fish species not counted in high level area report

### ISSUE THREAD

**Issue by RobinaSanderson** [AtlasOfLivingAustralia/la-pipelines#317]
**Steps to reproduce:**
1.	Use saved session: https://nectar-spatial-test.ala.org.au?ss=1619678990964
2.	Select Tools – Area report interactive
3.	Check number of Fish 
4.	Click on Number of Species “List” button

**Result:** 
the Fish total = 0. However in the Number of species “List” download there are various fish species with records listed e.g. Cheilodactylus fuscus (Red Morwong) has 706 records

**Notes:** 

- the area report PDF lists 477 species of fish
- this appears to be a problem in production as well.

**Comment by adam-collins** [comment]
Typo. Wrote `Fish` instead of `Fishes`.

https://github.com/AtlasOfLivingAustralia/spatial-hub/commit/c22faa1ccff2ab55b2b231e7b98bf80b9cfff23d

**Comment by adam-collins** [comment]
can be retested

**Comment by qifeng-bai** [comment]
@adam-collins Can you check if your patch  has been merged into develop branch, please
