### ISSUE TITLE
Spatial portal - Area report - Difference in numbers between interactive and .pdf

### ISSUE THREAD

**Issue by RobinaSanderson** [AtlasOfLivingAustralia/la-pipelines#318]
**Steps to reproduce:**
1.	Map area and all species occurrences for Jervis Bay locality with a 10 km radius. Saved session: https://nectar-spatial-test.ala.org.au?ss=1619682904186
2.	Select Tools – Area report PDF and download report
3.	Select Tools – Area report Interactive
4.	Compare numbers

**Results:**
•	Threatened species - PDF = 994,  interactive = 1742
•	Invasive species - PDF = 144, interactive = 268
•	Fishes - PDF = 477, interactive = 0

**Note:** 
Production PDF and interactive area reports has different numbers for 
- Threatened species - PDF = 1155 , interactive = 1936
- invasive species - PDF = 164, interactive = 493
- Journal map articles - PDF = 10 , interactive = 11
- fish - PDF = 574, interactive =

**Comment by adam-collins** [comment]
May be the difference between unique values between `speciesID` and `names_and_lsid` facets.

**Comment by adam-collins** [comment]
Existing production issue. Moving the issue to https://github.com/AtlasOfLivingAustralia/spatial-hub/issues/402
