### ISSUE TITLE
Spatial portal - Saved sessions – map doesn’t display if species added to custom area

### ISSUE THREAD

**Issue by RobinaSanderson** [AtlasOfLivingAustralia/la-pipelines#319]
**Steps to reproduce:**
1.	Add an area defined by a bounding box to the map – I used a area smaller than NSW
2.	Add a species to the area – I used pseudonaja textilis
3.	Select Save and name the session
4.	Select Load and select the saved session
The session opens but the map is solid grey.

**For example:**
https://nectar-spatial-test.ala.org.au/?ss=1619755422742 

**Note:** using the default option of Australia as the area allows the session to load properly.

**Comment by javier-molina** [comment]
I can reproduce the bug using a bounding box

https://nectar-spatial-test.ala.org.au/?ss=1619759291936

**Comment by RobinaSanderson** [comment]
Hi @djtfmartin  - I'm still getting a grey pane for both saved searches from last week and a new one today
https://nectar-spatial-test.ala.org.au/?ss=1620000927890
![image](https://user-images.githubusercontent.com/23368496/116832582-d04edb00-abf8-11eb-9cf1-a3017bb45356.png)

I'm using google chrome Version 90.0.4430.93 (Official Build) (64-bit)
I've also tried Firefox 78.10.0esr (64-bit) and got the same problem.

**Comment by adam-collins** [comment]
MapService.zoomToAll is not working correctly. It was setting an incorrect maxLatitude during testing.

**Comment by djtfmartin** [comment]
Need to update http://nectar-spatial-test.ala.org.au/
