### ISSUE TITLE
Spatial portal - single scatterplot issues

### ISSUE THREAD

**Issue by RobinaSanderson** [AtlasOfLivingAustralia/la-pipelines#320]
Issues:

- When Scatterplot single is selected and the parameters selection screen opens, only 6 environmental layers are available. There are 165 in production
- if you try to run the scatterplot with a custom area (bounding box defined) scatterplot hangs
- if you run the single scatterplot, then **Download** the scatterplot data and try to open in excel - you first get a message that excel will try to repair the file, then you get a message the file is corrupted. Sample data used for scatterplot - https://nectar-spatial-test.ala.org.au?ss=1619757132490 
 No background species selected. Layers used: **Endemism** and **Precipitation - annual (Bio12)**

**Comment by djtfmartin** [comment]
Scatterplot single didnt work for with or without an area.

**Comment by adam-collins** [comment]
Log in spatial-service indicates that spatial-hub failed to generate a valid qid.

**Comment by javier-molina** [comment]
Related to #327 and #334

**Comment by djtfmartin** [comment]
This can be re-tested.

**Comment by qifeng-bai** [comment]
It works on spatial-test
