### ISSUE TITLE
Spatial portal - Tabulate - layers not available for selection

### ISSUE THREAD

**Issue by RobinaSanderson** [AtlasOfLivingAustralia/la-pipelines#321]
**Tabulate 1D**

Select Tools - Tabulate 1D

in the layers selection section 21 layers are available. In Production there are 353

**Tabulate 2D**

1. select Tools - Tabulate 2D

in the layers selection 0 layers are available

**Comment by adam-collins** [comment]
Unrelated to biocache. No 2D tabulation available in this test environment.
