### ISSUE TITLE
Implement Missing Coordinate Precision, and the Too Precise flags

### ISSUE THREAD

**Issue by javier-molina** [AtlasOfLivingAustralia/la-pipelines#322]
From #285 description.

There are missing assertions that need to be carried to LA Pipelines implementation.

**Comment by djtfmartin** [comment]
I don't think we should (re)implement a flag for missing coordinate precision for 2 reasons:

1) GBIF arent doing this (and i think the reason why is (2)
2) Of the data in ALA, only 390,314 records have this value. That mean we will flag 99.5% of records with this problem which doesn't seem to be a useful thing to do.

Sorry for not commenting on the other issue.

cc @M-Nicholls @javier-molina
