### ISSUE TITLE
Spatial portal - Compare points - can't get past Loading

### ISSUE THREAD

**Issue by RobinaSanderson** [AtlasOfLivingAustralia/la-pipelines#326]
**Steps to reproduce:**
1. Tools - Compare points
2. Add point - and drop point on map of Australia
3. Add point - and drop point on map of Australia
4. Compare

**Result:**
Loading bar shows but doesn't go any further.
![image.png](https://images.zenhubusercontent.com/5823adcbe40e5714b170035c/5673ef19-a3eb-45b0-a223-044c5dd153c9)

**Notes:**
I let it run for 20 mins but didn't get any further

**Comment by adam-collins** [comment]
Unrelated to biocache.

Regression bug. Was also broken on production. Fixed with sampling.ala.org.au change.
