### ISSUE TITLE
Spatial portal - Compare areas - no species found

### ISSUE THREAD

**Issue by RobinaSanderson** [AtlasOfLivingAustralia/la-pipelines#327]
**Steps to reproduce:**
1. define an area using a bounding box
2. define a second area using a bounding box
3. Compare areas - select the 2 areas defined
4. choose to see all species
5. Compare 

**Results:**
Report displays. Occurrences are found, but no species are found.

**Areas selected:**
![image.png](https://images.zenhubusercontent.com/5823adcbe40e5714b170035c/19036cb4-6e09-4ea1-b8a0-b618ca992dae)

**Report results:**
![image.png](https://images.zenhubusercontent.com/5823adcbe40e5714b170035c/5f91bf4c-1afb-4bd0-b453-f4c310cb8ae6)

**Comment by adam-collins** [comment]
Log in spatial-service indicates that spatial-hub failed to generate a valid qid.

**Comment by adam-collins** [comment]
With the qid issue resolved, the output of /occurrences/facet/download with lookup=true count=true facet=names_and_lsid differs.

new, including many failed name matches (rows containing only a value in `number of records` column)
Species Name | Scientific Name Authorship | Kingdom | Phylum | Class | Order | Family | Genus | Species | Subspecies | Number of records
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --

current/expected
names_and_lsid | Species Name | Scientific Name Authorship | Taxon Rank | Kingdom | Phylum | Class | Order | Family | Genus | Vernacular Name | Number of records
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --

**Comment by djtfmartin** [comment]
This needs to be fixed.

**Comment by adam-collins** [comment]
https://github.com/AtlasOfLivingAustralia/biocache-service/pull/608

**Comment by adam-collins** [comment]
Biocache-service is deployed with the fix. Can be retested.

**Comment by qifeng-bai** [comment]
It works on Spatial-test
