### ISSUE TITLE
Set up production biocache servers

### ISSUE THREAD

**Issue by javier-molina** [AtlasOfLivingAustralia/la-pipelines#328]
This tasks aim to create the production servers for biocache that will soon replace the current production biocache servers.

- [x] Create VMs with latest supported Ubuntu for Biocache Service/Hub similar to current production
- [x] Deploy biocacache-service and hub

VM specs are the same as current production servers

**Comment by matthewandrews** [comment]
I've created two biocache-service instances so far; one more to go, plus the hub instances.
