### ISSUE TITLE
Vocabulary management for pipelines

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/la-pipelines#33]
A placeholder issue to discuss what we can aim to achieve with vocabulary management for stage 1 of the infrastructure upgrade.

The current pipelines implementation is largely using dictionaries (eg. for basisOfRecord, licence)  in a similar fashion to biocache-store code. Most of these dictionaries are managed here:

https://github.com/gbif/parsers/tree/master/src/main/resources/dictionaries/parse

More tooling for vocabulary management is in development by GBIF but may or may not be available for use in Stage 1 of the infrastructure upgrade.

cc @timrobertson100 

Thanks for the prompt @Tasilee

**Comment by timrobertson100** [comment]
For info:

We're in the process of migrating all that out of the dictionary codebases into  https://github.com/gbif/vocabulary

We are going through all verbatim terms seen in all vocabularies bootstrapping that DB (we also anticipate including all the [VertNet mappings](https://github.com/VertNet/DwCVocabs/tree/master/vocabs). The UI for data managers already exists on the GBIF registry but only for those with permission.

I anticipate the pipelines could use this around April / May.

**Comment by djtfmartin** [comment]
Thanks @timrobertson100 

For stage 1, we aren't currently planning to do any specific work on vocabularies so we are (ALA) likely to just go with the support for vocabulariesthe current version of pipelines has f.

**Comment by ansell** [comment]
Are values only recognised by the GBIF pipelines processing code if they already exist in a vocabulary? The ALA needs to have flexibility in how vocabularies work in that way to support our data providers needs.

**Comment by timrobertson100** [comment]
Thanks @ansell  - the vocabulary server is not used yet.

There will need to be some controlled vocabularies that are regionally focused (e.g. regional geo-codes)  but I anticipate that _most_ things will be cross-cutting concerns that aren't specific to ALA providers. Like ALA, GBIF and VertNet have built out many vocabularies over the last decade too and we are just starting discussions on folding that work into a common set (most likely including the TDWG vocab group too).

Do you have anything specific of concern or is it just to raise this general point?

**Comment by ansell** [comment]
Just a general point at this stage, as we are still planning the project.

**Comment by Tasilee** [comment]
Thanks @djtfmartin. Just adding a link to the work that Paula Zermoglio has started on vocabularies: https://github.com/tdwg/bdq/tree/master/tg4. The immediate problem we have in 'Data Quality'is the unconstrained possible terms in Darwin Core (TG2 work is based on DwC) ... as for example https://github.com/tdwg/dwc-qa/blob/master/data/GBIFDistinctValues/GBIF_distinct_sex_2017-02-27.csv :) etc. (Let alone all the other biodiversity-informatics terms).

**Comment by timrobertson100** [comment]
Thanks @Tasilee 
Paula and John W contributed to the design doc for the vocabulary server and we are now actively working with Paula to populate the content using work done to date through e.g. GBIF mappings, verbatim values seen, VertNet data mappings etc.

**Comment by charvolant** [comment]
It seems a little odd to use such a restricted structure for vocabularies. One of the use cases for a term is "what is this and what other information do you have on it" and I would have thought that SKOS for vocabulary modelling and allowing concepts to be easily extended would be a better fit.

We have a prototype vocabulary server at https://nectar-vocab-test.ala.org.au/ that implements these concepts. You can look at a vocabulary term via https://nectar-vocab-test.ala.org.au/show?iri=http%3A%2F%2Fwww.ala.org.au%2Fvocabulary%2F1.0%2FtaxonomicStatus%2FobjectiveSynonym or using JSON-LD at https://nectar-vocab-test.ala.org.au/ws/resource/show?iri=http%3A%2F%2Fwww.ala.org.au%2Fvocabulary%2F1.0%2FtaxonomicStatus%2FobjectiveSynonym

**Comment by timrobertson100** [comment]
Thanks @charvolant 

Our primary use case is data cleaning - not wider discovery - so the first phase is to get mappings that are otherwise locked in code into a DB and a standard mechanism to control those. I don't foresee this as the long term solution, but for the short-mid term, I anticipate this will help us quickly clean up the existing mess. The model is heavily influenced by SKOS but like you recognize is a subset to meet the immediate needs. I expect our vocabulary mappings are analogous to what (I presume) you have in your Talend system rather than your SKOS server.

**Comment by javier-molina** [comment]
GBIF already have this.
