### ISSUE TITLE
WMS issue - uncertainty circles in spatial portal not rendered 

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/la-pipelines#330]
Uncertainty circles in the spatial portal arent rendered properly with new heatmaps implementation.

**Comment by djtfmartin** [comment]
@adam-collins has a patch for this.

**Comment by adam-collins** [comment]
https://github.com/AtlasOfLivingAustralia/biocache-service/pull/599

**Comment by adam-collins** [comment]
Fix merged and working.
