### ISSUE TITLE
Dateline issues with mapping

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/la-pipelines#332]
see

https://aws-biocache-quoll.ala.org.au/ws/ogc/wms/reflect?BBOX=-20037508.342789244,-20037508.342789244,20037508.342789244,20037508.342789244&q=lsid%3A&SERVICE=WMS&REQUEST=GetMap&VERSION=1.1.1&SRS=EPSG%3A3857&ATTRIBUTION=Atlas+of+Living+Australia&FORMAT=image%2Fpng&BGCOLOR=0x000000&TRANSPARENT=true&ENV=color%3Ae6704c%3Bname%3Acircle%3Bsize%3A4%3Bopacity%3A0.8&OUTLINE=false&WIDTH=256&HEIGHT=256#

 {
   "message": "Error from server at http://localhost:8985/solr/biocache: Can't parse rectangle '["168.74999999999997 -90.3668243285445" TO "-168.39843749999997 90.53293981444256"]' because: Bad Y value -90.3668243285445 is not in boundary Rect(minX=-180.0,maxX=180.0,minY=-90.0,maxY=90.0)", "errorType": "Query syntax invalid"
 }

**Comment by javier-molina** [comment]
Low priority, it already happens in prod.

**Comment by djtfmartin** [comment]
Fixed in this PR https://github.com/AtlasOfLivingAustralia/biocache-service/pull/609
