### ISSUE TITLE
Suspect truncation issues in user assertion migration script

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/la-pipelines#333]
Noticed from load testing:

https://aws-biocache-quoll.ala.org.au/ws/occurrence/fa94690a-4965-4502-a8d3-8b216f421f88#

Error message:

{
"message": "Unexpected character ('"
Error: Parse error on line 2:
...pected character ('"' (code 34)): was ex
-----------------------^
Expecting 'EOF', '}', ':', ',', ']'
' (code 34)): was expecting comma to separate Object entries
 at [Source: (String)"[{"problemAsserted": "","comment": "Thanks Ely. The collecting date is consistent with the known activity of Samuel Browne (d. 1698). ","userId": "10012","uuid": "747add8a-c2a4-4e90-9882-9061aec7d91a","created": "2020-10-07T00:54:45Z","code": "50000","qaStatus": "50002","userEmail": "","referenceRowKey": "fa94690a-4965-4502-a8d3-8b216f421f88","name": "userVerified","relatedUuid": "8792d6d6-c197-4a8c-a34c-ad761532615a","rowkey": "fa94690a-4965-4502-a8d3-8b216f421f88","userDisplayName": "Nimal Kar"[truncated 13472 chars]; line: 1, column: 523] (through reference chain: au.org.ala.biocache.dto.UserAssertions[0])", "errorType": "Server error"
}

We have similar truncation issues with the migration script for Qids. See #324

**Comment by alexhuang091** [comment]
Hi Dave, 

- those data in `userassertions` I guess were migrated with old script which has some issues.
- I checked my local database which was migrated from biocache test but couldn't find this record.
- So I just need to find out from where this record comes and do a migration test locally with the new script to see if the issue still happens. I'll check with Adam.

**Comment by alexhuang091** [comment]
Hi Dave, I used the current migration script to migrate Cassandra data and migrated data is good.

So all we need to do is delete old data from quoll server and load new ones.

<img width="1651" alt="截屏2021-05-12 下午2 48 42" src="https://user-images.githubusercontent.com/61677987/117919889-380bd100-b331-11eb-9fa1-a1cb2c33e5b5.png">

**Comment by alexhuang091** [comment]
Hi Dave,

New data loading is finished.

https://aws-biocache-quoll.ala.org.au/occurrences/fa94690a-4965-4502-a8d3-8b216f421f88

**Comment by djtfmartin** [comment]
LGTM - thanks @alexhuang091

**Comment by alexhuang091** [comment]
> LGTM - thanks @alexhuang091

Hi Dave, I have local test code which reads all entries in the userassertions table. I'll run it against the quoll server tomorrow.

**Comment by alexhuang091** [comment]
Hi Dave,

I've done a test on data migrated from `aws-cass-cluster-1b.ala`. It's actually the same data I verified several days ago (to verify if my migration script is good).

Result:

- all 15750 rows `uuid, [assertion, assertion, ...]` can be read. Means for every record, we can read out the list of user assertions.
- 110 assertions have broken `snapshot` field (so failed to be parsed as JSON object) but it's because data originally broken in original database, has nothing to do with migration script.

So this ticket is safe to be closed I think. We can create a new ticket if new issues found.
