### ISSUE TITLE
Spatial Portal - AOO and EOO - can't find occurrences

### ISSUE THREAD

**Issue by RobinaSanderson** [AtlasOfLivingAustralia/la-pipelines#334]
Steps to replicate:
1. Tools - Calculate AOO and EOO
2. Select Australia as the area
3. Select Eudyptula minor as the species
4. keep all other defaults and select Next

Tool starts running, after about 3 mins there is an error message to say no occurrences can be found.
![image.png](https://images.zenhubusercontent.com/5823adcbe40e5714b170035c/64494f11-9938-4130-8da8-7728b1496ca4)

Notes:
I've tried searching for the species and adding it to the map, then running the tool, and I get the same error.

**Comment by adam-collins** [comment]
Log in spatial-service indicates that spatial-hub failed to generate a valid qid.

**Comment by adam-collins** [comment]
this can be retested

**Comment by qifeng-bai** [comment]
On Spatial-test, Move to Tas, select "Eucalyptus gunnii",  AOOEOO works
