### ISSUE TITLE
Create Spreadsheet with field and assertion changes

### ISSUE THREAD

**Issue by javier-molina** [AtlasOfLivingAustralia/la-pipelines#336]
As part of the end user documentation an easy to read spreadsheet that groups fields and assertions in different categories depending on the changes that happened from current production will be a valuable instrument to communicate with our user base.

Currently the single source of truth for field and assertion mapping is a json file part of biocache-service.

The spreadsheet should be easy to maintain and ideally should be generated from the single source of truth either entirely or almost entirely by means of a script or tool to such extent that the spreadsheet can be regenerated over and over again.

@RobinaSanderson to adjust these requirements as need it.

**Comment by brucehyslop** [comment]
the following command can be used to convert the json data into a csv:
```
curl "https://biocache-test.ala.org.au/ws/assertions/codes?deprecated=true" | jq -r '(map(keys) | add | unique) as $cols | map(. as $row | $cols | map($row[.])) as $rows | $cols, $rows[] | @csv' 
```

[pipelines_assertions_codes.csv](https://github.com/AtlasOfLivingAustralia/la-pipelines/files/6595011/pipelines_assertions_codes.csv)

**Comment by RobinaSanderson** [comment]
Spreadsheet of new, changed and removed assertions - 
[Assertions_NewChangedRemoved20210617.xlsx](https://github.com/AtlasOfLivingAustralia/la-pipelines/files/6674806/Assertions_NewChangedRemoved20210617.xlsx)

**Comment by RobinaSanderson** [comment]
Spreadsheet has been added to the knowledge base article: https://support.ala.org.au/en/support/solutions/articles/6000249563-ala-infrastructure-changes-2021
