### ISSUE TITLE
decade/occurrenceYear facet returning inconsistent results

### ISSUE THREAD

**Issue by adam-collins** [AtlasOfLivingAustralia/la-pipelines#337]
Faceting on `decade` returns the expected results, one per decade. The result indicates that the correct field to use is now `occurrenceYear` https://aws-biocache-quoll.ala.org.au/ws/occurrences/search?q=*:*&pageSize=0&facet=true&facets=decade&flimit=-1

However faceting on `occurrenceYear` returns incorrect results. A ten year span for each year.  https://aws-biocache-quoll.ala.org.au/ws/occurrences/search?q=*:*&pageSize=0&facet=true&facets=occurrenceYear&flimit=-1

**Comment by adam-collins** [comment]
production is also wrong

**Comment by djtfmartin** [comment]
Issue moved to [AtlasOfLivingAustralia/biocache-service #708](https://github.com/AtlasOfLivingAustralia/biocache-service/issues/708) via [**ZenHub**](https://www.zenhub.com/)
