### ISSUE TITLE
fix i18n mappings to new field names

### ISSUE THREAD

**Issue by brucehyslop** [AtlasOfLivingAustralia/la-pipelines#338]
The i18n mappings defined in the `messages.properties` files is used by the `QueryFormatUtil` produce the display query. 

The mappings need to updated to reflect the new field names and perform field translation before retrieving form the message source

**Comment by brucehyslop** [comment]
updates to `message.properties` done in AtlasOfLivingAustralia/biocache-service#603

**Comment by djtfmartin** [comment]
Reviewed and merged
