### ISSUE TITLE
WMS  - HQs are being ignored

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/la-pipelines#342]
The `hq` parameter for WMS tiles which allows certain facets to be hidden is being ignored.

This breaks the biocache-hub UI map which allows uses to switch layers off/on

**Comment by adam-collins** [comment]
`sel` also ignored

**Comment by adam-collins** [comment]
this fails https://aws-biocache-quoll.ala.org.au/ws/mapping/wms/reflect?q=*%3A*&qualityProfile=ALA&SERVICE=WMS&REQUEST=GetMap&VERSION=1.1.1&LAYERS=ALA%3Aoccurrences&STYLES=&FORMAT=image%2Fpng&TRANSPARENT=true&HEIGHT=256&WIDTH=256&BGCOLOR=0x000000&OUTLINE=false&ENV=colormode%3Ataxon_name%3Bname%3Acircle%3Bsize%3A4%3Bopacity%3A1%3B&GRIDDETAIL=32&STYLE=opacity%3A0.8&SRS=EPSG%3A3857&BBOX=15028131.257091932,-5009377.085697311,16280475.52851626,-3757032.814272983
 
might be single quote messing up the query

**Comment by adam-collins** [comment]
`sel` not in use anymore.

**Comment by djtfmartin** [comment]
FIxed and merged in 3.0.2
