### ISSUE TITLE
Set up production Zookeeper cluster

### ISSUE THREAD

**Issue by javier-molina** [AtlasOfLivingAustralia/la-pipelines#344]
Commision updated zookeeper Quoll cluster using latest version of Ubuntu

**Comment by matthewandrews** [comment]
I've created 5 new instances (`aws-zoo-2021-1` to `aws-zoo-2021-5`) but not deployed zookeeper to them yet.  Planning to create the new solr cluster, then deploy solr & zookeeper together.
