### ISSUE TITLE
Hide dynamic properties displayed as raw json

### ISSUE THREAD

**Issue by javier-molina** [AtlasOfLivingAustralia/la-pipelines#346]
Dynamic properties are displayed as raw json in biocache hub and must be hidden. This applies to the usual hubs (ala, avh, ozcam?)

Additional properties section already display content in a table.

See details

![Screen Shot 2021-05-14 at 1.10.33 pm.png](https://images.zenhubusercontent.com/56b920d76caf56c9d38c5513/d5b19482-c4a9-4eef-9117-6c23655925d3)

Source: https://aws-biocache-quoll.ala.org.au/occurrences/b2b2d325-6c4c-40f5-a479-b1d03359c764

**Comment by djtfmartin** [comment]
In version 3.0.0. i removed the `dynamicProperties` from the biocache service record JSON. The properties are available in the `miscProperties` field for backwards compatibility.

Hence there is nothing to do on biocache-hubs side
