### ISSUE TITLE
AVH Testing

### ISSUE THREAD

**Issue by javier-molina** [AtlasOfLivingAustralia/la-pipelines#348]
From Niels

> So, the issue with the duplicates not displaying on the occurrence detail pages appears to have been fixed. There is even some doubling up in the data set properties (duplicate status is there twice). Dynamic properties are still displayed as a JSON string. They also contain some properties that are Darwin Core terms (probably not a pipeline issue). Original vs. Processed looked good, although I get a printed 'a' tag around the processed conservation status. It lets me do a user assertion, but it does not show up afterwards, so I am not sure if it really lets me do it. Apart from these minor things it works quite well.

> I found some other issues, but they are already in the current AVH. One of them is the date widget, which displays the wrong data for incomplete dates that have year and month. This is in the old version:

![image.png](https://images.zenhubusercontent.com/56b920d76caf56c9d38c5513/314dd6a3-96b0-4a15-ae2c-ab844103b145)

> and this in the new version:

![image.png](https://images.zenhubusercontent.com/56b920d76caf56c9d38c5513/89a23b2a-5e48-44a4-833e-2ea3136a70b9)

> The new version gets the date precision right, but still gives an incorrect date.

> Also, 'Identification remarks' should not be under Event of course (it is also under Dataset), but that is probably just configuration.

**Comment by javier-molina** [comment]
@djtfmartin, @brucehyslop apologies I didn't add this earlier. Can you cast your eye on this and let me know your thoughts?

I would say there is something not displayed appropriately with the supplied date.

Duplicate 'Duplicate status' and Identification remarks I think they need some attention.

@nielsklazenga do you have the url for the particular record(s) you used?

**Comment by djtfmartin** [comment]
I've removed `dynamicProperties` from the biocache service output for a record to help with backwards compatibility for this release.

**Comment by nielsklazenga** [comment]
The record the screenshots were made from is:
- https://avh.ala.org.au/occurrences/96f223e8-d420-4d11-b93f-728344daf324
- https://aws-biocache-quoll.ala.org.au/avh/occurrences/96f223e8-d420-4d11-b93f-728344daf324

When trying to find it back, I noticed that the query that I used to get it: https://avh.ala.org.au/occurrences/search?q=*%3A*&fq=month%3A*&fq=assertions%3A%22incompleteCollectionDate%22, does not work in the test instance, https://aws-biocache-quoll.ala.org.au/avh/occurrences/search?q=*%3A*&fq=month%3A*&fq=assertions%3A%22incompleteCollectionDate%22. The 'incomplete collection date' option does not show in the Record Issues facet field, which explains that result. Also, a lot of the indexes in that facet field are not in human-friendly format, _e.g._ MISSING_GEOREFERENCEVERIFICATIONSTATUS. Not sure if that is something I was supposed to test for.

Also, a lot of the records I tried to find by just copying and pasting the UUID into the URL could not be found in the test instance. These are all old records, so this cannot be explained away by the data not being there when the data set was loaded. Maybe a new data load can still fix this?

**Comment by javier-molina** [comment]
Thanks @nielsklazenga

not human friendly names looks like something to address.

As to the missing records these are the DRs that have not yet been loaded to the pipelines due to inconsistencies: 

https://github.com/AtlasOfLivingAustralia/la-pipelines/issues?q=is%3Aissue+is%3Aopen+label%3Adata-cleansing+  
Chances are that the records you are chasing are on one of those DRs

**Comment by nielsklazenga** [comment]
Thanks @javier-molina , none of those missing DRs are in AVH. Two of the AVH DRs had configuration issues initially, but those issues were resolved quite quickly.

**Comment by brucehyslop** [comment]
The reason for no results returned from https://aws-biocache-quoll.ala.org.au/avh/occurrences/search?q=*%3A*&fq=month%3A*&fq=assertions%3A%22incompleteCollectionDate%22 is because we don't have a mapping defined for the assertion `incompleteCollectionDate` to a GBIF Occurrence Issue. 

The closes I can find is `IDENTIFIED_DATE_UNLIKELY` however it seems to an assertion on the `dateIdentified` whereas `year` and `month` are derived from the `eventDate`

**Comment by brucehyslop** [comment]
I'll revisit the assertion mappings. There seem to have been a few new assertion values added to pipelines since the original mapping was done (`MISSING_GEOREFERENCEVERIFICATIONSTATUS`).

**Comment by brucehyslop** [comment]
We should probably map `incompleteCollectionDate` or either `RECORDED_DATE_INVALID` or `RECORDED_DATE_UNLIKELY`

**Comment by nielsklazenga** [comment]
I am actually happy for the "incompleteCollectionDate" test not to be there anymore. I can get the same result with https://aws-biocache-quoll.ala.org.au/avh/occurrences/search?q=*%3A*&fq=month%3A*&fq=-day%3A*, which is a nicer query. Did not realise we had a 'day' field before.

**Comment by nielsklazenga** [comment]
`incompleteCollectionDate` is neither `invalid`, nor `unlikely`. Best not to map it to anything. It used to be included in `RECORDED_DATE_INVALID`, but it was deliberately taken out. With the date widget in place, it probably does not warrant a warning anymore.  The `date_precision` field does the job of the warning now: https://aws-biocache-quoll.ala.org.au/avh/occurrences/search?q=*%3A*&fq=date_precision:MONTH.

**Comment by brucehyslop** [comment]
FYI, the new field is `datePrecision` however both field names will work.

**Comment by nielsklazenga** [comment]
👍 Does that mean that all fields will be camel-cased?

**Comment by brucehyslop** [comment]
I've reviewed the assertion mappings and am suggesting add the following mappings:
 - `unrecognisedCollectionCode` -> `COLLECTION_MATCH_NONE`
 - `unrecognisedInstitutionCode` -> `INSTITUTION_MATCH_NONE`
 - `unrecognisedOccurrenceStatus` -> `OCCURRENCE_STATUS_UNPARSABLE`
 - `altitudeOutOfRange` -> `ELEVATION_UNLIKELY`

**Comment by brucehyslop** [comment]
most fields now use the DwC terms and are camel case
