### ISSUE TITLE
Collectory integration for a data provider  / IPT

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/la-pipelines#352]
See related issue #351

This is an extension to #351, which will load all the archives into the correct place in HDFS for a single data provider which is how we represent IPTs in collectory.

1) Collectory lookup using the data provider web service `/ws/dataProvider/dp321`
1) Retrieve a list of data resources for this data provider
1) For each data resource:
   1) Parse supplied JSON, and validate that this resource is available in DwCA format (as opposed to DwC CSV)
   1) Retrieve the URL for the DwCA archive from the connection parameters
   1) Download the archive
   1) Transfer to HDFS directory
   
cc @peggynewman @sadeghim

**Comment by djtfmartin** [comment]
I've written a basic jenkins job to do this. See http://nci3-jenkins:9196/job/Data-provider-loads/job/Load-data-provider/

**Comment by javier-molina** [comment]
Issue moved to [AtlasOfLivingAustralia/data-management #704](https://github.com/AtlasOfLivingAustralia/data-management/issues/704) via [**ZenHub**](https://www.zenhub.com/)
