### ISSUE TITLE
enumerated field values not processing in display name

### ISSUE THREAD

**Issue by brucehyslop** [AtlasOfLivingAustralia/la-pipelines#355]
The `QueryFormatUtil` is not correctly handling enumerated values (vocab) after mapping has occurred. 

Enumerated values are processed correctly when the new vocabulary is used however not with deprecated vocab value. 

eg: all these queries should result in the same display name: 
 - query: `basisOfRecord:PreservedSpecimen`
 - query: `basis_of_record:PreservedSpecimen`
 - query: `basisOfRecord:PRESERVED_SPECIMEN`
 - query: `basis_of_record:PRESERVED_SPECIMEN`

-> displayName: `Record type:Preserved specimen`

**Comment by djtfmartin** [comment]
Reviewed and merged. Released in 3.0.3
