### ISSUE TITLE
Error loading record with raw associatedOccurrences values

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/la-pipelines#358]
e.g.https://biocache-test.ala.org.au/occurrences/ff802318-5b38-4c0f-b855-891143b6b002

cc @brucehyslop @RobinaSanderson

**Comment by djtfmartin** [comment]
This is now working.
https://biocache-test.ala.org.au/occurrences/ff802318-5b38-4c0f-b855-891143b6b002

**Comment by brucehyslop** [comment]
There are still come processed `associatedOccurrences` that contain non uuid values. 

https://biocache-test.ala.org.au/occurrences/search?q=associatedOccurrences:(%22Colonyestimation1_adults%22%20OR%20%22-%22)

**Comment by djtfmartin** [comment]
@brucehyslop Possibly fixed in the last reinterpretation / reindex.
That URL doesn't give any results now.

**Comment by javier-molina** [comment]
Last url above does not get results for me either, I checked a partial download with associatedOccurrences and I could not spot any rough value.
