### ISSUE TITLE
WMS Dateline problem for density grids

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/la-pipelines#359]
Visible when zoomed out

<img width="1148" alt="Screen Shot 2021-05-22 at 2 11 25 pm" src="https://user-images.githubusercontent.com/444897/119227801-9db54580-bb07-11eb-8c68-c4b6ae5e8e36.png">

related to this is the display (or lack of) records in the antarctic

<img width="1122" alt="Screen Shot 2021-05-22 at 2 12 34 pm" src="https://user-images.githubusercontent.com/444897/119227839-d9500f80-bb07-11eb-8038-4bce34298563.png">

**Comment by djtfmartin** [comment]
For the second problem:

```
{
  "message": "Error from server at http://localhost:8986/solr/biocache: Error from server at null: java.lang.IllegalArgumentException: Too many cells (581 x 240) for level 11 shape Rect(minX=174.02343749999997,maxX=-84.0234375,minY=-86.28215909903321,maxY=-65.28223012387865)",
  "errorType": "Query syntax invalid",
  "statusCode": 400
}
```

suggest we need a separate grid level mapping for density grids (as well as the one we have for points).

**Comment by adam-collins** [comment]
https://github.com/AtlasOfLivingAustralia/biocache-service/pull/615

This pull request fixes both issues.
