### ISSUE TITLE
Add habitat values from IRMNG

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/la-pipelines#36]
Extracted from #26.

Needs detail added based on current biocache-store code.

**Comment by djtfmartin** [comment]
This discussion on IRMNG is relevant in how we continue to manage this requirement

https://github.com/AtlasOfLivingAustralia/biocache-store/issues/375#issuecomment-618078102

**Comment by djtfmartin** [comment]
This is a duplicate of #97
