### ISSUE TITLE
Image modal in `list` view shows "unable to load image..."

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/la-pipelines#362]
https://biocache-test.ala.org.au/occurrences/search?q=%28lsid%3Aurn%3Alsid%3Abiodiversity.org.au%3Aafd.taxon%3A435d01a5-7a68-4a24-b220-a7c32ea66b33+OR+lsid%3Ahttps%3A%2F%2Fid.biodiversity.org.au%2Ftaxon%2Fapni%2F51311124%29+AND+basis_of_record%3APRESERVED_SPECIMEN+AND+occurrence_date%3A%5B2000-01-01T00%3A00%3A00Z+TO+2010-01-01T00%3A00%3A00Z%5D&qualityProfile=ALA#tab_recordImages

click on an image in "Images" tab. Shows:

![image](https://user-images.githubusercontent.com/532845/119289295-ab94d300-bc8d-11eb-84db-56f2d9a1cffb.png)

Might be that `images-test` is not synced to new image server for release?

**Comment by javier-molina** [comment]
This was caused by the use of two image service instances, two days ago one service was shutdown while the other was sync with the latest data in solr quoll.

Images tab works now for me.
