### ISSUE TITLE
User annotation "type" drop-down is missing `Duplicate record` option

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/la-pipelines#364]
When viewing a single record, click the "Flag an issue" button. 

Prod has the following issue types:

![image](https://user-images.githubusercontent.com/532845/119290213-738e8f80-bc8f-11eb-9d5a-dfb652daec5b.png)

Pipelines is missing `Duplicate record`:

![image](https://user-images.githubusercontent.com/532845/119290276-91f48b00-bc8f-11eb-91b2-89f50495a996.png)

**Comment by javier-molina** [comment]
I thought that was because #350 hasn't being released to test.

**Comment by djtfmartin** [comment]
Ive pushed #350 to test and its still an issue.

**Comment by djtfmartin** [comment]
This is fixed on biocache-test.ala.org.au version 3.0.6

![Uploading Screen Shot 2021-05-25 at 9.58.05 pm.png…]()

**Comment by nickdos** [comment]
Tested ✅
