### ISSUE TITLE
Record view: data quality tests are mostly missing

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/la-pipelines#365]
E.g. compare the "Data quality tests" sections for this record in prod and test...

https://biocache.ala.org.au/occurrences/935022ca-0691-43a1-bd92-99ce37a8215d#dataQuality

https://biocache-test.ala.org.au/occurrences/935022ca-0691-43a1-bd92-99ce37a8215d#dataQuality

Latter is only showing the 5 "Missing properties".

**Comment by alexhuang091** [comment]
In this record https://biocache-test.ala.org.au/occurrences/fccf46f3-0260-4c77-a1a0-7aee0231760b

on the left side panel, you can see the passed data quality test is 0

<img width="291" alt="截屏2021-05-24 下午1 19 39" src="https://user-images.githubusercontent.com/61677987/119294676-5ca06b00-bc98-11eb-8c28-335101e3d525.png">

**Comment by djtfmartin** [comment]
I think Ive fixed this in 3.0.5.

**Comment by peggynewman** [comment]
The flags are there but they're a bit of a mishmash - the order is strange, the info links aren't working, and they are a mixture of uppercase variable names and human readable labels. Should I start a new ticket?

**Comment by brucehyslop** [comment]
@djtfmartin the change made to [AssertionCodes::getCodes](https://github.com/AtlasOfLivingAustralia/biocache-service/blob/12581d4616e26a5e823cc1025401fe3b74a0cea0/src/main/java/au/org/ala/biocache/dto/AssertionCodes.java#L42) will change the assertion / error codes. Is this going to be an issue for end users?

**Comment by brucehyslop** [comment]
FYI: there are no occurrence records that have the assertions:
- `CONTINENT_COUNTRY_MISMATCH`
- `CONTINENT_DERIVED_FROM_COORDINATES`
- `COORDINATE_ACCURACY_INVALID`
- `COORDINATE_PRECISION_INVALID`
- `COORDINATE_PRECISION_UNCERTAINTY_MISMATCH`
- `COORDINATE_REPROJECTION_SUSPICIOUS`
- `ELEVATION_NOT_METRIC`
- `ELEVATION_UNLIKELY`
- `GEOREFERENCED_DATE_UNLIKELY`
- `IDENTIFIED_DATE_INVALID`
- `INTERPRETATION_ERROR`
- `MISSING_COORDINATEPRECISION`
- `MODIFIED_DATE_INVALID`
- `MULTIMEDIA_DATE_INVALID`
- `MULTIMEDIA_URI_INVALID`
- `REFERENCES_URI_INVALID`
- `TAXON_INDETERMINATE_SPECIES`
- `UNCERTAINTY_NOT_SPECIFIED`
- `UNKNOWN_COUNTRY_NAME`

**Comment by brucehyslop** [comment]
> @djtfmartin the change made to [AssertionCodes::getCodes](https://github.com/AtlasOfLivingAustralia/biocache-service/blob/12581d4616e26a5e823cc1025401fe3b74a0cea0/src/main/java/au/org/ala/biocache/dto/AssertionCodes.java#L42) will change the assertion / error codes. Is this going to be an issue for end users?

This change is affecting the Data Quality filters in `biocache-hub` (see: #426). The Data Quality Checks spreadsheet has been updated to reflect current values in release v3.0.12.
