### ISSUE TITLE
Record density map option has broken legend image

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/la-pipelines#366]
https://biocache-test.ala.org.au/occurrences/search?q=%28lsid%3Aurn%3Alsid%3Abiodiversity.org.au%3Aafd.taxon%3A435d01a5-7a68-4a24-b220-a7c32ea66b33+OR+lsid%3Ahttps%3A%2F%2Fid.biodiversity.org.au%2Ftaxon%2Fapni%2F51311124%29+AND+basis_of_record%3APRESERVED_SPECIMEN+AND+occurrence_date%3A%5B2000-01-01T00%3A00%3A00Z+TO+2010-01-01T00%3A00%3A00Z%5D&qualityProfile=ALA&disableAllQualityFilters=true#tab_mapView

![image](https://user-images.githubusercontent.com/532845/119304419-8f535f00-bcaa-11eb-937e-c9f4e10f96d3.png)

https://biocache-test.ala.org.au/ws/density/legend?q=(lsid%3Aurn%3Alsid%3Abiodiversity.org.au%3Aafd.taxon%3A435d01a5-7a68-4a24-b220-a7c32ea66b33%20OR%20lsid%3Ahttps%3A%2F%2Fid.biodiversity.org.au%2Ftaxon%2Fapni%2F51311124)%20AND%20basis_of_record%3APRESERVED_SPECIMEN%20AND%20occurrence_date%3A%5B2000-01-01T00%3A00%3A00Z%20TO%202010-01-01T00%3A00%3A00Z%5D&disableAllQualityFilters=true&qualityProfile=ALA is the image URL in question, which returns `200` OK but contains zero bytes of data.

**Comment by djtfmartin** [comment]
Fixed now. This was a deployment issue.

Should be noted the legend is slow to generate but this is also the case on production.

**Comment by nickdos** [comment]
Tested ✅
