### ISSUE TITLE
Implement downloads with SOLR streaming web services

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/la-pipelines#367]
Now we have SOLR 8 with doc values we can make use of SOLR streaming for extracting large amounts of data from the index.
We predict this will have significant performance benefits (leading to a more stable SOLR cluster) for:

* Downloads of CSV from spatial portal and biocache UI
* Scatterplot
* MaxEnt
* Taxon Frequency
* AOO and EOO

The initial work for this has already been done on this [branch](https://github.com/AtlasOfLivingAustralia/biocache-service/tree/docvalues) but this needs to be brought up to date with the work on the `epic/pipelines/develop` branch.

This can be done for a v1.1 release of pipelines.

**Comment by peggynewman** [comment]
Slightly off topic, but while you're in the neighbourhood, I've had issues with downloads with SDS permissions. If I've downloaded a dataset with full res sensitive data, and given the DOI link to someone with the same SDS role, then they get a permission denied error. eg. this happened with an NT govt data supplier.

**Comment by javier-molina** [comment]
This rings the bell in principle this should work but probably it is probable a question for @nickdos , @Rita-C or @sbearcsiro about DOI Service permission implementation.

**Comment by adam-collins** [comment]
https://github.com/AtlasOfLivingAustralia/biocache-service/pull/634
