### ISSUE TITLE
Occurrence facet search on 'scientific name'  is changed from taxon_name to scientificName in biocache-ws-test

### ISSUE THREAD

**Issue by qifeng-bai** [AtlasOfLivingAustralia/la-pipelines#368]
Spatial Hub Previously used facets=taxon_name, but now it is changed to scientificName

Here is an example:

https://biocache-ws.ala.org.au/ws/search/grouped/facets returns taxon_name for scientific name

https://biocache-ws-test.ala.org.au/ws/search/grouped/facets returns scientificName

**Comment by brucehyslop** [comment]
You can still used the facet=taxon_name

https://biocache-test.ala.org.au/ws/occurrence/facets?q=*:*&facets=taxon_name this will return the same data as https://biocache-test.ala.org.au/ws/occurrence/facets?q=*:*&facets=scientificName however the response object will reference the facet that was requested. 

This should maintain backwards compatibility. 

It is recommended that the facet names returned from https://biocache-test.ala.org.au/ws/search/grouped/facets should.

**Comment by javier-molina** [comment]
@qifeng-bai can you please confirm whether this is actually an issue?

**Comment by qifeng-bai** [comment]
It won't be an issue to Spatial.
