### ISSUE TITLE
View in Spatial Portal button on map tab fails

### ISSUE THREAD

**Issue by peggynewman** [AtlasOfLivingAustralia/la-pipelines#369]
From URL https://biocache-test.ala.org.au/occurrences/search?q=data_resource_uid%3Adr1902#tab_mapView

Clicking on the "View in Spatial Portal" button on the map tab :
- goes to link eg https://nectar-spatial-staging.ala.org.au/?q=data_resource_uid:dr1902&disableAllQualityFilters=true
- pop up appears saying: _Failed to register query. Try again later._

**Comment by djtfmartin** [comment]
I think this is now fixed. nectar-spatial-staging.ala.org.au was not pointing at biocache-test.ala.org.au. I updated the config and restarted.

**Comment by nickdos** [comment]
Looks fine to me - moving to done
