### ISSUE TITLE
Downloading occurrences by facet over Tas from Biocache-WS-TEST is taking > 5 mins, but previous took < 30 seconds  

### ISSUE THREAD

**Issue by qifeng-bai** [AtlasOfLivingAustralia/la-pipelines#370]
When Spatial tries to download occurrences over Tas on Biocache-ws-test

https://biocache-ws-test.ala.org.au/ws/occurrences/facets/download?facets=names_and_lsid&lookup=true&count=true&q=qid:1621832744249

Results returned is 24000 records, size ~5.4M, takes > 5 minutes.  However, it only took  ~30seconds last Friday (21 May)

@adam-collins mentioned:
 -  that’s likely due to lookup=true and the namematching changed

**Comment by javier-molina** [comment]
@charvolant

**Comment by adam-collins** [comment]
Biocache-service methods that loop instead of bulk/batch
- `NameMatchSpeciesLookupService.getNamesForGuids`
- `NameMatchSpeciesLookupService.getSpeciesDetails`

**Comment by charvolant** [comment]
@adam-collins To save me the trouble to finding these, could you give me links?

**Comment by javier-molina** [comment]
@adam-collins is going to address the changes required in biocache-service

**Comment by adam-collins** [comment]
https://github.com/AtlasOfLivingAustralia/biocache-service/pull/622

**Comment by djtfmartin** [comment]
This is all deployed. @qifeng-bai can you re-test ?

**Comment by qifeng-bai** [comment]
It works
