### ISSUE TITLE
coordinatePrecision value not appearing on record page

### ISSUE THREAD

**Issue by peggynewman** [AtlasOfLivingAustralia/la-pipelines#371]
Record in prod:
https://biocache.ala.org.au/occurrences/03068f05-d4ff-41b7-aef2-cec84bee75f5
Record in pipelines:
https://biocache-test.ala.org.au/occurrences/03068f05-d4ff-41b7-aef2-cec84bee75f5

coordinatePrecision value is provided in original record
coordinatePrecision flags are being evaluated
but the coordinatePrecision value doesn't appear on the page

Flags:
MISSING_COORDINATEPRECISION
COORDINATE_PRECISION_INVALID
COORDINATE_PRECISION_INVALID (appears twice)
Coordinate precision not valid

**Comment by javier-molina** [comment]
This seems to be a result of https://github.com/gbif/pipelines/issues/517 and it has been also raised in #309 

The rational is here https://github.com/AtlasOfLivingAustralia/la-pipelines/issues/285

**Comment by djtfmartin** [comment]
I think this is fixed in 3.0.6

**Comment by peggynewman** [comment]
This was also a problem for lat/long and verbatimLocality.
Tested and seems to be fixed this morning. Closing.
