### ISSUE TITLE
solr index failed

### ISSUE THREAD

**Issue by alexhuang091** [AtlasOfLivingAustralia/la-pipelines#373]
This issue can be reproduced on any record.

- **This is the solr doc before adding a user assertion**:
 
<img width="545" alt="截屏2021-05-26 上午11 13 29" src="https://user-images.githubusercontent.com/61677987/119590098-79af7800-be17-11eb-91f1-a9ce05e75ebf.png">

- **After an user assertion was added**

<img width="566" alt="截屏2021-05-26 上午11 14 13" src="https://user-images.githubusercontent.com/61677987/119590107-7caa6880-be17-11eb-8841-19d52422e92f.png">

- **Then when I verified the assertion, there's an solr error**
```
2021-05-26 11:16:19,945 ERROR: [ConcurrentUpdateSolrClient] - error
org.apache.solr.client.solrj.impl.HttpSolrClient$RemoteSolrException: Error from server at http://localhost:8983/solr/biocache: Bad Request

request: http://localhost:8983/solr/biocache/update?commit=true&softCommit=false&waitSearcher=false&wt=javabin&version=2
Remote error message: Async exception during distributed update: Error from server at http://aws-solr-2021-4.ala:8983/solr/biocache-2021-05-23-18-56_shard5_replica_n8/: null

request: http://aws-solr-2021-4.ala:8983/solr/biocache-2021-05-23-18-56_shard5_replica_n8/
Remote error message: ERROR: [doc=f350efb0-4147-4c2a-aee0-16259890f3c3] multiple values encountered for non multiValued field biome: [TERRESTRIAL, TERRESTRIAL]
```

The error says **multiple values encountered for non multiValued field biome: [TERRESTRIAL, TERRESTRIAL]**, so the root cause is **biome became multi-valued after first reindex**.

When I do solr update, I do partial update, actually only those userassertion related fields will be added/updated. From solr documentation https://solr.apache.org/guide/8_1/updating-parts-of-documents.html

> The core functionality of atomically updating a document requires that all fields in your schema must be configured as stored (stored="true") or docValues (docValues="true") except for fields which are `<copyField/>` destinations, which must be configured as stored="false". Atomic updates are applied to the document represented by the existing stored field values. All data in copyField destinations fields must originate from ONLY copyField sources.
> 
> If <copyField/> destinations are configured as stored, then Solr will attempt to index both the current value of the field as well as an additional copy from any source fields. If such fields contain some information that comes from the indexing program and some information that comes from copyField, then the information which originally came from the indexing program will be lost when an atomic update is made

**except for fields which are `<copyField/> `destinations, which must be configured as stored="false"**

But our definition is like
`<copyField source="biome"            dest="speciesHabitats"/>`
`<field name="speciesHabitats"         type="string" docValues="true" indexed="true" />`

Also see from the screen capture that after the update, `speciesHabitats` field disappeared

Could @djtfmartin change the schema definition to see if the issue can be fixed?

**Comment by javier-molina** [comment]
@alexhuang091 could you please  check this again ?

speciesHabitats is no longer supported and we discussed on Wednesday it should be removed completely instead of being copied from biome.

If you still have issues please Slack @djtfmartin

**Comment by alexhuang091** [comment]
Hi @djtfmartin , 

The **latest biocache-service** needs to be deployed (so my fix in 12581d4616e26a5e823cc1025401fe3b74a0cea0 deployed) so index to solr can succeed and the I can test if this issue is fixed

**Comment by javier-molina** [comment]
And the commit is here https://github.com/AtlasOfLivingAustralia/biocache-service/commit/12581d4616e26a5e823cc1025401fe3b74a0cea0

**Comment by alexhuang091** [comment]
By the way @djtfmartin, as solr documentation says, **all `<copyField/> `destinations must be configured as stored="false"**  I think we'd better do the change and regenerate index?

**Comment by djtfmartin** [comment]
@alexhuang091 can you include a link to the SOLR doc you are referring to ?

**Comment by alexhuang091** [comment]
Hi Dave, 
from the log it's Remote error message: ERROR: [doc=**f350efb0-4147-4c2a-aee0-16259890f3c3**] multiple values encountered for non multiValued field biome: [TERRESTRIAL, TERRESTRIAL]

**Comment by djtfmartin** [comment]
The latest generated index doesnt have a `speciesHabitats` copy field, so I assume that'll fix it. Is that the case @alexhuang091  ?

**Comment by alexhuang091** [comment]
Hi Dave, no, **the update request failed**. See the error log I sent you on Slack. Seems it's a solr bug. You may need to configure something.

**Comment by alexhuang091** [comment]
We have this error

```
2021-05-31 21:09:39,261 [http-nio-127.0.0.1-8080-exec-4] ERROR au.org.ala.biocache.dao.SolrIndexDAOImpl  (SolrIndexDAOImpl.java:1046) - Failed to update solr doc, error message: Error from server at http://aws-solr-2021-1.ala:8983/solr/biocache-2021-05-30-19-28_shard2_replica_n2: TransactionLog doesn't know how to serialize class org.apache.lucene.document.LazyDocument$LazyField; try implementing ObjectResolver?
org.apache.solr.client.solrj.impl.CloudSolrClient$RouteException: Error from server at http://aws-solr-2021-1.ala:8983/solr/biocache-2021-05-30-19-28_shard2_replica_n2: TransactionLog doesn't know how to serialize class org.apache.lucene.document.LazyDocument$LazyField; try implementing ObjectResolver?
```

`TransactionLog doesn't know how to serialize class org.apache.lucene.document.LazyDocument$LazyField; try implementing ObjectResolver?`

Seems it's a bug in solr 8.8 https://stackoverflow.com/questions/66335803/solr-throws-error-on-partial-update-after-upgrade-to-8-8

**Comment by alexhuang091** [comment]
Hi Dave, let me know once it's ready to be tested again.

**Comment by djtfmartin** [comment]
Reindexing now with config changes.

**Comment by alexhuang091** [comment]
Hi @djtfmartin 
It's still true at least on `aws-solr-2021-1.ala` and `aws-solr-2021-2.ala`

<img width="427" alt="截屏2021-06-01 下午3 02 24" src="https://user-images.githubusercontent.com/61677987/120269056-62c2c700-c2ea-11eb-91c7-d175f636c9f3.png">

**Comment by alexhuang091** [comment]
This issue is fixed:
1. user can add multiple assertions, verify assertions. There's no exception.
2. there are no more multiple values in `biome` when assertion/verifications are added

This issue is good to be closed.
