### ISSUE TITLE
display of deprecated assertion/codes endpoint

### ISSUE THREAD

**Issue by brucehyslop** [AtlasOfLivingAustralia/la-pipelines#374]
add a `deprecated` param to the assertion/codes endpoint to include the list of deprecated assertion with the new assertion name

**Comment by brucehyslop** [comment]
When the param `deprecated=true` is used with the `assertions/codes` endpoint extra deprecated assertions are returned with the properties `deprecated` & `newName`

**Comment by adam-collins** [comment]
https://biocache-test.ala.org.au/ws/assertions/user/codes?deprecated=true contains no deprecated entries. This is expected.

https://biocache-test.ala.org.au/ws/assertions/codes?deprecated=true contains deprecated entries with name, newName and deprecated=true. At a glance it appears it is displaying pipelines-field-config.json:fieldValueMapping.assertions as these deprecated entries as expected.

**Comment by javier-molina** [comment]
Closing as per testing above.
