### ISSUE TITLE
Automated functional tests findings

### ISSUE THREAD

**Issue by alexhuang091** [AtlasOfLivingAustralia/la-pipelines#375]
https://biocache-2020.ala.org.au/ws/occurrences/search?q=lsid%3Aurn%3Alsid%3Abiodiversity.org.au%3Aafd.taxon%3Ab1d9bf29-648f-47e6-8544-2c2fbdf632b1&facets=genus

and 

https://biocache-test.ala.org.au/ws/occurrences/search?q=lsid%3Aurn%3Alsid%3Abiodiversity.org.au%3Aafd.taxon%3Ab1d9bf29-648f-47e6-8544-2c2fbdf632b1&facets=genus

have different query title returned.

<span class='lsid' id='urn:lsid:biodiversity.org.au:afd.taxon:b1d9bf29-648f-47e6-8544-2c2fbdf632b1'>**GENUS: Macropus**</span>
vs 
<span class='lsid' id='urn:lsid:biodiversity.org.au:afd.taxon:b1d9bf29-648f-47e6-8544-2c2fbdf632b1'>**genus: Macropus**</span>

**Comment by alexhuang091** [comment]
2nd issue:

https://biocache-2020.ala.org.au/ws/occurrences/search?q=text%3AMacropus&start=0&pageSize=20&sort=first_loaded_date&dir=desc&qc=&facets=taxon_name&facets=genus&facets=kingdom

https://biocache-test.ala.org.au/ws/occurrences/search?q=text%3AMacropus&start=0&pageSize=20&sort=first_loaded_date&dir=desc&qc=&facets=taxon_name&facets=genus&facets=kingdom

"totalRecords": **179705** vs "totalRecords": **305445**

**Comment by alexhuang091** [comment]
3rd issue:

https://biocache-test.ala.org.au/ws/occurrences/794e1d5b-fc14-4b77-a21a-8e73749dc910 not exists

**Comment by alexhuang091** [comment]
4th issue.

https://biocache-test.ala.org.au/ws/density/map?q=Macropus+rufus reutrns a png of size **64926** but old API returns **69274**

Test code checks the size although I don't know if it's reasonable

```
        and: "It is at least 66KB in size"
        response.data.buf.length >= 66000
        println("and it is at least 66KB in size")
```

**Comment by djtfmartin** [comment]
@alexhuang091  - doesnt seem very reasonable to me :)

**Comment by javier-molina** [comment]
@alexhuang091 

> https://biocache-2020.ala.org.au/ws/occurrences/search?q=lsid%3Aurn%3Alsid%3Abiodiversity.org.au%3Aafd.taxon%3Ab1d9bf29-648f-47e6-8544-2c2fbdf632b1&facets=genus
> 
> and
> 
> https://biocache-test.ala.org.au/ws/occurrences/search?q=lsid%3Aurn%3Alsid%3Abiodiversity.org.au%3Aafd.taxon%3Ab1d9bf29-648f-47e6-8544-2c2fbdf632b1&facets=genus
> 
> have different query title returned.
> 
> **GENUS: Macropus**
> vs
> **genus: Macropus**

The test can be safely adjusted, not sure why the capitalisation was changed though.



> 2nd issue:
> 
> https://biocache-2020.ala.org.au/ws/occurrences/search?q=text%3AMacropus&start=0&pageSize=20&sort=first_loaded_date&dir=desc&qc=&facets=taxon_name&facets=genus&facets=kingdom
> 
> https://biocache-test.ala.org.au/ws/occurrences/search?q=text%3AMacropus&start=0&pageSize=20&sort=first_loaded_date&dir=desc&qc=&facets=taxon_name&facets=genus&facets=kingdom
> 
> "totalRecords": **179705** vs "totalRecords": **305445**

I would comment this for the time being, we have less records at the moment in test


> 4th issue.
> 
> https://biocache-test.ala.org.au/ws/density/map?q=Macropus+rufus reutrns a png of size **64926** but old API returns **69274**
> 
> Test code checks the size although I don't know if it's reasonable
> 
> ```
>         and: "It is at least 66KB in size"
>         response.data.buf.length >= 66000
>         println("and it is at least 66KB in size")
> ```

I'm pretty sure this is the result again of having less records, even testing for 60K should be a good test while we implement a more decent test for it.

That should  make everything work again.

**Comment by alexhuang091** [comment]
5th
https://biocache-test.ala.org.au/ws/occurrences/search?q=text:Macropus&start=0&pageSize=20&sort=first_loaded_date&dir=desc&qc=&facets=taxon_name&facets=genus&facets=kingdom

and 

https://biocache-2020.ala.org.au/ws/occurrences/search?q=text:Macropus&start=0&pageSize=20&sort=first_loaded_date&dir=desc&qc=&facets=taxon_name&facets=genus&facets=kingdom

have different facetsresult

<img width="394" alt="截屏2021-06-07 下午12 03 21" src="https://user-images.githubusercontent.com/61677987/120949716-78236f80-c788-11eb-8bc7-370f4a2401f6.png">
<img width="449" alt="截屏2021-06-07 下午12 03 28" src="https://user-images.githubusercontent.com/61677987/120949728-7eb1e700-c788-11eb-8d47-f97fc8a9f94f.png">

**Comment by alexhuang091** [comment]
6th

https://biocache-test.ala.org.au/ws/occurrences/search?q=raw_name%3A%22Osphranter%20rufus%22&start=0&pageSize=20&sort=first_loaded_date&dir=desc&qc=&facets=taxon_name returns 0

https://biocache-2020.ala.org.au/ws/occurrences/search?q=raw_name%3A%22Osphranter%20rufus%22&start=0&pageSize=20&sort=first_loaded_date&dir=desc&qc=&facets=taxon_name  returns 59505 records

**Comment by alexhuang091** [comment]
also happened on this pair:
https://biocache-test.ala.org.au/ws/occurrences/search?q=raw_name%3A%22Acacia%20dealbata%22&start=0&pageSize=50&sort=first_loaded_date&dir=desc&qc=&facets=taxon_name returns 0

https://biocache-test.ala.org.au/ws/occurrences/search?q=raw_name%3A%22Acacia%20dealbata%22&start=0&pageSize=50&sort=first_loaded_date&dir=desc&qc=&facets=taxon_name returns 29727

**Comment by javier-molina** [comment]
@alexhuang091 we only need an extract from jenkins log to close this, correct?

**Comment by alexhuang091** [comment]
> @alexhuang091 we only need an extract from jenkins log to close this, correct?

That's correct

**Comment by Rita-C** [comment]
Jenkins job failed on 15 June.
```
au.org.ala.biocache.service.OcurrenceSearchSpec > Text seach Macropus should show all records of genus Macropus and a scattering of other species with the name macropus in them scattered across the kingdoms. There should be Plantae and Fungi amongst them FAILED
    org.spockframework.runtime.SpockComparisonFailure at OcurrenceSearchSpec.groovy:158

au.org.ala.biocache.service.OcurrenceSearchSpec > Search for the Australian Museum Entomology Collection should mostly show class Insecta, kingdom Animalia etc. There will be some errors as stuff like Genus nov. gets mismatched and some molluscs and other oddities. FAILED
    org.spockframework.runtime.SpockComparisonFailure at OcurrenceSearchSpec.groovy:305

au.org.ala.biocache.service.AssortedServicesSpec > Get an specific occurrence 794e1d5b-fc14-4b77-a21a-8e73749dc910 FAILED
    org.spockframework.runtime.ConditionNotSatisfiedError at AssortedServicesSpec.groovy:73

au.org.ala.biocache.service.AssortedServicesSpec > Shape File Download for genus Macropus agilis FAILED
    org.spockframework.runtime.ConditionNotSatisfiedError at AssortedServicesSpec.groovy:239

au.org.ala.biocache.service.AssortedServicesSpec > Disable Record Issues in download FAILED
    groovyx.net.http.HttpResponseException at AssortedServicesSpec.groovy:260

au.org.ala.biocache.service.AssortedServicesSpec > Download E.gunnii lats and longs FAILED
    groovyx.net.http.HttpResponseException at AssortedServicesSpec.groovy:294

17 tests completed, 6 failed
```

**Comment by nickdos** [comment]
Should this moved back into backlog, as Jenkins is still showing failed test?

**Comment by alexhuang091** [comment]
> @javier-molina should this moved back into backlog, as Jenkins is still showing failed test?

I just updated it and the last run at 3:38PM was successful.
