### ISSUE TITLE
Unable to push images from Profile Hub

### ISSUE THREAD

**Issue by javier-molina** [AtlasOfLivingAustralia/la-pipelines#381]
Pushing image to biocache is a feautre supported by profiles. API that supports it does not seem to be working.

"1. https://nectar-profiles-dev.ala.org.au/opus/c1f7df1f-921d-48af-a96c-4c6ef54ce404/profile/Acacia%20ashbyae/update
2. Push the private image fails

Another example with API
https://biocache-test.ala.org.au/ws/occurrence/dr15750?apiKey=4483c458-1716-4a73-809a-781be82e5714
Method - POST
Body -  
```
{
    ""multimedia"": [
        {
            ""creator"": [
                """"
            ],
            ""rights"": [
                """"
            ],
            ""rightsHolder"": [
                ""Kamilaroi Plant and Animal Encyclopaedia""
            ],
            ""license"": [
                ""Creative Commons - license at record level""
            ],
            ""title"": [
                ""bushfire""
            ],
            ""description"": [
                """"
            ],
            ""created"": [
                """"
            ],
            ""originalFilename"": [
                ""DSC_6606.jpeg""
            ],
            ""contentType"": [
                null
            ],
            ""identifier"": ""https://images.ala.org.au/image/proxyImageThumbnail?imageId=244cac6a-b76e-4ea5-80bd-99837518d4e0""
        }
    ],
    ""scientificName"": ""Osphranter rufus""
}

```

Response -
405 - Method not allowed."

This might be an existing bug. I could not test it in prod since I might not be able to delete test data/image.

Reported by @temi

**Comment by javier-molina** [comment]
@brucehyslop, @adam-collins when you have a chance any of you could do some analysis on this?

**Comment by javier-molina** [comment]
From Temi:

> BTW, I did some further testing with biocache-2020. It is giving me an internal server error. This suggests it was working in the past.

**Comment by adam-collins** [comment]
biocache-service no longer supports the upload of occurrence records. 

I wonder if this can be done in images independent of an occurrence record?

**Comment by adam-collins** [comment]
Is there are data resource in production where this function was used?

**Comment by adam-collins** [comment]
ALA's record a sighting page, how does this one work? 
https://biocollect.ala.org.au/bioActivity/create/e61eb018-02a9-4e3b-a4b3-9d6be33d9cbb?returnTo=%2Fsightings%2FbioActivity%2FprojectRecords%2Ff813c99c-1a1d-4096-8eeb-cbc40e321101&hub=sightings

**Comment by peggynewman** [comment]
@temi Profiles shouldn't be creating occurrence records at all. I suggest that you use the image service to upload images for the Profiles app to use - it has adequate image metadata incl scientificName.
We should close this.

**Comment by temi** [comment]
@adam-collins @peggynewman , was the API removed from biocache-service since data handling architecture changed?
This feature is in profiles since the beginning. But not used as far as I can see. We will hide it in the next release and see if anyone complains.

**Comment by adam-collins** [comment]
@temi biocache-service can no longer be used to create occurrence records. Hiding the feature seems like a good idea to me.

**Comment by javier-molina** [comment]
Covered by AtlasOfLivingAustralia/profile-hub#717
