### ISSUE TITLE
Galah image download function broken

### ISSUE THREAD

**Issue by javier-molina** [AtlasOfLivingAustralia/la-pipelines#382]
The column name change from images to imageIDs   will mess up the image downloading function for Galah.

This will require a new release of  Galah to use the new field unless this can be sorted at biocache-service or pipelines end.

cc @matildastevenson

**Comment by javier-molina** [comment]
cc: @djtfmartin, @brucehyslop for comments on best way forward, not sure if the deprecated flag would solve this.

**Comment by brucehyslop** [comment]
either `images` or `imageIDs` can be used when searching. Facet results should return the facet name that was originally used (eg. if a facet query uses `images` then `images` will be returned as the result. 

The occurrence object returns the same `images` property as previously.

Is there an example call to biocache-service that is resulting in an error or incompatible response?

**Comment by matildastevenson** [comment]
I'm using the `ws/occurrences/offline/download` endpoint and requesting `images` as one of the columns to return in the csv using the `fields` parameter. It successfully returns the field but the in the csv the column name is changed back to `imageIDs`

**Comment by djtfmartin** [comment]
thanks @matildastevenson  - which download format is this? Darwin core or the "legacy" format ? 
If you have the full request URL and params (minus your email) that would be great.

**Comment by djtfmartin** [comment]
@matildastevenson - Ignore that question. - i've remembered the service doesn't actually have a notion of "format" and its just a list of fields it deals with. So we should have enough information to reproduce.

**Comment by matildastevenson** [comment]
hi @djtfmartin , the url is `https://biocache-test.ala.org.au/ws/occurrences/offline/download?fields=decimalLatitude%2CdecimalLongitude%2CeventDate%2Ctaxon_name%2CtaxonConceptID%2Cid%2Cdata_resource%2Cimages%2Csounds%2Cvideos&qa=&emailNotify=false&reasonTypeId=10&dwcHeaders=true&sourceId=2004&fq=(lsid:urn:lsid:biodiversity.org.au:afd.taxon:83225d29-264f-4236-9dda-32f7d60fb3af)&fq=(year:%222012%22)&fq=(multimedia:%22Image%22%20OR%20multimedia:%22Sound%22%20OR%20multimedia:%22Video%22)`
It is using the darwin core format

**Comment by djtfmartin** [comment]
thanks @matildastevenson

**Comment by djtfmartin** [comment]
Fixed in 3.0.8 and deployed for testing

**Comment by matildastevenson** [comment]
Thanks @djtfmartin and @javier-molina , image downloads are now working as expected
