### ISSUE TITLE
Data resource in record view isn't linked to collectory metadata

### ISSUE THREAD

**Issue by peggynewman** [AtlasOfLivingAustralia/la-pipelines#386]
In the Data Resource field, records usually have a link out to the collectory page but this isn't working:

Compare:
https://biocache.ala.org.au/occurrences/48298c65-6304-44f4-9189-f58741dc401d
https://biocache-test.ala.org.au/occurrences/48298c65-6304-44f4-9189-f58741dc401d

Link should be to : https://collections.ala.org.au/public/show/dr15866

**Comment by adam-collins** [comment]
biocache-hub expects biocache-service's occurrences/{uuid} to include raw.attribution.dataResourceUid

**Comment by djtfmartin** [comment]
Fixed in 3.0.8 and deployed for testing

**Comment by nickdos** [comment]
Tested, all good ✅
