### ISSUE TITLE
Duplicate country codes

### ISSUE THREAD

**Issue by alexhuang091** [AtlasOfLivingAustralia/la-pipelines#388]
on record https://biocache-test.ala.org.au/occurrences/f11bab20-9b41-4ed9-8a82-ec2eb71b4674

You can see 2 `country` fields, the 2nd actually is country code. Don't know if both of them need to be shown

![1](https://user-images.githubusercontent.com/61677987/120247959-a6044200-c2b8-11eb-8f09-c4f14afacd78.jpg)

**Comment by adam-collins** [comment]
biocache-service message.properties naming should be Country Code.

**Comment by adam-collins** [comment]
https://github.com/AtlasOfLivingAustralia/biocache-service/pull/625

**Comment by djtfmartin** [comment]
Verified fixed. Required a hubs restart.

**Comment by javier-molina** [comment]
Works now!

**Comment by javier-molina** [comment]
@adam-collins I think this is the one that you mentioned about using the same approach as #409
