### ISSUE TITLE
AVH testing: display of collectors

### ISSUE THREAD

**Issue by nielsklazenga** [AtlasOfLivingAustralia/la-pipelines#389]
In the search results, collectors are enclosed by square brackets:

![image](https://user-images.githubusercontent.com/4694550/120252137-0306f480-c2c7-11eb-8f45-6a3c59230e48.png)

On the occurrence detail page, only the first collector is displayed:

![image](https://user-images.githubusercontent.com/4694550/120252182-23cf4a00-c2c7-11eb-9a37-607c74b33b01.png)

https://avh-test.ala.org.au/occurrences/d906d107-3c97-4271-8e89-c41f4bdb0f0f

**Comment by adam-collins** [comment]
https://github.com/AtlasOfLivingAustralia/biocache-service/pull/624

**Comment by djtfmartin** [comment]
Still looks like a bug. The display hasnt changed on biocache-test

**Comment by adam-collins** [comment]
Deployment issue. It is fixed now.

**Comment by Rita-C** [comment]
Tested on
https://biocache-test.ala.org.au/occurrences/d906d107-3c97-4271-8e89-c41f4bdb0f0f
https://avh-test.ala.org.au/occurrences/d906d107-3c97-4271-8e89-c41f4bdb0f0f
both displays collectors correctly.
