### ISSUE TITLE
AVH testing: wildcard search on collector not working

### ISSUE THREAD

**Issue by nielsklazenga** [AtlasOfLivingAustralia/la-pipelines#390]
Compare:

https://avh.ala.org.au/occurrences/search?q=collector_text%3AKlazenga

and 

https://avh-test.ala.org.au/occurrences/search?q=collector_text%3AKlazenga.

This is accessed in AVH through the 'Advanced search'.

**Comment by adam-collins** [comment]
If adding after discussion

schema additions
```
<!-- Free text search fields -->
<field name="recordedBy_text"  type="textgen" multiValued="true" indexed="true" stored="false" />

<copyField source="recordedBy_text" dest="recordedBy_text"/>
```

field mapping change for collector_text
```
"collector_text": "recordedBy_text",
```

**Comment by adam-collins** [comment]
Decided to use field type as a prefix. In this case `textgen_recordedBy`

**Comment by nielsklazenga** [comment]
Thanks @adam-collins , can we get one of those for identifiedBy as well?

**Comment by adam-collins** [comment]
Yes. I can confirm that is also in use. 
@brucehyslop 
`identified_by_text` -> `textgen_identifiedBy`

**Comment by adam-collins** [comment]
https://github.com/gbif/pipelines/pull/536

**Comment by djtfmartin** [comment]
Fix deployed and LGTM

**Comment by nielsklazenga** [comment]
@javier-molina , I have tested this. This issue can be closed.
