### ISSUE TITLE
Failed to parse eventDate

### ISSUE THREAD

**Issue by alexhuang091** [AtlasOfLivingAustralia/la-pipelines#393]
This record https://biocache-test.ala.org.au/occurrences/bc65c736-30ca-44b5-bf7c-ac5ed0db093d has an occurrence date of `Year: 2019, Month: 9, Day: 13` which seems strange.

![Screen Shot 2021-06-01 at 3 34 12 pm](https://user-images.githubusercontent.com/8326394/120271646-0e6e1600-c2ef-11eb-93c1-b756ddff3ac6.png)

This is the search if you want to run your own download https://biocache-test.ala.org.au/occurrences/search?q=catalogue_number%3A33354492&qualityProfile=ALA 

It seems the date parser for some reason won’t generate an event date even if it has all the components for it (it was an iso date)

**Comment by javier-molina** [comment]
@nickdos, @peggynewman , @djtfmartin can I have your opinion on this?

My take is that  the production behaviour should be preserved.

**Comment by djtfmartin** [comment]
I've done some work on this.

Pipelines interpreted dates and produces two formats 1) date 2) date time.
We were not indexing the latter properly.

Fixed on this branch: https://github.com/gbif/pipelines/tree/357_records_dropped

**Comment by djtfmartin** [comment]
This is now fixed on biocache-test.

**Comment by nickdos** [comment]
Confirmed now working as expected:

```
eventDate
--
13/9/19
```

in download file
