### ISSUE TITLE
SA - Department for Environment and Water 

### ISSUE THREAD

**Issue by javier-molina** [AtlasOfLivingAustralia/la-pipelines#395]
@peggynewman here are the findings from SA - Department for Environment and Water 

DRs:
https://biocache-test.ala.org.au/occurrences/search?q=%28data_resource_uid%3A%22dr366%22+OR+data_resource_uid%3A%22dr365%22%29&disableAllQualityFilters=true 
   

![Screen Shot 2021-06-01 at 9.47.26 pm.png](https://images.zenhubusercontent.com/56b920d76caf56c9d38c5513/c6cd57f7-8c46-44af-9a0c-72ab04256fef)

> Dataset level 
> Does the overall count of records look right to you? Roughly, the numbers differ by about 14000 (plants) and 5000 (animals) and I am not able to see which records are missing.
> On the “Images” tab, do images appear as expected for your dataset? No images – can’t test this
> Sensitive records - under the “Assertions” facet (on the left hand side), select any generalised records and check the Latitude, Longitude and Coordinates generalised  fields appear as expected. Coordinates as expected but dates have been generalised to year for sensitive species
> User Assertions – use the Customise Filters button, check “Has User Assertions”, and click Update. Check that the “Has User Assertions” facet appears as expected, and select a record to check that the assertion appears in the record. Remember to disable the Data Profile (filter) that Excludes records with unresolved user assertions. None of the records flagged with User assertions were included in the test data I viewed. Note comment above about the mismatched number of records.
> Duplicate check – again, use the Customise Filters button and check “Associated Record Type” and click Update. Click on a record to check its Associated status information. Can you see any problems? No
> Check the Map tab. Click "View in Spatial Portal”. Can you see any issues? Seemed ok
> Are you able to Download records successfully? Yes but day and month are not included in the downloads of sensitive records
> Single record 
> Click on a single record. You can compare a record in the new system with one in the old by changing the URL from biocache-test.ala.org.au to biocache.ala.org.au 
> Check: 
> Is the dataset metadata appearing correctly (for example, Collection, Institution, catalogue number, occurrence ID, collector, license)? Ok
> Do you see any issues with the date interpretation? No
> Check that the Taxonomy and Geospatial values appear as expected. Yes
> Click the “original vs processed” button to see the raw values provided against the values interpreted by the ALA.  Ok
> If you have a particular workflow or feature that you use regularly it would be great if you could let us know if you can see any issues with it. Of course, we’re interested as well if you didn’t find any issues or felt that there have been improvements. The response was quite quick in Edge.

**Comment by javier-molina** [comment]
And the DR are these: 

https://biocache-test.ala.org.au/occurrences/search?q=%28data_resource_uid%3A%22dr366%22+OR+data_resource_uid%3A%22dr365%22%29&disableAllQualityFilters=true

**Comment by peggynewman** [comment]
Record numbers don't look to be a problem from my perspective, so I'm not sure what she may have been looking at. I'll ask her.

dr | drname | prod_solr_count | cass_count | pipeline_count | diff
-- | --  | -- | -- | --
dr366 | SA Flora (BDBSA) | 1905464 |	1905985 | 1905985 | 521
dr365 | SA Fauna (BDBSA) | 1624827 | 1625276 | 1625276 | 449

**Comment by peggynewman** [comment]
sent an email back to Meg via the support queue. we can close this now.
