### ISSUE TITLE
South Australian Museum Australia provider for OZCAM

### ISSUE THREAD

**Issue by javier-molina** [AtlasOfLivingAustralia/la-pipelines#399]
_When I got to the end of this it occurred to me that I was possibly doing this wrong as the instructions are maybe telling me to email the following as separate individual emails to support@ala
If that's what you were looking for let me know and I'll chop up the following into separate emails.
Cheers
Keith_
 
I'm comparing things to the existing dataset found by removing the '-test' from the URL
https://biocache-test.ala.org.au/occurrences/search?q=data_resource_uid%3Adr346#tab_recordImages
so
https://biocache.ala.org.au/occurrences/search?q=data_resource_uid%3Adr346#tab_recordImages
 
Because I'm looking at the biocache in general the first thing I did was disable data profiles so the numbers aren't affected by that.
I'm using Firefox 89.0 on Windows 10
 
### Dataset level 

_Does the overall count of records look right to you?_ 
No, the number of records is different - there are slightly more records in the test biocache.
Total current: 527,145
Total test: 527,285

_On the “Images” tab, do images appear as expected for your dataset?_ 
No, there are either blank grey boxes or caption text where the grey image should be:
![image.png](https://images.zenhubusercontent.com/56b920d76caf56c9d38c5513/7630f6fb-1f2f-4320-b99c-c47fa5a57f64)
After a few minutes while I was checking something else the extra lines disappeared:
![image.png](https://images.zenhubusercontent.com/56b920d76caf56c9d38c5513/67155b38-a729-433d-bf4a-b4a05090f700)
 
_Sensitive records - under the “Assertions” facet (on the left hand side), select any generalised records and check the Latitude, Longitude and Coordinates generalised  fields appear as expected._ 
They do, I think. They state that the coordinates were supplied as the generalised value:
![image.png](https://images.zenhubusercontent.com/56b920d76caf56c9d38c5513/42517b43-1767-49ba-a92b-f6b0530fbe1a)

That might be confusing to users. It suggests that we or WA DEC generalised the data before sending it to the ALA. Possibly a clearer way to put it might be "Supplied value generalised to: "
User Assertions – use the Customise Filters button, check “Has User Assertions”, and click Update. Check that the “Has User Assertions” facet appears as expected, and select a record to check that the assertion appears in the record. Remember to disable the Data Profile (filter) that Excludes records with unresolved user assertions. 
No records are recorded as having assertions, whereas we have 89 unconfirmed assertions and 7 corrected ones in the current ala.

_Duplicate check – again, use the Customise Filters button and check “Associated Record Type” and click Update. Click on a record to check its Associated status information. Can you see any problems?_ 

There are two behaviours of note when looking at tissue records: It appears to be recording the tissue records as associated records when checking a voucher - when they're both held in this Museum. This isn't a duplicate but is desired behaviour.
This record:
https://biocache-test.ala.org.au/occurrences/f974a7cf-cc4b-45f2-86ff-b0a382da8388
Is of a tissue. In the associated records are listed a number of other tissues and the voucher from which those tissues were taken. Ideally if there are associated materialSample and preservedSpecimen records the preservedSpecimen would be designated as the representative record

_Check the Map tab. Click "View in Spatial Portal”. Can you see any issues?_ 
Nope, appears fine

_Are you able to Download records successfully?_ 
Yes
Single record 

Click on a single record. You can compare a record in the new system with one in the old by changing the URL from biocache-test.ala.org.au to biocache.ala.org.au 

Check: 

*  _Is the dataset metadata appearing correctly (for example, Collection, Institution, catalogue number, occurrence ID, collector, license)?_ 
Yes

* _Do you see any issues with the date interpretation?_ 
No, seems fine

*  _Check that the Taxonomy and Geospatial values appear as expected._ 
Coordinates are being truncated when they end in zeroes. That shouldn't happen. There was no datum supplied in our data (we know this is not ideal):
![image.png](https://images.zenhubusercontent.com/56b920d76caf56c9d38c5513/edc14ca6-30f3-46d9-88db-e9ff4d274a85)

* _Click the “original vs processed” button to see the raw values provided against the values interpreted by the ALA._  
A value we didn't send, the datum: "EPSG:4326" is being reported as original
Valid DarwinCore terms preservedSpecimen and materialSample are being parsed into invalid terms PRESERVED_SPECIMEN and MATERIAL_SAMPLE

*  _If you have a particular workflow or feature that you use regularly it would be great if you could let us know if you can see any issues with it. Of course, we’re interested as well if you didn’t find any issues or felt that there have been improvements._ 
Can't think of any.

**Comment by adam-collins** [comment]
### Summary of issues ### 
1. hubs image tab missing images https://biocache-test.ala.org.au/occurrences/search?q=data_resource_uid%3Adr346#tab_recordImages

2. Missing 'has user assertions', expected 89 unconfirmed (value 50005) and 7 corrected (value 50003) user assertion records.

3. Change duplicate representative record to select perservedSpecimen over materialSample occurrences. 

4. Consider feedback on duplicate detection:
```
There are two behaviours of note when looking at tissue records: It appears to be recording the tissue records as associated records when checking a voucher - when they're both held in this Museum. This isn't a duplicate but is desired behaviour.
https://biocache-test.ala.org.au/occurrences/f974a7cf-cc4b-45f2-86ff-b0a382da8388
Is of a tissue. In the associated records are listed a number of other tissues and the voucher from which those tissues were taken. Ideally if there are associated materialSample and preservedSpecimen records the preservedSpecimen would be designated as the representative record
```

5. Display of trailing zeros on coordinates will not change. Usage of coordinatePrecision is required. Today it appears that https://biocache-test.ala.org.au/occurrences/dfe3a48f-0e4b-4b63-9d13-dd1c94720d84 is mixing up raw and processed values in the Geospatial section with the display of raw_decimalLongitude instead of decimalLongitude and 'supplied as raw_decimalLongitude'.

6. `Supplied datum "EPSG:4326"` is incorrect. None was supplied. Appears to have changed since testing. Today it appears that https://biocache-test.ala.org.au/occurrences/dfe3a48f-0e4b-4b63-9d13-dd1c94720d84 is displaying geodeticDatum in the 'original' column in the 'Compare original vs processed values' dialog.

7. basisOfRecord is not altering the SOLR strings (upper case, underscores) to the expected camel case. e.g. MATERIAL_SAMPLE should map to materialSample.

**Comment by adam-collins** [comment]
1. images working on biocache-test.ala.org.au. Pull request later.

**Comment by javier-molina** [comment]
Not sure if 7. here, #409 and #401 could all be related. 

Adam mentioned this overlaps with #388

**Comment by adam-collins** [comment]
1 & 7 https://github.com/AtlasOfLivingAustralia/biocache-service/pull/630

**Comment by djtfmartin** [comment]
merged and deployed

**Comment by djtfmartin** [comment]
For 6., the fix was to add an explicit entry into SOLR schema for `raw_geodeticDatum`. Required a biocache service restart to take effect

<img width="886" alt="Screen Shot 2021-06-08 at 5 04 54 pm" src="https://user-images.githubusercontent.com/444897/121219535-b483c800-c87b-11eb-91e9-27797a15dd87.png">

**Comment by adam-collins** [comment]
Moved duplicates algorithm feedback to #436

**Comment by javier-molina** [comment]
1. Works
2. Still an issue
3. and 4. future work #436
5. decimal latitude still an issue??
6. Works
7. Still an issue

**Comment by javier-molina** [comment]
@alexhuang091 could you confirm whether these missing assertions are going to be covered by https://github.com/AtlasOfLivingAustralia/biocache-service/pull/642 or there is something else going on?

Compare https://biocache-test.ala.org.au/occurrences/search?q=data_resource_uid%3Adr346#tab_recordImages vs https://biocache.ala.org.au/occurrences/search?q=data_resource_uid%3Adr346#tab_recordImages

Prod has 98 user annotations test 0

**Comment by alexhuang091** [comment]
> @alexhuang091 could you confirm whether these missing assertions are going to be covered by [AtlasOfLivingAustralia/biocache-service#642](https://github.com/AtlasOfLivingAustralia/biocache-service/pull/642) or there is something else going on?
> 
> Compare https://biocache-test.ala.org.au/occurrences/search?q=data_resource_uid%3Adr346#tab_recordImages vs https://biocache.ala.org.au/occurrences/search?q=data_resource_uid%3Adr346#tab_recordImages
> 
> Prod has 98 user annotations test 0

Hi Javier, no, #642 affects `q=assertionUserId:xxx` but in this query it's `data_resource_uid`, they are not related.

I did a search in solr with `dataResourceUid:dr346` and there are records returned. Maybe @brucehyslop forgot to convert `data_resource_id` to `dataResourceId` being sending request to solr?

<img width="742" alt="截屏2021-06-22 下午2 24 11" src="https://user-images.githubusercontent.com/61677987/122863175-afd40f00-d365-11eb-8126-0c39a5cbb4cb.png">

**Comment by javier-molina** [comment]
@alexhuang091 sorry I was not clear, have a look to the updated comment above including screenshots.

**Comment by alexhuang091** [comment]
> @alexhuang091 sorry I was not clear, have a look to the updated comment above including screenshots.

Hi Javier, thanks for you screenshot.

- On prod, if you disable data-quality, you can see `98` unconfirmed issue. Enable data-quality, you can see `0`. that means `98` filtered out
<img width="314" alt="截屏2021-06-22 下午3 09 42" src="https://user-images.githubusercontent.com/61677987/122866790-e7de5080-d36b-11eb-840f-c964503f831c.png">

- On test, if you disable data-quality, you see `122` unconfirmed issue. Enable data-quality, you see `0`
<img width="306" alt="截屏2021-06-22 下午3 13 41" src="https://user-images.githubusercontent.com/61677987/122867192-7652d200-d36c-11eb-84eb-61aa2f6a8d01.png">
. that means they are fitered out. But why `0 records excluded` maybe it's an cache issue

**Comment by alexhuang091** [comment]
Hi @javier-molina , the exclude count is back correct now.

The exclude count in biocache-hubs is cached for 1 day. I temporarily set it to 1 minute on the test server so it can quickly get refreshed.

**Comment by adam-collins** [comment]
5 is `won't fix`. There was a discussion earlier in the year about this.
7 is fixed, however the `compare "original vs processed" values` intentionally does not format any values. 
![Screen Shot 2021-06-28 at 9 37 05 am](https://user-images.githubusercontent.com/8031500/123562824-73d0fc00-d7f4-11eb-9ab2-07650445765d.png)
![Screen Shot 2021-06-28 at 9 36 42 am](https://user-images.githubusercontent.com/8031500/123562825-75022900-d7f4-11eb-8dc2-3591e5b4eb8a.png)
![Screen Shot 2021-06-28 at 9 36 25 am](https://user-images.githubusercontent.com/8031500/123562827-759abf80-d7f4-11eb-95fa-2e9edff62bb1.png)
![Screen Shot 2021-06-28 at 9 35 53 am](https://user-images.githubusercontent.com/8031500/123562830-76335600-d7f4-11eb-9700-2392440e5a89.png)

**Comment by javier-molina** [comment]
Thanks @adam-collins
