### ISSUE TITLE
Sandbox integration

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/la-pipelines#4]
Need to ensure sandbox is functional with a pipelines backend.

**Comment by javier-molina** [comment]
These are some notes after having a chat with @peggynewman. Please confirm if I made any misrepresentation.

In short Sandbox still has a place in ALA system ecosystem, yet to be determined if it actually needs to be integrated with the LA pipelines.

Long version:
Peggy will think what is the long term need for sandbox and its touch points with Spatial Portal, Philolink and what are the actual needs/drivers or not to integrate it with LA pipelines

Sandbox will be retained for two purposes:

- Provide mapping of fields
- Provide a test environment

**Comment by javier-molina** [comment]
As per https://confluence.csiro.au/display/CIU/2020-12-17+Reference+Group this is out of scope for stage 1
