### ISSUE TITLE
Micro-service for license mapping, etc.

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/la-pipelines#40]
One of the processing jobs is to map a license string (from a record or data resource) to a known license type.  The image-service application also performs this task and thus there is duplication of code and rules for this. It makes sense to have a single service to perform this task that is used by multiple applications (pipelines, biocache-service(?), BioCollect, image-service, etc.). 

License types should probably be stored in a vocabulary service and then this micro-service can add the lookup function to map known strings to the proper license types.

**Comment by djtfmartin** [comment]
Good idea, a microservice makes sense. Currently this is handled in pipelines using a dictionary (similar to biocache-store).

https://github.com/gbif/parsers/blob/master/src/main/resources/dictionaries/parse/license.tsv

As GBIF plan to move these dictionaries into a vocab service, the micro service maybe come from here.

**Comment by javier-molina** [comment]
Out of scope for stage 1
