### ISSUE TITLE
query assertions:missingGeodeticDatum doesn't work

### ISSUE THREAD

**Issue by alexhuang091** [AtlasOfLivingAustralia/la-pipelines#401]
https://biocache-test.ala.org.au/ws/occurrences/search?q=assertions:missingGeodeticDatum&fq=id:0fbb3d99-000c-4906-99ed-871dba631383

https://biocache-test.ala.org.au/ws/occurrences/search?q=!assertions:missingGeodeticDatum&fq=id:0fbb3d99-000c-4906-99ed-871dba631383

These 2 queries return the same record. But their conditions(`q`) are contrary. One **requires** `missingGeodeticDatum` in `assertions`, the other **requires NO** `missingGeodeticDatum` in `assertions`

But if replace `missingGeodeticDatum` with `MISSING_GEODETICDATUM` then 2 queries work. Means `missingGeodeticDatum` in the url is not mapped to `MISSING_GEODETICDATUM`?

**Comment by djtfmartin** [comment]
I'm not sure this is an issue. The `!` doesn't seem to work in production.

See https://biocache.ala.org.au/occurrences/search?q=!genus:Macropus

The `-` operator works as expected:

https://biocache-test.ala.org.au/ws/occurrences/search?q=-assertions:missingGeodeticDatum&fq=id:0fbb3d99-000c-4906-99ed-871dba631383

returns 0 records.

**Comment by alexhuang091** [comment]
Hi Dave, nor do I know if ` ! `is a correct syntax. Just there's an existing query in alerts uses it.

by the way q=asserrtion: MISSING_GEODETICDATUM returns records with MISSING_GEODETICDATUM in assertions.
q=!assertions: MISSING_GEODETICDATUM returns records without MISSING_GEODETICDATUM in assertion.

I'll check the usage of `!` on Monday.

**Comment by djtfmartin** [comment]
Thanks @alexhuang091

**Comment by alexhuang091** [comment]
Hi @djtfmartin 

1. I have 1,000 records in local solr
2.I inserted "assertions":{"set":"`missingGeodeticDatum`"} to 2 docs

http://localhost:8983/solr/biocache/select?q=assertions:missingGeodeticDatum returns 2
http://localhost:8983/solr/biocache/select?q=!assertions:missingGeodeticDatum returns 998

according to solr https://solr.apache.org/guide/8_5/the-standard-query-parser.html#the-standard-query-parser

> The Boolean Operator NOT ("!")
> The NOT operator excludes documents that contain the term after NOT. This is equivalent to a difference using sets. The symbol ! can be used in place of the word NOT

> The Boolean Operator "-"
> The - symbol or "prohibit" operator excludes documents that contain the term after the - symbol.

**Comment by alexhuang091** [comment]
the query actually sent to solr is 

`&q=!assertions:missingGeodeticDatum&fq=id:0fbb3d99\-000c\-4906\-99ed\-871dba631383`

but the values actually stored in solr is
```
"assertions":["RECORDED_DATE_INVALID",
          "GEODETIC_DATUM_ASSUMED_WGS84",
          "MISSING_GEODETICDATUM",
          "MISSING_GEOREFERENCE_DATE",
          "MISSING_GEOREFERENCEPROTOCOL",
          "MISSING_GEOREFERENCESOURCES"]}]
```

so we actually should query with q=!**assertions:MISSING_GEODETICDATUM** instead of assertions:missingGeodeticDatum

@brucehyslop is this related to fieldmapping?

**Comment by brucehyslop** [comment]
The issue is that the regex that processed the query `!assertions:missingGeodeticDatum` doesn't handle the `!` operator and wasn't being translated.

**Comment by alexhuang091** [comment]
Hi @djtfmartin @brucehyslop will biocache-service pipeline translate any old field name into new name before feed reuqest to solr? for example `fq=has_user_assertions:true` translated to `fq=hasUserAssertions:true` and `fq=assertions:missingGeodeticDatum` to `assertions: MISSING_GEODETICDATUM`?

Since I still see `missingGeodeticDatum` being sent to solr (I suppose it's an old field name and should be `MISSING_GEODETICDATUM` now?)

If no translation happens, I should stop using old field names and use new names in query.

**Comment by alexhuang091** [comment]
It works now on biocache-test (`missingGeodeticDatum` translated to `MISSING_GEODETICDATUM`).

I ran biocace service locally and still see `missingGeodeticDatum` being sent to solr, maybe some local config issue?

Anyway it works on test so it's fixed.
