### ISSUE TITLE
add termsRequiredToTest to the assertions/codes response

### ISSUE THREAD

**Issue by brucehyslop** [AtlasOfLivingAustralia/la-pipelines#402]
The `termsRequiredToTest` property is now inherited from the `OccurrenceIssue` and included with the occurrence systemAssertions JSON property. 

Add the `termsRequiredToTest` to the `assertions/codes` response to maintain consistency.

**Comment by adam-collins** [comment]
Tests ok.

https://biocache-test.ala.org.au/ws/assertions/codes returns with `termsRequiredToTest` as a list, empty and not empty.
https://biocache-test.ala.org.au/ws/assertions/codes?deprecated=true returns with `termsRequiredToTest` as a list, empty and not empty, for those not non-deprecated. Deprecated entries have no `termsRequiredToTest` value.
https://biocache-test.ala.org.au/ws/assertions/user/codes returns with `termsRequiredToTest` as only empty lists.
https://biocache-test.ala.org.au/ws/assertions/user/codes?deprecated=true returns an identical response as `deprecated=false`.
