### ISSUE TITLE
Month legend not loading for map

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/la-pipelines#404]
cc @adam-collins 

<img width="1653" alt="Screen Shot 2021-06-05 at 8 02 06 pm" src="https://user-images.githubusercontent.com/444897/120902567-012b9100-c639-11eb-83f3-9263a058d34b.png">

URL: https://biocache-test.ala.org.au/occurrence/legend?q=*%3A*&disableAllQualityFilters=true&qualityProfile=ALA&fq=taxon_name%3A%22Hirundo%20(Hirundo)%20neoxena%22&cm=month&type=application/json

**Comment by javier-molina** [comment]
Probably @brucehyslop can look into this if Adam is still addressing collections community feedback.

**Comment by brucehyslop** [comment]
The issue was due to null facet values for month which caused an error when mapping field values. An update has been deployed to biocache-service test

**Comment by djtfmartin** [comment]
Verified this fixed on test.
