### ISSUE TITLE
Museum Victoria provider for OZCAM

### ISSUE THREAD

**Issue by javier-molina** [AtlasOfLivingAustralia/la-pipelines#405]
Number of Records differ:
test site
hRps://biocache-test.ala.org.au/occurrences/search?
q=data_resource_uid%3Adr342&disableAllQualityFilters=true&fq=collec1on_uid%3A%22co39%
22#tab_recordsView
Live site - filters turned off
hRps://biocache.ala.org.au/occurrences/search?
q=data_resource_uid:dr342&disableQualityFilter=spa1allysuspect&
disableQualityFilter=scien1ficname&
disableQualityFilter=loca1on&disableQualityFilter=duplicates&disableQualityFilter=loca1
on-uncertainty&disableQualityFilter=userasser
1ons&disableQualityFilter=outliers&disableQualityFilter=recordtype&
disableQualityFilter=occurrence-status&disableQualityFilter=dates-post-
1700#tab_recordsView
Test site - filters turned off
hRps://biocache-test.ala.org.au/occurrences/search?
q=data_resource_uid%3Adr342&disableAllQualityFilters=true&fq=collec1on_uid%3A%22co39%
22&fq=family%3A%22Halic1dae%22#tab_recordsView
Search: Data resource: Museums Victoria provider for
OZCAM | Occurrence records | Atlas of Living Australia
Atlas of Living Australia
Page 2 of 11
Live Site - filters off
hRps://biocache.ala.org.au/occurrences/search?
q=data_resource_uid%3Adr342&qualityProfile=ALA&disableQualityFilter=spa1allysuspect&
disableQualityFilter=scien1ficname&
disableQualityFilter=loca1on&disableQualityFilter=duplicates&disableQualityFilter=loca1
on-uncertainty&disableQualityFilter=userasser
1ons&disableQualityFilter=outliers&disableQualityFilter=recordtype&
disableQualityFilter=occurrence-status&disableQualityFilter=dates-post-
1700&fq=family%3A%22Halic1dae%22#tab_recordsView
biocache-test.ala.org.au
Search: Data resource: Museums Victoria provider for
OZCAM | Occurrence records | Atlas of Living Australia
Atlas of Living Australia
biocache.ala.org.au
Page 3 of 11
hRps://biocache.ala.org.au/occurrences/search?
q=data_resource_uid%3Adr342&qualityProfile=ALA&disableQualityFilter=spa1allysuspect&
disableQualityFilter=scien1ficname&
disableQualityFilter=loca1on&disableQualityFilter=duplicates&disableQualityFilter=loca1
on-uncertainty&disableQualityFilter=userasser
1ons&disableQualityFilter=outliers&disableQualityFilter=recordtype&
disableQualityFilter=occurrence-status&disableQualityFilter=dates-post-
1700&fq=family%3A%22Halic1dae%22#tab_recordsView
Search: Data resource: Museums Victoria provider for
OZCAM | Occurrence records | Atlas of Living Australia
Atlas of Living Australia
biocache.ala.org.au
Page 4 of 11
Test site Halic1dae
Taxa not alphabe1cally sorted
Page 5 of 11
Live site alphabe1cally sorted
Page 6 of 11
Number of specimens match for checked taxa
Test site
Live site
Halic1dae test site map looks same as live site map
Test site map
Page 7 of 11
Live site Halic1dae map
Test site open record similar data but slightly different wording
hRps://biocache-test.ala.org.au/occurrences/9b325b94-09a4-4ed7-bb24-d5796bd18c3a
Page 8 of 11
Live site
hRps://biocache.ala.org.au/occurrences/9b325b94-09a4-4ed7-bb24-d5796bd18c3a
Map for species looks same:
Test site
hRps://biocache-test.ala.org.au/occurrences/search?
q=data_resource_uid%3Adr342&disableAllQualityFilters=true&fq=collec1on_uid%3A%22co39%
22&fq=family%3A%22Halic1dae%22&fq=taxon_name%3A%22Lasioglossum%20(Chilalictus)%20
alacarinatum%22#tab_mapView
Record: Entomology:T15341 | Occurrence record | Atlas of
Living Australia
Atlas of Living Australia
biocache.ala.org.au
Search: Data resource: Museums Victoria provider for
Page 9 of 11
Live site
hRps://biocache.ala.org.au/occurrences/search?
q=data_resource_uid%3Adr342&qualityProfile=ALA&disableQualityFilter=spa1allysuspect&
disableQualityFilter=scien1ficname&
disableQualityFilter=loca1on&disableQualityFilter=duplicates&disableQualityFilter=loca1
on-uncertainty&disableQualityFilter=userasser
1ons&disableQualityFilter=outliers&disableQualityFilter=recordtype&
disableQualityFilter=occurrence-status&disableQualityFilter=dates-post-
1700&fq=family%3A%22Halic1dae%22&fq=taxon_name%3A%22Lasioglossum%20(Chilalictus)%
20alacarinatum%22#tab_mapView
OZCAM | Occurrence records | Atlas of Living Australia
Atlas of Living Australia
biocache-test.ala.org.au
Page 10 of 11
Just no1ced something on the live site when filters are turned on.
For Museums Victoria records for the bee family Halic1dae 11,465 are excluded as duplicates;
however, when that is applied there are only 4 images shown.
hRps://biocache.ala.org.au/occurrences/search?
q=lsid%3Aurn%3Alsid%3Abiodiversity.org.au%3Aafd.taxon%3Ad658068e-c8h-44c5-b0fcbb8baa0ff20b&
qualityProfile=ALA&fq=ins1tu1on_name%3A%22Museums%20Victoria%22#tab_
recordImages
When the duplicates filter is turned off many more images are shown. It appears the duplicates
but with images are excluded.
hRps://biocache.ala.org.au/occurrences/search?
q=lsid%3Aurn%3Alsid%3Abiodiversity.org.au%3Aafd.taxon%3Ad658068e-c8h-44c5-b0fcbb8baa0ff20b&
qualityProfile=ALA&fq=ins1tu1on_name%3A%22Museums%20Victoria%22&disa
bleQualityFilter=duplicates#tab_recordImages
Search: FAMILY: HALICTIDAE | Occurrence records | Atlas of
Living Australia
Atlas of Living Australia
biocache.ala.org.au
Page 11 of 11
Nice job.
Hope this helps.

**Comment by javier-molina** [comment]
@sadeghim, @adam-collins  as per email conversation.

**Comment by adam-collins** [comment]
@javier-molina is there a better formatted copy of this feedback?

**Comment by javier-molina** [comment]
@adam-collins 

I sent you that as an attachment by e-mail

**Comment by adam-collins** [comment]
### Summary
1. A few hundred fewer records on test. More investigation required.
2. UI feedback that the hub 'choose selection' dialog does not make it clear that the facets can be sorted by count or alphabetically.
3. Appears to be a coincidence that test shows more images when data quality filters are enabled.

**Comment by adam-collins** [comment]
Moved biocache-hubs feedback to https://github.com/AtlasOfLivingAustralia/biocache-hubs/issues/455

**Comment by javier-molina** [comment]
1. 420,912 records in test vs 420,778 in prod.
2.  Not an issue
3. No apparent issue  displaying images with or without DQ filters.
Good to go
