### ISSUE TITLE
OBIS Testing

### ISSUE THREAD

**Issue by javier-molina** [AtlasOfLivingAustralia/la-pipelines#406]
Here are some of my observations
 
I could add the data filters on the left are never used by me as they don't help me find data on a day or season etc.
 
Does not work if finding specific genus for example if the dataset contains 1000 species

[Beta testing new ALA portal_OBIS.docx](https://github.com/AtlasOfLivingAustralia/la-pipelines/files/6613786/Beta.testing.new.ALA.portal_OBIS.docx) 

Dataset is this:
https://biocache-test.ala.org.au/occurrences/search?q=data_provider_uid:dp5183

**Comment by adam-collins** [comment]
If I understand correctly this is an existing usability issue.
- open link https://biocache-test.ala.org.au/occurrences/search?q=data_provider_uid:dp5183
- click 'customize filters', select 'genus', click 'update'
- on the left expand the 'taxon' section
- click 'choose more...' for the 'genus'
- scroll down and notice that for every 100 genus values the next 100 are fetched. In alphabetical order.
- given there are >5000 genus for this data provider this means scrolling to the end, waiting for the next 100 genus to load, then repeating for a total of 50+ times.

The left hand side is not usable for finding a facet where there are many. There is a facet service available in biocache-service that does a 'begins with' filter on facets, and paging. 

Regardless of my interpretation of the feedback I would suggest adding a usability enhancement issue in biocache-hubs for search term filtering functionality in the 'choose more..' facet box.

**Comment by javier-molina** [comment]
Thanks @adam-collins, I think your suggestion for enhancement is sensible.

**Comment by javier-molina** [comment]
@adam-collins I completely miss the attached document below with further findings from OBIS

Could you check what we have there?

[Beta testing new ALA portal_OBIS.docx](https://github.com/AtlasOfLivingAustralia/la-pipelines/files/6613786/Beta.testing.new.ALA.portal_OBIS.docx)

**Comment by adam-collins** [comment]
### Summary
1. Feedback on duplicate detection, and a question on how it works.
2. Feedback on hubs search list when it shows taxon rank first.
```
Observation records have the taxonomic level displayed first – sometimes this doesn’t read well for the records that were not filtered out 
```
3. Question regarding data generalisation and `original` data shown.
4. Missing user assertions
5. Records download not sending an email
6. Species checklist download containing no records.
7. Field guide download containing no records.

**Comment by adam-collins** [comment]
6. Species checklist appears to be working. Note that it only returns species level taxon matches.

**Comment by adam-collins** [comment]
7. Field guide appears to be working. Note that it only returns species level taxon matches.

**Comment by adam-collins** [comment]
Moved biocache-hubs feedback to https://github.com/AtlasOfLivingAustralia/biocache-hubs/issues/455

**Comment by javier-molina** [comment]
Probably duplicate detection issue #436 needs to consider the input of this [DR](https://biocache.ala.org.au/occurrences/search?q=data_provider_uid:dp5183)

[Current production](https://biocache.ala.org.au/occurrence/search?q=data_provider_uid%3Adp5183&qualityProfile=ALA&disableAllQualityFilters=true&fq=duplicate_status%3A%22D%22) has 186,575 duplicate records while [test](https://biocache-test.ala.org.au/occurrences/search?q=data_provider_uid%3Adp5183&qualityProfile=ALA&disableAllQualityFilters=true&fq=duplicateStatus%3A%22ASSOCIATED%22)  contains 1,353,219.

**Comment by javier-molina** [comment]
1 to 3 not anymore a concern for this issue

**Comment by javier-molina** [comment]
@alexhuang091 could you confirm whether these missing assertions are going to be covered by https://github.com/AtlasOfLivingAustralia/biocache-service/pull/642 or there is something else going on?

Compare https://biocache-test.ala.org.au/occurrences/search?q=data_provider_uid:dp5183 vs https://biocache.ala.org.au/occurrences/search?q=data_provider_uid:dp5183#tab_recordImages

Prod has 4 user annotations test 0
