### ISSUE TITLE
Western Australian Herbarium  

### ISSUE THREAD

**Issue by javier-molina** [AtlasOfLivingAustralia/la-pipelines#407]
Sorry for the late responses - better late than never. I worked mostly with AVH. Using Chrome, Windows.

Found a few issues -
On the AVH test site - the image tab didn't show for me until I selected multimedia in the 'customize filters' - but I have not been able to replicate?? There are no images on the test site - even though the non-test site has images. Same experience with ALA.

In the 'customise filters' window - there are two "Associated record type" selections? (same with ALA)

Apparently PERTH dataset had no assertions in the test site (but occur on live site)

Would be helpful if when clicking on 'inferred associated record details' that it opens in a new tab automatically - so the original record can be referred to - the other UUIDs on the new page open to a new tab, so you can flip between the records and information delivered for each. [Looks like a helpful tool moving forward - especially if more fields can be added to help with verifying match or seeing how the data compares without clicking on each record]

With this query:
https://avh-test.ala.org.au/occurrences/search?q=collection_uid%3Aco75&fq=duplicate_status%3A%22ASSOCIATED%22&qc=data_hub_uid%3Adh9#tab_mapView
clicking on 'spatial portal' gave me 'no records' and the download was an empty zip file.
Happened with a second, different query.

https://avh-test.ala.org.au/occurrences/8e6bbeab-9032-47f9-bb9f-7c6620f3b496
Institution logo missing?
Looks like there is a change to Priority listing - I assume this is an effort to standardize this across states (hence Priority 2 now Threatened)?

https://avh-test.ala.org.au/occurrences/ef1ff900-b26d-44da-85b3-859d14501a03
?Habitat now "supplied as"? Is there some effort to standardize this??

It would also be really helpful when selecting "view record" that another tab opens (I know you can right click and open in new tab - but it is frustrating if you want to go back to the search but keep that record after clicking on 'view record')

**Comment by adam-collins** [comment]
### Issue Summary
1. spatial portal link not working. avh-test.ala.org.au is not redirecting to the spatial test site.
2. institution logo missing. avh-test.ala.org.au is using the image from collections-test.ala.org.au. No image there. collections.ala.org.au request for the same image does work.
3. habitat 'supplied as' does not make it clear that there is no processed habitat. Needs an 'unknown' value in the processed habitat, or the raw value. 
4. Some ui suggestions for comparing inferred duplicates.
5. I could only see one 'associated record type' in the customise filter today.
6. missing user assertions

**Comment by adam-collins** [comment]
1. Fixed on avh-test.
2. Added the image to collections-test
3. n/a
4. n/a
5. No longer OK on test. i18n in biocache-hubs has the same value for both instead of 
* `facet.duplicate_status` `Associated records` (ASSOCIATED, REPRESENTATIVE)
* `facet.duplicate_type` `Duplicate record type` (SAME_DATASET, DIFFERENT_DATASET) 
6. user assertions still missing

**Comment by adam-collins** [comment]
5. https://github.com/AtlasOfLivingAustralia/biocache-hubs/pull/452

**Comment by javier-molina** [comment]
@adam-collins I think this is the one that you mentioned about using the same approach as #409

**Comment by adam-collins** [comment]
biocache-hub UI enhancement move to biocache-hubs https://github.com/AtlasOfLivingAustralia/biocache-hubs/issues/454

**Comment by javier-molina** [comment]
@adam-collins what work is need it for 5. to include the i18n change in AVH? 

I think this is an existing issue but given that we have change #409 for AVH we can probably push this depending on priorities.

![Screen Shot 2021-06-30 at 2 09 38 pm](https://user-images.githubusercontent.com/8326394/123900770-09af8700-d9ad-11eb-9b11-7e18636eabec.png)

**Comment by adam-collins** [comment]
Need a biocache-hubs release followed by an avh-hub release with the updated biocache-hubs.

**Comment by nickdos** [comment]
https://avh-test.ala.org.au has been updated to latest snapshot version of biocache-hubs (3.0.6-SNAPSHOT).

**Comment by peggynewman** [comment]
Sent a response on the support queue. This can be closed now.
