### ISSUE TITLE
Australian National Herbarium  

### ISSUE THREAD

**Issue by javier-molina** [AtlasOfLivingAustralia/la-pipelines#408]
The main issue I can see is the way that the ‘asserted duplicates’ are working. In our case we deliver preservedSpecimens to AVH and livingSpecimens to ASBP and they are both linked to the original collection..
 
An example :
https://avh-test.ala.org.au/occurrences/48768d9b-19d2-4082-a87b-49bf1385a016 preserved (in AVH)
https://avh-test.ala.org.au/occurrences/00c5471a-4cbc-4121-ba8a-6560c580f779 living (in ASBP)
 
when I look at the ‘representative occurrence’ in AVH it brings up the livingSpecimen but doesn’t highlight I am no longer looking at PRESERVED SPECIMENs anymore.. I think this may get confusing..
 
In my mind the preservedSpecimen should take precedence over livingSpecimen but the assertion is working the other way, also within AVH there is no duplicate occurrence – does this affect analysis of downloads because there is no internal cross reference to another record? I haven’t had time to check. Also swapping the ‘representative occurrence’ will then start showing preservedSpecimens in the Seedbank portal which may be confusing in the opposite direction…
 
Basically I still see this as an inherent problem with the DwC Occurrence record and how it is overloaded with terms such as catalogNo etc which are essentially not about the ‘occurrence’ but how they are held in our collections. Lots of discussion about this in the latest proposed changes to DwC.
 
When I looked at the coordinates for a Critically endangered species (Acacia equisetifolia CANB 875031) which we have both preservedSpecimen  and livingSpecimen the coordinates are as I deliver them (-13.2836, 132.5428) but I am not sure what level of co-ordinate adjustment is made so this may be all OK.

Datasets are: Australian National Herbarium in AVH: https://avh-test.ala.org.au/occurrences/search?q=collection_uid%3Aco12 
Australian National Botanic Gardens Seedbank in ALA proper: https://biocache-test.ala.org.au/occurrences/search?q=data_resource_uid%3Adr820#tab_recordsView

**Comment by adam-collins** [comment]
Issue Summary
1. Discussion around duplicate detection. Suggested using preservedSpecimen before livingSpecimen for the representative record. Indicates there may be an issue with Seedbank records if doing this.

**Comment by nickdos** [comment]
Trying to test this issue but I'm not sure what the actual issue is here.... I've read it 3 times now and am none the wiser.

**Comment by adam-collins** [comment]
Moved remaining issues to #436 and https://github.com/AtlasOfLivingAustralia/biocache-hubs/issues/454

**Comment by adam-collins** [comment]
Moved duplicates algorithm feedback to issue #436

**Comment by adam-collins** [comment]
Nothing to test in this issue.
