### ISSUE TITLE
AVH testing: establishmentMeans facet casing

### ISSUE THREAD

**Issue by nielsklazenga** [AtlasOfLivingAustralia/la-pipelines#409]
Confirming that https://github.com/AtlasOfLivingAustralia/data-management/issues/504 has been resolved in the new infrastructure.

![image](https://user-images.githubusercontent.com/4694550/120966714-f6443e00-c7a9-11eb-9e6b-1d2a73f791ad.png)

Could something still be done about the casing of the facets? [`establishmentMeans`](https://dwc.tdwg.org/terms/#dwc:establishmentMeans) has a TDWG vocabulary now and the controlled values are camel-case.

I also have the feeling that values we deliver as 'cultivated' are mapped to 'managed', but we can worry about that later, as it will take some time for providers to catch up. This term has been moved to [`degreeOfEstablishment`](https://dwc.tdwg.org/terms/#dwc:degreeOfEstablishment), the vocabulary of which recognises `managed`, `cultivated` and `captive` as all different things.

**Comment by javier-molina** [comment]
This is what we have in prod

![Screen Shot 2021-06-09 at 12 08 08 pm](https://user-images.githubusercontent.com/8326394/121281607-82c23e00-c91b-11eb-94f5-9435e235cde5.png)

**Comment by nielsklazenga** [comment]
@javier-molina , what is in prod for AVH is not something you want to emulate in LA Pipelines, as the Biocache Store applies a specific mapping for AVH that is no longer used. The values for the establishment means facet in avh-test are correct. It would just be nice if they could be lowercase.

**Comment by javier-molina** [comment]
@brucehyslop this is something that can be addressed by i18n config, do you have capacity to include it in your backlog?

**Comment by brucehyslop** [comment]
I'm not familiar with the AVH webapp. If the interface values displayed use the i18n message.properties they can be fixed with an update to the AVH config. 
I can look into getting AVH running in dev.

**Comment by javier-molina** [comment]
@brucehyslop AVH is another biocache hub app. It uses a different skin and a filter for specific records from biocache service. 

Biocache Hub has the same facet and values so you can comfortably work there.

<img width="792" alt="Screen Shot 2021-06-10 at 6 09 47 pm" src="https://user-images.githubusercontent.com/8326394/121489373-5ee42280-ca17-11eb-82dd-bd4c9c603374.png">

**Comment by brucehyslop** [comment]
This can be done either with an update to the avh-hub message.properties or the biocache-service message.properties. 
If the change is made to biocache-service it will affect all biocache-hub instances. 

@nielsklazenga could I please confirm the labels should be mapped as follows:
 - NATIVE -> Native
 - INTRODUCED -> Not Native
 - MANAGED -> Cultivated
 - UNCERTAIN -> Unknown

**Comment by brucehyslop** [comment]
this update has been deployed to https://avh-test.ala.org.au

**Comment by javier-molina** [comment]
LGTM 
![Screen Shot 2021-07-12 at 10 21 38 am](https://user-images.githubusercontent.com/8326394/125214519-f5e41900-e2fa-11eb-879c-62b7060cd144.png)

**Comment by nielsklazenga** [comment]
That is a step backwards, as these are not the right values.

https://avh.ala.org.au has the right values.

![image](https://user-images.githubusercontent.com/4694550/125221784-1ff20700-e30c-11eb-8829-77c77e39b0c8.png)

Only the values should be lowercase:

- `native`
- `introduced`
- `managed`
- `uncertain`

**Comment by nielsklazenga** [comment]
Sorry @brucehyslop , missed this bit earlier:

> @nielsklazenga could I please confirm the labels should be mapped as follows:
> - NATIVE -> Native
> - INTRODUCED -> Not Native
> - MANAGED -> Cultivated
> - UNCERTAIN -> Unknown

Correct mapping is:
- NATIVE -> native
- INTRODUCED -> introduced
- MANAGED -> managed
- CULTIVATED -> cultivated
- UNCERTAIN -> uncertain

So, no mapping really. These are the values we deliver and the values in the TDWG vocabularies.

**Comment by brucehyslop** [comment]
Have updated the mapping as above. 

@nielsklazenga there are no records in solr with establishementMean = CULTIVATED
The DwC vocab for establishementMeans also does not have a `cultivated` as a "Controlled value" https://dwc.tdwg.org/em/#:~:text=The%20Establishment%20Means%20Controlled%20Vocabulary,%3AestablishmentMeans%20and%20dwciri%3AestablishmentMeans%20.


![Screen Shot 2021-07-15 at 3 37 08 pm](https://user-images.githubusercontent.com/12233783/125734601-3307269d-fad7-44b9-a490-1cf88162e605.png)

**Comment by nielsklazenga** [comment]
Thanks @brucehyslop , in the [GBIF Vocabulary](https://rs.gbif.org/vocabulary/gbif/establishment_means.xml) we have been using, 'cultivated' is a synonym of 'managed', so we changed all our 'cultivated' records to managed several years ago. 'managed' is still a recognised term in the new vocabulary, so I rather fix this in the data than with mapping in SOLR.

**Comment by brucehyslop** [comment]
Mapping defined avh-hub message properties, deployed https://avh-test.ala.org.au/

Note: no records exists with establishment means = "cutivated" 

![Screen Shot 2021-08-11 at 2 08 56 pm](https://user-images.githubusercontent.com/12233783/128968330-29d87b9e-758a-415e-abd9-001be6063b6f.png)

**Comment by nielsklazenga** [comment]
Thanks @brucehyslop. It looks like what is delivered as 'cultivated' is changed to 'MANAGED' during processing:

![image](https://user-images.githubusercontent.com/4694550/128973772-9fe5e2d7-5a1e-4e39-9209-043c95d4de13.png)
(this is "original vs. processed")

This is probably because the old GBIF vocabulary, in which 'cultivated' is a synonym of 'managed', is still being used. I suggest we leave it like this. When the new vocabulary is implemented, terms like 'cultivated' and 'managed' will move to a different term anyway.

**Comment by javier-molina** [comment]
@nielsklazenga I will leave this open (but sitting in the Done column) until we release this version to prod.
