### ISSUE TITLE
Feedback from Flora and Fauna Atlas NT 

### ISSUE THREAD

**Issue by peggynewman** [AtlasOfLivingAustralia/la-pipelines#410]
[dr361 Fauna Atlas NT](https://biocache-test.ala.org.au/occurrence/search?q=(data_resource_uid%3A%22dr361%22))
[dr362 Flora Atlas NT](https://biocache-test.ala.org.au/occurrence/search?q=(data_resource_uid%3A%22dr362%22))
[dr15866 Flora Atlas NT](https://biocache-test.ala.org.au/occurrence/search?q=(data_resource_uid%3A%22dr15866%22))

Feedback below. Action is to reload CSVs from the upload server into pipelines. Need to be converted to DWCA.  

![image](https://user-images.githubusercontent.com/1271932/121105034-98b1ff00-c846-11eb-9581-9646ce7d52ff.png)

![image](https://user-images.githubusercontent.com/1271932/121105073-af585600-c846-11eb-96f2-3e60aa7d2daa.png)

**Comment by charvolant** [comment]
NT Fauna corrected and dr361 loaded with the correct records. Checking sensitivity after reload and re-index.

There appear to be duplicate keys in dr362. Checking to see if there is an additional term in the key terms.

dr15866 comes from a Royal Botanic Garden IPT server. stateProvince usually refers to region in this dataset 'The Northern Territory' matches 225394 records, Central Australia North gives 9055, Darwin and Gulf gives 2114. 236563 out of 325548 records. dr15866 shows 325405, 260799 in the NT which is roughly in line with the numbers quoted above. The IPT doesn't provide the original of the record.

**Comment by charvolant** [comment]
See, also #400

**Comment by peggynewman** [comment]
Oh dear, this is at least the second time I've (noticed that I've) opened a second GH issue for the same thing. Sorry everyone.

@nielsklazenga check out the text from the email to review the numbers for DNA AVH.

**Comment by nielsklazenga** [comment]
@peggynewman , the DNA AVH Darwin Core Archive that was uploaded last Friday contained 325,548 records, so the numbers for the DNA herbarium in ALA looks pretty good.

**Comment by peggynewman** [comment]
Where do you think their "276,981" comes from? @nielsklazenga

**Comment by nielsklazenga** [comment]
I think a lot of the NT (that's the herbarium in Alice Springs) records might be in ALA (and in the cache I keep) twice. They were initially delivered as part of the DNA collection, but split off later. When they start delivering their own records, that will sort itself out.

**Comment by javier-molina** [comment]
@charvolant tomorrow I will catch up with Peggy to summarise the collection community findings and actions at our end so we can get back to them.

If @peggynewman is not across the latest status for this would you mind letting us know where it is?

I think the last thing remaining was to analyse/find an explanation for the sensitive records. 

Thanks

**Comment by peggynewman** [comment]
Sent thank you email and summary today.
