### ISSUE TITLE
POST for `/ws/webportal/params` fails to return a response

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/la-pipelines#414]
Using a tool like PostMan, the following 2 URLs can be checked via `POST` method - prod one returns a QID value and test server fails to return a response:

https://biocache-ws.ala.org.au/ws/webportal/params?q=lsid%3Ahttps%3A%2F%2Fid.biodiversity.org.au%2Fnode%2Fapni%2F7635785&fq=geospatial_kosher%3Atrue&fq=-occurrence_status_s%3Aabsent&fq=occurrence_date%3A%5B1780-01-01T00%3A00%3A00.000Z+TO+2030-01-01T00%3A00%3A00.000Z%5D&bbox=true

https://biocache-ws-test.ala.org.au/ws/webportal/params?q=lsid%3Ahttps%3A%2F%2Fid.biodiversity.org.au%2Fnode%2Fapni%2F7635785&fq=geospatial_kosher%3Atrue&fq=-occurrence_status_s%3Aabsent&fq=occurrence_date%3A%5B1780-01-01T00%3A00%3A00.000Z+TO+2030-01-01T00%3A00%3A00.000Z%5D&bbox=true

SP uses this URL, so issue was detected in SP testing

CC @qifeng-bai

**Comment by qifeng-bai** [comment]
FYI: Biocache-ws-test works with NONE-urlencoded query string:
https://biocache-ws.ala.org.au/ws/webportal/params?q=lsid:https://id.biodiversity.org.au/node/apni/7635785&fq=geospatial_kosher:true&fq=-occurrence_status_s:absent&fq=occurrence_date:[1780-01-01T00:00:00.000Z TO 2030-01-01T00:00:00.000Z]&bbox=true

**Comment by qifeng-bai** [comment]
And also, posting data with  application/x-www-form-urlencoded does not work.
@nickdos mentioned application/x-www-form-urlencoded should be what our clients are using to send form-based data via POST. 

![Screen Shot 2021-06-09 at 2 50 20 pm](https://user-images.githubusercontent.com/31238531/121295543-90cf8900-c932-11eb-9f4d-5ef3b52fe907.png)

**Comment by brucehyslop** [comment]
This is a field mapping issue, the field `occurrence_status_s` doesn't have a mapping which is causing the solr query to fail. If you use `occurrence_status` the request should work (either form-urlencoded or query parameters).

https://biocache-ws-test.ala.org.au/ws/webportal/params?q=lsid%3Ahttps%3A%2F%2Fid.biodiversity.org.au%2Fnode%2Fapni%2F7635785&fq=geospatial_kosher%3Atrue&fq=-occurrence_status%3Aabsent&fq=occurrence_date%3A%5B1780-01-01T00%3A00%3A00.000Z+TO+2030-01-01T00%3A00%3A00.000Z%5D&bbox=true

**Comment by nickdos** [comment]
Agree with Bruce - SP is using a non-standard field there - see https://biocache.ala.org.au/fields?filter=occurrence_status

**Comment by qifeng-bai** [comment]
SP works now.  Will biocache support returning error as JSON in future,  if Spatial set Accept=application/json
