### ISSUE TITLE
Configure test environment in NCI 

### ISSUE THREAD

**Issue by javier-molina** [AtlasOfLivingAustralia/la-pipelines#415]
NCI has some servers that were used early on for the infrastructure upgrade project and also hosts biocache-2020.ala.org.au / biocache-ws-2020.ala.org.au servers that were used for DQ release and are a subset of current production environment.

To continue the work for Infrastructure Upgrade v1.1 release we need to have a complete test environment, albeit reduced capacity).

The usual suspects are:

- biocache hub
- biocache service
- cassandra cluster
- spark cluster
- spark master / Jenkins
- second name node for HDFS
- solr clusters
- zookeeper

TBC: What servers need to be updated. which ones can be reused with minimal change, any servers no longer used?

**Comment by djtfmartin** [comment]
Test environment is now functional. Issues with DOIs and logger services have been resolved. This can be closed.
