### ISSUE TITLE
Move Jenkins to its own VM

### ISSUE THREAD

**Issue by javier-molina** [AtlasOfLivingAustralia/la-pipelines#417]
Currently Jenkins is hosted in spark master node which also hosts the HDFS node master service.

Moving Jenkins to its own VM will help any potential contention

**Comment by javier-molina** [comment]
@matthewandrews are you happy to hand this over to @sadeghim for when he has some capacity after the production deployment?. As far as I remember the only remaining work is to configure Jenkins.

**Comment by matthewandrews** [comment]
Sure, yes, Jenkins is installed on the new server - we just need to copy the jobs over from current pipeline Jenkins, and configure the jobs that run on the spark cluster etc.

**Comment by javier-molina** [comment]
Issue moved to [AtlasOfLivingAustralia/data-management #701](https://github.com/AtlasOfLivingAustralia/data-management/issues/701) via [**ZenHub**](https://www.zenhub.com/)
