### ISSUE TITLE
Create shared filesystem on Spark nodes for DM Operations

### ISSUE THREAD

**Issue by javier-molina** [AtlasOfLivingAustralia/la-pipelines#418]
Data Management team will benefit from having a shared file system available on Spark nodes where they can host several resources from scripts to a staging area for intermediate DWcAs.

**Comment by javier-molina** [comment]
@sadeghim, Matt mentioned this is now finished, I will wait to see if you have any comments before closing this ticket.

**Comment by matthewandrews** [comment]
Yes this is all done.
