### ISSUE TITLE
Changes to data quality filters in test

### ISSUE THREAD

**Issue by RobinaSanderson** [AtlasOfLivingAustralia/la-pipelines#420]
Some of the assertions and fields the data quality filters used have either been changed or removed.

Bruce and I are updating the data quality filters to reflect the changes and will list what we've done in the attached word document
[DataProfileQueries20210623.docx](https://github.com/AtlasOfLivingAustralia/la-pipelines/files/6799166/DataProfileQueries20210623.docx)

**Comment by brucehyslop** [comment]
data quality profiles have been updated in test and the saved profile json is in the [data-quality-filter-service/data-profiles `pipelines-profiles` branch](https://github.com/AtlasOfLivingAustralia/data-quality-filter-service/tree/pipelines-profiles/data-profiles)

**Comment by adam-collins** [comment]
The filters on biocache-test appear to be using the new ALA Default profile as expected.

The link beside 'exclude records based on record type` does not correctly parse the (.. AND ..) term for the inverted fq. This may be addressed by #445 
![Screen Shot 2021-06-28 at 11 00 58 am](https://user-images.githubusercontent.com/8031500/123565487-66217380-d800-11eb-90a2-0ddfcb27a436.png)
