### ISSUE TITLE
SOLR streaming extensions - Min/Max query - facet range

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/la-pipelines#421]
to be added

**Comment by adam-collins** [comment]
https://github.com/AtlasOfLivingAustralia/biocache-service/pull/636

**Comment by nickdos** [comment]
Tested with [this query](https://biocache-test.ala.org.au/occurrences/search?taxa=Acacia&q=state%3A%22Australian+Capital+Territory%22+AND+occurrence_date%3A%5B2000-01-01T00%3A00%3A00Z+TO+2010-01-01T00%3A00%3A00Z%5D&qualityProfile=ALA&disableAllQualityFilters=true) that uses a data range filter (`&fq=eventDate:[2000-01-01T00:00:00Z TO 2010-01-01T00:00:00Z]`)  and produces 887 results. 

Download file shows 887 records, as expected.

Can I assume I've tested the appropriate code/change above?

**Comment by adam-collins** [comment]
This makes it more clear, for the changed webservice, test matches prod
`-176.468,-54.762778,178.5,69.9` https://biocache-test.ala.org.au/ws/webportal/bbox?q=year:2020
`-176.468,-54.762778,178.5,69.9` https://biocache.ala.org.au/ws/webportal/bbox?q=year:2020
