### ISSUE TITLE
SOLR Streaming - Endemic query

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/la-pipelines#422]
Investigate the use of stream decorators including [complement function](https://solr.apache.org/guide/6_6/stream-decorators.html) to achieve endemic queries with a reduce impact on the SOLR cluster.

**Comment by adam-collins** [comment]
https://github.com/AtlasOfLivingAustralia/biocache-service/pull/637

**Comment by adam-collins** [comment]
Request hanging fixed with https://github.com/AtlasOfLivingAustralia/biocache-service/pull/641

**Comment by javier-molina** [comment]
Last work reviewed by Adam

**Comment by javier-molina** [comment]
Closing this as it is a technical task but has been reviewed. Regression and functional test would pick any issues.
