### ISSUE TITLE
Change "text" field copyField  - SOLR field type in schema

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/la-pipelines#423]

**Comment by djtfmartin** [comment]
Merged and deployed

**Comment by nickdos** [comment]
Trying to test this issue... is the only change to use `textgen` fieldtype (seems to be unstemmed)?

**Comment by nickdos** [comment]
These 2 searches in prod and test give a big enough difference that I think there might be an issue with `q=text:foo` searches.

Prod: [`text:peggy`](https://biocache.ala.org.au/occurrences/search?q=peggy&disableAllQualityFilters=true&fq=data_resource_uid%3A%22dr340%22) = 772 results
Test: [`text:peggy`](https://biocache-test.ala.org.au/occurrences/search?q=text%3Apeggy&disableAllQualityFilters=true&qualityProfile=ALA&fq=data_resource_uid%3A%22dr340%22) = 52 results

Looking at some records in prod and not test I can see missing records from data_resources that have very similar total number of records (e.g. Aust Museum has more records in test but is missing a bunch or records in the search above) suggesting it is not a data issue but an indexing issue.

**Comment by djtfmartin** [comment]
Stemming added and eems to working (although not well with the above examples)

https://biocache.ala.org.au/occurrences/search?q=klazenga

**Comment by nickdos** [comment]
Not getting any records for [`text:peggy`](https://biocache-dq-test.ala.org.au/occurrences/search?q=text:peggy) now... vs 772 for old prod and 57 for old test...

**Comment by nickdos** [comment]
Stemming does not appear to be working for me. E.g. these two queries should return the same results set but don't:

https://biocache-dq-test.ala.org.au/occurrences/search?q=text:parrots  (0 results)
https://biocache-dq-test.ala.org.au/occurrences/search?q=text:parrot  (4,319,873 results)

**Comment by nickdos** [comment]
Change seems benign, so moving to done. I've raise a separate issue (#485) for the stemming of query input if needed.
