### ISSUE TITLE
Size of downloaded Eucalyptus in Tas occurrences > 1M

### ISSUE THREAD

**Issue by qifeng-bai** [AtlasOfLivingAustralia/la-pipelines#428]
Spatial registered a query for eucalyptus in Tasmania
https://biocache-ws-test.ala.org.au/ws/webportal/params/details/1623986920118

When we do search,  a result shows 74078 records
https://biocache-ws-test.ala.org.au/ws/occurrences/search?q=qid:1623986920118

However, when we download, it downloads 1M records (limited by pagesize)

https://biocache-ws-test.ala.org.au/ws/webportal/occurrences.gz?q=qid:1623986920118&pageSize=1000000&start=0&fl=id,longitude,latitude

**Comment by adam-collins** [comment]
fixed by https://github.com/AtlasOfLivingAustralia/biocache-service/pull/639

**Comment by adam-collins** [comment]
This was another instance of fqs getting ignored.

**Comment by qifeng-bai** [comment]
SP tests passed with Biocache-test
