### ISSUE TITLE
Refactor ScatterplotController to use SOLR streaming 

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/la-pipelines#429]
Refactor ScatterplotController to use SOLR streaming to reduce impact on SOLR cluster.

**Comment by adam-collins** [comment]
https://github.com/AtlasOfLivingAustralia/biocache-service/pull/674

**Comment by adam-collins** [comment]
Fixed broken test.

**Comment by qifeng-bai** [comment]
Scatterplot passed on Spatial-test
