### ISSUE TITLE
Manage EnvironmentalDNA and GenomicDNA

### ISSUE THREAD

**Issue by javier-molina** [AtlasOfLivingAustralia/la-pipelines#431]
Biocache Store implementation uses two ALA custom values for Basis of Record: GenomicDNA and EnvironmentalDNA that are not part of the DwC standard but have served the classification of collections containing records with Environmental or Genomic DNA samples/sequences.

As a stop gap solution, while a more general approach is defined, the pipelines implementation will use the Collectory Content Type field to define the values "EnvironmentalDNA" and "GenomicDNA".

In addition at the record level, Basis of Record will have a value of "Material Sample".

The pipelines processing will produce a new field contentType available in Biocache Hub for faceting.

PR here: https://github.com/gbif/pipelines/pull/550

**Comment by djtfmartin** [comment]
Reviewed and merged
