### ISSUE TITLE
Automatically update technical section on assertion wiki pages

### ISSUE THREAD

**Issue by RobinaSanderson** [AtlasOfLivingAustralia/la-pipelines#435]
Create and run a script that edits the assertion wiki pages as follows:

**1. Code Reference**
The template for documenting assertions developed during the data quality project includes a section with a Code reference or Technical information link. 

As an example: https://github.com/AtlasOfLivingAustralia/ala-dataquality/wiki/COORDINATES_CENTRE_OF_COUNTRY

For new assertions this needs to be populated.

For existing assertions (such as the example above) new links are required for pipelines.

~~Question: do we keep the old links to biocache to assist Living Atlases? If so, we should have headings for Post-Pipelines Upgrade and Pre-Pipelines Upgrade~~  Already addressed.

As code is changing continuously a link to a fixed line of code will be outdated quickly  a link to a representative search in [pipelines](https://github.com/gbif/pipelines) or related repo will be used, instead of a fixed code line, so someone reading the wiki pages can find their way from it.

A couple of examples of the suggested search

Pipelines repo search
https://github.com/search?q=repo%3Agbif%2Fpipelines+MISSING_COLLECTION_DATE+in%3Afile&type=Code

GBIF organisation search
https://github.com/search?q=org%3Agbif+MISSING_COLLECTION_DATE+in%3Afile&type=Code

**2. Replaces**
For assertions that replace an old one, populate this section as follows:

- If the old assertion has a wiki page, add a link to that assertion 
- It the old assertion does not have a wiki page then just add the name of the old assertion

**3. Required fields**
- Rename section **Required fields** to **Related terms**
- Add the list of fields from pipelines code

**Comment by javier-molina** [comment]
Can the addition of links to source code be automated by running a script across a set of wiki files?

**Comment by brucehyslop** [comment]
Updates have been applies to the assertions wiki pages and can be managed / synced using the script. 
See #512

**Comment by javier-molina** [comment]
@RobinaSanderson I have glanced through a few pages and things look good.

Do you have any comments on the result before we close this ticket?

**Comment by javier-molina** [comment]
Reviewed by Robina and myself, looks good.
