### ISSUE TITLE
Clustering/Associated records feedback analysis

### ISSUE THREAD

**Issue by adam-collins** [AtlasOfLivingAustralia/la-pipelines#436]
Duplicates algorithm feedback indicates that choosing the representative record should be changed and choose preservedSpecimen before other basisOfRecord types.

1. (Australian National Hervarium feedback #408) Represetative record should put preservedSpecimen before livingSpecimen. e.g. AVH lists preservedSpecimens and ASBP lists the duplicate livingSpecimens.
- Note that duplicates detected in the Seedbank portal may have a problem preservedSpecimen becomes the representative record over the livingSpecimen.
- dataset referenced: Australian National Botanic Gardens Seedbank in ALA proper: https://biocache-test.ala.org.au/occurrences/search?q=data_resource_uid%3Adr820#tab_recordsView
- dataset referenced: Australian National Herbarium in AVH: https://avh-test.ala.org.au/occurrences/search?q=collection_uid%3Aco12

2. (South Australian Museum Australia provider for OZCAM
#399) Representative record should put preservedSpecimen before materialSample. 
```
There are two behaviours of note when looking at tissue records: It appears to be recording the tissue records as associated records when checking a voucher - when they're both held in this Museum. This isn't a duplicate but is desired behaviour.
https://biocache-test.ala.org.au/occurrences/f974a7cf-cc4b-45f2-86ff-b0a382da8388
Is of a tissue. In the associated records are listed a number of other tissues and the voucher from which those tissues were taken. Ideally if there are associated materialSample and preservedSpecimen records the preservedSpecimen would be designated as the representative record.
```

3. Probably  the input of this [DR](https://biocache.ala.org.au/occurrences/search?q=data_provider_uid:dp5183) needs to be considered too.

- 1.3 million records (almost 1/4 of OBIS records) are excluded because they are considered duplicate records. Are they duplicated OBIS records (could ALA have repeated harvests without dumping old harvests?), or duplicates of other data in ALA 

[Current production](https://biocache.ala.org.au/occurrence/search?q=data_provider_uid%3Adp5183&qualityProfile=ALA&disableAllQualityFilters=true&fq=duplicate_status%3A%22D%22) has 186,575 duplicate records while [test](https://biocache-test.ala.org.au/occurrences/search?q=data_provider_uid%3Adp5183&qualityProfile=ALA&disableAllQualityFilters=true&fq=duplicateStatus%3A%22ASSOCIATED%22)  contains 1,353,219.

4.  
<p class="MsoNormal" style="margin: 0cm; font-size: 12pt; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;"><span style="font-size: 10pt; font-family: Arial, sans-serif; color: rgb(49, 132, 155);">You won’t have RECORDS for the following associatedMedia because the catalogNumbers you sent me belong to audio TRACKS (for which I don’t supply records), not species occurrence records (which I do supply)  i.e. multiple taxa per track. That would be the reason you have multiple occurrences of the track catalogNumber i.e. the same audio file is the associatedMedia for &gt;1 species occurrence record. You have all of the species occurrence records – see catalogNumber field in the following table – and you need the mp3 file to link to the catalogNumbers</span><o:p></o:p></p>

associatedMedia | Species occurrence catalogNumber
-- | --
X01960.mp3 | X02336
X01960.mp3 | X02337
X01960.mp3 | X02338
X01960.mp3 | X02339
X01960.mp3 | X02340
X01960.mp3 | X02341
X02074.mp3 | X02682
X02074.mp3 | X02683

<p class="MsoNormal" style="margin: 0cm; font-size: 12pt; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;"><span style="font-size: 10pt; font-family: Arial, sans-serif;">And there’s a problem here with the way the Atlas is displaying the records in the catalogNumber search results. It’s excluding X02082 as a ‘duplicate record’, which it isn’t.<span class="Apple-converted-space"> </span><span style="color: rgb(49, 132, 155);">It’s a recording of a different species at the same locality and time, which is NOT a duplicate species occurrence<span class="Apple-converted-space"> </span><a href="https://biocache.ala.org.au/occurrences/search?q=qid%3A1625208471152&amp;qualityProfile=ALA" title="https://biocache.ala.org.au/occurrences/search?q=qid%3A1625208471152&amp;qualityProfile=ALA" style="color: rgb(5, 99, 193); text-decoration: underline;">https://biocache.ala.org.au/occurrences/search?q=qid%3A1625208471152&amp;qualityProfile=ALA</a>.</span></span><o:p></o:p></p><p class="MsoNormal" style="margin: 0cm; font-size: 12pt; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;"><span style="font-size: 10pt; font-family: Arial, sans-serif; color: rgb(49, 132, 155);"> </span><o:p></o:p></p><p class="MsoNormal" style="margin: 0cm; font-size: 12pt; font-family: Calibri, sans-serif; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;"><span style="font-size: 10pt; font-family: Arial, sans-serif; color: rgb(49, 132, 155);">In fact, you should probably have found a lot more instances of this than you’ve sent me, which perhaps suggests that the logic the ALA algorithm uses for deciding what is a duplicate record is not appropriate. A search for the following excludes both of the following occurrence records<span class="Apple-converted-space"> </span><a href="https://biocache.ala.org.au/occurrences/search?q=qid%3A1625208953920&amp;qualityProfile=ALA" title="https://biocache.ala.org.au/occurrences/search?q=qid%3A1625208953920&amp;qualityProfile=ALA" style="color: rgb(5, 99, 193); text-decoration: underline;">https://biocache.ala.org.au/occurrences/search?q=qid%3A1625208953920&amp;qualityProfile=ALA</a><span class="Apple-converted-space"> </span>both on the basis of location uncertainty and X02689 as a duplicate.</span><o:p></o:p></p>

associatedMedia | Species occurrence catalogNumber
-- | --
X02077.aif | X02688
X02077.aif | X02689

**Comment by timrobertson100** [comment]
> 1.3 million records (almost 1/4 of OBIS records) are excluded because they are considered duplicate records. Are they duplicated OBIS records (could ALA have repeated harvests without dumping old harvests?), or duplicates of other data in ALA

I looked into some examples and found you have predator/prey datasets like [this](https://collections.ala.org.au/public/show/dr9963) with [this example](https://biocache.ala.org.au/occurrences/2140dce3-0f26-4ca9-8bb9-c6aedc1680ba) record.  In this case, it's linking records within the same dataset that represent individual organisms of the same species in the same catchment - perhaps it didn't use to do that but for some uses these would be considered duplicates. 

For the many acoustic tracking records that are flagged, it's linking detections of the same species at the same location on the same day such as [this](https://biocache.ala.org.au/occurrences/fd785d47-3d33-4b61-9d7e-ab3f617e0085) and [this](https://biocache.ala.org.au/occurrences/1b004414-721d-4477-8742-f455245d3f1e). Interestingly, the records are providing a `quantity` and `quantityType` of _detections per receiver day_ which then does imply it is reasonable to link them as possible duplicates (each claims to provide the detections per day of the species for the same station).

**Comment by javier-molina** [comment]
These were the numbers on 25 Jun 2021:
![Screen Shot 2021-06-25 at 11 40 50 am](https://user-images.githubusercontent.com/8326394/124704581-a89d2b80-df37-11eb-8712-60a167c01eb1.png)


And this is an explanation and possible change from Dave:

> The duplicate count is reduced significantly if we add a filter to exclude duplicates in the same dataset
> adding `&fq=duplicateType:DIFFERENT_DATASET`
> 
> i propose we add this the the DQ filter for “Exclude duplicate records”
> 
> We can only do this though after the switch
>

**Comment by javier-molina** [comment]
Points 1 and 2 are related to existing behaviour of duplicate detection (now clustering) algorithm and are now noted in DQ backlog AtlasOfLivingAustralia/DataQuality#242. 

Point 3 and 4 are related to record counts differences between new processing and the previous version. These will be addressed as per [comment above](https://github.com/AtlasOfLivingAustralia/la-pipelines/issues/436#issuecomment-875294215) once we go through the relevant change management for DQ filters.

**Comment by peggynewman** [comment]
DQ filters were updated
