### ISSUE TITLE
flimit=0 gives an empty response, with no count

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/la-pipelines#442]
This affects the SP and results in all counts for species groups being 0.

<img width="645" alt="Screen Shot 2021-06-23 at 1 57 26 pm" src="https://user-images.githubusercontent.com/444897/123106141-4cfb7a00-d430-11eb-80d4-e9e29577669f.png">

**Comment by djtfmartin** [comment]
Fixed and deployed to test.

**Comment by adam-collins** [comment]
Working on https://nectar-spatial-staging.ala.org.au/
![Screen Shot 2021-06-28 at 11 13 50 am](https://user-images.githubusercontent.com/8031500/123565990-eeecdf00-d801-11eb-9c01-f427290ed606.png)
