### ISSUE TITLE
Display of data quality profile category broken

### ISSUE THREAD

**Issue by brucehyslop** [AtlasOfLivingAustralia/la-pipelines#445]
The display of the profile category does not function if the filter contains multiple query terms.

![Screen Shot 2021-06-24 at 5.46.39 pm.png](https://images.zenhubusercontent.com/5e97bb52fae5a95a1a220ad1/f2513e50-a18b-4c38-9d2a-f803f41f1a6f)

**Comment by adam-collins** [comment]
The display has additional issues:
- `view excluded records` link does not do what it says.
- `Further information` links display old links that work but have the old page titles.
  - `spatiallyValid` links to https://github.com/AtlasOfLivingAustralia/ala-dataquality/wiki/geospatial_kosher
  - `-assertions:"PRESUMED_SWAPPED_COORDINATE"` links to https://github.com/AtlasOfLivingAustralia/ala-dataquality/wiki/INVERTED_COORDINATES

**Comment by javier-molina** [comment]
Thanks @adam-collins , the items below are still work in progress and are being addressed as we speak.

> * `Further information` links display old links that work but have the old page titles.
>   
>   * `spatiallyValid` links to https://github.com/AtlasOfLivingAustralia/ala-dataquality/wiki/geospatial_kosher
>   * `-assertions:"PRESUMED_SWAPPED_COORDINATE"` links to https://github.com/AtlasOfLivingAustralia/ala-dataquality/wiki/INVERTED_COORDINATES

**Comment by javier-molina** [comment]
Related issues #419 #456 have to be released together.

**Comment by javier-molina** [comment]
@adam-collins any further comment re: code changes or review in general, see comment above for how this needs to be tested.

**Comment by alexhuang091** [comment]
![issue](https://user-images.githubusercontent.com/61677987/125394595-4340b300-e3ed-11eb-9624-8a513e445ee6.jpg)
filter value is broken

**Comment by alexhuang091** [comment]
And I remember there are explanations/links for userAssertions 50001 and 50005. Can they be put here?

![2](https://user-images.githubusercontent.com/61677987/125394945-d11c9e00-e3ed-11eb-8536-3c70bc988936.jpg)

**Comment by nickdos** [comment]
@javier-molina should this move back to "in progress" to fix the missing values highlighted in the comment above?

**Comment by brucehyslop** [comment]
Issues relating to the display of DQ filters and links are covered in #419

**Comment by brucehyslop** [comment]
The reason the links for `userAssertions` are not displaying on test is because there are no records with `userAssertions` all Solr shards. The link data relies on a request to biocache-service to retrieve the index field data. 

  https://biocache-ws-test.ala.org.au/ws/index/fields?fl=userAssertions

This endpoint triggers a Solr LUKE request which queries a single shard. If that shard that is chosen does have records that contain a field the field on not returned. 

The links will be displayed sporadically depending on which shard is chosen. 

![Screen Shot 2021-08-19 at 3 26 12 pm](https://user-images.githubusercontent.com/12233783/130012874-82fb7922-6b07-4e2f-8b13-f490e3f4cb05.png)

The issue does not occur in production because records that contain `userAssertions` are distributed across all shards.

**Comment by brucehyslop** [comment]
The issue does not occur in production because records that contain `userAssertions` are distributed across all shards.

**Comment by brucehyslop** [comment]
The this is the same reason there is no link displayed for `outlierLayerCount` however this is because sampling on not being run on test. 

The link does display on prod.
