### ISSUE TITLE
downloaded file doesn't have Shape-README.html

### ISSUE THREAD

**Issue by alexhuang091** [AtlasOfLivingAustralia/la-pipelines#446]
download from https://biocache-test.ala.org.au/ws/occurrences/index/download?q=Macropus+agilis&reasonTypeId=10&fileType=shp&apiKey=10ebb915-62ce-4489-8f7a-a047a51215af 

The zip file does not contain the Shape-README.html as expected.

**Comment by adam-collins** [comment]
Shapefile downloads are deprecated. 
![Screen Shot 2021-06-28 at 9 21 00 am](https://user-images.githubusercontent.com/8031500/123562464-45522180-d7f2-11eb-8433-ae34e0df8603.png)
