### ISSUE TITLE
Add content type to default list of facets for ALA hub (biocache hub)

### ISSUE THREAD

**Issue by javier-molina** [AtlasOfLivingAustralia/la-pipelines#447]
#431 added contentType to the list of available facets for Record section however that field is not visible by default.

Given that contentType is the new way to filter eNDA and genomicDNA collections it is important to have it visible by default so it makes things easy for users.

![Screen Shot 2021-06-25 at 11.46.09 am.png](https://images.zenhubusercontent.com/56b920d76caf56c9d38c5513/cb0bcec0-ae46-45e9-89ec-53b0fea9d64f)

**Comment by alexhuang091** [comment]
@javier-molina Config changes made on test-server, could you do a test?

**Comment by adam-collins** [comment]
Resetting filters to default does select `Content Types`.

**Comment by nickdos** [comment]
LGTM
