### ISSUE TITLE
some DRs unique key fields in UUID

### ISSUE THREAD

**Issue by peggynewman** [AtlasOfLivingAustralia/la-pipelines#448]
So fare we've been able to find impacts here:

dr_uid | dr_name | example
--|--|--
[dr1411](https://biocache-test.ala.org.au/occurrences/search?q=%28data_resource_uid%3A%22dr1411%22%29&disableAllQualityFilters=true) | inaturalist | https://biocache-test.ala.org.au/occurrences/83440236
[dr10487](https://biocache-test.ala.org.au/occurrences/search?q=%28data_resource_uid%3A%22dr10487%22%29&disableAllQualityFilters=true) | base | https://biocache-test.ala.org.au/occurrences/FungiITS1-62061-1087883
[dr361](https://biocache-test.ala.org.au/occurrences/search?q=%28data_resource_uid%3A%22dr10487%22%29&disableAllQualityFilters=true) | fauna atlas nt | https://biocache-test.ala.org.au/occurrences/DOLFIN1242

These datasets were excluded in the full migration. Not all datasets that were excluded are impacted.

**Comment by djtfmartin** [comment]
Fixed on test
