### ISSUE TITLE
Improve test coverage

### ISSUE THREAD

**Issue by javier-molina** [AtlasOfLivingAustralia/la-pipelines#449]
Test coverage on biocache service  dropped from 30% to 14%

- [x] Biocache service cleanup required, with the removal of redundant code (19 classes already identified as not-used)
- [x] Identification of unused methods
- [x] Review controller to ensure they are using the updated search methods in `SolrIndexDAO`  and `SearchDAO`
- [x] Check if EYA is using WMS - add if so legacy (unperformant) methods for geojson can be removed/deprecated
- [x] Review if ShapeFile generation code can be removed (given we've deprecated service)
- [x] Need to identify areas that have poor coverage
- [x] Review Spring dependencies
- [x] Review geotools version
- ~~[ ] Using beta versions of methods from google libraries~~

We should aim for minimum test coverage of 50%.

Worked started on this branch: https://github.com/AtlasOfLivingAustralia/biocache-service/tree/remove-redundant-code

**Comment by adam-collins** [comment]
First pull request containing some cleanup and increase in test coverage https://github.com/AtlasOfLivingAustralia/biocache-service/pull/654

**Comment by adam-collins** [comment]
new working branch https://github.com/AtlasOfLivingAustralia/biocache-service/tree/449-part-2

**Comment by djtfmartin** [comment]
Coverage in 3.0.18 is **38%**

**Comment by adam-collins** [comment]
- 40% coverage in 449-part-2 after enabling the grails tests.
- Removed unused dependencies 88MB -> 51MB war. Did not remove any `scope=test` dependencies. Hopefully didn't remove anything needed.

**Comment by adam-collins** [comment]
- `SearchDAO` and `SolrIndexDAO` search method review is sufficiently done with the use of streaming for the methods with the most impact on performance.
- Spring dependencies is moved to #450 
- Geotools version is 22.2, a 2020 release.
- Further review of dependencies can take place after #450, if necessary.
- `develop` branch is at 43% coverage today. For the purpose of this project it is sufficiently improved.
- Review of unused classes and methods is done.
- Shapefile generation is removed.

**Comment by qifeng-bai** [comment]
Test coverage is  42.901%  now
