### ISSUE TITLE
Upgrade to Spring 5

### ISSUE THREAD

**Issue by javier-molina** [AtlasOfLivingAustralia/la-pipelines#450]

**Comment by javier-molina** [comment]
Message from Bruce last Friday

> I've just finished deploying biocache-service to test however am getting an error related to the validation, will revert.

**Comment by javier-molina** [comment]
Latest PR

**Comment by brucehyslop** [comment]
downgraded `hibernate-validator` from v7.0.1 to v6.2.0

`hibernate-validator` v7 requires new Jakarta EE v9 over Java EE v8 

https://github.com/AtlasOfLivingAustralia/biocache-service/commit/ac4789b522765263754899e86655a396c05153e6

**Comment by nickdos** [comment]
@brucehyslop - Can we move this to done and rely on the regular functional test plan to cover this issue, as it is so broad in scope?

**Comment by brucehyslop** [comment]
sounds good to me.
