### ISSUE TITLE
Stats are coming in as unclassified for ala-hub

### ISSUE THREAD

**Issue by javier-molina** [AtlasOfLivingAustralia/la-pipelines#452]
seems like stats are still coming in as unclassified for ala-hub and not being tagged as source ALA. https://logger.ala.org.au/service/sourceBreakdown?eventId=1002

biocache-service sends it to logger but ala-hub sends sourceID as param to service (&sourceTypeId=0)

**Comment by javier-molina** [comment]
This might be an existing issue.

**Comment by brucehyslop** [comment]
There are no source_type_id = 0 with logged in the DB on prod and is an existing issues. 

The has been a fix one in PR AtlasOfLivingAustralia/logger-service#21 however this does not appear to be deployed to production. 
The MD5 hash for the deploy on prod matches logger-service 2.4-PRERELEASE build Thu May 28 2020 11:07:20 GMT+1000. 
The PR was merged 10 Jul 2020, 15:45 GMT+10

**Comment by brucehyslop** [comment]
will be fixed with the next release of logger-service
