### ISSUE TITLE
qa parameter ignored in downloads

### ISSUE THREAD

**Issue by javier-molina** [AtlasOfLivingAustralia/la-pipelines#453]
qa field for the /ws/offline/occurrence/download no longer works- any value in this field is ignored. This is also happens when I download via the UI and select the assertion columns.

**Comment by brucehyslop** [comment]
I can't see replicate the the behaviour with the `qa` field being ignored. `biocache-service` is respecting the field. 
 - https://biocache.ala.org.au/ws/occurrences/offline/download?q=id:%2231950a5c-2a03-494b-bb6d-7d3942ab51d3%22&reasonTypeId=10&email=test.user@ala.org.au&qa=includeAll
 - https://biocache.ala.org.au/ws/occurrences/offline/download?q=id:%2231950a5c-2a03-494b-bb6d-7d3942ab51d3%22&reasonTypeId=10&email=test.user@ala.org.au&qa=all
 - https://biocache.ala.org.au/ws/occurrences/offline/download?q=id:%2231950a5c-2a03-494b-bb6d-7d3942ab51d3%22&reasonTypeId=10&email=test.user@ala.org.au&qa=none

The ala-hub is passing `qa=includeall` (lower case) when requesting all "Quality Assertions". This has the same affect as `qa=none`

**Comment by javier-molina** [comment]
@matildastevenson could you please shed some light here please or otherwise confirm if this is no longer issue?

**Comment by matildastevenson** [comment]
I only checked `qa=includeall` so that would be why that didn't work.
The API documentation gives the impression it is also possible to pass individual assertions e.g. `qa=ZERO_COORDINATE`, and I thought this was possible previously, but is not currently working

**Comment by brucehyslop** [comment]
Added back the handling of csv list of assertions `qa={assertion name}`. 

This was removed when the streaming offline downloads work https://github.com/AtlasOfLivingAustralia/biocache-service/commit/e3221e6dc64426cfa4af1805202487bae4871782

**Comment by nickdos** [comment]
Tested - custom download contains QA fields now ✅
