### ISSUE TITLE
Broken tooltips in AVH Assertion list

### ISSUE THREAD

**Issue by javier-molina** [AtlasOfLivingAustralia/la-pipelines#455]
![Screen Shot 2021-06-29 at 3 57 18 pm](https://user-images.githubusercontent.com/8326394/123744853-b8db5800-d8f2-11eb-9414-94471c7d9dc8.png)

**Comment by nickdos** [comment]
I suspect this might be a config fix.

**Comment by nickdos** [comment]
FIxed with config change:

`dataQualityChecksUrl = https://docs.google.com/spreadsheet/pub?key=0AjNtzhUIIHeNdHJOYk1SYWE4dU1BMWZmb2hiTjlYQlE&single=true&gid=1167507250&output=csv`

![image](https://user-images.githubusercontent.com/532845/123880038-2f289a80-d985-11eb-92b0-d7c69591a806.png)
