### ISSUE TITLE
Create a DefaultValuesTransform that uses collectory

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/la-pipelines#46]
GBIF have implemented the equivalent of our default values as a transform that interacts with the GBIF registry to retrieve a set of default field values for records. We need to implement an analogue to this for the collectory. This transform does need to be ran at the start of the interpretation pipeline. 

The analogue to GBIF's transform can then be deprecated after stage 2 is complete in favour of GBIF's implementation, when we are using GBIF's registry to store default values.

The output of the GBIF's `DefaultValuesTransform` is to create a new verbatim avro files  separate from the verbatim.avro file created in the initial ingest step (DWCA -> AVRO). In the pipelines. in  this is referred to as the `ExtendedRecord` which is essentially verbatim.avro and default values. This `ExtendedRecord` is passed to all transforms in the interpretation pipeline.

This output contains the verbatim data plus the default values and this is what is used for adding raw value fields to the SOLR index.

<img width="435" alt="Screen Shot 2020-04-04 at 12 37 25 pm" src="https://user-images.githubusercontent.com/444897/78503801-c68e4600-7760-11ea-91f6-22ceba374249.png">

related to #12

**Comment by RobinaSanderson** [comment]
**Timing**
The default values transform needs to occur after the DwCA transform and before the rest of the transforms.

**Steps to demonstrate** To be confirmed
1. Look up the collectory.
2. Find default values.
3. Add to verbatim avro.

To be done:

List default value fields to be included.

**Comment by djtfmartin** [comment]
Work for this has been done on the feature/default-values branch and includes an end to end test.
Default values are added at the start of the interpretation process and are written to the `interpreted/verbatim` AVRO output directory. These values are then available for downstream processes including the other transforms in the InterpretationPipeline, UUIDMintingPipeline and SOLR indexing.

**Comment by djtfmartin** [comment]
Work is done in this PR https://github.com/AtlasOfLivingAustralia/la-pipelines/pull/76

**Comment by peggynewman** [comment]
Review complete. Thanks.
