### ISSUE TITLE
Many occurrences end up as Other scientificName

### ISSUE THREAD

**Issue by javier-molina** [AtlasOfLivingAustralia/la-pipelines#460]
From Tim:

> @Doug, this was reported via Spatial but seems to be consistent in Biocache as well - faceting on Scientific name for genus Hakea results in a huge amount of occurrences left in "Other scientificName", including common species as pointed out by this user: https://support.ehelp.edu.au/a/tickets/110958
> 
> 
> ![image](https://user-images.githubusercontent.com/8326394/123889927-c13a9e00-d999-11eb-8497-ad95a241c13c.png)
> 
> 
> 10:53
> Is this related to the names issue you mentioned this morning?

From Doug:

> Don’t think so. The underlying query to the biocache is https://biocache-ws.ala.org.au/ws/webportal/legend?cm=scientificName&q=qid:1625013224695&type=application/json This produces a massive list of species at the end under ‘other’. A search of https://biocache.ala.org.au/occurrences/search?taxa=Hakea produces the following list
> 
> ![image](https://user-images.githubusercontent.com/8326394/123890043-edeeb580-d999-11eb-87ce-886eb3a1443c.png)
> 
> 
> 11:20
> The returned result doesn’t even contain the top species.
> 11:22
> Removing the qid and just putting taxa:Hakea produces the same result, so I think there’s a problem with the biocache-service

**Comment by nickdos** [comment]
Closing in place of #462.
