### ISSUE TITLE
Trailing `.` stripped from advanced search input

### ISSUE THREAD

**Issue by javier-molina** [AtlasOfLivingAustralia/la-pipelines#461]
Doug:

> An interesting little buglet. Searching for a supplied/raw name of Wissadula grandifolia doesn’t turn anything up but doing a text search turns up two records with a supplied name of “Wissadula grandifolia Baker f.” https://avh.ala.org.au/occurrences/99abb34a-d755-454d-ae2d-354286917342 searching for a raw name with a wildcard still doesn’t turn anything up. Although the exact, exact, exact form does https://avh.ala.org.au/occurrences/search?q=raw_name%3A%22Wissadula+grandifolia+Baker+f.%22 However, you can’t search for it from the UI, because it strips the ‘.’ at the end.

> It looks like a bug to me. Someone going to AVH and entering Wissadula grandifolia into the taxon name search for the supplied taxon name should expect to find instances that have that supplied name, even if the supplied name includes the author. And it’s impossible to find, even if they do put the author in because an essential period at the end gets stripped off. Whether it’s a new bug or not I can’t tell, because search on biocache-legacy isn’t working.

**Comment by nickdos** [comment]
Looks like either `biocache-hubs` or `avh-hub` issue.

**Comment by qifeng-bai** [comment]
Test passed
