### ISSUE TITLE
`/explore/group/{group}.json` output shows repeated taxa (EYA broken pagination)

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/la-pipelines#467]
Bug reported by a user - https://support.ehelp.edu.au/a/tickets/111300.

When scrolling through list of species in EYA, the list is paginated at 50 items and user can extend the list by clicking on the "show more species" link at end of the list. 

![image](https://user-images.githubusercontent.com/532845/124432703-40264100-ddb5-11eb-8f58-137d5e9274ef.png)

The list of taxa is generated from this following call (first 50 items)

https://biocache-ws.ala.org.au/ws/explore/group/Birds.json?lat=-35.2513&lon=149.1635&radius=5&fq=geospatial_kosher%3Atrue&qc=&sort=count&pageSize=50

Clicking the "show more species" link, calls the same service but adds `&start=50` to the request:

https://biocache-ws.ala.org.au/ws/explore/group/Birds.json?lat=-35.2513&lon=149.1635&radius=5&fq=geospatial_kosher%3Atrue&start=50&common=false&sort=index&pageSize=50&qc=

The problem is that taxa in the first 50 are reappearing in subsequent paginated requests, when `&start=50` is added. E.g. item 2 from the second call is already present as item 34 in the first call. SO the users sees the same species appearing over and over in the list.

Requesting the 3rd, 4th and subsequent pages, simply returns the same results as page 2, e.g.

https://biocache-ws.ala.org.au/ws/explore/group/Birds.json?lat=-35.2513&lon=149.1635&radius=5&fq=geospatial_kosher%3Atrue&start=100&common=false&sort=index&pageSize=50&qc= 

is the same as the link above it.

It also seems that the sorting is broken when `start` is provided, as the `count` values should decrease but they are completely inconsistent: `1, 3317, 9435, 1, etc.` and items appear to be sorted by taxon name.

**Comment by timhicks-ala** [comment]
Additionally reported in helpdesk tickets 111246, 111339 and 111354.

**Comment by adam-collins** [comment]
https://github.com/AtlasOfLivingAustralia/biocache-service/pull/656

**Comment by djtfmartin** [comment]
This looks fixed to me. Can someone else verify ?

**Comment by nickdos** [comment]
Not fixed for me on https://biocache-dq-test.ala.org.au/explore/your-area#-35.2730|149.1163|12|Birds

**Comment by nickdos** [comment]
@adam-collins pointed out that EYA is not sending the correct `sort` param so needs a fix there.

**Comment by adam-collins** [comment]
Hubs is sending inconsistent `sort` values. In the screenshot records <=50 are `sort=count` and the appended records are `sort=index` or `sort=taxa`.

**Comment by nickdos** [comment]
Prod is sending the correct params afaict (this is second page of results for birds):
![image](https://user-images.githubusercontent.com/532845/125017505-a31a1f80-e0b6-11eb-9aa4-b1c37b6a7aae.png)
 see sort = count, as expected.

**Comment by nickdos** [comment]
So `count` is a invalid value?

**Comment by nickdos** [comment]
First page of results that looks fine:

```
lat: -35.2728
lon: 149.1160
radius: 5
fq: geospatial_kosher:true
qc: 
sort: count
pageSize: 50
```

second page of results:
```
lat: -35.2728
lon: 149.1160
radius: 5
fq: geospatial_kosher:true
start: 50
common: false
sort: count
pageSize: 50
qc: 
```

which is wrong

**Comment by nickdos** [comment]
OK, can see there are actually 2 calls to `/ws/explore/group/Birds.json` when you click on the "show more species" link:

![image](https://user-images.githubusercontent.com/532845/125023823-fbefb500-e0c2-11eb-9ce0-330c1611e8ff.png)

First one correctly specifies the `sort=count` and the second one then sends `sort=index` and this one appears to clobber the first one. So will try and debug this to see why there are 2 WS calls being triggered.

**Comment by nickdos** [comment]
@adam-collins - with a minor fix in hubs, this is now working as expected for the default sort order `count` but its not working for sorting by `commonName`. The way that was working, was it sent these params `common=true&sort=index` but now that simply returns results sorted by `scientificName`, so seems the `common=true` is being ignored. Can you take a look please?

**Comment by nickdos** [comment]
Can someone pls code review [the commit above](https://github.com/AtlasOfLivingAustralia/biocache-hubs/commit/a87d902863ff220491dd0fd875353cb7c78304f6)?

**Comment by adam-collins** [comment]
https://github.com/AtlasOfLivingAustralia/biocache-service/pull/663 fixes `common=true&sort=index`

**Comment by nickdos** [comment]
UI fix deployed to test site.

**Comment by alexhuang091** [comment]
@nickdos 

https://biocache-ws.ala.org.au/ws/explore/group/Birds.json?lat=-35.2513&lon=149.1635&radius=5&fq=geospatial_kosher%3Atrue&qc=&sort=count&pageSize=50

https://biocache-ws.ala.org.au/ws/explore/group/Birds.json?lat=-35.2513&lon=149.1635&radius=5&fq=geospatial_kosher%3Atrue&qc=&sort=count&pageSize=50&start=100

these 2 queries return exactly same content which is not expected.
