### ISSUE TITLE
min depth and max depth terms not dwc standard

### ISSUE THREAD

**Issue by peggynewman** [AtlasOfLivingAustralia/la-pipelines#469]
The terms `min depth` and `max depth` have no units of measurement apparent on the record page

The correct DwC terms are 
http://rs.tdwg.org/dwc/terms/minimumDepthInMeters
http://rs.tdwg.org/dwc/terms/maximumDepthInMeters

See whale record for example: https://biocache.ala.org.au/occurrences/71996a3f-60bc-4f34-b1cb-63f615503610

It's clear from https://biocache.ala.org.au/fields?filter=depth that the fields are in meters
Also there aren't any crazy other measurement values in the field ([min at least](https://biocache-ws.ala.org.au/ws/occurrences/facets/download?q=*%3A*&facets=min_depth_d&count=true&lookup=true))

Can we update the labels?

**Comment by djtfmartin** [comment]
Yes, this looks like something to fix in i18n properties.

**Comment by javier-molina** [comment]
@peggynewman What are the proposed labels?

**Comment by peggynewman** [comment]
Maximum depth in metres
Minimum depth in metres

**Comment by djtfmartin** [comment]
Fixed in test
https://biocache-test.ala.org.au/occurrences/71996a3f-60bc-4f34-b1cb-63f615503610

**Comment by qifeng-bai** [comment]
Tested
