### ISSUE TITLE
Place holder: Default values transform

### ISSUE THREAD

**Issue by RobinaSanderson** [AtlasOfLivingAustralia/la-pipelines#47]
This is a placeholder that requires further information.

The default values transform needs to occur after the DwCA transform and before the rest of the transforms.

Look up the collectory.
Find default values.
Add to verbatim avro.

To be done:
- List default value fields to be included.

**Comment by RobinaSanderson** [comment]
Duplicate

**Comment by djtfmartin** [comment]
Work is done in this PR https://github.com/AtlasOfLivingAustralia/la-pipelines/pull/76
