### ISSUE TITLE
NCI IO is very poor for running  certain Spark pipelines

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/la-pipelines#473]
Screenshots from AWS running IndexRecordToSolrPipeline

<img width="1471" alt="Screen Shot 2021-07-05 at 3 52 21 pm" src="https://user-images.githubusercontent.com/444897/124589322-c5f7ca00-de51-11eb-9688-a11ec9e02185.png">

Same pipeline on NCI (different timescale)

<img width="1500" alt="Screen Shot 2021-07-05 at 3 38 12 pm" src="https://user-images.githubusercontent.com/444897/124589411-e1fb6b80-de51-11eb-80e7-2f9b6b31df89.png">

The pipeline ultimately fails on NCI with various timeout exception.

**Comment by javier-molina** [comment]
We are not going to use Spark on NCI hence there is nothing to action here.
