### ISSUE TITLE
`decimalLatitude` appears twice in downloads

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/la-pipelines#476]
Looks like a copy&paste error in a properties files - see screenshot:

![image](https://user-images.githubusercontent.com/532845/124685107-eee09380-df13-11eb-8711-d0eec99eb998.png)

Column `AD` should be `Decimal longitude`.

**Comment by alexhuang091** [comment]
In message.properties there are
`facet.raw_decimalLongitude=Latitude (unprocessed)`
`decimalLongitude=Decimal latitude (WGS84)`

Just need to change them to longitude

**Comment by alexhuang091** [comment]
Change is done here
https://github.com/AtlasOfLivingAustralia/biocache-service/commit/a4218f9be7393389e3b6d789afaee1ad1f9560c3

**Comment by RobinaSanderson** [comment]
Tested by
1. search for hakea epiglottis
2. select download from search results page
3. select to download as ALA legacy format
4. view download

it now includes Decimal longitude heading
![image](https://user-images.githubusercontent.com/23368496/125566312-cc6aa1da-c291-436e-a024-21cb86e97879.png)
