### ISSUE TITLE
Missing Conservation status in downloaded species checklist

### ISSUE THREAD

**Issue by timhicks-ala** [AtlasOfLivingAustralia/la-pipelines#477]
Issue raised in https://support.ehelp.edu.au/a/tickets/111208

1. Example view/area in Explore your area: https://biocache.ala.org.au/explore/your-area#-37.1603|139.7901|12|ALL_SPECIES
2. Download a species checklist of this view
3. Example includes 1544 separate species, but the Conservation column in the downloaded CSV file is totally blank. The Invasive column is also blank (although I'm not sure if any species in this example have an invasive status listed).
4. View the same records in Biocache. Many of them have one or another Conservation status under the Occurrence filter.

![image](https://user-images.githubusercontent.com/57081387/124698505-57d40580-df2c-11eb-8642-9f8384e4ffd9.png)

**Comment by nickdos** [comment]
[records-2021-07-07.csv](https://github.com/AtlasOfLivingAustralia/la-pipelines/files/6774206/records-2021-07-07.csv)

**Comment by djtfmartin** [comment]
Fix for this here: https://github.com/AtlasOfLivingAustralia/biocache-service/pull/660

awaiting review

**Comment by djtfmartin** [comment]
Fix deployed to test environment.

**Comment by nickdos** [comment]
tested ✅
