### ISSUE TITLE
Display filtered index/fields returns incorrect values

### ISSUE THREAD

**Issue by brucehyslop** [AtlasOfLivingAustralia/la-pipelines#481]
The filtered index fields https://biocache.ala.org.au/ws//index/fields?fl=establishmentMeans,decimalLatitude,decimalLongitude,assertions only returns 2 results.

The issue is because default behaviour is to return facet counts if the are is a field list supplied. The luke response from solr does not return the facet counts for numeric fields (`decimalLatitude` or `decimalLongitude`) which causes the parsing of the response to fail.

https://github.com/AtlasOfLivingAustralia/biocache-service/blob/af5f8b9173df582657850e6570e76bf60ab31361/src/main/java/au/org/ala/biocache/dao/SolrIndexDAOImpl.java#L430

**Comment by qifeng-bai** [comment]
biocache-ws-test returns 4 records now
