### ISSUE TITLE
COORDINATE_ROUNDED iNaturalist records 

### ISSUE THREAD

**Issue by peggynewman** [AtlasOfLivingAustralia/la-pipelines#484]
All inaturalist records throw a COORDINATE_ROUNDED warning

https://biocache.ala.org.au/occurrences/search?q=data_resource_uid%3Adr1411&fq=assertions%3ACOORDINATE_ROUNDED

Text on the assertion is : Original coordinate modified by rounding

Sample record:
https://biocache.ala.org.au/occurrences/8a618382-59e0-48aa-9e56-a530109ecba9

In 'original vs processed'  the original record has loads of decimal places, and the processed has 6. 

The main record listing shows the original values with lots of decimal places. It should probably show the processed value.

**Comment by javier-molina** [comment]
I must be missing something, the processed values are being displayed in the record view page.

![Screen Shot 2021-07-15 at 11 02 18 am](https://user-images.githubusercontent.com/8326394/125711794-d3b0f164-0f2c-491b-9d34-e63dc7524598.png)

**Comment by peggynewman** [comment]
Is it club view maybe?

![image](https://user-images.githubusercontent.com/1271932/125737859-8e5f3ea6-f1c7-48f0-bb3a-7c56b4baafed.png)

**Comment by peggynewman** [comment]
It is Club View! Nothing to see here. Closing.
