### ISSUE TITLE
Regions app issues

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/la-pipelines#488]
https://regions-test.ala.org.au reports errors and does not load [region pages](https://regions-test.ala.org.au/States%20and%20territories/NEW%2520SOUTH%2520WALES#group=Birds&subgroup=&guid=&from=1850&to=2021&tab=speciesTab&fq=-*%3A*) properly.

JS console shows this call is returning a 500 code:

https://nci3-biocache-service.ala.org.au/ws/breakdown.json?q=cl10925%3A%22NEW+SOUTH+WALES%22&fq=rank:(species%20OR%20subspecies)&fq=-occurrence_status_s:absent&fq=geospatial_kosher:true&fq=occurrence_year:*&pageSize=50&fq=occurrence_year:[1850-01-01T00:00:00Z%20TO%202021-12-31T23:59:59Z]&rank=kingdom&callback=jQuery34105324642835281993_1626590106035&_=1626590106036

(prod is ok with the same call).

**Comment by javier-molina** [comment]
Already tested by Nick
