### ISSUE TITLE
Requested qa field returns data with description name as column name

### ISSUE THREAD

**Issue by daxkellie** [AtlasOfLivingAustralia/la-pipelines#490]
When a qa field is requested like `qa = COUNTRY_INVALID`, the data returns the column name as `Country invalid`, which appears to be the description name. This isn't true for every field though (for example, `qa = FOOTPRINT_SRS_INVALID` returns the qa field name `FOOTPRINT_SRS_INVALID`).

It would be preferable to return the qa field name, rather than the description name.

In addition, headings.csv should add descriptions for the following assertions that still lack one:

```
FOOTPRINT_SRS_INVALID
FOOTPRINT_WKT_INVALID
POSSIBLY_ON_LOAN
TAXON_MATCH_AGGREGATE
UNCERTAINTY_NOT_SPECIFIED
```

Possibly related to issues #489 and #453

**Comment by daxkellie** [comment]
An example where `qa = COUNTRY_INVALID`
https://nci3-biocache-service.ala.org.au/ws//occurrences/offline/download?disableAllQualityFilters=true&fields=decimalLatitude%2CdecimalLongitude%2CeventDate%2CscientificName%2CtaxonConceptID%2CrecordID%2CdataResourceName&qa=COUNTRY_INVALID&emailNotify=false&sourceId=2004&reasonTypeId=10&email=ala4r%40ala.org.au&dwcHeaders=true&fq=(lsid:urn:lsid:biodiversity.org.au:afd.taxon:51dc6bc2-9165-4fc3-a374-1010ac3037d0)&fq=(year:%221930%22)

**Comment by alexhuang091** [comment]
> 
> In addition, headings.csv should add descriptions for the following assertions that still lack one:
> 
> ```
> FOOTPRINT_SRS_INVALID
> FOOTPRINT_WKT_INVALID
> POSSIBLY_ON_LOAN
> TAXON_MATCH_AGGREGATE
> UNCERTAINTY_NOT_SPECIFIED
> ```
> 
> Possibly related to issues #489 and #453

Hi Dax, you mean the description in column H?
Could you give me some example assertions which have a valid description? 

Thanks

**Comment by nickdos** [comment]
There are 2 behaviours for the headings row and they depend on whether you add the param `&dwcHeadings=true` to the download request. If that param is not sent, then you get the descriptions fields as the headings row. However, if you send the param as shown, then the codes are used for the headings row (and first column of the headings.csv file).

The reason for this is to be backwards compatible with the legacy way of doing it. @daxkellie you are asking for:

> It would be preferable to return the qa field name, rather than the description name.

So I suggest that ALA4R and galah send `&dwcHeadings=true` with the request to obtain this.

We will fix the missing descriptions so the output of QA fields is consistent.

**Comment by matildastevenson** [comment]
galah ignores the headings.csv file so we don't mind what is in there. All requests already add `dwcHeaders=true` (see Dax's comment above). Is the expected behaviour with `dwcHeaders=true` that we will get the assertion ids or descriptions in the column names?

**Comment by alexhuang091** [comment]
> galah ignores the headings.csv file so we don't mind what is in there. All requests already add `dwcHeaders=true` (see Dax's comment above). Is the expected behaviour with `dwcHeaders=true` that we will get the assertion ids or descriptions in the column names?

Hi Matilda, with `dwcHeaders=true` you will get code as column names.
