### ISSUE TITLE
Downloads show no records

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/la-pipelines#494]
All records downloads on prod result in a records file with just the header row. 

Might be related to SOLR schema change that was made at same time that last release was deployed??

**Comment by nickdos** [comment]
@adam-collins fixed prod by rolling back the index from overnight run.

Still suggests an issue in schema files/branches, possibly.

See https://github.com/AtlasOfLivingAustralia/la-pipelines/issues/458#issuecomment-885390452

**Comment by javier-molina** [comment]
@adam-collins, @nickdos:  Dave mentioned in yesterday's meeting the index and config are fixed in production and there is nothing else to action. 

Unless you think otherwise  I will close this.
