### ISSUE TITLE
Setup test environment on AWS (databox)

### ISSUE THREAD

**Issue by javier-molina** [AtlasOfLivingAustralia/la-pipelines#495]
A few considerations

- [ ] Start/Stop from Jenkins
- [x] Synchronisation of DwCA from production
- [x] Synchronisation of UUIDs

**Comment by djtfmartin** [comment]
Synchronisation of DwCA & UUIDs from production has been done with cron (set up by @matthewandrews) and Jenkins jobs that can be used to restore DwCA & UUIDs from production to the databox environment.

**Comment by djtfmartin** [comment]
this is done
