### ISSUE TITLE
Scatterplot highlights are broken in production

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/la-pipelines#497]
The drawing of the rectangle should result in points being highlighted on the map. Suspect this is broken due to recent re-working of WMS controller code.

<img width="1679" alt="Screen Shot 2021-07-27 at 7 50 56 am" src="https://user-images.githubusercontent.com/444897/127109655-56ddef1d-72d8-4437-8fc9-05d5e2c21843.png">

**Comment by adam-collins** [comment]
https://github.com/AtlasOfLivingAustralia/biocache-service/pull/683

**Comment by qifeng-bai** [comment]
Spatial-test does not work as expected (It points to biocache-test). However,  it showed that 3 records in legend, so I suspected it may be caused by missing geoserver style.  I will check up on it

**Comment by qifeng-bai** [comment]
Passed test via spatial-test.ala.org.au
