### ISSUE TITLE
Collectory integration - collection lookups and attribution

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/la-pipelines#5]
Requirements include:

- [x] Need to retrieve attribution and licence information
- [x] Needs to perform collection code lookups

**Comment by djtfmartin** [comment]
Added integration with

**Comment by djtfmartin** [comment]
Work is done in this PR https://github.com/AtlasOfLivingAustralia/la-pipelines/pull/76

**Comment by javier-molina** [comment]
This task is no longer applicable: "DwCA archives should be retrieved from accessing Collectory webservices. We need some java code that can be ran prior to the DwCA ingestion pipeline that retrieves and unpackages the archives."
