### ISSUE TITLE
Create DWcA with images/media extension - analysis

### ISSUE THREAD

**Issue by sadeghim** [AtlasOfLivingAustralia/la-pipelines#50]
Scope for this task is only metadata extraction.

Actual ingestion and processing of images will happen on a separate transformation.

**Comment by RobinaSanderson** [comment]
Split into analysis and implementation issues.

Need to document all the ways we add images and discuss how we should deal with them. - Put together a proposal of how we should tackle this.

Question is how we will maintain the image references. Can use production with export as we won't be ingesting images? 

Need to test ingest of DwCA with images and don't want duplicate images in Production.

**Comment by sadeghim** [comment]
The options that I can think of are:

- [ ] 1. Have image identifiers as the `image_id` in the images server.
- [ ] 2. Have the original url/filenameas the identifier.

Pros and cons of each options:
Approach | Pros | Cons
-- | -- | --
1 | identifier will be tha `image_id` in the image service and this can help us to not include the images in the `dwca.zip`.  <br /> All the images will have valid URLs. Since the images are accumulated during the years, there are some of them that the URL is not valid anymore. | If there is an original `dwca.zip` file, it may end up with the duplicate images as the identifer in the supplied file can be different that `image_id` that we have put in the exported archive.
2 | |

**Comment by javier-molina** [comment]
The actual implementation was addressed on  #103
