### ISSUE TITLE
"Download now" button results in 404

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/la-pipelines#500]
I ran a download from biocache UI and on the final confirmation screen, the "Your download is running" message with a progress bar is replaced with the "You download is ready" with the action button: "Download now". When I click this:

https://biocache.ala.org.au/biocache-download/dd0dfc2b-2e11-30ce-91bb-ca8afff9715e/1627442814970/extra-sp-dwc-records-2021-07-28.zip

I get a 404:

> Error: Page Not Found (404)
> Path: /biocache-download/dd0dfc2b-2e11-30ce-91bb-ca8afff9715e/1627442814970/extra-sp-dwc-records-2021-07-28.zip

I've seen this the last 2 downloads I've tried but it was working prior to this.

**Comment by matthewandrews** [comment]
Curious.  This URL is working for me @nickdos ...

**Comment by nickdos** [comment]
Mmmm let me check my /etc/hosts....
