### ISSUE TITLE
Raw eventDate is not displaying in Compare original vs processed record view

### ISSUE THREAD

**Issue by peggynewman** [AtlasOfLivingAustralia/la-pipelines#504]
Example of the problem:
https://biocache.ala.org.au/occurrences/c126cef9-5543-45bc-971f-d018d27cf15f

One that is working:
https://biocache.ala.org.au/occurrences/ca9d95ab-8355-4f1b-8d0b-18f51be2fa99

**Comment by peggynewman** [comment]
Another problem record found today:
https://biocache.ala.org.au/occurrences/743f6bc0-e5ed-4371-b12e-48e794141567

![image](https://user-images.githubusercontent.com/1271932/129836932-ab9ff721-3fb5-481b-b775-a5fa3d48f6e9.png)

**Comment by brucehyslop** [comment]
code was expecting `raw_eventDate` to have datatype of Date. 

Fix made in PR AtlasOfLivingAustralia/biocache-service#693

![Screen Shot 2021-09-03 at 5 22 13 pm](https://user-images.githubusercontent.com/12233783/131966690-c1dfd966-84e3-4f2f-9c2b-fd9268d8f146.png)

**Comment by javier-molina** [comment]
https://biocache.ala.org.au/occurrences/c126cef9-5543-45bc-971f-d018d27cf15f works now in Prod

![Screen Shot 2021-09-16 at 8 35 09 pm](https://user-images.githubusercontent.com/8326394/133597660-5d19a305-c298-4f46-967d-d11f6d5c40c3.png)
