### ISSUE TITLE
DwCA exports by la-pipelines dwca-export do not pass GBIF data validation

### ISSUE THREAD

**Issue by nielsklazenga** [AtlasOfLivingAustralia/la-pipelines#505]
I just ran a few of the Darwin Core Archives produced by `la-pipelines dwca-export` through the GBIF Data Validator:

- https://www.gbif.org/tools/data-validator/1622015287629
- https://www.gbif.org/tools/data-validator/1622015287631

The verdict is that the archives have some validation issues and cannot be indexed by GBIF. This is the summary:

![image](https://user-images.githubusercontent.com/4694550/129666556-3edc5a0c-5e1f-4a33-862d-18dd758cbbb9.png)

**Comment by djtfmartin** [comment]
Related issue raised here https://github.com/gbif/pipelines/issues/585

**Comment by djtfmartin** [comment]
PR for review
https://github.com/gbif/pipelines/pull/588
