### ISSUE TITLE
Spring 5 - https://biocache-ws-test.ala.org.au/ws/index/fields.json gives 404

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/la-pipelines#507]
Some apps are using `ws/index/fields.json` instead of `ws/index/fields` - notably apps with charts -  so we'll need to add this URL back in to the spring 5 upgrade.

**Comment by brucehyslop** [comment]
As of spring 5.2.4 `PathExtensionContentNegotiationStrategy` has been deprecated as it can make a site a trojan for a Reflected File Download (RFD) attack.

see: https://github.com/spring-projects/spring-framework/issues/24179

It is recommended that content negotiation be performed via the http `Accept` header or a request parameter. 

Options are: 

1. revert to a version of spring prior to v5.2.4
2. specify multiple request mappings for endpoint that require specific content type based on path extension.  
  eg: `@RequestMapping(value = { "index/fields", "index/fields.json" }, method = RequestMethod.GET)`

**Comment by nickdos** [comment]
https://biocache-ws-test.ala.org.au/ws/index/fields.json still throws 404.
