### ISSUE TITLE
`/occurrences/info` service throwing 500 error

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/la-pipelines#511]
When clicking on dots on the map, the popups are not showing. JS error reveals calls are returning `500 error`.

https://biocache-ws-test.ala.org.au/ws/occurrences/info?q=state%3A%22Western%20Australia%22&disableAllQualityFilters=true&qualityProfile=ALA&zoom=4&lat=-15.613161352216446&lon=138.7924799323082&radius=50&format=json

With response:

```json
{
  "message": "/WEB-INF/jsp/json/infoPointGeojson.jsp (line: [11], column: [0]) Unable to load tag handler class [atg.taglib.json.JsonObjectTag] for tag [json:object]",
  "errorType": "Server error",
  "statusCode": 500
}
```

**Comment by brucehyslop** [comment]
taglib was removed in cleanup of dependencies https://github.com/AtlasOfLivingAustralia/biocache-service/commit/10582818045f0166256e4cb9527d59116a799113
