### ISSUE TITLE
Maintain script(s) that automatically updates assertion wiki pages

### ISSUE THREAD

**Issue by javier-molina** [AtlasOfLivingAustralia/la-pipelines#512]
#435 Deals with automating the update of sections in assertion wiki pages.

While the current script will do the job, at the moment it is build as a one off script.

Assertions will continue evolving hence it would be great to have this script as part of the tools for biocache-hubs maybe so it can be accessed, used and maintained by development team.

This also relates to #426

**Comment by brucehyslop** [comment]
Added script to automate the syncing of assertions wiki with assertions from `biocache-service`

See documentation:
https://github.com/AtlasOfLivingAustralia/biocache-service/tree/develop/scripts#managing-data-quality-wiki-pages

**Comment by djtfmartin** [comment]
Issue moved to [AtlasOfLivingAustralia/biocache-service #705](https://github.com/AtlasOfLivingAustralia/biocache-service/issues/705) via [**ZenHub**](https://www.zenhub.com/)
