### ISSUE TITLE
Filtering by alau_user_id or userId does not work in test

### ISSUE THREAD

**Issue by javier-molina** [AtlasOfLivingAustralia/la-pipelines#514]
Reported by Temi:

> A filter used by BioCollect is alau_user_id. It does not look like I can filter by that value in biocache-test at the moment.

> userId and alau_user_id is working in production.
> but both not working in test
> the query I am using - https://biocache-test.ala.org.au/occurrences/search?q=*:*&fq=(data_resource_uid:dr364)&fq=userId:4228

**Comment by brucehyslop** [comment]
The are no records in `nci3-solr` for `userId:4228`

There is a field mapping from `alau_user_id` to `userId` so these fields are equivalent.

**Comment by adam-collins** [comment]
Something different with the dwca export. Prod maps 4228 to userId, nci3 maps 4228 to recordedByID. SOLR matches this. Nothing to fix.

**Comment by javier-molina** [comment]
Hi @temi 

Please see comments above, we have an outdated export in test.

Are you able to find a suitable record with the queries below to confirm the original biocollect call works?

https://biocache-test.ala.org.au/occurrences/search?q=alau_user_id:*

or 
https://biocache-test.ala.org.au/occurrences/search?q=alau_user_id:*&fq=(data_resource_uid:insert_dr_id_here)

This is an example using the original query you provided but using other values, I'm not sure what would be a suitable dr for Biocollect though.
https://biocache-test.ala.org.au/occurrences/search?q=*:*&fq=(data_resource_uid:dr689)&fq=alau_user_id:1067

Thanks

**Comment by temi** [comment]
Hi @javier-molina , I am unable to test this since all records do not have a supplied user id in test data. But the comments above suggests that there would be not issue in production system. Therefore, I am happy to give this a thumbs up.
![image](https://user-images.githubusercontent.com/1152259/133006088-324e5c3d-8090-4276-9e0c-2114612d5c21.png)
