### ISSUE TITLE
raw license not populated

### ISSUE THREAD

**Issue by javier-molina** [AtlasOfLivingAustralia/la-pipelines#515]
From Nick:

Regression testing biocache-service I've found a difference with prod - see missing raw license field:
![image](https://user-images.githubusercontent.com/8326394/132455644-c7f10fb3-130b-451f-9487-f88039c7457b.png)

**Comment by brucehyslop** [comment]
The data in solr differs between test and prod
http://nci3-solr-1.ala:8983/solr/biocache/select?q=id%3A655027c5-614e-41b8-84df-43c3b95e9c06&fl=id%2Craw_license%2Clicense
vs
http://aws-solr-2021-1.ala:8983/solr/biocache/select?q=id%3A655027c5-614e-41b8-84df-43c3b95e9c06&fl=id%2Craw_license%2Clicense

Not a regression in biocache-service

![Screen Shot 2021-09-09 at 1 25 07 pm](https://user-images.githubusercontent.com/12233783/132617393-e712393f-61c7-4c0d-9b9e-5a94e4ca96c2.png)

**Comment by javier-molina** [comment]
Thanks @brucehyslop for the initial investigation. @adam-collins is aware of your investigation and will check the AVRO files to check where the issue is.

**Comment by adam-collins** [comment]
The raw_licence value is not present in the `/dwca-export/dr13282/dr13282.zip` file on nci3. It is on aws. 

Nothing broken.

**Comment by javier-molina** [comment]
@nickdos please see above, this is a data issue, are you satisfied that the below shows it works?

Here are records with raw licence

https://biocache-test.ala.org.au/occurrences/search?q=license:*%20AND%20raw_license:*

And one particular example
 https://biocache-ws-test.ala.org.au/ws/occurrence/compare/31c40c56-9553-4404-a00d-0399eeaa1337

**Comment by nickdos** [comment]
All good - closing issue.
