### ISSUE TITLE
Provide a mapping of deprecated fields and assertions

### ISSUE THREAD

**Issue by javier-molina** [AtlasOfLivingAustralia/la-pipelines#53]
LA pipelines will produce a set of processed records aligned with dwc standard.

Currently biocache service exposes a set of legacy records but have a mapping to dwc terms. TBC The legacy fields are currently stored either os both in Cassandra and Solr. 

Legacy fields for which a dwc term is available are not going to be stored/produced by LA pipelines hence for example the new Solr index will expose only basisOfRecord instead of basis_of_record yet biocache service should still expose  basis_of_record 

This tasks consist of identifying all those legacy fields that LA pipelines won't produce so biocache service can provide a mapping service.

**Comment by ansell** [comment]
Alternatively, la-pipelines could be putting the existing location fields into the solr index to minimise the number of changes to biocache-service.

**Comment by javier-molina** [comment]
@djtfmartin I think we have talked about this in several conversations but could you cast your eyes on the new description and let me know if it captures the essence of the fields that LA pipelines is not going to produce ?

**Comment by RobinaSanderson** [comment]
I think a full mapping will have 4 parts:
1. What fields will be used as is?
2. What fields will still be used but may be renamed due to using GBIF code?
3. What fields will be deprecated?
4. What fields will be new?

**Comment by javier-molina** [comment]
Notes from Sprint 8 planning:

It is suggested to start capturing test vectors from current prod biocache-service so these can feed test planning activities (and potentially understand the fields being queried?)

**Comment by javier-molina** [comment]
#120 is related to this.

**Comment by brucehyslop** [comment]
Most deprecated field mappings are camel case versions of the legacy field however for some fields the mapping corresponds with the Darwin Core field name returned by the field list API. 

Below is a list of all automatically generated field mappings. 
```
{
    "accepted_name_usage": "acceptedNameUsage",
    "access_rights": "accessRights",
    "associated_media": "associatedMedia",
    "associated_references": "associatedReferences",
    "associated_sequences": "associatedSequences",
    "associated_taxa": "associatedTaxa",
    "basis_of_record": "basisOfRecord",
    "bibliographic_citation": "bibliographicCitation",
    "catalogue_number": "catalogNumber",
    "class_id": "classID",
    "collection_code": "collectionCode",
    "collection_id": "collectionID",
    "collection_name": "collectionName",
    "collection_uid": "collectionUid",
    "collector": "recordedBy",
    "coordinate_precision": "coordinatePrecision",
    "coordinate_uncertainty": "coordinateUncertaintyInMeters",
    "country_code": "countryCode",
    "cultivated": "establishmentMeans",
    "data_generalizations": "dataGeneralizations",
    "data_provider_uid": "dataProviderUid",
    "data_resource_uid": "dataResourceUid",
    "dataset_id": "datasetID",
    "dataset_name": "datasetName",
    "dynamic_properties": "dynamicProperties",
    "elevation": "verbatimElevation",
    "end_day_of_year": "endDayOfYear",
    "event_id": "eventID",
    "event_remarks": "eventRemarks",
    "event_time": "eventTime",
    "family_id": "familyID",
    "field_notes": "fieldNotes",
    "field_number": "fieldNumber",
    "footprint_srs": "footprintSRS",
    "footprint_wkt": "footprintWKT",
    "georeference_protocol": "georeferenceProtocol",
    "georeference_remarks": "georeferenceRemarks",
    "georeference_sources": "georeferenceSources",
    "georeference_verification_status": "georeferenceVerificationStatus",
    "georeferenced_by": "georeferencedBy",
    "georeferenced_date": "georeferencedDate",
    "higher_classification": "higherClassification",
    "higher_geography": "higherGeography",
    "identification_id": "identificationID",
    "identification_qualifier": "identificationQualifier",
    "identification_references": "identificationReferences",
    "identification_remarks": "identificationRemarks",
    "identification_verification_status": "identificationVerificationStatus",
    "identified_by": "identifiedBy",
    "identified_date": "dateIdentified",
    "individual_count": "individualCount",
    "information_withheld": "informationWithheld",
    "infraspecific_epithet": "infraspecificEpithet",
    "institution_code": "institutionCode",
    "institution_id": "institutionID",
    "institution_name": "institutionName",
    "institution_uid": "institutionUid",
    "island_group": "islandGroup",
    "kingdom_id": "kingdomID",
    "latitude": "decimalLatitude",
    "life_stage": "lifeStage",
    "location_according_to": "locationAccordingTo",
    "location_id": "locationID",
    "location_remarks": "locationRemarks",
    "longitude": "decimalLongitude",
    "max_depth_d": "maximumDepthInMeters",
    "max_elevation_d": "maximumElevationInMeters",
    "measurement_accuracy": "measurementAccuracy",
    "measurement_determined_by": "measurementDeterminedBy",
    "measurement_determined_date": "measurementDeterminedDate",
    "measurement_id": "measurementID",
    "measurement_method": "measurementMethod",
    "measurement_remarks": "measurementRemarks",
    "measurement_type": "measurementType",
    "measurement_unit": "measurementUnit",
    "measurement_value": "measurementValue",
    "min_depth_d": "minimumDepthInMeters",
    "min_elevation_d": "minimumElevationInMeters",
    "name_according_to": "nameAccordingTo",
    "name_published_in": "namePublishedIn",
    "nomenclatural_code": "nomenclaturalCode",
    "nomenclatural_status": "nomenclaturalStatus",
    "occurrence_date": "eventDate",
    "occurrence_id": "occurrenceID",
    "occurrence_remarks": "occurrenceRemarks",
    "occurrence_status": "occurrenceStatus",
    "order_id": "orderID",
    "organism_quantity": "organismQuantity",
    "organism_quantity_type": "organismQuantityType",
    "original_name_usage": "originalNameUsage",
    "other_catalog_numbers": "otherCatalogNumbers",
    "owner_institution_code": "ownerInstitutionCode",
    "parent_name_usage": "parentNameUsage",
    "phylum_id": "phylumID",
    "previous_identifications": "previousIdentifications",
    "raw_datum": "verbatimCoordinateSystem",
    "raw_latitude": "verbatimLatitude",
    "raw_locality": "locality",
    "raw_longitude": "verbatimLongitude",
    "raw_sex": "sex",
    "raw_taxon_name": "scientificName",
    "record_number": "recordNumber",
    "related_resource_id": "relatedResourceID",
    "relationship_of_resource": "relationshipOfResource",
    "relationship_remarks": "relationshipRemarks",
    "reproductive_condition": "reproductiveCondition",
    "rightsholder": "rightsHolder",
    "sampling_effort": "samplingEffort",
    "sampling_protocol": "samplingProtocol",
    "scientific_name_authorship": "scientificNameAuthorship",
    "scientific_name_id": "scientificNameID",
    "specific_epithet": "specificEpithet",
    "start_day_of_year": "startDayOfYear",
    "state": "stateProvince",
    "taxon_concept_lsid": "taxonConceptID",
    "taxon_id": "taxonID",
    "taxon_remarks": "taxonRemarks",
    "taxonomic_status": "taxonomicStatus",
    "type_status": "typeStatus",
    "typified_name": "typifiedName",
    "verbatim_coordinates": "verbatimCoordinates",
    "verbatim_event_date": "verbatimEventDate",
    "verbatim_locality": "verbatimLocality",
    "verbatim_srs": "verbatimSRS",
    "verbatim_taxon_rank": "verbatimTaxonRank",
    "water_body": "waterBody"
}
```

Some stats of the mapping:

- 146 Solr fields with no corresponding pipelines field
- 66 of those are also in the biocache field list
- 21 fields where the field type differs between Solr schemas
- 17 Darwin Core fields where this is no field in either Solr schema

see: https://github.com/AtlasOfLivingAustralia/la-pipelines/issues/192#issuecomment-730857564

**Comment by brucehyslop** [comment]
A new shared spreadsheet has been create for collections of mapping notes: [pipeline_field_mappings.xlsx](https://csiroau-my.sharepoint.com/:x:/r/personal/hys006_csiro_au/Documents/pipeline_field_mappings.xlsx?d=w0c875dc154914b11a626e4bdeb12d178&csf=1&web=1&e=sPe7a0).

To record mapping notes please add the note to the relevant field name in sheets `Solr_(pipelings)_field_comments` and/or `Solr_(legacy)_field_comment`. The `pipeline_field_mappings` is autogenerated and locked to prevent modification.

See the notes on field `common_name` & `vernacularName` for an example.

**Comment by brucehyslop** [comment]
New columns have been added to capture the record counts for each of the fields.
This should be useful it inform which fields can be safely deprecated.

 - there are 1,091 fields in that have no records that use these fields.
 - there are 2,301 fields that are used by < 10 records.

**Comment by javier-molina** [comment]
After discussing with Dave, this will be the result of analysing the spreadsheet #192 particularly for fields and assertions that can't be automatically mapped.

This is activity is not  need it for actual index generation, neither #230 nor #149 as the Solr index generation is not based on field/assertions cherry picking.

This issue will be moved to #52

**Comment by brucehyslop** [comment]
There is a new assertions mapping sheet with in the pipelines mapping spreadsheet in sharepoint [pipeline_field_mappings.xlsx](https://csiroau.sharepoint.com/:x:/r/sites/ALAInfrastructureRefresh-WP12/Shared%20Documents/General/pipeline_field_mappings.xlsx?d=w5a1723baa0104cd9bc2db35f0e7c199a&csf=1&web=1&e=bwauTC) 

Summary of mapping:
 * 22 missing assertion mappings ![#ff0000](https://via.placeholder.com/15/FF0000/000000?text=+)
 * 33 new assertions in pipelines ![#00b0f0](https://via.placeholder.com/15/00B0F0/000000?text=+)
 * 44 GBIF or ALA OccurrenceIssue without mappings or data populated in `solrcloud-quoll`
 * 31 assertions mapped
   * 15 mappings exact name match (camel to snake case) ![#92d050](https://via.placeholder.com/15/92D050/000000?text=+)
   * 9 manual mappings that need review ![#ffco00](https://via.placeholder.com/15/FFC000/000000?text=+)
   * 7 biocache assertions with no data populated in `solrcloud-quoll` ![#ffff00](https://via.placeholder.com/15/FFFF00/000000?text=+)

**Comment by brucehyslop** [comment]
The pipelines_field_mapping.xlsx spreadsheet has been updated with the latest mappings. This can be used as a reference for field mappings.

I've added a few more filter options to help analysis.

Deprecated Solr v6 (legacy) fields:
| Solr v6 (legacy)<br>field_name                                    | field_type | multi_value | record_count |
|-----------------------------------------------|------------|-------------|--------------|
| abcd_identification_qualifier                 | string     | FALSE       | 93953554     |
| abcd_identification_qualifier_insertion_point | string     | FALSE       | 0            |
| assertions_missing                            | string     | TRUE        | 94816607     |
| assertions_passed                             | string     | TRUE        | 94816607     |
| assertions_unchecked                          | string     | TRUE        | 94816608     |
| australian_herbarium_region                   | string     | FALSE       | 0            |
| bbox                                          | string     | FALSE       | 0            |
| biogeographic_region                          | string     | TRUE        | 0            |
| citation                                      | string     | FALSE       | 0            |
| cultivar_name                                 | string     | FALSE       | 344          |
| cultivated                                    | string     | FALSE       | 0            |
| date_deleted                                  | tdate      | FALSE       | 13           |
| decimal_latitudelatitude                      | string     | FALSE       | 0            |
| deleted                                       | string     | FALSE       | 0            |
| distance_outside_expert_range                 | tdouble    | FALSE       | 0            |
| duplicate_inst                                | textgen    | TRUE        | 0            |
| duplicates_original_institution_id            | string     | FALSE       | 0            |
| duplicates_original_unit_id                   | string     | FALSE       | 0            |
| exchange_number                               | string     | FALSE       | 0            |
| generalised_locality                          | string     | FALSE       | 1            |
| geospatial_issue                              | string     | FALSE       | 1            |
| geospatially_kosher                           | string     | FALSE       | 0            |
| ibra                                          | string     | FALSE       | 0            |
| ibra_subregion                                | string     | FALSE       | 0            |
| images                                        | string     | FALSE       | 2680368      |
| imcra                                         | string     | FALSE       | 0            |
| interaction                                   | string     | TRUE        | 166456       |
| loan_botanist                                 | string     | FALSE       | 0            |
| loan_date                                     | tdate      | FALSE       | 0            |
| loan_number                                   | string     | FALSE       | 0            |
| loan_return_date                              | string     | FALSE       | 0            |
| loan_returned_date                            | tdate      | FALSE       | 0            |
| location_determined                           | string     | FALSE       | 93949031     |
| mappable                                      | string     | FALSE       | 10           |
| matched_name                                  | textgen    | TRUE        | 94122448     |
| mytest                                        | string     | FALSE       | 0            |
| natural_occurrence                            | string     | FALSE       | 0            |
| near_named_place_relation_to                  | string     | FALSE       | 0            |
| outlier_for_layers                            | string     | FALSE       | 0            |
| photo_page_url                                | string     | FALSE       | 0            |
| photographer                                  | string     | FALSE       | 33126        |
| portal_id                                     | string     | FALSE       | 493545       |
| preferred_flag                                | string     | FALSE       | 0            |
| quad                                          | quad       | FALSE       | 93278188     |
| quality_assertion                             | string     | FALSE       | 0            |
| query_assertion_uuid                          | string     | TRUE        | 0            |
| query_assertions                              | string     | FALSE       | 0            |
| record_type                                   | string     | FALSE       | 0            |
| rem_text                                      | text       | TRUE        | 24972304     |
| scientific_name_addendum                      | string     | FALSE       | 0            |
| scientific_name_without_author                | string     | FALSE       | 0            |
| source                                        | string     | FALSE       | 240056       |
| suitable_modelling                            | string     | FALSE       | 94816608     |
| system_assertions                             | string     | FALSE       | 94816608     |
| systemAssertions                              | string     | TRUE        | 0            |
| taxonomic_kosher                              | string     | FALSE       | 94816609     |
| taxonomically_kosher                          | string     | FALSE       | 0            |
| text_rev                                      | text_rev   | TRUE        | 0            |
| type_status_qualifier                         | string     | FALSE       | 0            |
| valid_distribution                            | string     | FALSE       | 74           |
| verbatim_date_identified                      | string     | FALSE       | 0            |
| verification_date                             | string     | FALSE       | 0            |
| verification_notes                            | string     | FALSE       | 0            |
| verifier                                      | string     | FALSE       | 0            |

Multiple Solr v6 (legacy) fields map to a single Solr v8 (pipelines) field

| Solr v8 (pipelines)<br>field_name          | dynamic | field_type | multi_value | record_count | Solr v6 (legacy)<br>field_name           | field_type       | multi_value | record_count |
|---------------------|---------|------------|-------------|--------------|----------------------|------------------|-------------|--------------|
| countryConservation |         | string     | FALSE       | 1371287      | aust_conservation    | string           | FALSE       | 0            |
| countryConservation |         | string     | FALSE       | 1371287      | country_conservation | string           | FALSE       | 1313889      |
| dynamicProperties   |         | text       | FALSE       | 72515742     | dynamic_properties   | string           | FALSE       | 81588        |
| dynamicProperties   |         | text       | FALSE       | 72515742     | misc_properties      | string           | FALSE       | 0            |
| id                  |         | string     | FALSE       | 88943377     | id                   | string           | FALSE       | 94816610     |
| id                  |         | string     | FALSE       | 88943377     | row_key              | string           | FALSE       | 94816600     |
| identifiedBy        |         | string     | FALSE       | 24316143     | identified_by        | string           | FALSE       | 8800178      |
| identifiedBy        |         | string     | FALSE       | 24316143     | identified_by_text   | textgen          | TRUE        | 0            |
| identifiedBy        |         | string     | FALSE       | 24316143     | identifier_by        | string           | FALSE       | 14366        |
| lastLoadDate        |         | date       | FALSE       | 0            | last_load_date       | tdate            | FALSE       | 94807529     |
| lastLoadDate        |         | date       | FALSE       | 0            | last_modified_time   | string           | FALSE       | 0            |
| recordedBy          |         | string     | TRUE        | 73726656     | collector            | string           | FALSE       | 64593189     |
| recordedBy          |         | string     | TRUE        | 73726656     | collectors           | string           | TRUE        | 77930290     |
| stateProvince       |         | string     | FALSE       | 84683874     | places               | string           | FALSE       | 80402651     |
| stateProvince       |         | string     | FALSE       | 84683874     | state                | string           | FALSE       | 88322401     |
| subspecies          |         | string     | FALSE       | 2827235      | subspecies           | string           | FALSE       | 3605976      |
| subspecies          |         | string     | FALSE       | 2827235      | subspecies_name      | string           | FALSE       | 3634924      |
| subspeciesID        |         | string     | FALSE       | 2825023      | subspecies_guid      | string           | FALSE       | 3634924      |
| subspeciesID        |         | string     | FALSE       | 2825023      | subspecies_id        | string           | FALSE       | 3605976      |
| taxonConceptID      |         | string     | FALSE       | 88287773     | lsid                 | string           | FALSE       | 0            |
| taxonConceptID      |         | string     | FALSE       | 88287773     | taxon_concept_lsid   | string           | FALSE       | 94095328     |
| userId              |         | string     | FALSE       | 12127        | alau_user_id         | string_lowercase | FALSE       | 1795814      |
| userId              |         | string     | FALSE       | 12127        | user_id              | string_lowercase | FALSE       | 1795814      |

**Comment by djtfmartin** [comment]
I've added mappings for the following to [deprecated-fields.json](https://github.com/AtlasOfLivingAustralia/ala-install/blob/27_pipelines_spark_hadoop/ansible/roles/biocache-service/files/config/deprecated-fields.json) in ala-install:

* geospatial_kosher
* sounds
* taxonomic_issue
* videos

this is deployed to the dev server.

**Comment by djtfmartin** [comment]
I've added code to provide the `datePrecision` field on this branch:

https://github.com/gbif/pipelines/tree/223_unique_key_checks
