### ISSUE TITLE
Create DwCA by dropping fields having default values in collectory

### ISSUE THREAD

**Issue by sadeghim** [AtlasOfLivingAustralia/la-pipelines#54]
For the default values, either we can incorporate them into the exported DwCA `meta.xml` or we can develop a pipeline which is described in #46

**Comment by sadeghim** [comment]
Since we already have some collectory interaction code in la-pipeline https://github.com/AtlasOfLivingAustralia/la-pipelines/blob/feature/uuid-management/pipelines/src/main/java/au/org/ala/kvs/client/ALACollectoryMetadata.java
I think that adding default fields into `meta.xml` is not part of this task. Though removing these fields from the generated dwca should be considered.
Changing the title to reflect this.

**Comment by sadeghim** [comment]
According to the following query in Cassandra DB we can detect if the default values in collectory are used in a record or not:

```cql

select rowkey, "defaultValuesUsed", deleted , "dateDeleted" from occ.occ ;

 rowkey                               | defaultValuesUsed | deleted | dateDeleted
--------------------------------------+-------------------+---------+----------------------
 235e03cc-b33c-478a-aba9-fd19d569a3f3 |             false |    null |                 null
 80806b3d-ff9d-43ab-b9d4-6c166bf39e66 |              true |    null |                 null
 a11a3cba-72a1-43fe-964a-2c143fd243ef |              null |    true | 2013-04-09T17:31:48Z
 4e89253f-9d5a-44b2-b753-1bf6d6a31f1a |             false |    null |                 null
 3f489f2b-3290-441e-90ff-ef8fa4e2b2b8 |             false |    null |                 null
 353dbc01-ea7f-4a52-b7b8-f6876db243c9 |              true |    null |                 null
 0c75b48f-cf4a-4139-9ce8-7f52e7a0dd04 |             false |    null |                 null
 97a9df2a-7b62-492a-b66d-669fc131661b |             false |    null |                 null
 6959d0fb-c83f-409a-b4f8-efbd9e698875 |              true |    null |                 null
 2387fa8f-3e83-4d77-b384-14c4a7bc58ee |              true |    null |                 null
 9f52540a-1581-4b54-9155-2fd2664f1dac |              true |    null |                 null
 befe7c53-5ad9-4b93-b5be-d4b6670feaf9 |             false |    null |                 null
 b94ea6e8-f6a6-4e1c-85f8-6f5e5af3ec3a |              null |    true | 2013-04-09T17:31:48Z

```

**Comment by javier-molina** [comment]
This is no longer required. There is already integration with collectory.

**Comment by sadeghim** [comment]
After investigating the data in the database I can confirm that the default values specified in collectory end up in `processed` fields and all the empty raw fields stay `null`.
Here is the biocache-store code that is used for default value processing:
https://github.com/AtlasOfLivingAustralia/biocache-store/blob/ba02ffb33bf89fa9443d57c961a118b3c09fe263/src/main/scala/au/org/ala/biocache/processor/DefaultValuesProcessor.scala#L33
```scala
            if (raw.getProperty(key).isEmpty) {
              //set the processed value to the default value
              processed.setProperty(key, value)
              raw.setProperty(key, value)
              if (!processed.getDefaultValuesUsed && !processed.getProperty(key).isEmpty){
                processed.setDefaultValuesUsed(true)
              }
```
Although it specify the raw values as the processed ones, it seems that it doesn't get updated in Cassadnra.
Maybe here is the code to persist that back into DB:
https://github.com/AtlasOfLivingAustralia/biocache-store/blob/ba02ffb33bf89fa9443d57c961a118b3c09fe263/src/main/scala/au/org/ala/biocache/processor/RecordProcessor.scala#L128
```scala
        occurrenceDAO.updateOccurrence(guid, currentProcessed, processed, systemAssertions, Processed)
```
It seems it doesn't pass the raw field to the update method and that's why it worked they way it is.

And final action, we can just close the issue as the exported fields from Cassandra don't have default values.
