### ISSUE TITLE
Temporal transform vs EventProcessor gap analysis and implementation

### ISSUE THREAD

**Issue by RobinaSanderson** [AtlasOfLivingAustralia/la-pipelines#55]
Placeholder - will require more detail

The high-level functions of biocache-store's EventProcessor should be compared with those of GBIF's TemporalTransform to capture which tests and interpretations that are missing from TemporalTransform.

This analysis does not need to be line for line.

The result of this issue should be one or more issues listing the additional functionality needed to accommodate anything that the ALA needs that is not already available in the TemporalTransform.

**Comment by javier-molina** [comment]
This branch needs to be synced with master.

**Comment by qifeng-bai** [comment]
We use GBIF temporal interpret , but its interpret can only parse certain formats of georeferencedBy and dateIdentified, like 1990-02-06, 06-Feb-1990, but it cannot parse 13/03/2010.  Do we need to support it?

**Comment by javier-molina** [comment]
Waiting for response from GBIF

**Comment by javier-molina** [comment]
Dave made changes to this work/branch. Bai has to review when he is back.

**Comment by djtfmartin** [comment]
Please review the commits here:

https://github.com/AtlasOfLivingAustralia/la-pipelines/pull/75
