### ISSUE TITLE
TypeStatusProcessor gap analysis

### ISSUE THREAD

**Issue by RobinaSanderson** [AtlasOfLivingAustralia/la-pipelines#56]
Placeholder - will require more detail

The high-level functions of biocache-store's TypeStatusProcessor should be compared with those of GBIF's XXXTransform to capture which tests and interpretations that are missing from XXXTransform.

This analysis does not need to be line for line.

The result of this issue should be one or more issues listing the additional functionality needed to accommodate anything that the ALA needs that is not already available in the XXXTransform.

**Comment by qifeng-bai** [comment]
TypeStatus is part of Identification in DwC.  We need to add this process into Identification related interpreter .

**Comment by qifeng-bai** [comment]
https://github.com/gbif/gbif-api/issues/72

**Comment by nickdos** [comment]
@qifeng-bai please add some output from SOLR prod index for `type_status` distinct values.

**Comment by javier-molina** [comment]
GBIF have implemented isoparatype at the gbif-api end. This can now be closed.
