### ISSUE TITLE
BasisOfRecordProcessor gap analysis and implementation

### ISSUE THREAD

**Issue by RobinaSanderson** [AtlasOfLivingAustralia/la-pipelines#57]
Placeholder - will require more detail

The high-level functions of biocache-store's BasisOfRecordProcessor should be compared with those of GBIF's BasicTransform to capture which tests and interpretations that are missing from BasicTransform or related transforms.

This analysis does not need to be line for line.

The result of this issue should be one or more issues listing the additional functionality needed to accommodate anything that the ALA needs that is not already available in the BasicTransform.

**Comment by javier-molina** [comment]
Look at the vocabulary provisions at GBIF for use by this task.

**Comment by qifeng-bai** [comment]
Check https://docs.google.com/spreadsheets/d/1D8jQ2xyPP_Df4QuBQs0Ti3FTkpoquMiEErBorqjoxKI/edit?ts=5ea93bdb#gid=628312428
