### ISSUE TITLE
Add duplicate check of unique keys to UUID pipeline

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/la-pipelines#62]
Add duplicate check of unique keys to UUID pipeline. This is to catch the scenario where the data provider has specified a field(s) as providing a unique key, but there are duplicates.

**Comment by djtfmartin** [comment]
A duplicate check has been developed on this branch.

https://github.com/gbif/pipelines/tree/129_dwca_parallel_loading

This code is ready for review.

**Comment by javier-molina** [comment]
@djtfmartin I was thinking whether there is any value in performing the check (or the whole UUID pipeline) before the interpretation to save processing and time for DR that potentially won't be processed if duplicates are found?

**Comment by djtfmartin** [comment]
This work has been reviewed and merged.

@javier-molina that would require some rework as UUID pipeline is reliant on the verbatim.avro with default values being generated beforehand, so we'd need to split pipelines up. Would be useful for working large datasets, but for small datasets (1 million records or less) less so as running interpretation takes 2-3 mins on the cluster.
