### ISSUE TITLE
Setup travis build for la-pipelines

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/la-pipelines#63]
Adding an issue for tracking. Build have now been setup in travis which are running Junit tests.
The build concludes by pushing built artefacts to ALA's nexus repository.

**Comment by ansell** [comment]
I added jacoco code coverage and coveralls.io reporting as an example of how to link up the travis build with code coverage tooling.

The current unit test coverage can be seen at:

https://coveralls.io/github/AtlasOfLivingAustralia/la-pipelines

**Comment by djtfmartin** [comment]
I believe this is done now. Travis builds are running and deploying to nexus.
