### ISSUE TITLE
Remove the use of custom settings.xml from la-pipelines

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/la-pipelines#68]
We had some issues with setting up the travis build  that meant we had to add a custom maven settings.xml instead of the standard ALA one. We did this because all dependency downloads are routed through nexus.ala.org.au and for some reason it wasnt proxying through to the required repositories hold geotools and hadoop libraries.

Addition repositories where added to nexus (called Cloudera and OSGeo) but that didnt fix it. Its possibly just a caching issue.

We should remove the custom settings.xml at some point.

**Comment by ansell** [comment]
As discussed in Slack, it was not likely a cache issue. It was likely forgetting to add the new repositories to the publicly exposed set of repositories, as they are otherwise not exposed by default.

**Comment by djtfmartin** [comment]
This can be closed. The custom settings is now deleted.
