### ISSUE TITLE
Spark Software as a service hosting analysis

### ISSUE THREAD

**Issue by javier-molina** [AtlasOfLivingAustralia/la-pipelines#70]
This issue was to evaluate some spark software as a service solutions.
The obvious candidate here is ApAche Spark on Apache EMR.

https://aws.amazon.com/emr/features/spark/

**Comment by matthewandrews** [comment]
I'd like to be involved, or in touch, with this.

**Comment by javier-molina** [comment]
Thanks @matthewandrews happy to have a chat with @djtfmartin and you to progress this.

**Comment by javier-molina** [comment]
Early in the project we decided to manage our own set up as AWS offer didn't offer the flexibility we need it at the time such as controlling the version of Spark we need it to run, or apply custom patches.
