### ISSUE TITLE
Move georeferencedDate from temporal to LocationRecord

### ISSUE THREAD

**Issue by qifeng-bai** [AtlasOfLivingAustralia/la-pipelines#72]
BiocacheStore set georeferencedDate to temporal record, but Dwc Core use georeferencedDate in location record. 
We should move georeferencedDate this field from temporal record to location. 

Todo: 
Add a new field georeferenceDate to LocationRecord, and write its interpreter. 

Discussion:
We cannot extend an original LocationRecord to a new ALA record, since there are pre-process and post-process, eg, writing DwC to avro, uses the LocationRecord.  It needs massive refactoring.

We need to fork GBIF pipeline

This ticket is related to #22 and #55

**Comment by qifeng-bai** [comment]
After we move georeferencedDate to LocationRecord, the 'GEOREFERENCE_POST_OCCURRENCE' assertion compares georeferencedDate in LocationRecord and eventDate in TemporalRecord, we need to make decision which interpreter should does, or if it is worthy ?

**Comment by qifeng-bai** [comment]
It is included into pull request review #75

**Comment by djtfmartin** [comment]
GBIF have raised an issue for this here: https://github.com/gbif/pipelines/issues/290
