### ISSUE TITLE
Create Spark cluster on NCI

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/la-pipelines#77]
Adding an issue for tracking. Also see #78 which may determine how we deploy to NCI servers.

Requirements:
- [x] Creation of VMs and enable SSH access for developers
- [x] Installation of HDFS
   - Replication factor 3, and we should look into a High Availability deployment (separate name nodes)
- [x] Installation of Apache Spark
- [x] Setup of Jenkins master and installation of Jenkins slaves on each Spark node

**Notes on Spark Cluster setup**
The AWS test deployment was setup with spark-2.4.5-bin-hadoop2.6.tgz
Spark was downloaded and unzipped on each node.
The master node was started using SPARK_HOME/sbin/start-master.sh
Slave nodes on each machine started using SPARK_HOME/sbin/start-slave.sh spark://MASTER_HOST:7077

**Comment by ansell** [comment]
One big thing that has come up recently is the discovery that we will only have 8 IP addresses available for the new NCI cloud.

Matt and I will therefore need to work through the various access/management/monitoring/security/etc. issues associated with private-IP-address-only servers for the first time (as a blocker) for this issue.

**Comment by matthewandrews** [comment]
The networking etc for new NCI is sorted out now.  The six instances are ready for Spark to be installed.  I have yet to set up a shared filesystem (NFS) but will do that soon.

**Comment by javier-molina** [comment]
NFS mount is already available.

**Comment by matthewandrews** [comment]
We may hold off on this for a bit, given that we have the AWS quoll environment to work with, and there is a pressing need for the Solr instances at NCI to be used for testing current biocache (including the data quality project work) in the short term, using Solr 6. Once that's done we can upgrade that cluster to Solr 8 to set things up as a dual-use environment for pipelines work and biocache testing.

**Comment by djtfmartin** [comment]
This work now complete.  This environment has been setup via ansible.
The cluster is working and running all process up to the point of indexing. As we lack a SOLR cluster in NCI for pipelines use, this is the best we can do for now.
