### ISSUE TITLE
Make external file loading configurable

### ISSUE THREAD

**Issue by qifeng-bai** [AtlasOfLivingAustralia/la-pipelines#79]
Currently, LocationInterpreter needs to load a number of resource files, such as country centre SHP file. The file paths were hard coded inside. We need to turn it to configurable.

2, Move some other resources files to resource folder

related task #22

**Comment by javier-molina** [comment]
#84 is blocking this ticket.

**Comment by javier-molina** [comment]
Bai estimates 2 more days development work.

**Comment by djtfmartin** [comment]
The work on this needed to be enhanced to use a default vocab file if the configuration hasnt specified the location of an external file path. This copies the functionality of biocache-store.

**Comment by qifeng-bai** [comment]
My suggestions is that: Vocab.loadVocabFromFile(String externalFilePath, String classpathFile)  . Checking if enternal file exists, and if we should the file in classpath should hand over to the implementation, like StateProvince class.

**Comment by djtfmartin** [comment]
Thanks Bai. Sounds fine to me. Ill leave it to you to refactor this.

**Comment by qifeng-bai** [comment]
pull request: 
https://github.com/gbif/pipelines/pull/328
