### ISSUE TITLE
ALA Taxonomy service for pipelines

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/la-pipelines#8]
This issue is for tracking work thats already under way. There is a WIP prototype developed here:

https://github.com/djtfmartin/ala-namematching-service

This is currently functional, but need to:

- Improve matching
- Write functional tests
- Add diagnostics to response and store them in AVRO

**Comment by djtfmartin** [comment]
This is currently functional, but need to:

* Improve matching
* Write functional tests
* Add diagnostics to response and store them in AVRO

**Comment by peggynewman** [comment]
@djtfmartin What do you mean by Improve Matching? Isn't matching just the internal workings of the names index - and this activity is just putting a wrapper around it?

**Comment by djtfmartin** [comment]
The requirement here is to make sure the functionality in these classes:

https://github.com/AtlasOfLivingAustralia/biocache-store/blob/master/src/main/scala/au/org/ala/biocache/processor/ClassificationProcessor.scala

https://github.com/AtlasOfLivingAustralia/biocache-store/blob/master/src/main/scala/au/org/ala/biocache/caches/ClassificationDAO.scala

makes it through to the pipeline implementation.  Ideally and if practical, as much of this logic should be pushed down to ala-name-matching library.

**Comment by charvolant** [comment]
* Refactored service and made configurable https://github.com/AtlasOfLivingAustralia/ala-namematching-service/pull/3
* Added hinting mechanism https://github.com/AtlasOfLivingAustralia/ala-namematching-service/pull/9
* Added check API call https://github.com/AtlasOfLivingAustralia/ala-namematching-service/pull/10
* Structured taxonomy transform/interpreter to use namematching client https://github.com/gbif/pipelines/pull/338
* Use hints in taxonomy transform/interpreter https://github.com/gbif/pipelines/pull/351
