### ISSUE TITLE
Use BitMapFactory for the stateProvince lookup

### ISSUE THREAD

**Issue by qifeng-bai** [AtlasOfLivingAustralia/la-pipelines#81]
This implementation needs to use the current shape file that biocache store uses.
-----------------
This PR enables the use of GBIF's `org.gbif.pipelines.kv.BitmapFactory` for the `stateProvince` lookup. This will be a reasonable performance enhancement as it minimises lookups against the ShapeFiles.

**Comment by muttcg** [comment]
Currently, @MattBlissett is working on GADM, it is still work in progress:
http://api.gbif-uat.org/v1/geocode/bitmap

**Comment by javier-molina** [comment]
Bai to ask Matt where things are

**Comment by MattBlissett** [comment]
There's now a bitmap for the GADM layer: https://github.com/gbif/geocode/blob/master/geocode-ws/src/main/resources/org/gbif/geocode/ws/layers/gadm.png

And some explanation of how it was generated here: https://github.com/gbif/geocode/blob/master/geocode-ws/MapImageLookup.adoc

So the result is: http://api.gbif-uat.org/v1/geocode/reverse?lat=7.36759&lng=-1.1425387

It's not yet integrated with Pipelines.

**Comment by qifeng-bai** [comment]
https://github.com/gbif/pipelines/pull/405

**Comment by djtfmartin** [comment]
This is done and merged.
