### ISSUE TITLE
Intermittent MetadataFetchFailedException thrown when indexing dr2009 on HDFS

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/la-pipelines#82]
The following `MetadataFetchFailedException` exception has been thrown on several runs of indexing dr2009, but is not consistently thrown. This has only been seen when ran on HDFS (not seen when running on EFS).

```
Exception in thread "main" java.lang.RuntimeException
 org.apache.spark.SparkException
 Job aborted due to stage failure
 ResultStage 3 (foreach at BoundedDataset.java
124) has failed the maximum allowable number of times
 4. Most recent failure reason
 org.apache.spark.shuffle.MetadataFetchFailedException
 Missing an output location for shuffle 0   at org.apache.spark.MapOutputTracker$$anonfun$convertMapStatuses$2.apply(MapOutputTracker.scala
882)    at org.apache.spark.MapOutputTracker$$anonfun$convertMapStatuses$2.apply(MapOutputTracker.scala
878)    at scala.collection.Iterator$class.foreach(Iterator.scala
891)  at scala.collection.AbstractIterator.foreach(Iterator.scala
1334)       at org.apache.spark.MapOutputTracker$.convertMapStatuses(MapOutputTracker.scala
878)    at org.apache.spark.MapOutputTrackerWorker.getMapSizesByExecutorId(MapOutputTracker.scala
691)  at org.apache.spark.shuffle.BlockStoreShuffleReader.read(BlockStoreShuffleReader.scala
49)      at org.apache.spark.rdd.ShuffledRDD.compute(ShuffledRDD.scala
105)      at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala
346)      at org.apache.spark.rdd.RDD.iterator(RDD.scala
310)     at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala
52)     at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala
346)      at org.apache.spark.rdd.RDD.iterator(RDD.scala
310)     at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala
52)     at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala
346)      at org.apache.spark.rdd.RDD.iterator(RDD.scala
310)     at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala
52)     at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala
```

Currently investigating causes and mitigation. A few things of note:

* The cluster after loading all data sources was imbalanced with the datanode on the HDFS master (aws-spark-quoll-1) using twice the amount of storage
* The tests where all done with a replication factor of 1 for HDFS. As some processes are only ran on the master (aws-spark-quoll-1), and HDFS only distributes the data as required.
* There where messages ConnectExceptions in the logs for the Spark slaves nodes pointing failing to connect to master
* The following error was seen in the logs `secondary namenode java.io.IOException: Inconsistent checkpoint fields`

The last point may have been mitigated by setting the following in hdfs-site.xml

```
<property>
  <name>dfs.namenode.checkpoint.dir</name>
  <value>file:///data/hdfs/namesecondary</value>
</property>
```

**Comment by djtfmartin** [comment]
A change was made to hdfs-site to increase replication, to hopefully increase the spread of the data across the nodes (reducing requests to master node)

```
<property>
 <name>dfs.replication</name>
 <value>2</value>
</property>
```

Testing this configuration with repeated runs of indexing.

**Comment by timrobertson100** [comment]
Without knowing your HDFS setup it is difficult to comment accurately. 

Typically you keep master nodes and data nodes separate in HDFS (you'd often colocate your HDFS masters with the ZK nodes). Masters can be pretty chatty, and you don't want to load up those master machines with other processes. 

I suggest you run ZK, Spark Master and HDFS NNs on the master machines (you should have 3 masters), and on the worker-nodes run the HDFS DN and spark workers (you should probably aim for 5+ workers). I'd run a separate machine for the datasets you process that are not running through Spark (or at worst, colocate them on the worker nodes, not the masters). 

Running a process on the same node as a DataNode should result in data stored on that machine (known as data locality). It sounds like you are seeing this. A reading process will also read locally if possible before doing a read across the network.

We run replication as 3 (which is pretty common). 

If you want to rebalance your cluster, you can use the [hdfs balancer](https://hadoop.apache.org/docs/r2.7.2/hadoop-project-dist/hadoop-hdfs/HDFSCommands.html#balancer). You can also [change the replication factor of existing files](https://community.cloudera.com/t5/Support-Questions/quot-How-we-can-change-Replication-factor-when-Data-is/td-p/197406).

**Comment by djtfmartin** [comment]
Thanks @timrobertson100 
Currently we are using 6 spark nodes, with each node a HDFS DataNode, and 1 of those nodes is the master HDFS and NameNode. We aren't currently running ZK with spark and HDFS.

```
<configuration>
<property>
 <name>dfs.replication</name>
 <value>2</value>
</property>
<property>
  <name>dfs.namenode.checkpoint.dir</name>
  <value>file:///data/hdfs/namesecondary</value>
</property>
<property>
  <name>dfs.name.dir</name>
    <value>file:///data/hdfs/namenode</value>
</property>

<property>
  <name>dfs.data.dir</name>
    <value>file:///data/hdfs/datanode</value>
</property>
</configuration
```

**Comment by djtfmartin** [comment]
Havent managed to reproduce this after increasing the replication factor in HDFS to 2.
