### ISSUE TITLE
interpretTemporal cannot recognise  some dates in dd/MM/yyyy format

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/la-pipelines#89]
Issue transferred from https://github.com/gbif/pipelines/issues/315

When `TemporalInterpreter. interpretTemporal()` is parsing DwcTerm.dateIdentified
It can parse:
12/12/2012 , 12/13/2012, 11/DEC/2012.,

but failed without any assertion on
11/12/2012

We need to support parsing of these formats for this field and other date fields (e.g . `eventDate`, `georeferencedDate`).

Bug for #55 

GBIF.org will continue (by default) to recognize only ISO dates, or unambiguous d/m/y m/d/y dates.

After GBIF accepts the changes,  ALA needs to modify transform to pass "pref date formats "in configurations to TemporationInterpreter, Date parser uses the  appointed formats solve ambiguous dates, like EU or US .

**Comment by qifeng-bai** [comment]
@peggynewman Shall we add ASSUMED_DMY_FORMAT assertion?

**Comment by timrobertson100** [comment]
Thanks Bai

I anticipate that we do need date parsing methods to allow for a format to be supplied in GBIF (DwC-A can even declare this at the dataset level) so invasive changes in the existing parsers seem reasonable to me (e.g. additional format parameter in relevant methods). That could be done in a new parser, and deprecating the existing if needed.

**Comment by qifeng-bai** [comment]
@djtfmartin @timrobertson100  I created a branch for this task https://github.com/gbif/pipelines/tree/au_date_format%2389
These changes did not change the way of GBIF using TemporalInterpreter and related date parsers. This implementation tried to minimise the changes on GBIF.
Main changes on:
1, Copy the original TemporalInterpeter code to DefaultTemproalInterprter - 
- changing 'static' methods to normal, 
- Allow to initialise with a given Date parser,  
- adding two "Event_Date_Ambigours,  Identified_Date_Ambigous assertions" - (NOT in OccenceIssues yet)

2, Extended GBIF parser (support ISO) in ALA date parser to support (D/M/Y).
 
Any suggestions are welcomed

**Comment by javier-molina** [comment]
Thanks @qifeng-bai   for the update.

Tim is on leave at the moment, probably best to progress this with @muttcg, @fmendezh and @asturcon

**Comment by MattBlissett** [comment]
Fede is also on leave this week.

At this stage of integrating ALA, are we looking only to bring ALA's processes into pipelines, or additionally to align GBIF and ALA's interpretation where that's reasonable?  If it's the former, I think this approach is OK.

If it's the latter, then I think what Tim wrote:

> invasive changes in the existing parsers seem reasonable to me (e.g. additional format parameter in relevant methods). That could be done in a new parser, and deprecating the existing if needed.

(and what I think) is we should keep a single data parser, and allow it to be configured. GBIF could then make use of DMY/MDY parsing if we detect it for a dataset.

The GBIF date parser in fact already supports requesting DMY or MDY dates with a format (`hint`) parameter, though we don't use it.  What's missing is setting the parse confidence lower for ambiguous dates, and a couple of additional formats added to https://github.com/gbif/parsers/blob/master/src/main/java/org/gbif/common/parsers/date/ThreeTenNumericalDateParser.java#L114 .  (We have added them as we see them to the list of ISO formats, but we don't need to add to the DMY list.)

It's then `TEXTDATE_PARSER.parse(date, DateFormatHint.DMY)` to use it, and it covers the ALA test case here.

**Comment by qifeng-bai** [comment]
@MattBlissett Thanks, Matt.  
I am refactoring the D/M/Y parser by using ThreeTenNumbericalDateParser. 
What I am not sure is that when we receive a confusing date, like 3/2/2000, we "assume" it as d/M/Y, or "recognise" it as d/M/Y by configuration?

**Comment by MattBlissett** [comment]
> What I am not sure is that when we receive a confusing date, like 3/2/2000, we "assume" it as d/M/Y, or "recognise" it as d/M/Y by configuration?

This would need to be by configuration -- GBIF.org will continue (by default) to recognize only ISO dates, or unambiguous d/m/y m/d/y dates.

I think the date parser (ThreeTenNumericalDateParser etc) needs to support returning a `PROBABLE` or `POSSIBLE` status when a DateFormatHint.DMY is supplied and the date could be ambiguous (3/2/2000), so you can add the  Identified_Date_Ambiguous assertion. Currently it returns `DEFINITE` status if an appropriate hint is supplied.

I think I expect something like this:
```
TextDateParserTest.java (or the ThreeTenNumericalDateParserTest):
    parseResult = TEXTDATE_PARSER.parse("04/08/2018", DateFormatPreference.PREFER_DMY);
    assertEquals(LocalDate.of(2018, Month.AUGUST, 4), LocalDate.from(parseResult.getPayload()));
    assertEquals(ParseStatus.PROBABLE, parseResult.getStatus());

    parseResult = TEXTDATE_PARSER.parse("14/08/2018", DateFormatPreference.PREFER_DMY);
    assertEquals(ParseStatus.DEFINITE, parseResult.getStatus());

    parseResult = TEXTDATE_PARSER.parse("04/08/2018"); // or DEFAULT preference
    // Failed parsing, two alternativePayloads with equal "POSSIBLE" status for 4 August and 8 April.
```

**Comment by qifeng-bai** [comment]
@MattBlissett It is exactly what I am doing

**Comment by qifeng-bai** [comment]
Refactor Planning  for discussion:

Temporal/Location interpreter related work:

1, gbif-api:
	Add two assertions: GEOREFERENCED_DATE_UNLIKELY,GEOREFERENCED_DATE_INVALID

2, gbif-parser:
	Create new PrefTextDateParser:  Wrap up a set of DateTimeFormatters to parse method.
temporalParser1 = DateParsers.defaultTemporalParser();
temporalParser2 = PrefTextDateParser.getInstance(orderings)

temporalParser1.parse(“1/2/2010”)  -> failed
temporalParser2.parse(“1/2/2010”)  -> succeed

Instead of:
textDateParser.parse(“1/2/2010”, ordering) 

3, gbif-pipelines:
 	
3.1 Add DefaultDateFormat=”DMY” into PipelineConfig class
	
3.2 Change static TemporalInterpreter to non-static class,
  
We can initiate a standard ISO temporal parser or a special DMY/MDY parser      
private TemporalParser temporalParser;

private DefaultTemporalInterpreter(){
 temporalParser = DateParsers.defaultTemporalParser();
}

private DefaultTemporalInterpreter(DateComponentOrdering[] orderings){
  temporalParser = PrefTextDateParser.getInstance(orderings);
}

3.3 Transform
DefaultTemporalInterpreter dtr;
if(config.getDefaultDateFormat() == "DMY"){
 dtr = DefaultTemporalInterpreter.getInstance(DMY_FORMATS);
}else if( config.getDefaultDateFormat() == "MDY" ){
 dtr = DefaultTemporalInterpreter.getInstance(MDY_FORMATS);
}else
 dtr = DefaultTemporalInterpreter.getInstance();


return Interpretation.from(source)
   .to(tr)
   .when(er -> !er.getCoreTerms().isEmpty())
   .via(dtr::interpretTemporal)
   .get();

**Comment by qifeng-bai** [comment]
See branch: https://github.com/gbif/pipelines/tree/24_eu_us_date

**Comment by qifeng-bai** [comment]
If date format is determined in dataset level,    @djtfmartin  mentioned: Something in the meta.xml within the darwin core archive,  Something in the collectory or registry.

In those cases,  the intepreter needs to read 'date format' field of each record to determine which date format should be used, then my implementation does not work on this scenario.

**Comment by qifeng-bai** [comment]
link to pull request: https://github.com/gbif/pipelines/pull/368

**Comment by javier-molina** [comment]
Work for this was eventually completed on https://github.com/gbif/pipelines/pull/394.
