### ISSUE TITLE
Prepare gbif/pipelines ala-dev branch for merge to master

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/la-pipelines#93]
After discussions with GBIF, we are aiming to merge the `ala-dev` branch on to master in gbif/pipelines.

Prior to this being done, we need to:

- [x] Clean up pom files - pom files should reference GBIF pipelines parent pom and make use of the same maven property version values inherited from the parent where possible
- [x] Fix integration tests to use maven docker plugin so that the build runs successfully in Jenkins (as well as travis)
- [x] Fix integration tests to download the required shapefiles so that builds run successfully in Jenkins (as well as travis)
- [x] Fix builds of `ala-dev` branch in GBIF Jenkins and Travis.
- [ ] Fix up issues reported by Code Smells in GBIF's Sonar: https://sonar.gbif.org

**Comment by djtfmartin** [comment]
Theres an outstanding issue with using the GBIF parent-pom. Referencing this pom is causing OOM errors for the integration tests.

**Comment by djtfmartin** [comment]
Fixed the  OOM error. Still need to do something regarding SHP files.

**Comment by djtfmartin** [comment]
The work on this issue is done subject to review by GBIF.

**Comment by djtfmartin** [comment]
The build for the `ala-dev` branch is now completing successfully in GBIF Jenkins and Travis.

**Comment by javier-molina** [comment]
@djtfmartin do we need to tag the current state of the branch otherwise are we parking any PR that want to mergechanges  to ala-dev?  

@charvolant, @qifeng-bai, @sadeghim FYI see PR gbif/pipelines#326 things are moving quiet fast here which is good but we need to be careful not to step into each others toes.

**Comment by djtfmartin** [comment]
thanks @javier-molina 

the merge is currently blocked by this issue

https://github.com/gbif/pipelines/issues/337

We can still progress other PRs in the mean time before the merge. My understanding is that GBIF  (@muttcg) will have some feedback for gbif/pipelines#326 in addition to the work for https://github.com/gbif/pipelines/issues/337

**Comment by djtfmartin** [comment]
The work for gbif/pipelines#337 is now complete.

**Comment by djtfmartin** [comment]
Further refactoring work required before a merge is possible.

**Comment by javier-molina** [comment]
Fede is on leave but I left a message for him to resume the integration work once he is back. 

Nikolai is going to help us align ala-dev branch but we need to coordinate that process and define how we will continue integrating new features moving forward after the initial 'big' merge. This is analogous to the tidy up that happen recently to move all our code to GBIF repo and the then more controlled feature branch approach.

**Comment by djtfmartin** [comment]
GBIF (Nik) have now re-organised the `gbif/pipelines` into the new structure with 

* common code (sdks, tools, examples, docs)
* gbif
* livingatlas

**Comment by djtfmartin** [comment]
`ala-dev` has been updated with the contents of `gbif-dev`.

My understanding of next steps is this:
- [ ] bring ala-dev up to date with gbif-dev new structure 
- [ ] merge ala-dev into gbif-dev (to be done by GBIF)
- [ ] rename gbif-dev to develop 
- [ ] delete/archive ala-dev branch

**Comment by javier-molina** [comment]
ala-dev branch will be deleted in the future.
