### ISSUE TITLE
Implement  interpretation of coordinateUncertaintyInMeters

### ISSUE THREAD

**Issue by qifeng-bai** [AtlasOfLivingAustralia/la-pipelines#94]
We need to convert coordinateUncertaintyInMeters  to metres, the supported UOMs are km, ft, km in, etc. 

@peggynewman Check this, please
* GBIF can only parse ft and in,
* ALA can parse ft and km , not inch. And supports pattens of 
km|kilometres|kilometers|m|metres|meters|ft|feet

If coordinateUncertaintyInMeters is out of range, set the value to null and raise assertion:COORDINATE_UNCERTAINTY_METERS_INVALID

If coordinateUncertaintyInMeters is not supplied and  coordiantePrecision is out of Range 0..1, BiocacheStore assumes coordinateUncertaintyInMeters is misplaced to coordiantePrecision,  then UNCERTAINTY_IN_PRECISION assertion will be raised, and the coordinatePrecision will be converted to coordinateUncertaintyInMeters

**Comment by javier-molina** [comment]
@qifeng-bai what is the difference between Deprecated and Cancelled/Suspended status in the spreadsheet? Suspended until when? 

My understanding from Peggy's comment is that this assertion is going away so I would mark it as Deprecated. 

Feel free to move this to the Done column once no more (analysis, I think) work is left

@RobinaSanderson do you think we need to document valid statuses and colors in the spreadsheet, in a similar way you did for the process diagram or is that over engineering?
